### ISSUE TITLE
Windows 10 Crafting Issue

### ISSUE THREAD

**Issue by Cl0n** [Nukkit/Nukkit#1002]
### Issue description
Every Time i craft in the Inventory or Workbench i become an error and my Items "uncraft".

### Steps to reproduce the issue

1. Open inventory/workbench
2. try to craft Sticks etc...

### OS and versions
* Nukkit: Nukkit 1.0dev ???(Apple)?(Pie)? implement v0.15.6 alpha (protocol version 82)
* OS: 
       Server: Windows Server 2012 r2 
       Client: Windows 10 Pro 
* Device: PC

### Crashdump, backtrace or other files
Error Log: https://gist.github.com/Cl0n/cf0e1c6e5a29ab2096359214c0cbf95b

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/issues/576
