### ISSUE TITLE
Error spammed in console

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#1009]
### Issue description

Write a short description about the issue
Whilst players are moving around occasionally could not tick level "level name" : java.lang.RuntimeException: java.io.EOFException is spammed into the console with no stack trace. 
### Steps to reproduce the issue

1. This possibly could be due to it being a pc anvil formatted map although there isn't any unknown blocks in the map. 
2. ...

### OS and versions

* Nukkit:
* OS: Ubuntu
* Device: windows and pocket edition

### Crashdump, backtrace or other files

* ...
Using guava to get the root exception this stack trace is given http://pastebin.com/vM0ukMdp

**Comment by Pub4Game** [comment]
It happens when the chunk is corrupted.

**Comment by imjack** [comment]
Would it be possible to add a more user friendly message rather than giving an error with no message? Maybe with the chunk coordinates?
