### ISSUE TITLE
Chunk loading bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1015]
### Issue description
after some time chunks dont load to player

### Steps to reproduce the issue
make some bigger world

### OS and versions
* Nukkit: latest

**Comment by Creeperface01** [comment]
![screenshot_2016-08-30-08-18-32](https://cloud.githubusercontent.com/assets/10363500/18084353/342b4a94-6ea7-11e6-9885-955bba00396b.png)

**Comment by Creeperface01** [comment]
It looks like chunkUpdate / request issue

**Comment by NycuRO** [comment]
@Creeperface01 How you add statitics ? :/ Is tip or popup? And what plugin?

**Comment by Creeperface01** [comment]
@NycuRO popup, Tip is laggy. And Annihilation v2.0

**Comment by NycuRO** [comment]
@Creeperface01 Thanks :)

**Comment by File14** [comment]
I use tip, no problems.

**Comment by Creeperface01** [comment]
@File14 mmmm I'll check it

**Comment by Creeperface01** [comment]
@Pub4Game This issue is still there ...

**Comment by Creeperface01** [comment]
but player see chunk loaded, just blocks textures aren't
