### ISSUE TITLE
FarmLand

### ISSUE THREAD

**Issue by nightmare3832** [Nukkit/Nukkit#1017]
I want the event when stepping on a FarmLand.

**Comment by File14** [comment]
Same here, but there is no. So I Forked Nukkit by myself and removed the farmland stepping code.

**Comment by Creeperface01** [comment]
:D

**Comment by Creeperface01** [comment]
I'll fix this :)

**Comment by nightmare3832** [comment]
thx

**Comment by nightmare3832** [comment]
I think File14's cord may be put out if it's made FarmLand from FarmLand.

**Comment by nightmare3832** [comment]
I'm Japanese, so I'm worried whether I can speak well.
:(

**Comment by Creeperface01** [comment]
or not i think it should be PlayerInteractEvent action physical but what about animal? :D there is not interact event

**Comment by Creeperface01** [comment]
yes in craftbukkit is EntityInteractEvent too xD

**Comment by nightmare3832** [comment]
xD

**Comment by File14** [comment]
@nightmare3832 You can now: https://github.com/Nukkit/Nukkit/pull/1124

Close this issuse.

**Comment by File14** [comment]
@Pub4Game close this
