### ISSUE TITLE
spawning underground

### ISSUE THREAD

**Issue by crichardson32** [Nukkit/Nukkit#1018]
client ios
nukkit version 3f8f9f7817873442a85c719b99c20d78d3f1762a

for somereason i keep spawning underground .. is this expected?

**Comment by PeratX** [comment]
There is some probable reasons:
* You are underground before exit (maybe by teleport)
* You are too close to the void
* Someone put block where you spawn

**Comment by Pub4Game** [comment]
@PeratX A bug really is, sometimes you can spawn in caves

**Comment by crichardson32** [comment]
@PeratX 
All the items you listed are invalid in my sitatuation. 

This happens almost every time either I spawn underground or somewhere underwater and i die.

This is on a brand new server never been played before and only by me.

What i have done is delete worlds and player folders to cause it to regenerate the items and it still happens more often than not.

This is using iOS client and master branch of nukkit.
