### ISSUE TITLE
100% load all the time!

### ISSUE THREAD

**Issue by daniktheboss** [Nukkit/Nukkit#1020]
Hello, my cpu says around 10% load but in nukkit it says 100% load with 1 person on walking around.

1. Join world.
2. 100% load.

* Nukkit: 1.0dev apple pie for mcpe 0.15.6 alpha
* OS: linux 
* Device: android

No crashes

**Comment by Snake1999** [comment]
How much cores does your server have? Nukkit takes the CPU usage data directly from Java system. I don't know if Java works fine :)

**Comment by xxFlare** [comment]
@Snake1999 Same problem. 30 players memory is full. Can you check block cache code? It seems to be the issue.

**Comment by daniktheboss** [comment]
I think 4

**Comment by daniktheboss** [comment]
Hello??

**Comment by Creeperface01** [comment]
Yes 70 players - 2,2 GB RAM

**Comment by MagicDroidX** [comment]
Check your plugins.

**Comment by daniktheboss** [comment]
There is no plugins!
