### ISSUE TITLE
DoublePlant

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1022]
### Issue description

Write a short description about the issue
If i'm planted double plants , have 1 block height. Double Tall grass*
### Steps to reproduce the issue

1. ...Enter server
2. ...Put Double Plants or Double Tall Grass

### OS and versions

* Nukkit: https://github.com/Nukkit/Nukkit/commit/b0d6e71fc2aff23bf8269a95adc601af891375a0
* OS: Debian 8.4 64bit Minimal
* Device: Android 4.3 , Allview , 0.15.6 alpha

### Crashdump, backtrace or other files

* ...

**Comment by Snake1999** [comment]
Seems like this feature is not implemented. We are doing this :)

**Comment by Snake1999** [comment]
Done. Thank you @Creeperface01 :)

**Comment by NycuRO** [comment]
@Creeperface01 @Snake1999 Thanks :)
