### ISSUE TITLE
Chunka bug

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1024]
### Issue description

Write a short description about the issue
I'm enter on server ,and chunks not loading. I'm change chunks loading ,but not work. I'm restarting server ,but not work. I'm re-enter on server,but not work.

I'm using Empty World ,but not show any problems in log and with debug > 1. Not problems.
![screenshot_2016-09-02-16-26-58](https://cloud.githubusercontent.com/assets/13573011/18205493/e877225e-712a-11e6-97a7-4d7efec59157.png)

### Steps to reproduce the issue

1. Start server
2. Enter server

### OS and versions

* Nukkit: https://github.com/Nukkit/Nukkit/commit/1fd1e58bf5ad50b9841b8b44e72a0b6f5d2ecfc8
* OS: Debian 8.4 64bit Minimal
* Device: Android 4.3 , Allview , 0.15.6 alpha

### Crashdump, backtrace or other files

* ...

**Comment by NycuRO** [comment]
@MagicDroidX @fromgate @Snake1999

**Comment by Pub4Game** [comment]
I don't have any problem with chunks.

**Comment by Pub4Game** [comment]
I think you need update Nukkit

**Comment by Creeperface01** [comment]
I have same issue :)

**Comment by Creeperface01** [comment]
Chunks stop loading after few time

**Comment by Creeperface01** [comment]
Or sever still loads new chunks but they are invisible to client

**Comment by Snake1999** [comment]
Seems weird... Try use `/status` to see how much chunks loaded. If the player move for a while and no more chunks are loaded, there is a problem.

**Comment by Creeperface01** [comment]
But i can walk into unloaded chunks or i can touch blocks there, but i dont see blocks textures. And if i walk into i suck

**Comment by Pub4Game** [comment]
Are you using the last version? MDX recently fixed some bugs

**Comment by Creeperface01** [comment]
What commit? 

![screenshot_2016-08-30-08-18-32](https://cloud.githubusercontent.com/assets/10363500/18223215/23196536-71b0-11e6-8a5d-5001c89fd0b2.png)

**Comment by Creeperface01** [comment]
But ill try the last version of nukkit

**Comment by Pub4Game** [comment]
close?

**Comment by Creeperface01** [comment]
I think so

**Comment by NycuRO** [comment]
Not fixed. @Pub4Game

**Comment by Creeperface01** [comment]
Hmmm
