### ISSUE TITLE
Cobble Generator

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1025]
Cobble generator not work.

If i'm place lava and water ,work's for 3 times, but other not...

Need put cobble again to create. Works for 3 times. 

Latest version ,debian 8.4 64bit minimal , 0.15.6 alpha version @MagicDroidX  @fromgate

**Comment by NycuRO** [comment]
@Snake1999

**Comment by NycuRO** [comment]
EDIT : IS VISUAL BUG,PLEASE FIX . IF I'M TAP BLOCK ,COBBLESTONE APPEREAL. PLEASE FIX VISUAL BUG.

**Comment by Snake1999** [comment]
Would mind using the template next time?

**Comment by NycuRO** [comment]
No,sorry for not use template,but i need fix ... In 3 h need start my skyblock server and have this issue..

**Comment by Tee7even** [comment]
Well, you can already start to think of excuses. It's not getting fixed in 2 hours.

**Comment by NycuRO** [comment]
Ok.

**Comment by daniktheboss** [comment]
😂

**Comment by Smasher535** [comment]
😂
