### ISSUE TITLE
Middle clicking grass switches to previously selected item

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#1026]
### Issue description

When you middle click grass it switches to the previously selected item in your hotbar. In this case my hotbar were completely empty, middle clicking will temporarily add the item: "grass" to my hotbar, but then the item disappears. However, I don't have this problem when middle clicking tall grass.
### Steps to reproduce the issue
1. Middle click grass with your mouse.
2. Notice that the grass almost instantly switches back to your previously selected item (Regardless if your hotbar slot had an item previously or not.)
### OS and versions
- Nukkit: build 444 (current build)
- OS: Windows 10
- Device: PC

**Comment by Snake1999** [comment]
Middle clicking is not supported by all MCPE versions, including WIN10, android and iOS. You can report it to mojang bug reporting sites.

**Comment by Pub4Game** [comment]
It supports in win 10

**Comment by Snake1999** [comment]
Really? I don't know as ... no packets receiving actions is discovered by me. Maybe we should discuss with our members

**Comment by Pub4Game** [comment]
It works, but some items like the torch is not taken

**Comment by stayandwait** [comment]
@Pub4Game Reopen request. I can confirm this is a bug and middle click being supported in Minecraft Windows 10 edition.

**Comment by stayandwait** [comment]
This issue is actually a duplicate of this report. No idea how I didn't realize that until now. I might as well add grass as one of the affected items. Since this already affects torches and ladders too.
https://github.com/Nukkit/Nukkit/issues/737
