### ISSUE TITLE
PrintStream lag

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1028]
### Issue description
sometimes server sucks

### Steps to reproduce the issue
idk

### OS and versions

* Nukkit:
* OS:
* Device:

### Crashdump, backtrace or other files
java.io.PrintStream.write(PrintStream.java:523)
java.io.PrintStream.print(PrintStream.java:669)
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1059)
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
java.lang.Thread.dispatchUncaughtException(Thread.java:1952)

**Comment by Creeperface01** [comment]
or what does this mean?

**Comment by Snake1999** [comment]
I can't reproduce :/
