### ISSUE TITLE
Memory used si BIG

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1030]
### Issue description

Write a short description about the issue
My skyblock server used MORE MORE MEMORY and chunks.

I have minimal minimal chunks and used 2gb ram for 1300 chunks and 13 players online.

Why? Please you can fix?

If i'm using /gc , my server memory used is fixed. 
### Steps to reproduce the issue

1. ... Enter server ,wait 1 minut with other players
2. ... Use /status and /gc and again /status for watch problem fixed.

### OS and versions

* Nukkit: https://github.com/Nukkit/Nukkit/commit/16628717b39202601d13faf6385da5fd70bfaef8
* OS: Ubuntuu 16.04.1 LTS 64bit 
* Device: Android 4.3 , Allview V1 Viper S 3G, 0.15.6 alpha

You can enter to server : nycuro-skyblock.ddns.net port 19135 for watch ..

### Crashdump, backtrace or other files

* ...

**Comment by NycuRO** [comment]
20:54:05 [INFO] ---- Server status ----
20:54:05 [INFO] Uptime: 0 days 0 hours 0 minutes 16 seconds
20:54:05 [INFO] Current TPS: 20.0
20:54:05 [INFO] Load: 54.32%
20:54:05 [INFO] Network upload: 0.0 kB/s
20:54:05 [INFO] Network download: 0.0 kB/s
20:54:05 [INFO] Thread count: 13
20:54:05 [INFO] Used memory: 832.31 MB. (21.2%)
20:54:05 [INFO] Total memory: 3925.5 MB.
20:54:05 [INFO] Maximum VM memory: 3925.5 MB.
20:54:05 [INFO] Available processors: 2
20:54:05 [INFO] Players: 10 online, 50 max.
20:54:05 [INFO] World "world": 109 chunks, 2 entities, 131 blockEntities. Time 0.0ms
20:54:05 [INFO] World "skyblock0": 256 chunks, 15 entities, 143 blockEntities. Time 1.0ms

**Comment by NycuRO** [comment]
For 365 chumls . 832.31MB is very big .

**Comment by NycuRO** [comment]
And with /gc used :

20:54:57 [INFO] Chunks: 305
20:54:57 [INFO] Entities: 9
20:54:57 [INFO] Block Entities: 1
20:54:57 [INFO] Memory freed: 667.64 MB
> status
20:54:58 [INFO] ---- Server status ----
20:54:58 [INFO] Uptime: 0 days 0 hours 1 minutes 9 seconds
20:54:58 [INFO] Current TPS: 20.0
20:54:58 [INFO] Load: 4.29%
20:54:58 [INFO] Network upload: 6.38 kB/s
20:54:58 [INFO] Network download: 4.24 kB/s
20:54:58 [INFO] Thread count: 13
20:54:58 [INFO] Used memory: 131.62 MB. (3.35%)
20:54:58 [INFO] Total memory: 3925.5 MB.
20:54:58 [INFO] Maximum VM memory: 3925.5 MB.
20:54:58 [INFO] Available processors: 2
20:54:58 [INFO] Players: 10 online, 50 max.
20:54:58 [INFO] World "world": 161 chunks, 2 entities, 131 blockEntities. Time 0.0ms
20:54:58 [INFO] World "skyblock0": 785 chunks, 15 entities, 168 blockEntities. Time 1.0ms

**Comment by Pub4Game** [comment]
Maybe it's the fault of your plugin?
![image](https://cloud.githubusercontent.com/assets/11244874/18408788/6b372e24-7742-11e6-8a64-d97d00da22d4.png)

**Comment by Creeperface01** [comment]
i also have this problem with 70 - 90 players nukkit takes over 2 GB RAM

**Comment by Creeperface01** [comment]
but its on bedwars

**Comment by Creeperface01** [comment]
> status
09:56:39 [INFO] ---- Server status ----

> 09:56:39 [INFO] Uptime: 0 days 0 hours 46 minutes 15 seconds

> 09:56:39 [INFO] Current TPS: 20.0

> 09:56:39 [INFO] Load: 3.42%

> 09:56:39 [INFO] Network upload: 0.0 kB/s

> 09:56:39 [INFO] Network download: 0.0 kB/s

> 09:56:39 [INFO] Thread count: 20

> 09:56:39 [INFO] Used memory: 621.35 MB. (34.13%)

> 09:56:39 [INFO] Total memory: 1434.0 MB.

> 09:56:39 [INFO] Maximum VM memory: 1820.5 MB.

> 09:56:39 [INFO] Available processors: 8

> 09:56:39 [INFO] Players: 44 online, 100 max.

> 09:56:39 [INFO] World "BedWars_hub": 337 chunks, 16 entities, 11 blockEntities. Time 0.0ms

> 09:56:39 [INFO] World "Phizzle_bw-3" (Phizzle): 25 chunks, 51 entities, 1 blockEntities. Time 0.0ms

> 09:56:39 [INFO] World "Phizzle_bw-5" (Phizzle): 231 chunks, 48 entities, 10 blockEntities. Time 0.0ms

> 09:56:39 [INFO] World "Nether_bw-2" (Nether): 237 chunks, 30 entities, 2 blockEntities. Time 1.0ms

> 09:56:39 [INFO] World "Kingdoms_bw-1" (Kingdoms): 472 chunks, 119 entities, 49 blockEntities. Time 0.0ms

**Comment by Pub4Game** [comment]
@Creeperface01 it too BedWars 💃

**Comment by NycuRO** [comment]
I don't have Bedwars @Pub4Game  and @Creeperface01 . Please @Pub4Game ,you can give me your nukkit.yml?

**Comment by NycuRO** [comment]
And server-proprietes @Pub4Game ? And what version you use? ;/

My plugins : 18:43:59 [INFO] Plugins (18): WorldEdit v1.0, EmptyWorld v0.0.1, EconomyAPI v1.0.1, MadPerms v1.0.0, EconomySell v1.0.1, SpamBan v1.0.0, TimeCommander v1.0.0, Presents v1.2, EconomyShop v1.0.1, FixBiome v0.0.1, FloatingText v1.1.1, Regions v0.0.4, BlockProtect v1.0.0, LeetTP v1.2.6-b29, EasyAuth v1.0.0, ToolsPro v0.0.4, AutoMessage v0.2, Mskyblock v2.0.6

**Comment by NycuRO** [comment]
![14248095_1687972548189511_1292437836_o 1](https://cloud.githubusercontent.com/assets/13573011/18411757/e9d09b28-7786-11e6-951b-eb7fe86b7c38.png)

With 700 chunks and 10 players....

My nukkit,yml : 

# Advanced configuration file for Nukkit
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
 #Multi-language setting
 #Available: eng, chs, cht, jpn, rus, spa, pol, bra, kor, ukr
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 shutdown-message: "Serverul se restarteaza..."
 #Allow listing plugins via Query
 query-plugins: true
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: true
 #Number of AsyncTask workers
 #If set to auto, it'll try to detect the number of cores (and at least 4)
 async-workers: 2

network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable
 batch-threshold: 256
 #Compression level used of Zlib when sending batched packets. Higher = more CPU, less bandwidth usage
 compression-level: 4
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: true

debug:
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables commands: /status /gc
 commands: true

timings:
 #Enable core and plugin timings by default
 enabled: false
 #Enable monitoring at verbose level, include high-frequency timings
 verbose: false
 #Interval between history frames in ticks
 #Default is 5 minutes (6000 ticks)
 history-interval: 6000
 #Length of the whole timing history in ticks
 #Default is 1 hour (72000 ticks)
 #This value is capped at a maximum of history-interval * 12
 history-length: 72000
 #For special cases of servers with special permission to bypass the max
 #This max helps keep data file sizes reasonable for processing on Aikar's Timing parser side
 #Setting this will not help you bypass the max unless Aikar has added an exception on the API side
 bypass-max: false
 #If set to true, name of your server won't be sent
 privacy: false
 #Settings sections to ignore. These sections won't be sent to Aikar's Timing parser
 #For example: [all] or [settings, timings]
 ignore: []

level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: true
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this
 always-tick-players: false

chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 1
 #Amount of chunks sent around each player
 max-chunks: 10
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 4
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: false

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 1
 #Radius of chunks around a player to tick
 tick-radius: 1
 light-updates: false
 clear-tick-list: false

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 1
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 1

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900

spawn-limits:
 #Max amount of these entities
 monsters: 70
 animals: 15
 water-animals: 5
 ambient: 15

aliases:
 #Aliases for commands
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)
 

And server-proprietes : 

#Properties Config file
#2016-09-09 08:53:51
motd=Â§6Â«Â«Â« Â§eNycuRO Â§6Â»Â»Â» Â§cÂ«Â«Â« Â§7SkyBlock Â§cÂ»Â»Â»
server-port=19135
server-ip=0.0.0.0
view-distance=1
white-list=0
announce-player-achievements=off
spawn-protection=500
max-players=50
allow-flight=off
spawn-animals=off
spawn-mobs=off
gamemode=0
force-gamemode=off
hardcore=off
pvp=off
difficulty=2
generator-settings=
level-name=world
level-seed=
level-type=emptyworld
enable-query=on
enable-rcon=off
rcon.password=zMDg1NTc2Z
auto-save=on
 

@Pub4Game @Creeperface01

**Comment by Creeperface01** [comment]
# Advanced configuration file for Nukkit
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading.

settings:
 #Multi-language setting
 #Available: eng, chs, cht, jpn, rus, spa, pol, bra, kor
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 shutdown-message: "Server closed"
 #Allow listing plugins via Query
 query-plugins: false
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: false
 #Number of AsyncTask workers
 #If set to auto, it'll try to detect the number of cores (and at least 4)
 async-workers: auto

network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable.
 batch-threshold: 128
 #Compression level used of Zlib when sending batched packets. Higher = more CPU, less bandwidth usage
 compression-level: 3
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: true

debug:
 #If > 1, it will show debug messages in the console
 level: 2
 #Enables commands: /status /gc
 commands: true

level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: true
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: false

chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 4
 #Amount of chunks sent around each player
 max-chunks: 96
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 1
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 50
 #Radius of chunks around a player to tick
 tick-radius: 3
 light-updates: false
 clear-tick-list: true

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 8
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 8

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900

spawn-limits:
 #Max amount of these entities
 monsters: 70
 animals: 15
 water-animals: 5
 ambient: 15

aliases:
 #Aliases for commands
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

**Comment by Creeperface01** [comment]
can it be caused by chunk caching?

**Comment by NycuRO** [comment]
Idk...

**Comment by NycuRO** [comment]
In genisys php not have this problem

**Comment by NycuRO** [comment]
@Creeperface01 Please,you can give me SynapseAPI.jar if you have jar? Please creeper :+1:

**Comment by MagicDroidX** [comment]
Try to reduce the "Maximum VM memory". It may dues to the Java Memory Management.

**Comment by NycuRO** [comment]
@MagicDroidX ... example?

**Comment by Creeperface01** [comment]
@NycuRO why? its broken....

**Comment by NycuRO** [comment]
@Creeperface01 What it's broken?

**Comment by NycuRO** [comment]
@Creeperface01 For test Synapse in Nukkit..
