### ISSUE TITLE
Non issue: Banned on forums

### ISSUE THREAD

**Issue by TheAppleGamer** [Nukkit/Nukkit#1031]
### Issue description

Write a short description about the issue
I just went to the website for the first time to find my ip was banned
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Nukkit:
* OS:
* Device:

### Crashdump, backtrace or other files

* ...

**Comment by Tee7even** [comment]
Heh, there's much people banned by IP, including myself, looks like someone just banned the whole country or something.
![image](https://cloud.githubusercontent.com/assets/6763610/18417772/ce37b8c2-7841-11e6-986b-106c5c009358.png)

**Comment by NycuRO** [comment]
And i i'm banned.... @MagicDroidX

**Comment by flaxues** [comment]
I'm also banned

**Comment by MagicDroidX** [comment]
I've blocked the ip ranges of the spammer but Xenforo somehow banned other ips. Fixed.
