### ISSUE TITLE
Feature: Synapse support

### ISSUE THREAD

**Issue by DaMatrix** [Nukkit/Nukkit#1032]
iTXTech has created a program called [Nemisys](https://github.com/iTXTech/Nemisys) (java version) and [Synapse](https://github.com/iTXTech/Synapse) (PHP version) which acts like BungeeCord for Pocket Edition.  The protocol doesn't seem too complicated to implement, and I think this would be a feature that a lot of people woud make use of.

### OS and versions

* Nukkit: all
* OS: all
* Device: all

**Comment by Pub4Game** [comment]
This will not be implemented in Nukkit.
