### ISSUE TITLE
water/lava bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1035]
### Issue description

![image](https://cloud.githubusercontent.com/assets/10363500/18608041/6fe6cd48-7cde-11e6-8232-0fb9b631fce7.png)
### Steps to reproduce the issue

idk just find water? :D
### OS and versions

Android / windows 10

**Comment by PeratX** [comment]
Chunk broader?

**Comment by Creeperface01** [comment]
and how to fix it?

**Comment by MagicDroidX** [comment]
This might be a client-side issue. I've also found this on WIN10E but it seems fine on PE.

**Comment by yescallop** [comment]
Sometimes PE has this bug, too. It's also on other blocks, especially on flat world
