### ISSUE TITLE
Not able to join the server

### ISSUE THREAD

**Issue by KingHorse2015** [Nukkit/Nukkit#1036]
Not able to join with latest version of win 10
![knipsel2](https://cloud.githubusercontent.com/assets/15171668/18608709/fee36288-7cf0-11e6-96bc-f50295c78bb8.PNG)

1. launch the latest version of nukkit
2. update mcpe win10 version to latest

* Nukkit: latest 17 sep
* OS: windows 10 1607
* Device: Desktop

Thanks Nick

**Comment by MagicDroidX** [comment]
This may due to the UWP Loopback and you can try connect Nukkit with external IP address.
