### ISSUE TITLE
A bug with the fallout from the world

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#104]
Fall out of the world, click "Respawn", but nothing happens

**Comment by caoli5288** [comment]
Any console output?

**Comment by Pub4Game** [comment]
Nothing, just fall out of the world

**Comment by Pub4Game** [comment]
@MagicDroidX and fix it)) Please

**Comment by MagicDroidX** [comment]
@Pub4Game How to reproduce. :)

**Comment by Pub4Game** [comment]
Just fall out of the world....
