### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#105]
![image](https://cloud.githubusercontent.com/assets/11244874/11533165/58ce112e-9919-11e5-85e2-2e39bc833075.png)

**Comment by MagicDroidX** [comment]
I have just update the pom.xml

**Comment by Pub4Game** [comment]
ok. Thanks

**Comment by Pub4Game** [comment]
Still the same error

**Comment by MagicDroidX** [comment]
I will check it out. Looks like travis ci build passed.

**Comment by MagicDroidX** [comment]
Try to add the module in Project Structure-> Module -> from maven

**Comment by Pub4Game** [comment]
?
![image](https://cloud.githubusercontent.com/assets/11244874/11533838/cce5f786-991c-11e5-8b59-fb95bb6f4549.png)
