### ISSUE TITLE
PR's

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1051]
### Issue description

Write a short description about the issue
Hello all. I have one question. Why not accept or close pull requests? Exist 10 pull request usefull and is not accepted. Why?

If you not accept,you can close? 

Just give advice. If not in use, you can close them . Some think that they are not interested ..

And genisys ( php software mcpe ) have one generator with name NORMAL1 , you can add and in nukkit? :)
### Steps to reproduce the issue

1. ...Not exist
2. ...

### OS and versions

* Nukkit:no need
* OS:no need
* Device:no need

### Crashdump, backtrace or other files

* ...

**Comment by Pub4Game** [comment]
Use forum nukkit.io for questions.
