### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#106]
![image](https://cloud.githubusercontent.com/assets/11244874/11534211/99a030e2-991e-11e5-9e25-ceb04be4d92f.png)
![image](https://cloud.githubusercontent.com/assets/11244874/11534228/b3da20e4-991e-11e5-824e-09226abf3c75.png)

**Comment by MagicDroidX** [comment]
It is still **NEED FIX** now :D

**Comment by Pub4Game** [comment]
This happens even if you create a flat world =_=

**Comment by Pub4Game** [comment]
@MagicDroidX Old version Nukkit
![image](https://cloud.githubusercontent.com/assets/11244874/11610598/f1ac8a64-9bb8-11e5-84ab-d805be756e25.png)
