### ISSUE TITLE
Buttons (in redstone circuits) are not implemented

### ISSUE THREAD

**Issue by bonnedav** [Nukkit/Nukkit#1060]
### Issue description

The Sever wont let me place buttons.
When I try to place a button it just goes away after a second.

### Steps to reproduce the issue

1. Just try to place a button.

### OS and versions

* Nukkit: 1.0dev ???(Apple)?(Pie)?
* OS: Windows 10
* Device: Android

### Crashdump, backtrace or other files

* ...

**Comment by Snake1999** [comment]
An unimplemented feature here :3

**Comment by bonnedav** [comment]
Well, could someone fix this and pressure plates for me please. Because this it a deal breaker for me.

**Comment by Snake1999** [comment]
If you are here only to ask without contributing, daydreaming anyone would do everything for you, you are wrong. Here we are a open-source team - that means you should give before you take

**Comment by bonnedav** [comment]
I am sorry. I was tired and not thinking straight. I did not intend to be rude but I realize now that I was. I am sorry.
