### ISSUE TITLE
How to remove spam in unix console

### ISSUE THREAD

**Issue by Dakado** [Nukkit/Nukkit#1062]
I have big issues running nukkit on unix systems because my console is spammed by the informations that are normally in windows displayed in the console frame:

This is the spam in the `console:
`> ]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.36%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.33%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.33%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.39%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.32%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.27%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 18.69%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.37%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 1.76%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 1.76%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.27%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 1.1%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.34%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.28%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.31%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 2.46%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.24%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.36%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.41%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.3%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.98%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.35%]0;Nukkit 1.0dev | Online 0/20 | Memory 2% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 0.77%list
`

How do I remove this spam and color formatting ?

Thanks.

**Comment by Snake1999** [comment]
Your console seems does not support jansi. Try edit your starting batch file from `java -jar nukkit.jar` to `java -jar nukkit.jar --disable-ansi`
Jansi is something that makes your console colorful, but a small amount of devices does not support it. I suggest you to have your operating system and java runtime updated to the latest.

**Comment by Dakado** [comment]
Thanks, however it still prints plenty of those random characters.
