### ISSUE TITLE
Big chunks of stone just pop up.

### ISSUE THREAD

**Issue by Kjgohr5600** [Nukkit/Nukkit#1063]
## **Issue description**

Ok, so on my map (which is a flap map) this just big chunks of stone appear, and the appear randomly. For example, one day a big chunk of stone may not be there, then the next it will just appear. And the ruin building (they spawn on top of them. and when I use world-edit to remove them they just come back. Can someone tell me why this is happening.
OS and versions:
- Nukkit
- OS: Window 10
- Minecraft Windows 10 Beta

Here's a picture:
![screenshot 19](https://cloud.githubusercontent.com/assets/17054680/18898030/b79469b8-84e3-11e6-822b-72656a423be9.png)

**Comment by Muqsit** [comment]
Could mean three things.
Your chunk was corrupted.
That chunk was never generated.
Your (nukkit) generator isn't a flat world.

**Comment by Kjgohr5600** [comment]
What do you mean "corrupted".

**Comment by Kjgohr5600** [comment]
And if it wasn't set to flat, how do I fix it

**Comment by Creeperface01** [comment]
this chunk could not be loaded or just is missing

**Comment by Snake1999** [comment]
I cannot understand what you said...

**Comment by Kjgohr5600** [comment]
@Snake1999 I was saying that my map, which is a flat world keeps developing big chunks of stone, and placing them in random places (in buildings, etc..)

**Comment by Kjgohr5600** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17054680/18936740/bddf5ba0-859e-11e6-88dd-2321593fe637.png)

Could it have something to do with this. I am so confused.

**Comment by Kjgohr5600** [comment]
![screenshot 22](https://cloud.githubusercontent.com/assets/17054680/18936745/db49ead4-859e-11e6-8cdc-5084dc6f26f3.png)

Could it have something to do with this. I am so confused.

**Comment by imjack** [comment]
I think the chunk is corrupt or it can't be loaded by Nukkit. So it generates a chunk to send it to the player.

**Comment by Kjgohr5600** [comment]
Ok, but I DON'T KNOW HOW TO FIX IT... Lol

**Comment by Kjgohr5600** [comment]
Wrong button.. lol

**Comment by MrPowerGamerBR** [comment]
@Kjgohr5600 you can't "uncorrupt" a chunk, if it is a PC map, you can try loading it on Minecraft and walking around, however this will regen the corrupt chunks, but may fix the error you are having.

**Comment by MrPowerGamerBR** [comment]
Okay, it is a leveldb file.

Sometimes the chunk isn't corrupted, only the NBT data is (due to some item/entity/etc) but Nukkit considers the chunk to be corrupted, causing the regen.

The only way to try is by making Nukkit more "lenient" on NBT errors.
