### ISSUE TITLE
@MagicDroidX broke Nukkit

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1068]
### Issue description
Every version after [this commit](https://github.com/Nukkit/Nukkit/commit/74ed06abfc8d01f1c7c5f81094fd4daee2a5492f) is broken, the server shows as offline and nobody can connect (shows the server is offline)

Versions before this commit works fine, as a reference, build 1368 works, but build 1370 is broken and every version after 1370 has the same issue.

### Steps to reproduce the issue
1. Download the latest build
2. Run Nukkit
3. Try to connect to the server

### OS and versions

* Nukkit: Este servidor estß rodando Nukkit 1.0dev ???(Apple)?(Pie)? implementando versÒo da API 1.0.0 para Minecraft: PE v0.15.9 alpha (versÒo do protocolo 83)
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files

No errors.

**Comment by Muqsit** [comment]
I can confirm this issue. I thought I was the only one lol

**Comment by MrPowerGamerBR** [comment]
#1069 fixes this issue without removing everything @MagicDroidX made on that commit.

**Comment by Snake1999** [comment]
Try it now as #1069 merged?)

**Comment by yescallop** [comment]
it works fine

**Comment by Muqsit** [comment]
Close issue

**Comment by Muqsit** [comment]
And GG =D
