### ISSUE TITLE
How to run nukkit

### ISSUE THREAD

**Issue by SavionLegendZzz** [Nukkit/Nukkit#107]
how do i run nukkit?

**Comment by Angelic47** [comment]
first, you need to compile nukkit. there are many ways to compile nukkit, such as using maven.
1.run "git submodule update --init", which to download language files' submodule.
2.run "mvn clean package" and you will get a jar.
finally, simply run "java -jar nukkit.jar", you will start nukkit successfully and enjoy.

**Comment by SavionLegendZzz** [comment]
hmmm i have the jar do i do this in command prompt

**Comment by Angelic47** [comment]
hmm if you have the jar (update to newest recommend), then you needn't to compile nukkit again
just run "java -jar nukkit.jar" to start it

**Comment by CavinMiana** [comment]
I would close this lol
