### ISSUE TITLE
Double Flower issues... a lot of issues...

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1075]
### Issue description
Something that I found randomly

### Steps to reproduce the issue
1. Get any double block flower
2. Place it
3. The flower will be placed and two *insert flower you placed here* will be dropped too

### OS and versions
* Nukkit: Este servidor estß rodando Nukkit 1.0dev ???(Apple)?(Pie)? implementando versÒo da API 1.0.0 para Minecraft: PE v0.15.9 alpha (versÒo do protocolo 83)
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files
GitHub isn't allowing placing this GIF because it is too big, here's the direct link: http://i.imgur.com/2I4YrkX.gif

**Comment by File14** [comment]
I have the same issuse! It does it for Double grass as well! Please fix this!

**Comment by MrPowerGamerBR** [comment]
![http://i.imgur.com/7g1Hcjb.png](http://i.imgur.com/7g1Hcjb.png)

Doing this fixes the drop issue, however breaks the plant physics (if you break the bottom half of the plant, the top part doesn't break and vice-versa)

**Comment by MrPowerGamerBR** [comment]
Update: Breaking a double flower also drops two flowers.

**Comment by MrPowerGamerBR** [comment]
Update²: Breaking the top half of a double flower drops nothing, but breaking the bottom half of a double flower drops two flowers.

**Comment by File14** [comment]
Cool! :D
