### ISSUE TITLE
freeze for 1 minutes. multiple world teleport

### ISSUE THREAD

**Issue by jhelom** [Nukkit/Nukkit#1086]
### Issue description
freeze for 1-2 minutes of client and server. 
multiple world teleport repeating.
no plugins.

### Steps to reproduce the issue

1. teleport world A -> B
2. teleport world B -> C
3. teleport world C -> D
4. freeze (1-2 minutes)
5. unfreeze, move again

### OS and versions
* Nukkit: 5c3b378902780625831027a685df3c4ba2d1d3f0
* OS: Ubuntu
* Device: iOS / PE v0.15.9

### Crashdump, backtrace or other files
* none

**Comment by yescallop** [comment]
how can you do this without plugin

**Comment by Snake1999** [comment]
Ask your plugin author to find out why.
