### ISSUE TITLE
Buttons and redstone

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1089]
Sorry for not all question and other have this issue,but is not one bug. You can implement redstone,please?

Buttons and preasure plates,not all. ClearSky have more more more more better redstone ,but is PHP ,not java.

ClearSky is epic because have all redstone compatible with SinglePlayer ( all works as SinglePlayer ) .

You can translate redstone from ClearSky and add to nukkit? Thanks all :)

I'm watch @Creeperface01 like java. Creeper,you can help with implementation redstone? :) Thanks :)
# Nukkit_Epic_Java_Software

**Comment by Creeperface01** [comment]
@NycuRO already helped :D close
