### ISSUE TITLE
Previously generated world issue

### ISSUE THREAD

**Issue by haniokasai** [Nukkit/Nukkit#1094]
### Issue description

When i join in generated world,client crash.
### Steps to reproduce the issue

1. ..When i join in generated world,client crash..
2. ..but i create new world and join in it,i can join..
### OS and versions

- Nukkit: latest version
- OS:ubuntu
- Device:0.15.10
### Crashdump, backtrace or other files

- ...

**Comment by Snake1999** [comment]
What?

**Comment by MrPowerGamerBR** [comment]
@Snake1999 probably his world contains invalid blocks and this causes a client crash.

But when he generates a new world, it doesn't crash.

**Comment by haniokasai** [comment]
＠MrPowerGamerBR　i thought like it,however i use  this build(http://ci.mengcraft.com:8080/job/nukkit/451/) and change protocol 83 to 84,i could join.

**Comment by haniokasai** [comment]
this world....  http://archive.haniokasai.com/nukkit/worlda.tar.gz

**Comment by MrPowerGamerBR** [comment]
@haniokasai will checkout your world later, but fixing those world issues are incredibly difficult.

**Comment by haniokasai** [comment]
i dont know why i can join in this map at genisys but i cant join in it at nukkit.

**Comment by IrishUHC** [comment]
I can confirm this issue.
