### ISSUE TITLE
Item durability is broken

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1105]
### Issue description
Okay, I don't know if this was already implemented in Nukkit, however I noticed this now and I thought I should report it.

### Steps to reproduce the issue
1. Get any tool
2. Try to use the tool
3. The durability bar doesn't decrease

### OS and versions

* Nukkit: Este servidor estß rodando Nukkit 1.0dev ???(Apple)?(Pie)? implementando versÒo da API 1.0.0 para Minecraft: PE v0.15.10 alpha (versÒo do protocolo 84)
* OS: Windows 10 and Android 6.0.1
* Device: PC and Moto G Turbo

### Crashdump, backtrace or other files
![http://i.imgur.com/l5gVsBW.gif](http://i.imgur.com/l5gVsBW.gif)
(look at the diamond shovel, also ignore that dirt, MCW10 issue)

**Comment by MrPowerGamerBR** [comment]
Again, I don't remember if this was implemented before in Nukkit (even tho it should be very easy to implement if it isn't). No plugins, so it isn't a plugin fault.

**Comment by Snake1999** [comment]
An unimplemented feature here :)

**Comment by MrPowerGamerBR** [comment]
@Snake1999 seriously? I thought it was already implemented :yum:

Doesn't seem to difficult to implement tho, we already have the getMaxDurability() of every item (well, I hope getMaxDurability() does work, didn't try yet), just add 1 to the item durability on every tool use and check if the getMaxDurability() > durability, done.

**Comment by Snake1999** [comment]
Try again as #1111 merged?)

**Comment by kniffo80** [comment]
Can confirm it works. I think this one can be closed for now.

**Comment by MrPowerGamerBR** [comment]
Can confirm, thanks @boy0001!
