### ISSUE TITLE
Tall Flowers and Anvil

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1115]
Sorry for non uses steps ,but isn't needed.

@Creeperface01 has commited : Add anvil and etc..

But,anvil not work on Windows10 Edition...

And if i'm placed Double Tall Flowers is ok. If i'm break ,ok is breakable. If i'm exit and enter again,flower not break. Tested bugs on Windows 10 Edition with:

Version nukkit : https://github.com/Nukkit/Nukkit/commit/efa7b77c7e82a48bcbe4482c818f00c5ae788491
Version MCPE: MC Windows 10 Edition Beta 0.15.10.
Hosted: On Ubuntuu 16.04.1 LTS 64bit

Bug on Anvil _probably how fix_ : If i'm put item in Anvil. Anvil is duplicate and in Anvil,and in inventory. For fix probably anvil ,need fix this problem 👍 

Items is not duplicate,but get close action of Anvil.

**Comment by IrishPacks** [comment]
W10 will always ruin our server softwares. I'll try to make a commit that fixes W10 for good.
