### ISSUE TITLE
Slabs and Stairs bug

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1126]
Slabs and Stairs have one bug...

I still give back. If you do not believe me, I invite you to see the server.

Version nukkit : efa7b77
Version MCPE: MC Windows 10 Edition Beta 0.15.10.
Hosted: On Ubuntuu 16.04.1 LTS 64bit

![image](https://cloud.githubusercontent.com/assets/13573011/19221831/eeac1bac-8e53-11e6-92e2-12f07d216fea.png)

**Comment by caspervanneck** [comment]
@NycuRO its true i have it on windows 10
