### ISSUE TITLE
Chest are useless/ don't save

### ISSUE THREAD

**Issue by AGTInformous** [Nukkit/Nukkit#1129]
Hello everyone,
There's a bad bug in Nukkit. The chest are useless; You can't save things in them. And what is Minecraft without chests? :/

Steps to reproduce the issue:
1. Build a Chest
2. Put things into it
3. close the chest, open it again
4. The things disappeared...
- Nukkit: 1.0dev ???
- OS: Windows 10 (Server); Android (Client)
- Device: S6 Edge (Client)

**Comment by MrPowerGamerBR** [comment]
I couldn't reproduce this bug:

1. Place a chest
2. Put 64 tulips inside of the chest
3. Closed the chest
4. Opened the chest, they are still in there
5. Rebooted the server
6. Yep, still in the chest.

OS: Windows 10
Device: PC (Minecraft Windows 10 Edition)

**Comment by AGTInformous** [comment]
Oh... I don't understand this. Maybe because I use the 0.15.9 Server with an 0.15.10 Client?

**Comment by MrPowerGamerBR** [comment]
@AGTInformous do you have any plugins? I doubt that it is a protocol problem.

**Comment by AGTInformous** [comment]
Yes I have many plugins, one is "AnyVersion" because without this I can't join the Server.

**Comment by MrPowerGamerBR** [comment]
@AGTInformous try removing all plugins and try again (and keep AnyVersion because I still doubt that it is due to AnyVersion), if the items is inside the chest after doing your steps, then it is a plugin causing that issue.

**Comment by Pub4Game** [comment]
@AGTInformous please update nukkit to latest build

**Comment by AGTInformous** [comment]
Hm I tried it with the old version with AnyVersion and it hasn't worked.. Same with the lastest build without any plugin. :/

**Comment by AGTInformous** [comment]
Oh if I'm in the survival mode it works
