### ISSUE TITLE
re-enter join bug "Disconnected form Server"

### ISSUE THREAD

**Issue by tigerza117** [Nukkit/Nukkit#1142]
### Issue description

Write a short description about the issue
### Steps to reproduce the issue

1. re-enter join bug "Disconnected form Server"
   clip https://www.youtube.com/watch?v=GT7BnXNvPAE&feature=youtu.be
### OS and versions

- Nukkit: latest update
- OS: Linux
- Device: CPU E3-1240v5 3.5GHz Ram 32Gb SharePort Server

**Comment by IrishUHC** [comment]
i have the same type of issue, it just crashes my game instead.
