### ISSUE TITLE
incorrect work of the game modes

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#115]
Game modes (2,3) do not work correctly.

**Comment by CavinMiana** [comment]
I did not even know there was a 2 and 3 lol. I thought it was just 0, and 1.

**Comment by CavinMiana** [comment]
I just checked the code and it seems fine to me. Try testing it again.

**Comment by Pub4Game** [comment]
I can break blocks in adventure mode... 

I can't fly in spectator mode

**Comment by Pub4Game** [comment]
@MagicDroidX When you turn on gamemode 3, you are given a block of "Stone"

**Comment by Pub4Game** [comment]
If you use "((Player) sender).setGamemode(3);" the interface does not change!
![image](https://cloud.githubusercontent.com/assets/11244874/11630974/f59c86c0-9d10-11e5-8c63-1aecf1e02275.png)


if use command /gamemode 3

![image](https://cloud.githubusercontent.com/assets/11244874/11631055/533be6c2-9d11-11e5-8c84-f3e0fd4af399.png)

**Comment by Pub4Game** [comment]
@MagicDroidX plwase fix

**Comment by MagicDroidX** [comment]
@Pub4Game Cannot reproduce it.

**Comment by Pub4Game** [comment]
@MagicDroidX 
![image](https://cloud.githubusercontent.com/assets/11244874/12005523/bde7a706-abba-11e5-8f4b-e51a5acac9b3.png)

Here is another example of a bug with the interface

**Comment by MagicDroidX** [comment]
You can double click the jump buttom, can't you?

**Comment by Pub4Game** [comment]
I clicked.... But it's survival.... And I switched to it from gamemode - 3

**Comment by MagicDroidX** [comment]
OK, I see. I'll try to fix this.

**Comment by MagicDroidX** [comment]
It seems that PocketMine has the same issue, however i will fix this.

**Comment by Niall7459** [comment]
You're not meant to be able to break blocks when in adventure mode...
