### ISSUE TITLE
PlayerList Not Update

### ISSUE THREAD

**Issue by tigerza117** [Nukkit/Nukkit#1156]
### Issue description
PlayerList Not Update

### OS and versions

* Nukkit: https://github.com/Nukkit/Nukkit/tree/32c322802204be2c202048a9027c026e766833bd
* OS: Centos 7
* Device: Device: CPU E3-1240v5 3.5GHz Ram 32Gb SharePort Server
https://drive.google.com/file/d/0B8zmPEDhW28MbXk5WUJ4OGdRazA/view?usp=sharing

**Comment by OverTook** [comment]
I have same problem :D

**Comment by jhelom** [comment]
I have encounter the same issue.
