### ISSUE TITLE
FloatingTextParticle Error

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1160]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... Make a textparticle on your server.
2. ... It makes Rope and it doesn't work.

### OS and versions

* Nukkit: 0.15.10
* OS: 0.15.10
* Device: LG X Screen

**Comment by Snake1999** [comment]
I'm afraid this design itself is not a good idea to make the entity into a form of a particle. Maybe generate a floating text entity instead?

**Comment by Pub4Game** [comment]
Confirm

**Comment by OverTook** [comment]
@Snake1999 mojang removed Entity ID -1 in mcpe 0.15.0.

Genisys changed their Entity ID. plz fix it. sorry..

https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/level/particle/FloatingTextParticle.php

**Comment by Pub4Game** [comment]
check again

**Comment by Creeperface01** [comment]
yes, im using entity instead of particle on my server.. because players then see this particle on all worlds and i must spawn it to every player... when i create entity for that its better

**Comment by File14** [comment]
I'm using FloatingTextParticle and it works good, however I would recommend using it as @Creeperface01 does.

**Comment by Snake1999** [comment]
@OverTook Check it again.

**Comment by OverTook** [comment]
@Snake1999 https://github.com/MCFT-Server/FloatingText/issues/1

    .

**Comment by OverTook** [comment]
@Snake1999 I heard that the FloatingTextParticle's Entity ID had been removed.

**Comment by Creeperface01** [comment]
No players? :O

**Comment by File14** [comment]
It's not removed. 
@OverTook please close this "issue" there is nothing wrong with the floatingtextparticle.

**Comment by Snake1999** [comment]
@OverTook The particle for floating text is one of the worst design I have ever heard, Nukkit only added this as for compatibility.
To display floating text in clients, clients should receive an invisible entity. Creating more and more 'particles' will make the server get slower as particles can not be removed or edited as entities.
My opinion, do not use this particle anymore, it is **deprecated**.
