### ISSUE TITLE
Signs on spawn.

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1163]
Version nukkit : https://github.com/Nukkit/Nukkit/commit/32c322802204be2c202048a9027c026e766833bd
Version MCPE: MC Windows 10 Edition Beta 0.15.10.
Hosted: On Ubuntuu 16.04.1 LTS 64bit

If you break signs with TEXT in spawn , sign appereal without text.

**Comment by Snake1999** [comment]
I think this might be caused by **spawn protection**. Disable the spawn protection in config and try again ?)
