### ISSUE TITLE
Flat World Bug

### ISSUE THREAD

**Issue by tigerza117** [Nukkit/Nukkit#1166]
### Issue description
*i am noob eng -.-

When you place a block into a new flat in the first went to the chunk. So it will block any place Onew.

https://drive.google.com/file/d/0B8zmPEDhW28MSHozRkYwTktEeWM/view?usp=sharing

### OS and versions

* Nukkit: latest update
* OS: Centos7
* Device: CPU E3-1240v5 3.5GHz Ram 32Gb SharePort Server

**Comment by Snake1999** [comment]
Duplicate https://github.com/Nukkit/Nukkit/issues/772
