### ISSUE TITLE
Bug BlockItemFrame

### ISSUE THREAD

**Issue by tigerza117** [Nukkit/Nukkit#1175]
### Issue description
jva.lang.NullPointerExceptionat cn.nukkit.block.BlockItemFrame.onActivate(BlockItemFrame.java:50)  at cn.nukkit.level.Level.useItemOn(Level.java:1812)  at cn.nukkit.Player.handleDataPacket(Player.java:1960)  at cn.nukkit.network.Network.processPackets(Network.java:188)  at cn.nukkit.network.Network.processBatch(Network.java:164)  at cn.nukkit.Player.handleDataPacket(Player.java:1750)  at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)  at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)  at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)  at cn.nukkit.network.Network.processInterfaces(Network.java:75)  at cn.nukkit.Server.tick(Server.java:989)  at cn.nukkit.Server.tickProcessor(Server.java:786)  at cn.nukkit.Server.start(Server.java:765)  at cn.nukkit.Server.(Server.java:456)

https://www.youtube.com/watch?v=D5mUNx5wdWk

### OS and versions

 * Nukkit: https://github.com/Nukkit/Nukkit/commit/5885d4247651c84b055aa150ae487bb4bfbd271c
* OS: Centos 7
* Device: Device: CPU E3-1240v5 3.5GHz Ram 32Gb SharePort Server

**Comment by Snake1999** [comment]
Duplicate https://github.com/Nukkit/Nukkit/issues/1171
