### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1176]
### Issue description
server uses a lot RAM

### Steps to reproduce the issue
idk

### OS and versions
latest

### Crashdump, backtrace or other files
0:00:05 [INFO] ---- Server status ----

> 00:00:05 [INFO] Uptime: 0 days 19 hours 57 minutes 56 seconds

> 00:00:05 [INFO] Current TPS: 20.0

> 00:00:05 [INFO] Load: 0.47%

> 00:00:05 [INFO] Network upload: 0.0 kB/s

> 00:00:05 [INFO] Network download: 0.0 kB/s

> 00:00:05 [INFO] Thread count: 359

> 00:00:05 [INFO] Used memory: 1787.92 MB. (88.95%)

> 00:00:05 [INFO] Total memory: 2010.0 MB.

> 00:00:05 [INFO] Maximum VM memory: 2010.0 MB.

> 00:00:05 [INFO] Available processors: 8

> 00:00:05 [INFO] Players: 3 online, 200 max.

> 00:00:05 [INFO] World "lobby": 159 chunks, 13 entities, 19 blockEntities. Time 0.0ms

should it use 1787 mb? on my second server, there is over 1000 - 2000 chunks, 100 players and RAM usage is up to 1 - 2 GB

**Comment by Snake1999** [comment]
Who make 359 threads running at the same time? Check your config (max workers), and check your plugins as well. :)

**Comment by NycuRO** [comment]
I can confirm. But i changed the config from Genisys and fixed issue more.
I'm using and Time-Commander with " gc " in 5 mins because uses more more more more.
For me , it's ok now.

**Comment by Creeperface01** [comment]
Yes im using threads in my plugin :D thxi didnt notice that

**Comment by Creeperface01** [comment]
status
10:09:36 [INFO] ---- Server status ----

> 10:09:36 [INFO] Uptime: 0 days 6 hours 7 minutes 25 seconds

> 10:09:36 [INFO] Current TPS: 20.0

> 10:09:36 [INFO] Load: 1.64%

> 10:09:36 [INFO] Network upload: 0.0 kB/s

> 10:09:36 [INFO] Network download: 0.0 kB/s

> 10:09:36 [INFO] Thread count: 19

> 10:09:36 [INFO] Used memory: 1235.03 MB. (67.84%)

> 10:09:36 [INFO] Total memory: 1413.0 MB.

> 10:09:36 [INFO] Maximum VM memory: 1820.5 MB.

> 10:09:36 [INFO] Available processors: 8

> 10:09:36 [INFO] Players: 24 online, 200 max.

> 10:09:36 [INFO] World "lobby": 199 chunks, 34 entities, 19 blockEntities. Time 0.0ms

OK now there is 19 threads and still eats 1400 mb...

**Comment by Creeperface01** [comment]
and workers are set to "auto"

**Comment by Pub4Game** [comment]
```
---- Server status ----
Uptime: 1 days 0 hours 55 minutes 51 seconds
Current TPS: 20.0
Load: 20.11%
Network upload: 61.93 kB/s
Network download: 6.98 kB/s
Thread count: 36
Used memory: 2100.02 MB. (53.04%)
Total memory: 3882.06 MB.
Maximum VM memory: 3959.5 MB.
Available processors: 24
Players: 18 online, 1000 max.
World "world": 1355 chunks, 33 entities, 2714 blockEntities. Time 1.0ms
```

**Comment by Creeperface01** [comment]
As i said.. Other my servers like bedwars uses very little RAM..

**Comment by Snake1999** [comment]
My server has 24 CPU cores, and use 30 to 40 threads. What happened to your plugin? Will it better if use workers instead of memory-eating threads?)

**Comment by NycuRO** [comment]
@Snake1999 Can you give me your server?

**Comment by NycuRO** [comment]
@Creeperface01 Use my nukkit.yml for fix:

# Advanced configuration file for Nukkit
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
 #Multi-language setting
 #Available: eng, chs, cht, jpn, rus, spa, pol, bra, kor, ukr, deu
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 shutdown-message: "Â§eServerul de Â§cBlockParty Â§ese restarteaza...\nÂ§aIntra iar din hub."
 #Allow listing plugins via Query
 query-plugins: false
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: false
 #Number of AsyncTask workers
 #If set to auto, it'll try to detect the number of cores (and at least 4)
 async-workers: 6

network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable
 batch-threshold: 256
 #Compression level used of Zlib when sending batched packets. Higher = more CPU, less bandwidth usage
 compression-level: 4
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: true

debug:
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables commands: /status /gc
 commands: true

timings:
 #Enable core and plugin timings by default
 enabled: false
 #Enable monitoring at verbose level, include high-frequency timings
 verbose: false
 #Interval between history frames in ticks
 #Default is 5 minutes (6000 ticks)
 history-interval: 6000
 #Length of the whole timing history in ticks
 #Default is 1 hour (72000 ticks)
 #This value is capped at a maximum of history-interval * 12
 history-length: 72000
 #For special cases of servers with special permission to bypass the max
 #This max helps keep data file sizes reasonable for processing on Aikar's Timing parser side
 #Setting this will not help you bypass the max unless Aikar has added an exception on the API side
 bypass-max: false
 #If set to true, name of your server won't be sent
 privacy: false
 #Settings sections to ignore. These sections won't be sent to Aikar's Timing parser
 #For example: [all] or [settings, timings]
 ignore: []

level-settings:
 #The default format that levels will use when created
 default-format: anvil
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: false
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this
 always-tick-players: false

chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 1
 #Amount of chunks sent around each player
 max-chunks: 50
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 28
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 16
 #Radius of chunks around a player to tick
 tick-radius: 3
 light-updates: false
 clear-tick-list: true

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 2
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 2

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900

spawn-limits:
 #Max amount of these entities
 monsters: 70
 animals: 15
 water-animals: 5
 ambient: 15
 
player:
 #If true, player data will be saved as players/playername.dat
 #If false, nukkit won't save player data as "dat" files, in order that plugins can do something on it.
 save-player-data: true
 
aliases:
 #Aliases for commands
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:

**Comment by Creeperface01** [comment]
i tried to print name of all threads using getClass().getSimpleName() but somethreads havent name WTF?

**Comment by Creeperface01** [comment]
And im using only one thread to get data of subservers
