### ISSUE TITLE
PocketMine advanced, #NukkitGreat

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1177]
Now PocketMine is moved to https://github.com/pmmp/PocketMine-MP and have MORE MORE MORE bugs fixed and other features.

Nukkit is fork of PocketMine and have issues.. Anyone can port code from new-pocketmine for fix bugs?

Yes,not have enchanting and other as Nukkit PR's ( I don't know why developers not accept but no way ) ,but fixed bugs and is more ok.

And exist and 0.16 branch and blocks for 0.16 and Nukkit not have more in Creative-Inventory. 
Anyone can help to translate code for #NukkitGreat ?

**Comment by DaMatrix** [comment]
nukkit is NOT a fork of pocketmine. it's made in a completely different language, for starters.

**Comment by Snake1999** [comment]
For your word FORK, this issue does not any meaning at all
