### ISSUE TITLE
[0.16] Progress & Ideas for Working on 0.16

### ISSUE THREAD

**Issue by Snake1999** [Nukkit/Nukkit#1179]
This is an issue which we stuff discuss ideas and progress on 0.16 in, and will be closed after 0.16 works are done. If you have any idea, post it here :)

WIP: Wait In Peace. We are always doing - that means you needn't remind us to do it faster. If you need it now, you can contribute to our work and write code by yourself.

**Note: we are doing our work on master branch now**
- [X] Make client joinable
- [X] Client command auto-complete
- [x] Recheck all packets
- [x] Unsigned integers & longs (VarInt)support in network layer
- [ ] API for command auto-complete
- [ ] Game rules in client

For bugs found or features to check: (not only in win10)
- [x] Sounds unavailable (as packet changed in 0.16)
- [ ] Particles unavailable (?)
- [ ] Check if inventories works
- [ ] Check if entities works
- [ ] Take a look into client declared permissions system (?)

---

***0.16 clients are able to join Nukkit now (https://github.com/Nukkit/Nukkit/pull/1214), if you have no idea what on earth if one feature exists or not, you can try it out by yourself.
Next step will be APIs - to make features in 0.16 more easier to use by plugins.***

---

Thank you @File14 and @MrPowerGamerBR , our developers are looking into https://github.com/pmmp/PocketMine-MP/pull/42, https://github.com/iTXTech/Genisys/pull/2113 and https://github.com/iTXTech/Genisys/pull/2131. WIP :)

**Comment by File14** [comment]
**Useful links:** 
https://github.com/pmmp/PocketMine-MP/pull/42
https://github.com/iTXTech/Genisys/pull/2113

**Comment by Creeperface01** [comment]
so nukkit 0.16 branch is 0.15.90?

**Comment by Niall7459** [comment]
Will commands be Nukkit or Vanilla?

**Comment by kvetinac97** [comment]
I'm working on it

**Comment by MrPowerGamerBR** [comment]
I tried @kvetinac97 fork, while it doesn't work yet (the client crashes upon joining), I'm sure @kvetinac97 will be able to get 0.16.0 working on a Nukkit server. 👍

**Comment by Creeperface01** [comment]
MCPE crashes often, entity metadata is broken, (at least invisible doesn't work), underwater bubbles are still visible (maybe related to metadata)

**Comment by kvetinac97** [comment]
One of my builds fixed the lead bug, however, every other one is still here.

**Comment by Snake1999** [comment]
Added working progress; if any idea, don't show off that "I have an idea but you don't listen to me", contribute to our nukkit instead.

**Comment by boybook** [comment]
Significant development
![77ab53db40c02df0ab0d891329d34f05](https://cloud.githubusercontent.com/assets/8210983/19829767/f0fa27c2-9e1c-11e6-8a55-30a8ff00773c.jpg)
![fbf64e86983005d45c5dae8fe3f60e8d](https://cloud.githubusercontent.com/assets/8210983/19829783/3caf7d16-9e1d-11e6-80f6-80feb4e9ea2e.jpg)
![1428ec0634dac3ef1e70c2efa0cdb054](https://cloud.githubusercontent.com/assets/8210983/19829799/762e90b8-9e1d-11e6-8b1e-f10fc6138b3c.jpg)
![93d84a7865e676da8c09b0dfc6a656a5](https://cloud.githubusercontent.com/assets/8210983/19829808/96b12c9c-9e1d-11e6-8832-ca2f66f39da9.jpg)

**Comment by File14** [comment]
@Snake1999 https://github.com/iTXTech/Genisys/pull/2131

**Comment by MrPowerGamerBR** [comment]
Thanks for all the hard work @Snake1999 @Creeperface01 @boybook @yescallop! 👍 

If wasn't for everyone involved in the 0.16 fork, maybe Nukkit wouldn't even get updated to 0.16 and would be stuck forever in 0.15.10.

**Comment by Snake1999** [comment]
Now we can join server with 0.16 clients. Enjoy :)
https://github.com/Nukkit/Nukkit/pull/1214

**Comment by EnderKenji** [comment]
Please add 0.16 new items and functional sponge.

**Comment by Niall7459** [comment]
Hey, I start to work on villages and other biomes soon!

I am currently working on BigTrees!

**Comment by Creeperface01** [comment]
Awesome! Im very excited

**Comment by archie426** [comment]
Wouldn't the checklist be easier in projects? Don't get me wrong, why else would GH support tick boxes.

**Comment by Snake1999** [comment]
![](https://cloud.githubusercontent.com/assets/7609294/20025430/35bee7ec-a329-11e6-9d20-953d770c26b8.jpg)
0.16.1 came out. Should we do something ... to adapt it?

**Comment by yescallop** [comment]
@Snake1999 the protocol version is the same

**Comment by SuperMaXAleX** [comment]
No need to change something on it. The protocol is the same yea.

**Comment by Snake1999** [comment]
Sounds available now :) https://github.com/Nukkit/Nukkit/pull/1261

**Comment by NycuRO** [comment]
@Snake1999 Particles and sounds work all in windows 10

**Comment by File14** [comment]
Falling Blocks needs to be repaired. (Can't see them).

Commands needs to be fixed(Sometimes it says unknown command" on IOS).

**Comment by yescallop** [comment]
@File14 Falling Blocks have been fixed in #1256

**Comment by File14** [comment]
TNT needs to be fixed. (Explosion Particle & Sound)

**Comment by TheAppleGamer** [comment]
I have fixed the command bug but no one is going to accept a work around of it

**Comment by MattBDev** [comment]
Any chance of getting pistons added?
