### ISSUE TITLE
PR'S ,question. Please not close and read this.

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1189]
Sorry for this issue DEVS and sorry for flood, but i have an question. @Pub4Game @MagicDroidX @Snake1999 

Exist 16 PR'S and 8-9-10 is ready. Why isn't accepted or closed?
Man ,i know .... wait wait wait wait. It's hard to accept or close ,serious?

Isn't nab PR's ,is good PR's with enchanting fix, brewing ,more optimizations, more fix ,and isn't accepted.

All uses wait to accept PR's and not accepted. Why?

Because of this, no one is too involved to help, because he did not disregarded or did not consider codes.

Accept or refuse, once you choose that type finish. Even it is so hard?

I think you would need to care more and codes of others, not only of the "popular". Know that there are developers, not just @Creeperface01 or @boy0001 

Again sorry for this issue ,but if is ready PR , accept or reject. Isn't hard.

**Comment by IrishPacks** [comment]
I couldn't agree more.

**Comment by SupremeMortal** [comment]
You could just make a fork that accepts pull requests and updates from upstream like:

**Comment by NycuRO** [comment]
@IrishPacks Why not?
