### ISSUE TITLE
Big cpu load

### ISSUE THREAD

**Issue by daniktheboss** [Nukkit/Nukkit#1190]
### Issue description
When I run the server, one player on and not walking the cpu is at 100% load.

### Steps to reproduce the issue
1. Get a server
2. Join
3. 100% load

### OS and versions
* Nukkit: fresh install
* OS: linux
* Device: android 0.15.x

### Crashdump, backtrace or other files
None

**Comment by Snake1999** [comment]
How many CPU cores do you have? How much memory and brandwidth do you have? 
Nukkit is not suggested for too-low configurated computers, in my personal opinion, you should have more than 4 cores of CPU,   4GB of memory, and 10Mb brandwidth for 100 players online.

**Comment by daniktheboss** [comment]
20mb bandwidth, 1 player local, 4 cores, 2gb. Zero plugins fresh install.

**Comment by daniktheboss** [comment]
WHY ARE U CLOSING IT?! MY PC IS FINE AND NUKKIT IS FRYING PCS!

**Comment by boy0001** [comment]
@daniktheboss 
Can you do `/timings on` and then five minutes later do a `/timings paste`?
