### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#120]
If you use the command before booting server, this error occurs

```
[ALERT] java.lang.NullPointerException
	at cn.nukkit.command.CommandReader.run(CommandReader.java:60)
```

**Comment by caoli5288** [comment]
Maybe it should be blocked before boot done.

**Comment by Snake1999** [comment]
Maybe command executing could be executed in an async task, not immediately. And this async task should be activated after server start done.
