### ISSUE TITLE
New Generator, New Improvments

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1209]
Hello all and i'm sorry for this issue ,but is one question.

I and @Creeperface01 i'm created one plugin with more features in WorldGenerator specialy **FOR NUKKIT** ,not for all softwares ( Genisys or ClearSky or BukkitPE or other software , please not translate or copy-paste code ,it's for NUKKIT) with more improvments in world.

Have more features as:
- Swamp Trees with Swamp Biome like SinglePlayer
- Acacia Trees with Savanna Biome like SinglePlayer
- DarkOak Trees with Roofed Forest and Roofed Forest M like SinglePlayer
- Big tree ( Oak and Jungle ) with Jungle Biome like SinglePlayer
- Diorite, Andesite and Granite in WorldGenerator.

New coming soon. But the interes of the issue is :   

I want to implement all this to Nukkit but i need help. I don't know how i can use Eclipse or IntelIj ( thanks for help other ,but it's hard ) and devs not like to create 100000..... commits.

Anyone can help implement? :D 

Plugin is here and you can test here or report bugs: https://github.com/NycuRO/BiomeMaster

**Comment by File14** [comment]
Why not adding these biomes into Nukkit as it's in MCPE singleplayer? Why has this to be a plugin?

**Comment by NycuRO** [comment]
@File14 I want this ,but devs not like create more commits

**Comment by Niall7459** [comment]
If you want I can help implement it into the server core?

**Comment by Creeperface01** [comment]
Ok it would be awesome

**Comment by Niall7459** [comment]
Actually its quite tricky.

I may have to change some code not sure yet /:

**Comment by Niall7459** [comment]
Getting the hang of it now...

**Comment by Niall7459** [comment]
I can't get my MCPE connected to the server to test it!

So far I _think_ i have got jungle biome completed!

**Comment by NycuRO** [comment]
@Niall7459 And savanna and roofed forest and other is ready.

**Comment by Niall7459** [comment]
Cool thanks, got trees working just a few small bugs.

**Comment by NycuRO** [comment]
@Niall7459 Yes,need fix

**Comment by Niall7459** [comment]
i cant really help sorry.

**Comment by Niall7459** [comment]
Hey!
Pleased to say its going well should get implemented soon!

**Comment by Niall7459** [comment]
Pretty much done just need to finilize and fix some bugs

nice work!!!!

**Comment by NycuRO** [comment]
@Niall7459 You can help :)

**Comment by Niall7459** [comment]
I am almost done implementing it into **nukkit**

**Comment by Niall7459** [comment]
I GOT IT WORKING

IT WORKS

WE WELCOME JUNGLE AND LOADS MORE TO NUKKIT CORE
GUYS YOU ARE AMAZING!!!!!!!!!!!!!!!!!!!

screen:
![screen shot 2016-11-03 at 16 17 52](https://cloud.githubusercontent.com/assets/9781846/19974665/1b3d9fa6-a1e1-11e6-82a1-1d3608ddc0a1.png)

Just forgot to add savanna biome and then im done, i will put a pr in!

**Comment by Niall7459** [comment]
Put in the PR https://github.com/Nukkit/Nukkit/pull/1250

**Comment by MagicDroidX** [comment]
#1250
