### ISSUE TITLE
POCKETMINE PLUGINS NOT COMPATIBLE WITH NUKKIT!

### ISSUE THREAD

**Issue by VoliPlays** [Nukkit/Nukkit#1210]
Hello i have a server in development.And because the nukkit is at the beggining I wanna know how to make the pocketmine plugins compatible!
Hope you help me!

**Comment by boy0001** [comment]
You can't, though you can use Bukkit plugins:
 - https://forums.nukkit.io/resources/pokkit.108/
Or Nukkit plugins:
 - https://forums.nukkit.io/resources/

**Comment by VoliPlays** [comment]
Hmm i think nycuro uses pocketmine plugin but i don't k ow if is nukkit fine thanks!

**Comment by Snake1999** [comment]
YOU CANNT FOREVER
