### ISSUE TITLE
Duplicate player name in the player list

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1215]
### Issue description

If you join a server and view the TAB list, there will be a "duplicate" of the player.
### Steps to reproduce the issue
1. Join a server
2. Look at the player TAB
### OS and versions

- Nukkit: Este servidor estß rodando Nukkit 1.0dev ???(Apple)?(Pie)? implementando versÒo da API 1.0.0 para Minecraft: PE v0.16.0 alpha (versÒo do protocolo 91)
- OS: Windows 10
- Device: Windows 10
### Crashdump, backtrace or other files

![http://i.imgur.com/8IPleIC.png](http://i.imgur.com/8IPleIC.png)

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/pull/1170

**Comment by MrPowerGamerBR** [comment]
@Pub4Game I'm using the latest version and it still has that issue, this didn't happen in 0.15.10 however it does happen in 0.16.0

**Comment by boybook** [comment]
Maybe In 0.16.0 the other name was added by client. So we maybe need to remove some things.
