### ISSUE TITLE
Saying something in chat for the first time duplicates the previous message

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1216]
### Issue description

If you join a server and say something in the chat, the latest sent message is duplicated.
### Steps to reproduce the issue
1. Join a server
2. Wait for something to be sent in chat (Example: "player joined the game"
3. Say something in chat
4. It will show "player joined the game" again and will send your chat message
### OS and versions
- Nukkit: Este servidor estß rodando Nukkit 1.0dev ???(Apple)?(Pie)? implementando versÒo da API 1.0.0 para Minecraft: PE v0.16.0 alpha (versÒo do protocolo 91)
- OS: Windows 10
- Device: Windows 10

**Comment by IrishPacks** [comment]
Seems to be a client-side issue.

**Comment by Snake1999** [comment]
Tested out and packets are sent once on server upload stream.
Seems it's mojang's turn to be blamed :)
