### ISSUE TITLE
Debug messages when joining

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1217]
### Issue description

Yeah, I think someone forgot to remove the debug messages when merging the 0.16 PR.
### Steps to reproduce the issue
1. Join a server
### OS and versions

- Nukkit: Este servidor estß rodando Nukkit 1.0dev ???(Apple)?(Pie)? implementando versÒo da API 1.0.0 para Minecraft: PE v0.16.0 alpha (versÒo do protocolo 91)
- OS: Windows 10
- Device: Windows 10
### Crashdump, backtrace or other files

![http://i.imgur.com/MRrTvbq.png](http://i.imgur.com/MRrTvbq.png)

**Comment by EnderKenji** [comment]
Yep, same as me using Multicraft control panel. And it shows "Loading" status even server already online, which means... weird, it should be "Online", green light.
![screenshot 101](https://cloud.githubusercontent.com/assets/15629214/19838415/bd6ad81e-9f09-11e6-9922-1bdc4662f6a1.png)

**Comment by Creeperface01** [comment]
if you have 200 players online at the same time :D

**Comment by MagicDroidX** [comment]
@boybook

**Comment by boybook** [comment]
Sorry, I forgot removing it.

**Comment by Creeperface01** [comment]
@boybook still is not fully fixed :D

**Comment by boybook** [comment]
Debug messages?
