### ISSUE TITLE
Command doesn't work properly.

### ISSUE THREAD

**Issue by EnderKenji** [Nukkit/Nukkit#1220]
### Issue description

Commands not working properly.

 It only reads 1 ars, like /mw tp 1, but only read /mw tp and it does nothing. If i do /mw tp only, it send me usage of the command, detect args[1] as null.  You also can try /teleport command. 

but, command works fine if u send command as ConsoleCommandSender / on console.
### Steps to reproduce the issue

Already told in desc.
### OS and versions

- Nukkit: Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v0.16.0 alpha (protocol version 91)
- OS: Windows 10
- Device: Windows 10
##

**Comment by boybook** [comment]
I'm recoding the command encode, it will be fixed in a moment.
