### ISSUE TITLE
server doesn't stop

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1222]
### Issue description

sometimes server doesn't stop properly.
There is this message in the console "Took too long to stop, server was killed forcefully!" but process is still running.. so server won't be started again.
### Steps to reproduce the issue

happens randomly
### OS and versions
- Nukkit: 1.0-SNAPSHOT
- OS: windows 10
- Device: HP
### Crashdump, backtrace or other files

> 20:21:45 [DEBUG] Disabling all plugins
> 
> 20:21:45 [INFO] Disabling Annihilation v1.0
> 
> 20:21:45 [INFO] [Annihilation] Annihilation disabled
> 
> 20:21:45 [INFO] Disabling GTCore v1.0
> 
> Took too long to stop, server was killed forcefully!
> - ...

**Comment by Creeperface01** [comment]
and i can still send commands after this

**Comment by MagicDroidX** [comment]
@boy0001 Maybe this is due to the new logger?

**Comment by Creeperface01** [comment]
No it happened before too

**Comment by Creeperface01** [comment]
Or when was new logger added?

**Comment by boy0001** [comment]
About a day before you created this issue.

**Comment by Creeperface01** [comment]
So its not the cause

**Comment by Creeperface01** [comment]
But it happened again today, server stuck while stopping command reader thread, but wasnt stopped Only message appeared in the console

**Comment by boybook** [comment]
It never happened on my computer. Mayne your plugins caused it?

**Comment by Creeperface01** [comment]
Plugins can cause, commandReader cannot be interupted?

**Comment by boy0001** [comment]
@Creeperface01 
Nukkit does the following on shutdown
 - Disable all plugins
 - Unload levels
 - Remove event handlers
 - Stopping tasks
 - Closing console
 - Stopping network interface
 - Disabling timings
 - Stopping threads

According to the log you posted above, it's getting stuck on disabling GTCore. Do you have the log of it getting stuck on any other stage?

**Comment by Creeperface01** [comment]
Yes but server killer should stop server shouldnt it?

**Comment by MagicDroidX** [comment]
There might be a running thread created by a plugin which prevent to server from being stopped.

**Comment by Creeperface01** [comment]
But i think it happened even without plugins.  In PocketMine it happens too sometimes

**Comment by Creeperface01** [comment]
But i have Only mysql query thread
