### ISSUE TITLE
slow jenkins

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1226]
Jenkins server is very slow :/ i tried to download nukkit and it took around 10 minutes

**Comment by Snake1999** [comment]
There are 4 mirrors in http://nukkit.io . Try it

**Comment by MagicDroidX** [comment]
We have no official jenkins now and all jenkins are provided by nukkit lovers in the world.
As a result, the quality of the service can not be guaranteed.
Our site is paid by my own pocket money due to 0 donation. :/
And it may not suitable for building a jenkins on it.

**Comment by Creeperface01** [comment]
oh i see :/ 0 donation seriously? o.O

**Comment by Creeperface01** [comment]
im going to post some maps with adf.ly to earn more money and im going to donate something :D but i haven't much money

**Comment by Creeperface01** [comment]
@MagicDroidX maybe this is the reason...
![image](https://cloud.githubusercontent.com/assets/10363500/19908867/639afa9e-a085-11e6-9a37-d64c6c4760f7.png)

**Comment by MagicDroidX** [comment]
:/ #blamepaypaldotme
