### ISSUE TITLE
0.16.0 client

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1229]
OS and versions

Nukkit: https://github.com/Nukkit/Nukkit/commit/a928eaa5d081d12f6d52189479f771afd256e7f1
OS: windows 10
Device: Laptop ASUS ROG 

If you enter on server with Windows 10 ,with 0.15.10 map and plugins ,get crash client

**Comment by Creeperface01** [comment]
bugs.mojang.com

**Comment by haniokasai** [comment]
me too.
i think some block id were removed?

**Comment by haniokasai** [comment]
in my srv,i used ID247 block,but it were removed from mcpe,so my client crashed.

**Comment by Creeperface01** [comment]
What is 247? Update block?

**Comment by haniokasai** [comment]
sorry i thought 247 was remove,but not.

**Comment by haniokasai** [comment]
when i use specific plugin,client was crash.

**Comment by MrPowerGamerBR** [comment]
@haniokasai probably the plugin uses packets

**Comment by haniokasai** [comment]
i set viewdistance :5,i cant join server,viewdistance 15,i could join.

**Comment by NycuRO** [comment]
@haniokasai One method for fix?

**Comment by Tee7even** [comment]
Same, but crashing after joining a completely new world.
