### ISSUE TITLE
A rope?

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1235]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... use https://github.com/MCFT-Server/FloatingText this plugin.
2. ... it will create a rope.

### OS and versions

* Nukkit:  build 500
* OS: 0.16.0
* Device: 0.16.0 (LG X Screen)

**Comment by Snake1999** [comment]
That's what you should ask your plugin author. Send an issue in their issue tracker. 
Since 0.16, many client behaviors are changed, that causes manything changed, we Nukkit have to adapt them.
