### ISSUE TITLE
Chunks not loading?

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1237]
https://gyazo.com/d5bbc2d505969b6f8898dc2f8e900134

using 0.16 for windows and on my phone, it seems like chunks just stop loading while exploring. If you relog they load, but obviously its not ideal to continually relog

using nukkit as of a928eaa5d081d12f6d52189479f771afd256e7f1

**Comment by MrPowerGamerBR** [comment]
Maybe this fixes the issue #1232
