### ISSUE TITLE
Placing a Item Frame crashes the client

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1238]
### Issue description
When you place a Item Frame, the client crashes.

### Steps to reproduce the issue

1. Place a Item Frame

### OS and versions

* Nukkit: latest... I know, I tried using "ver" in the console and it crashed the console
* OS: Windows 10
* Device: MCW10

**Comment by MrPowerGamerBR** [comment]
Still crashing in the latest build.

**Comment by NycuRO** [comment]
@boybook @Snake1999 ..... very very buggy ...

**Comment by Snake1999** [comment]
@NycuRO If you dare spam again, we will block you out from this project

**Comment by NycuRO** [comment]
Ok.. :/
