### ISSUE TITLE
Gravel bug

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1241]
OS and versions

Nukkit: a928eaa
OS: windows 10
Device: Laptop ASUS ROG

If you set //sphere gravel 5 ,or sand, gravel is blocked and isn't Fallable...

I'm used: https://github.com/boy0001/FastAsyncWorldedit

**Comment by Creeperface01** [comment]
its plugin issue....

**Comment by Creeperface01** [comment]
but i think its not even plugin bug but its a feature...

**Comment by MrPowerGamerBR** [comment]
It is a FAWE feature, it disables gravity to improve performance.

@boy0001

**Comment by boy0001** [comment]
Not a bug. why do you need it to fall anyway? If it's to make terrain, falling gravel is a fairly primitive, use the heightmap brush instead.

**Comment by NycuRO** [comment]
@boy0001 For mountains...

**Comment by NycuRO** [comment]
Add config with enable and disable

**Comment by boy0001** [comment]
@NycuRO 
There are brushes specifically for terraforming. Using gravel spheres is much slower and hacky.

**Comment by NycuRO** [comment]
@boy0001 Repeat, you can add in config, true or false for Falling?

**Comment by boy0001** [comment]
@NycuRO 
No, learn how to use the other brushes.

**Comment by NycuRO** [comment]
@boy0001 And you can implement Super Pickaxe? Thanks.
