### ISSUE TITLE
Commands bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1242]
### Issue description
players can not send commands after re-logging

### Steps to reproduce the issue
join to the server, try commands (should work), then leave and join again, you won't see available commands, and wont be able to use them

### OS and versions
* Nukkit: 1.0-SNAPSHOT
* OS: Windows 10
* Device: Acer Iconia tab 8

**Comment by MrPowerGamerBR** [comment]
Can confirm, it happens right before Nukkit blocks my IP for 5 seconds.

**Comment by Creeperface01** [comment]
@MrPowerGamerBR have you the same nukkit version? :D

**Comment by Muqsit** [comment]
Try executing
player.sendCommandData();
On player join.

**Comment by MrPowerGamerBR** [comment]
@Muqsit this was already fixed (at least for me) in the latest Nukkit version.

**Comment by Snake1999** [comment]
Confirmed in iOS client. This is a "probably happen" bug, we need more people to confirm in different client platforms.

**Comment by File14** [comment]
Same isssuse here for IOS users. Windows 10 is working perfect.

**Comment by NycuRO** [comment]
Android work perfectly . Ios have problems..

**Comment by Muqsit** [comment]
The same for pocket mine.
