### ISSUE TITLE
Water Bucket and Pumpkin/Melon Seeds

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1243]
OS and versions

Nukkit: a928eaa
OS: windows 10/ android , bugs is on all OS
Device: Laptop ASUS ROG

In survival . if you have one bucked and you watch to get with Water ,not work.

And in survival ,pumpkin /melon seeds isn't placeable and NetherWart .

**Comment by solo5star** [comment]
pumpkin and melon are fixed +_+ #1317
