### ISSUE TITLE
Console commands are async, and not safe

### ISSUE THREAD

**Issue by boy0001** [Nukkit/Nukkit#1248]
Console commands are executed from the CommandReader thread rather than the main thread:
 - https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/command/CommandReader.java#L70

For example `save-all` results in modifications to the RandomAccessFile from the CommandReader thread. If an autosave is occuring at the same time it'll corrupt the world.

Possible solutions:
 - Schedule the command to run on the main thread
 - Use locks to prevent concurrent modification to the file (#1102)

**Comment by Muqsit** [comment]
69 open issues hype.

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/Nukkit/Nukkit/issues/1431
