### ISSUE TITLE
0.16 have 1.9 system attack,wtf

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1252]
I'm watched to SteadFight 0.16.0 commits ,and have 1.9 attack, probably need add and in Nukkit.

Commit: https://github.com/Hydreon/Steadfast2/commit/033acc6fc3e3e617f389b52eddf321340cc4d7ea

**Comment by liach** [comment]
Is this even related to Nukkit?

**Comment by File14** [comment]
Well, don't add it to Nukkit.
