### ISSUE TITLE
Teleport issue?

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1268]
### Issue description
players gets stuck in air on teleport, usually between worlds (maybe long distance). THis doesn't happen always, but very often

### Steps to reproduce the issue
Teleport between worlds

### OS and versions

* Nukkit Version: 1.0-SNAPSHOT
 
* Java Version: 8

* Host OS: linux

* Host Configuration: Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz, 2 GB RAM, 100 Mb

* Client Edition: all

* Client Version: 0.16.1

**Comment by Snake1999** [comment]
How do you 'teleport between worlds'? By command /tp?

If you did it by plugin, PASTE YOUR PLUGIN CODE, if you don't have the code, ask plugin author.

**Comment by Creeperface01** [comment]
player.teleport()

**Comment by File14** [comment]
Same issue.

**Comment by boybook** [comment]
Chunk packets loss?

**Comment by Creeperface01** [comment]
@boybook maybe nukkit doesn't send all chunk sections, (e.g. empty sections)
