### ISSUE TITLE
Question GM and AllowFlight 

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#127]
Hmm... Very strange! Why if I have a Gamemode = 1, then AllowFlight - true? There is no such thing in PocketMine

**Comment by Pub4Game** [comment]
@MagicDroidX ?

**Comment by MagicDroidX** [comment]
Sry but i cannot understand :s

**Comment by Pub4Game** [comment]
Nukkit:
Gamemode = 1; AllowFlight = true
PocketMine
Gamemode  = 1; AllowFlight = false

**Comment by Pub4Game** [comment]
Don't know how else to explain :D

**Comment by MagicDroidX** [comment]
You are certainly allowed to fly in creative mode. :/ I think this is not an issue.

**Comment by caoli5288** [comment]
I think so. not an issue.

**Comment by Pub4Game** [comment]
I keep track of 2 different parameter! Therefore, they should vary creative is one thing, but flying it is totally different!

**Comment by MagicDroidX** [comment]
In pocketmine's `setGamemode` method, `$this->allowFlight = $this->isCreative();`.

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/11917535/2001f6f6-a71c-11e5-9405-30ddf25d0338.png)

However, in PM it is working correctly... Everything is blocked from the message
