### ISSUE TITLE
Enchantment is Buggy

### ISSUE THREAD

**Issue by RedstoneAlmeida** [Nukkit/Nukkit#1271]
### Issue description

Max enchanted level affect this code addEnchantment
```
Item item = new Item(278, 0, 1);
				int enchantId = 15;
				int enchantLevel = 15;
				Enchantment enchantment = Enchantment.getEnchantment(enchantId);
				enchantment.setLevel(enchantLevel);
				item.addEnchantment(enchantment);
				if(sender instanceof Player){
					((Player) sender).getInventory().addItem(item);
				}
```
Item give max level 5

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: 8 upd 111

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Creeperface01** [comment]
read API more properly. Use enchantment.setLevel(level, false);

**Comment by RedstoneAlmeida** [comment]
thanks.
