### ISSUE TITLE
EXPERIENCE fixed source

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1280]
There is a mistake about calculateRequireExperience. (Sorry, i don't know how to use Pull repuests)

if you use /xp command when your level is 15, it skip 16 // and, i fix it. please merge it!
(sorry for my bad enlgish.)

~~~~~~~~~~~~~~~~~~~
    public static int calculateRequireExperience(int level) {
        if (level < 16) {
            return 2 * level + 7;
        } else if (level >= 16 && level <= 31) {
           //Fixed 17 to 16;
            return 5 * level - 38;
        } else {
            return 9 * level - 158;
        }
    }

**Comment by Snake1999** [comment]
Create a pull request

**Comment by OverTook** [comment]
@Snake1999 I said "Sorry, i don't know how to use Pull repuests"
