### ISSUE TITLE
Forums? 

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1292]
Nobody can rehister on forums, please fix. 
@MagicDroidX

**Comment by MagicDroidX** [comment]
Roger that, boss. XD

**Comment by ShadowPauler** [comment]
This is a real issue, nobody can register or contact you via email or verify their email address on the Nukkit.io forums. @MagicDroidX

**Comment by ShadowPauler** [comment]
@MagicDroidX This is why the forums Nukkit.io forums are dead, I am the only one trying to tell everyone but @Creeperface01 helped :D
