### ISSUE TITLE
Entity constructor is not called

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1304]
idk why, but i have an entity (its registered) but if chunk with entity loads, it also load the entity, but it doesn't call its constructor... i put debug everywhere but its not called and initEntity() as well. if i put debug in any other method in this class, i can see it in console, so its right instance

**Comment by Creeperface01** [comment]
and variables are not even initialized.... but its my class instance

**Comment by Creeperface01** [comment]
for example i have final variable (public final String var1 = "afasa";) but its null

**Comment by MagicDroidX** [comment]
I guess you should update the variables in after onLoad. :/
