### ISSUE TITLE
Commands doesn't work when using 0.16 and 0.17 client

### ISSUE THREAD

**Issue by liuchibing** [Nukkit/Nukkit#1307]
### Issue description

Can't use command supported by the server when using 0.16 or 0.17 client.

### Steps to reproduce the issue

1. Connect to a server
2. Send any command such as /tp
3. Get the message "Unknown Command. Try /help for a list of commands."(This were sent by the client, not the server."

### OS and versions

* Nukkit Version:   45a7f20 
 
* Java Version: 1.8.0_102

* Host OS: Windows 10 and Ubuntu 16.04.1 LTS

* Host Configuration: 4 GB RAM, 128GB SSD drive, 4 core CPU from Intel

* Client Edition: Android

* Client Version: 0.16.1 and 0.17 build 1

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by IrishPacks** [comment]
Try "./" in front of it. i.e. /tp would become ./tp.

**Comment by liuchibing** [comment]
Thank you very much! But I wonder if there is a more direct and easier way to use commands.

**Comment by SoyPro** [comment]
nukkit works with 0.17?

**Comment by File14** [comment]
Yes.

**Comment by SoyPro** [comment]
ok thanks for your answer

**Comment by JackboyPlay** [comment]
@File14 how works Nukkit with 1.0?

**Comment by File14** [comment]
@JackboyPlay I haven't tested it yet, but you can download it here: https://github.com/yescallop/Nukkit/archive/1.0.zip
