### ISSUE TITLE
Error World

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#131]
![image](https://cloud.githubusercontent.com/assets/11244874/11631850/266a8582-9d15-11e5-842e-6373e8eddf81.png)

**Comment by MagicDroidX** [comment]
This might has been fixed now. Plz try more!

**Comment by fromgate** [comment]
I meet this error too, but it was gone after clean install (all files including server configuration files were deleted)

**Comment by Pub4Game** [comment]
@MagicDroidX ok

**Comment by Pub4Game** [comment]
@MagicDroidX Hmm.... Again 
![image](https://cloud.githubusercontent.com/assets/11244874/11694803/1bd7507e-9ebd-11e5-90f7-046c51346489.png)

**Comment by Pub4Game** [comment]
@MagicDroidX and
![image](https://cloud.githubusercontent.com/assets/11244874/11695192/fc55687e-9ebe-11e5-9f1c-61922d7e5bc1.png)

**Comment by caoli5288** [comment]
Fixed #148
