### ISSUE TITLE
Grass Growth Replaces Blocks

### ISSUE THREAD

**Issue by Magicode1** [Nukkit/Nukkit#1311]
### Issue description

When grass grows on the plains biome, it replaces blocks previously there.

### Steps to reproduce the issue

1. Fresh install Nukkit (The Jenkins build I downloaded)
2. Go on your new world to the plains
3. build a structure there (Or anything on top of the grass)
4. Grass will soon grow through and replace any block it grows through.

### OS and versions

* Nukkit Version: Build #519 (Nov 28, 2016 9:16:10 AM) from Mengcraft Jenkins 
 
* Java Version: 1.8.0_65

* Host OS: Debian

I run it on a Raspberry Pi 2 Model B

* Client Edition: iOS

* Client Version: 16.0

It doesn't crash the game, it just annoys players to have to constantly rebuild blocks on the plains.

Thanks for your time 😃

**Comment by Creeperface01** [comment]
tall grass can grow? :D

**Comment by JackboyPlay** [comment]
@Creeperface01 yeah if it eats many jelly beans!
