### ISSUE TITLE
Enchantment not working 

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1314]
Heloo guys, it isnt possible to enchant in gamemode 0.
If you put your sword (or something else) into your enchanter and enchant the sword and if you put after that your sword into your inventory the sword disappears and a normal stone sword is in my inventory

**Comment by Snake1999** [comment]
I can't get any message! How to reproduce? Which system? Which client platform? How many configurations? Which client version? Where are detail?

If you know how to use template, you'll know issue template will help you describe your problem more clearly, and we can find the problem easier.

**Comment by Creeperface01** [comment]
i think this is known issue someone have to take a look at it only

**Comment by JackboyPlay** [comment]
@Snake1999 
How to reproduce: Use your brain and read my issue....
System: Ubuntu 
Client PF: Windows 10 [Maybe it wont work in MCPE too]
Client Version: 0.16.*
How many configurations: What do you mean with that?
Where are detail: The details are far far away in a unknown galaxy...

**Comment by Creeperface01** [comment]
Nukkit version: nukkit-1.0-SNAPSHOT

**Comment by DaMatrix** [comment]
I know what causes this, it's the item cheat protection. I'll look at fixing this.
