### ISSUE TITLE
Apollo - New Software , fork of Nukkit. I can have permission to fork?

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1316]
Hi all.

I want to create one new project ( New MCPE Software Java ) with name Apollo.

How Nukkit is not a "copy" of PocketMine that Genisys, I decided if I could have permission to can create this project.

I want to create Apollo for new features world , for fix more more bugs ,for more performance ,with Mob Al and other.

I can have permission for fork Nukkit? Thanks :)

**Comment by caspervanneck** [comment]
@NycuRO can i help you with building

**Comment by NycuRO** [comment]
@caspervanneck Yes.

**Comment by xxFlare** [comment]
This is why github created pull requests, you can implement any feature in Nukkit you want.

On the other hand, you can create a fork whenever you want because this is github. I would not recommend doing this, remember ImagicalMine? It ruined the whole community.

**Comment by NycuRO** [comment]
@xxFlare I want , i dediced what. I don't need any oppinions.

**Comment by NycuRO** [comment]
"This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version."

Sorry for issue.

Thanks.
