### ISSUE TITLE
Biome elevations don't change anything

### ISSUE THREAD

**Issue by DaMatrix** [Nukkit/Nukkit#1322]
### Issue description

I'm using a plugin to call 
`Biome.setElevation`
on a few different biomes, and it doesn't change the way the terrain generates at all. Is this a bug or just unfinished feature?

### OS and versions

* Nukkit Version: 5eb62df 
 
* Java Version: 
`openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)`

* Host OS: Ubuntu 16.04 Server

* Host Configuration: 256 GB RAM, 4096 GB Raid100, 2x 16 core 2.8Ghz Xeon, 1Gbps internet upload

* Client Edition: Android Lollipop

* Client Version: 0.16.1

### Crashdump, backtrace or other files

Nothing

**Comment by Creeperface01** [comment]
your code?

**Comment by DaMatrix** [comment]
Somewhat hacky, but it does change the values:
`	public void onEnable() {
		try {
		    Field field = Server.getInstance().getDefaultLevel().getClass().getDeclaredField("generatorInstance");
		    field.setAccessible(true);
		    Generator gen = (Generator) field.get(Server.getInstance().getDefaultLevel());
		    field = gen.getClass().getDeclaredField("selector");
		    field.setAccessible(true);
		    BiomeSelector selector = (BiomeSelector) field.get(gen);
		    field = selector.getClass().getDeclaredField("biomes");
		    field.setAccessible(true);
		    Map<Integer, Biome> biomes = (Map<Integer, Biome>) field.get(selector);
		    
		    for (Biome biome : biomes.values())	{
		    	biome.setElevation(100, 100);
		    }
		} catch (Exception e) {
		    e.printStackTrace();
		}
	}`

**Comment by yungtechboy1** [comment]
Height is based on seed and not Biome Property.
