### ISSUE TITLE
Moon in the update to 1.0.0

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1336]
Issue description
This relates Branch 1.0.0
The flaw involves the Texture of the month

OS and versions
Nukkit Version: db1959c /Branch 1.0.0
Client Version: 1.0.0
 
Picture:
![2016-12-26 1](https://cloud.githubusercontent.com/assets/19613582/21481783/fba2b636-cb6b-11e6-8fde-59a94012f3b7.png)

**Comment by poustmal** [comment]
This problem I had too,but one day the moon was normal in my server

**Comment by SuperAlecs** [comment]
Same with other version

**Comment by caspervanneck** [comment]
lol

**Comment by File14** [comment]
Haha this bug is a bit funny
