### ISSUE TITLE
Item frame crashes mcpe app

### ISSUE THREAD

**Issue by poustmal** [Nukkit/Nukkit#1337]
Nukkit version:e36f472
Game version:0.16.0
Server is running on Pocketserver app (android)
When I try to place an item frame block,it crashes the mcpe app and when I join again,its invisible,but you can break it.
![screenshot_2016-12-26-21-56-20](https://cloud.githubusercontent.com/assets/22281205/21486149/acf84efa-cbb7-11e6-836a-f8633f5147f5.png)
![screenshot_2016-12-26-21-59-29](https://cloud.githubusercontent.com/assets/22281205/21486151/b5065b78-cbb7-11e6-88cb-ac63ee8c1ddc.png)

**Comment by Pub4Game** [comment]
don't create duplicate issues https://github.com/Nukkit/Nukkit/issues/1238

**Comment by poustmal** [comment]
I didn't know,sorry
