### ISSUE TITLE
Hello ,could you are explain me )

### ISSUE THREAD

**Issue by misha1** [Nukkit/Nukkit#1340]
If  I download this pack in my computer  , how i can Start this server ? sorry , because  it's my first times(

**Comment by misha1** [comment]
in geniyus , when i download , in pack have file start.cmd ,and in nukkit i dont know nothing((

**Comment by JackboyPlay** [comment]
Download the jar file from jenkins and start it :)
(Download from the jar: http://ci.regularbox.com/job/Nukkit/)
