### ISSUE TITLE
Leaves do not decay

### ISSUE THREAD

**Issue by qazedc1212** [Nukkit/Nukkit#1341]
### Issue description
Leaves do not decay

### Steps to reproduce the issue
1. Grow/find tree
2. Break wood 
3. Wait

### OS and versions
* Nukkit Version: 1.0 
 
* Java Version: 1.8.0_111

* Host OS: Ubuntu 16.04

* Host Configuration: 1 GB RAM, 20 GB SSD drive, 2 core CPU from Intel, 150 Mb internet upload

* Client Edition: Win 10, iOS

* Client Version: 0.16.0

**Comment by vzlomka76** [comment]
It's not implemented

**Comment by yungtechboy1** [comment]
FIxed With PR #1415

**Comment by Landy005** [comment]
Please make this an option, this is super annoying for builders when the leaves we place dissapear.
