### ISSUE TITLE
Error at installing

### ISSUE THREAD

**Issue by AndreySK4** [Nukkit/Nukkit#1344]
I have this error at installing Nukkit:
![_20161230_163959](https://cloud.githubusercontent.com/assets/17062704/21566851/a2a3a102-ceaf-11e6-9f97-7af1757b93c9.JPG)

Any fix?

OS:Debian 8
Java version: 1.8.0_111

**Comment by PikachuFan** [comment]
Also got this error when running the jar file. Any advice or fixes?

**Comment by imjack** [comment]
Assuming you're building the jar it looks like its missing the lang files

**Comment by AndreySK4** [comment]
I'm added the lang files and it's working but now i have error with server.properties

**Comment by TheDiamondYT1** [comment]
@Pub4Game @MagicDroidX Someone ***really*** needs to add a check for lang files and exit if none.

**Comment by qazedc1212** [comment]
A tutorial if you guys don't know how to compile it.
https://forums.nukkit.io/threads/how-to-compile-nukkit-from-source.27282/#post-29039

**Comment by TheDiamondYT1** [comment]
Its not hard
