### ISSUE TITLE
Iron doors act like wooden ones

### ISSUE THREAD

**Issue by qazedc1212** [Nukkit/Nukkit#1348]
Iron doors can be opened without redstone

Steps to reproduce the issue

1. Place iron door
2. Open with fist
3. Door opens
 OS and versions

* Nukkit Version: 1.0DEV
* Java Version: 1.8.0_111
* Host OS: Ubuntu 14.04
* Host Configuration: 1 GB RAM, 20 GB SSD drive, 2 core CPU from Intel, 150 Mb internet upload
* Client Edition: Win 10/iOS
* Client Version: 1.0.0

**Comment by Pub4Game** [comment]
It's not a bug until the redstone is not implemented is the only way to open them.
