### ISSUE TITLE
How

### ISSUE THREAD

**Issue by majovec** [Nukkit/Nukkit#135]
how to replace bukkit place pocketmine Since I have MCPE server on which the pocketmine 1.7 so as to replace a nukki

**Comment by MagicDroidX** [comment]
What do you mean?

**Comment by fromgate** [comment]
I think he's asking about tutorial how to transfer worlds and player settings from PocketMine to Nukkit.
@majovec  Am I right?

**Comment by majovec** [comment]
yes exactly because I have paid server on minecraft pocket edition , and he goes to the system PocketMine 1.7 but would like to change to Nukkit therefore advice please 
PS:Sorry for the grammar I do not speak much English and I use translator

**Comment by Creeperface01** [comment]
Nepoužívej ten překladač :D

**Comment by majovec** [comment]
neupouzivat :D to se ti rekne njn musim se ptat zde kdyz ty me na tu otazku neodpovidas

**Comment by MagicDroidX** [comment]
Nukkit is compatible with pocketmine's configurations ,world and players' datas. Except ban list.

**Comment by majovec** [comment]
But how to put it on their server. I want to really be on erver nukkit

**Comment by BlindTail** [comment]
Nukkit is awesome; but there is a lack of basic plugins right now. Does your PocketMine server use any plugins today? None of those will work.

Could you run your server without the ability for players to log in? So then any player that wants to could use your player name and get your inventory.

We have to wait until at least SimpleAuth is ported before switching to Nukkit.

**Comment by Creeperface01** [comment]
Hm i will port simpleauth to nukkit

**Comment by Creeperface01** [comment]
But idk how to compile it because im new in java (but i have some experience from other languages) So can you give me some easy tutorial? And is possible run plugins or nukkit from source code?

**Comment by BlindTail** [comment]
Creeperface01 said:
> Hm i will port simpleauth to nukkit

This would be AWESOME. I hope the core Nukkit developers consider helping you make this happen; because it would be a great "first plugin" example for API testing.

Creeperface01 said:
> But idk how to compile it because im new in java (but i have some experience from other languages)
> So can you give me some easy tutorial? And is possible run plugins or nukkit from source code?

I'm in the same boat. I am not sure how to set up a development environment for Nukkit. I believe you also need something called gradle.

**Comment by majovec** [comment]
Hele Creeepere a ty by si mi nepordil ?

**Comment by Creeperface01** [comment]
S čím

**Comment by majovec** [comment]
jak to aplikovat na server ten nukit jen na muj test server chtel bych to vyzkouset ja uz sem se te nekoliktrat ptal na minetoxu ale ty si me jak si ignoroval :)

**Comment by Creeperface01** [comment]
Stáhneš si nukkit.jar a pak do stejné složky dáš ten spubor start.cmd

**Comment by majovec** [comment]
ted nejsem nejako v obraze ja myslel ze to ma byt neco jako je ten pocket mine taky v pharu

**Comment by Creeperface01** [comment]
A do toho cmd dáš toto No a ten jar soubor se musí jmenovat nukkit.jar a pak spustíš to cmd

java -jar nukkit.jar
PAUSE

**Comment by majovec** [comment]
pockat pockat to musi byt server pro normal MC abych tam rozjel nukkit ?

**Comment by Creeperface01** [comment]
Co ne nukkit to musí být musíš stáhnout ten jar soubor z jenkins webu nukkitu

**Comment by majovec** [comment]
to vim ale kdyz najedu na fakahede do spravce souboru kam dal ?

**Comment by Creeperface01** [comment]
Tak na fakahede ne.. Nevím jestli to pujde v normal mc ten jsem tam nikdy nwkupoval můžeš se zeptat v podpoře

**Comment by majovec** [comment]
aha ja celou dobu myslel ze to jde dat i na MCPE -,-

**Comment by Pub4Game** [comment]
Please chat here:
https://gitter.im/Nukkit/Nukkit
No need to create superfluous notifications

**Comment by Creeperface01** [comment]
To ne

**Comment by majovec** [comment]
skoda ja sem to chtel z jednoho duvodu zkusit na tom rozjet bw jelikoz to moje uz me .... kdyz stale nemuzu nejit chybu v tom shopu
