### ISSUE TITLE
Chunks bug

### ISSUE THREAD

**Issue by vzlomka76** [Nukkit/Nukkit#1359]
is such a hole has appeared in the world, where it came from - no one knows
Notify me of it the player, if it enter, then you will suffocate in the wall, but you can go through it, through worldedit (plugin Regions) I tried to close it, but all the blocks disappear. What should I do?
![2017-01-05 12-03-16](https://cloud.githubusercontent.com/assets/16573760/21675264/42de01ee-d342-11e6-9bfc-19067bd5c27f.png)

**Comment by qazedc1212** [comment]
Try placing a block in the broken chunk. The block should be replaced by what was previously there

**Comment by vzlomka76** [comment]
@qazedc1212 if I put a block, then it is put, but if i death or quit it disappears

**Comment by Pub4Game** [comment]
@yescallop Any ideas?

**Comment by yescallop** [comment]
@Pub4Game I think all chunk sections should be sent, doing this with inflating hardly affects the performance. And it could fix another bug of teleporting

**Comment by Pub4Game** [comment]
@yescallop You try to fix it?

**Comment by yescallop** [comment]
Is this bug in 1.0.0?

**Comment by Pub4Game** [comment]
Yes

**Comment by kvetinac97** [comment]
Does it have something in common with the PC world "chunk errors" (some regions not loading)?

**Comment by vzlomka76** [comment]
@kvetinac97 Map generated in nukkit

**Comment by Creeperface01** [comment]
the similar bug appears if you are in normal world and then teleport to another empty world, you still see chunk sections from last world

**Comment by Pub4Game** [comment]
This problem was solved in PM-MP. Someone will do it?

**Comment by Creeperface01** [comment]
in nukkit it isn't async?

**Comment by vzlomka76** [comment]
@Creeperface01 at first everything was fine, I saw this place, where the river flowed, but then one day, in many places there were holes, new worlds I did not create (there is only one world)

**Comment by kvetinac97** [comment]
Strange bug :/ Changed the map which bugged to first map, but it still lags... maybe Nukkit isn't loading so many chunks, or uses different ordering...?

**Comment by Creeperface01** [comment]
@kvetinac97 měl jsem podobný problém ale pouze při prvním testu teď to asi ani nedělá každopádně zdá se mi to nějak více vytížené :D

**Comment by xpyctum** [comment]
#326 copy (maybe, 50%50)
