### ISSUE TITLE
When player left, armor will remove

### ISSUE THREAD

**Issue by SuperAlecs** [Nukkit/Nukkit#1363]
### Issue description

Write a short description about the issue
the title say all

### Steps to reproduce the issue

1. ... left the game with armor
2. ... join back and your armor will removed
3. ...

### OS and versions

* Nukkit Version: 1.0.0 
 
* Java Version: 7

* Host OS: Ubuntu

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: iOS

* Client Version: 1.0.0

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Pub4Game** [comment]
I don't get this bug
