### ISSUE TITLE
Nukkit 1.0.0 moon bug

### ISSUE THREAD

**Issue by LucGamesYT** [Nukkit/Nukkit#1373]
I have a Moon bug in version 1.0.0 Windows 10

![image](https://cloud.githubusercontent.com/assets/19286296/21954811/a2ce3ed6-da5c-11e6-80aa-ff85b0ab879f.png)

**Comment by Snake1999** [comment]
Does this problem also exists on single-player games?

If yes, it might be problem on mojang-made clients;
If no, tell us detailed causes and configurations. We might get confused if no template should be used.

**Comment by poustmal** [comment]
This happens also to me.I use android.

**Comment by poustmal** [comment]
Set time to day and then to night,moon will be ok.

**Comment by Tee7even** [comment]
>Set time to day and then to night,moon will be ok.

This is not a solution.

**Comment by Creeperface01** [comment]
it fixed i think

**Comment by imjack** [comment]
I personally haven't seen this bug in awhile. Possibly close?

**Comment by Snake1999** [comment]
Umm... reopen this issue if this bug happens again. I cannot reproduce this.

**Comment by Creeperface01** [comment]
It was caused by bad packet format
