### ISSUE TITLE
Item Frame crashes the client 

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1383]
### Issue description

Write a short description about the issue
Client crashes when placed Item Frame
### Steps to reproduce the issue

1. Place Item Frame
2. ...
3. ...

### OS and versions

* Nukkit Version: Nukkit:1.0 dev    API:1.0.0    protocol:100
 
* Java Version: 1.8.0_111

* Host OS: Linux

* Host Configuration: 4GB RAM, 35GB SSD drive, 4 core CPU from Intel, 10 Mb internet upload

* Client Edition: ?? Windows 10 Android iOS

* Client Version: 1.0.0

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/issues/1238
