### ISSUE TITLE
Armor Bug

### ISSUE THREAD

**Issue by RedstoneAlmeida** [Nukkit/Nukkit#1384]
### Issue description

Player using armor on quit, armor simply not appear to get through to some to leave

### Steps to reproduce the issue

1. I'm Using Armor, Diamond, Chain, ....
2. I'm Quit from Server using Menu(ESC)
3. I'm join in Server

### OS and versions

* Nukkit Version: (https://github.com/Nukkit/Nukkit/commit/6009873aea282e2d88cf16b9c3624c7817e14155)
 
* Java Version: jre1.8.0_111 and jdk1.8.0_77

* Host OS: Windows

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.0.0

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by SuperAlecs** [comment]
It's SimpleLogin's bug
