### ISSUE TITLE
Not taking fall damage when player Y > 128

### ISSUE THREAD

**Issue by kvetinac97** [Nukkit/Nukkit#1385]
### Issue description
When I have world with blocks built with Y over 128, and I fall e. g. from Y 135 to Y 129 (works with every two values over 128), I don't get fall damage. However, when in total, I fall e.g. 220-215-200-196, I die (suddenly from 10 hearts).

### Steps to reproduce the issue
1. Create or download map with more blocks with Y > 128
2. Start falling and not taking damage
Be sure to run Nukkit <b>WITHOUT</b> any plugins.

### OS and versions
Latest update to master ("Update Version to 1.0.0")
* Java Version: 8
* Host OS: Windows 10 Personal
* Host Configuration: 4 GB RAM
* Client Edition: Windows 10 Edition, Minecraft PE
* Client version: 1.0.0

No error messages had been displayed in console.

**Comment by Creeperface01** [comment]
@kvetinac97 to je divne :D ja tuto chybu u sebe nemam a to jsem to určitě neměnil :D to asi někdo omylem změnil zase

**Comment by kvetinac97** [comment]
Will be fixed once somebody merges #1392 into master ;)
