### ISSUE TITLE
Some problems with items

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1394]
### Issue description

Write a short description about the issue
1.Acacid Sapling and Dark Oak Sapling grows into Oak Wood
2.Create a backpack without Diamond Spade
3.The survival mode also cannot synthetic Diamond Spade
### Steps to reproduce the issue

1. Planting Acacid Sapling and Dark Oak Sapling
2. Looking to create a backpack ...   without Diamond Spade
3. Try to survive in the synthesis of Diamond Spade

### OS and versions

* Nukkit Version: [f12716f](https://github.com/Nukkit/Nukkit/commit/f12716fb566e01168f0fcd8625c757c80aab5449)
 
* Java Version: 1.8.0_111

* Host OS: Linux

* Host Configuration: 4 GB RAM, 50GB SSD drive, 4 core CPU from Intel , 10 Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.0.0

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by lsw46** [comment]
0.0

**Comment by shnzk** [comment]
Grammar ERROR! the correct sentence of "4 core CPU from Intel" should be "4 cores Intel CPU"
