### ISSUE TITLE
Teleporting to an other world : chunk not loading, glitch

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#1396]
### Issue description

When teleporting a player to an other world using the method teleport (in a plugin), the chunk of the destination sometime don't load and the player is "glitched", like if he was coming back and forth from where he was to where he was teleported, but no chunk load, he only sees entities/players.
The only way to fix is to reconnect (re - teleport doesn't fix).
It seems to happen randomly (only sometimes).

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: https://github.com/Nukkit/Nukkit/commit/f12716fb566e01168f0fcd8625c757c80aab5449 
 
* Java Version: Java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

* Host OS: CentOS
 
* Host Configuration: 32 GB RAM, 240 GB SSD(SSD/HDD/...) drive, ? Xeon 1230v3 4 core CPU from Intel (Intel/AMD/...), 1Gbps Mb internet upload

* Client Edition: tested on iOS, Android, Win 10

* Client Version: 1.0.2

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by kvetinac97** [comment]
Actually, good method to fix this is to:

1. Send ChangeDimensionPacket and teleport to nether world
-> schedule 2.5 second task
 2. Send ChangeDimensionPacket (so sky won't look like Nether...) and teleport to second world

This makes MCPE think it is teleported many blocks away, so it resets its chunk cache ;)

**Comment by yescallop** [comment]
@kvetinac97 I tried sending a ChangeDimensionPacket to client, but I can't stop the loading screen

**Comment by Guillaume351** [comment]
@yescallop Thanks for the update, the issue that I mentioned is fixed (being teleported back and forth) but I still have sometimes a chunk not loading, see those pictures 
![fullsizeoutput_e1](https://cloud.githubusercontent.com/assets/6786268/22181329/b209862e-e08a-11e6-82cf-a7dba440582b.jpeg)
![fullsizeoutput_e2](https://cloud.githubusercontent.com/assets/6786268/22181331/b22ad6bc-e08a-11e6-9415-efa4884d49ea.jpeg)
![fullsizeoutput_e3](https://cloud.githubusercontent.com/assets/6786268/22181330/b22acac8-e08a-11e6-81ad-e45b95d711a0.jpeg)

**Comment by MrPowerGamerBR** [comment]
@Guillaume351 can you interact with the blocks in that unloaded chunk? (can you place/break blocks?)

**Comment by Guillaume351** [comment]
@MrPowerGamerBR If I hold my finger on the screen, I see the block "selected", so there are there, but not displaying

**Comment by MrPowerGamerBR** [comment]
@Guillaume351 this is a render bug in Nukkit

https://github.com/NiclasOlofsson/MiNET/wiki/Handling-levels,-maps-and-chunks

> A major issue, and something to take in to consideration is how MCPE renders chunks. In order for MCPE to be able to render chunks that contains blocks, it MUST have a surrounding frame of chunks, a diagram of this can be seen below. In order to deal with this, we have two methods in the AnvilWorldProvider, PruneAir & MakeAirChunksAroundWorldToCompensateForBadRendering, although this is mentioned below, I will mention it again as it is rather important. PruneAir removes all unused air chunks in the world (air chunks that do not have chunks surrounding them that have blocks inside of them), this lowers bandwith & CPU usage, and MakeAirChunksAroundWorldToCompensateForBadRendering adds air chunks to all chunks with blocks within them. This means that you do not have to do this yourself with a tool like MCEdit. Note that if you can see the lit up part of the blocks that are invisible this is your problem, but if the chunks aren't even there then this is not the problem.

**Comment by Guillaume351** [comment]
@MrPowerGamerBR If I understand, MiNET made a workaround to fix it, no ? Maybe it would be interesting to port it to Nukkit ?

**Comment by MrPowerGamerBR** [comment]
@Guillaume351 yeah, MiNET has a workaround for that, I don't know if Nukkit has that workaround implemented.

What you can do is use MCEdit and manually add new air chunks outside of the arena (I suppose that is some kind of a arena and there isn't more chunks after that one).

**Comment by Guillaume351** [comment]
@yescallop Update : the bug still happen even with your "hack" :/

**Comment by yescallop** [comment]
@Guillaume351 I have that issue, too. But this is the best I can do, I'll try other methods.

**Comment by Guillaume351** [comment]
@yescallop The strange thing is that I don't have the issue with the exact same maps on SteadFast. Thank you for your help, at least I have it less now

**Comment by yescallop** [comment]
@Guillaume351 I sent an issue to Mojang, now the best method to solve this is to ask official help.
Link: https://bugs.mojang.com/browse/MCPE-19818

**Comment by Guillaume351** [comment]
@yescallop https://github.com/pmmp/PocketMine-MP/commit/0944064eb8dcdbda77a0b9811281b6255efa246a This may help, even if it still a "hack"
