### ISSUE TITLE
Unable to connect to server.

### ISSUE THREAD

**Issue by UNST4BL3** [Nukkit/Nukkit#1417]
Client: Windows 10 beta
Server: Nukkit 1.0dev
I am hosting on the same machine as I am running the client.

When attempting to connect to the server for the first time, with no configuration changes, connection is lost. Server shows up in the list. No errors are outputted in console, and the server starts as it should.

Thanks, this is likely an error on my part.

**Comment by MrPowerGamerBR** [comment]
@UNST4BL3 did you do this? https://github.com/iTXTech/Genisys/wiki/FAQs
