### ISSUE TITLE
Why is there no setNested in config

### ISSUE THREAD

**Issue by CoolGuyMC** [Nukkit/Nukkit#1424]
I was in making a plugin and I realized there is no setNested...

**Comment by MrPowerGamerBR** [comment]
@CoolGuyMC I think you are coming from PocketMine-MP

In Nukkit, there isn't a "setNested", "getNested", you just need to use like you would in Bukkit.

getConfig().set("wow.nested.things", "super wow");

This will create a nested config

**Comment by CoolGuyMC** [comment]
@MrPowerGamerBR Oh okay, how would I use these codes? I still don't really understand...
,,,
cfg.setNested(number + ".data." + i, new Object[]{0, 0, 0, 1, 1, ""});
...

'''
Object data = cfg.getNested(number + ".data." + 27);
...

Thanks again

**Comment by MrPowerGamerBR** [comment]
@CoolGuyMC change that new Object[] to a ArrayList and save it as a list.

**Comment by CoolGuyMC** [comment]
@MrPowerGamerBR Oh k thanks, how would I get the data from it tho? Example:

Object data = cfg.get(number + ".data." + 27);
Item item = Item.get((int)data[0]);

**Comment by Snake1999** [comment]
I don't recommend using Config for storing data. For data like player economy, login, or so, there is a more powerful tool called SQL Database. If you already fell in love with config, use SimpleConfig instead.@CoolGuyMC

BTW, you need to forget something taken from PM, sometimes PM ways are unfriendly for developing are too slow for running in servers.

**Comment by MrPowerGamerBR** [comment]
@Snake1999 well, Nukkit's API is almost the same thing as PM-MP, so you can't really forget everything about PM-MP.

Except that backwards horrible Config thingy from PM-MP, in PM-MP the Config is so confusing, at least Nukkit isn't like that,
