### ISSUE TITLE
"moved wrongly"

### ISSUE THREAD

**Issue by jdongel2004** [Nukkit/Nukkit#1429]
Hello, I'm korean. so, my English is poor.

When I climb up the stairs, or half block(?), I go back and console has 'player name' moved wrongly 
PMMP has plugins with this, but I think Nukkit doesn't have plugins..
How can I fix this problem?

OS : Ubuntu 16.04
Nukkit version : Lastest version
JAVA version : 1.8
MCPE version : 1.0.0

**Comment by MagicDroidX** [comment]
`Player::setCheckMovement(false)`
