### ISSUE TITLE
EntityArmorChangeEvent actives wrongly.

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1434]
### Issue description

That event actives wrongly,

### Steps to reproduce the issue

1. ... Open the server, and you walk into the lava.
2. ... EntityArmorChangeEvent will active.

### OS and versions

* Nukkit Version: 544
 
* Java Version: 1.8

* Host OS: Windows 10 Redstone

* Host Configuration: 8 GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload (I don't know else)

* Client Edition: Android

* Client Version: 0.10.0.16

**Comment by MrPowerGamerBR** [comment]
Are you sure? I tried reproducing this issue but I couldn't reproduce it.

Unless if you are talking that it triggers the event when the armor breaks inside lava, in that case I think this is the intended behavior.

**Comment by OverTook** [comment]
@MrPowerGamerBR 

I use this code, and their console has a lot of"Activing"..
~~~~~~~~~~~
if(!(event.getEntity() instanceof Player)){
			return;
		}
		
		Enchantment enc = event.getOldItem().getEnchantment(Enchantment.ID_BOW_FLAME);
		if(enc == null){
			Server.getInstance().getLogger().alert("Activing");
		}

**Comment by MrPowerGamerBR** [comment]
@OverTook now I could reproduce this issue.

You need to be 100% inside of Lava, if you are just touching it nothing will happen.

**Comment by OverTook** [comment]
@MrPowerGamerBR

Thx for your help. XD

**Comment by MrPowerGamerBR** [comment]
```
        //Armor change
        if (index >= this.getSize()) {
            System.out.println("Triggered: " + index + ", " + this.getSize());
            EntityArmorChangeEvent ev = new EntityArmorChangeEvent(this.getHolder(), this.getItem(index), item, index);
            Server.getInstance().getPluginManager().callEvent(ev);
            if (ev.isCancelled() && this.getHolder() != null) {
                this.sendArmorSlot(index, this.getViewers());
                return false;
            }
            item = ev.getNewItem();
        } else {
            EntityInventoryChangeEvent ev = new EntityInventoryChangeEvent(this.getHolder(), this.getItem(index), item, index);
            Server.getInstance().getPluginManager().callEvent(ev);
            if (ev.isCancelled()) {
                this.sendSlot(index, this.getViewers());
                return false;
            }
            item = ev.getNewItem();
        }
```
This is the code that triggers the issue
![http://i.imgur.com/6fm6Ord.png](http://i.imgur.com/6fm6Ord.png)
Strange... but I think I know why this happens.

**Comment by OverTook** [comment]
@MrPowerGamerBR 
LOL. can u fix it?

**Comment by MrPowerGamerBR** [comment]
@OverTook yes, already fixing it, I will submit a pull request when I fix it

**Comment by OverTook** [comment]
@MRPowerGamerBR
WOW. Thx for your kind help.

but,, there is another bugs are exist..

When you canceled that event, it will be not canceled. Are you try that too?

**Comment by OverTook** [comment]
Other users looks it is canceled successfully, but you looke it failed.

(Item Copy Bug?)

Hm... I can't explain more in detail. Sorry. I am not good at english... :c

**Comment by MrPowerGamerBR** [comment]
@OverTook I think it is a client bug, I will look at it later, let me just fix this issue first.

**Comment by OverTook** [comment]
@MRPowerGamerBR

Thx.

**Comment by MrPowerGamerBR** [comment]
Okay, now I really found the issue, it was in another place, not in that code I shared.

**Comment by MrPowerGamerBR** [comment]
https://github.com/Nukkit/Nukkit/pull/1438

**Comment by OverTook** [comment]
@MRPowerGamerBR

I really thanks for your help :D
