### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#144]
How many cores can nukkit use? 4?

**Comment by Snake1999** [comment]
That is equal to how many cores can Java uses. Usually all cores exists in your computer. :3

**Comment by fromgate** [comment]
@Snake1999 
But what about multithreading? Does nukkit use it? Or all processes (moving entity, updating state of tile enitities, netoworking, saving data to disc, etc) performing using single thread?

**Comment by Snake1999** [comment]
@fromgate 
Yes, our Nukkit use multi-thread to fasten many operations, such as compressing network packet, writing file, generating world, populating, calculating light. All these operations are carried by `AsyncTask` and runs by `AsyncWorker`. The count of workers can be edited in nukkit.yml file, and the default number is 2*(cpu count).

**Comment by Creeperface01** [comment]
Has it pocketmine too?

**Comment by Creeperface01** [comment]
Can pocketmine use 4 cores?
