### ISSUE TITLE
1.0.3.0 branch

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1451]
1.0.3.0 is now released for beta users, so I think it would be good if Nukkit created a 1.0.3.0 branch, right?

I already made some progress with 1.0.3.0 support on my branch: https://github.com/PocketDreams/SequinLand/tree/mcpe-1.0.3.0

(Can connect to the server without any issues, TransferPacket works)

**Comment by Pub4Game** [comment]
I've created a branch, I'd appreciate it if you make a pull request.

**Comment by MrPowerGamerBR** [comment]
@Pub4Game will create as soon as possible 😉

**Comment by MrPowerGamerBR** [comment]
@Pub4Game https://github.com/Nukkit/Nukkit/pull/1454

**Comment by Pub4Game** [comment]
Thanks

**Comment by MrPowerGamerBR** [comment]
1.0.3.0 is now available for everyone

**Comment by Snake1999** [comment]
Available confirmed. I've tested transferring, it works fine.

**Comment by Snake1999** [comment]
Merged :)
