### ISSUE TITLE
Classes define overlapping

### ISSUE THREAD

**Issue by woofie** [Nukkit/Nukkit#1455]
### Issue description

on plugin compile, there are warnings, I don't know if they are major, but it has to do with the recent update of jline.

### Steps to reproduce the issue

1. compile plugin

### Crashdump, backtrace or other files
[WARNING] jline-2.14.2.jar, jansi-1.14.jar define 31 overlapping classes:
[WARNING]   - org.fusesource.hawtjni.runtime.Library
[WARNING]   - org.fusesource.jansi.AnsiConsole$1
[WARNING]   - org.fusesource.jansi.Ansi$1
[WARNING]   - org.fusesource.jansi.AnsiString
[WARNING]   - org.fusesource.jansi.internal.Kernel32$COORD
[WARNING]   - org.fusesource.jansi.internal.CLibrary
[WARNING]   - org.fusesource.jansi.internal.Kernel32$SMALL_RECT
[WARNING]   - org.fusesource.jansi.internal.CLibrary$Termios
[WARNING]   - org.fusesource.jansi.Ansi$Erase
[WARNING]   - org.fusesource.jansi.internal.CLibrary$WinSize
[WARNING]   - 21 more...

**Comment by MrPowerGamerBR** [comment]
They are overlapping because JLine now includes Jansi.

But it shouldn't be a issue, after all, it is just a warning. 😉

**Comment by Snake1999** [comment]
Because of JLine includes Jansi, will it be OK if we remove the Jansi as well as update JLine to the latest version in pom.xml file ? @MrPowerGamerBR

**Comment by MrPowerGamerBR** [comment]
@Snake1999 yeah you can do that if you want 😉
