### ISSUE TITLE
bed does not work

### ISSUE THREAD

**Issue by vzlomka76** [Nukkit/Nukkit#1462]
### Issue description

when you lie down on the bed, then the chunks as it unloaded or something like that, because the player is on the bed coordinates, but it is not visible to other players

### Steps to reproduce the issue

1. Place bed
2. lie on the bed

### OS and versions

* Nukkit Version: https://github.com/Nukkit/Nukkit/commit/da6a07c8404e385a7903e211c3c121d91dab2100
 
* Java Version: ??

* Host OS: ??

* Host Configuration: 3 GB RAM, 20 GB SSD drive, 7 core CPU

* Client Edition: Windows 10, PocketEdition

* Client Version: 1.0.0
![2017-02-05 22-01-13](https://cloud.githubusercontent.com/assets/16573760/22628981/c80bd598-ebee-11e6-84a6-52f83351bd12.png)

**Comment by Creeperface01** [comment]
fixed?

**Comment by vzlomka76** [comment]
@Creeperface01 i fix this myself
