### ISSUE TITLE
Anvil Errors

### ISSUE THREAD

**Issue by YaBoiBalAnce** [Nukkit/Nukkit#1483]
Im using latest Nukkit Commit at the moment of this post.
Ubuntu 16.10

Im getting this that is spamming the console.  Its quite annoying.
Not sure how it gets there. Like if i completely restart the server it will go away for a while then will happen again.
![screen shot 2017-02-12 at 11 49 56 am](https://cloud.githubusercontent.com/assets/6061891/22865061/9a1f531e-f119-11e6-9988-06421a6b86c2.png)

**Comment by PeratX** [comment]
Broken world file.
