### ISSUE TITLE
Server and Client on the same computer does not work

### ISSUE THREAD

**Issue by User9043589** [Nukkit/Nukkit#1484]
### Issue description

If you run the server on a PC, you can not connect to the Server with the Minecraft Windows 10 Edition installed on the same PC.
If the server is installed on another PC in the network you can connect without problems.

### Steps to reproduce the issue

1. Run the Server and the Windows 10 Edition Client on the same Computer and try to connect
2. Run the Server and the Client on 2 different Computers then (To solve the Problem).

### OS and versions

* Nukkit Version: Nukkit 1.0dev ???(Apple)?(Pie)? implementing API version 1.0.0 for Minecraft: PE v1.0.3 (protocol version 101) 
 
* Java Version: java version "1.8.0_111" 64bit

* Host OS: Windows 10 Pro 64bit

* Host Configuration: 16 GB RAM, 300 GB SSD/ 500GB HDD, Intel Core i7 4790, 40 Mb internet upload

* Client Edition: Windows 10 Edition

* Client Version: 1.0.3

### Crashdump, backtrace or other files

* 
NONE/No Errors

```
* NONE/No Errors

**Comment by SleepSpace9** [comment]
Have a look here: https://github.com/iTXTech/Genisys/wiki/FAQs
(Question: I cannot connect to servers hosted on the same computer with Windows 10 Edition Beta. How can I fix this?)

**Comment by SuperAlecs** [comment]
Try To change server's port

**Comment by JackboyPlay** [comment]
Try to start 1st your server and then start the windows10 client

**Comment by Snake1999** [comment]
Both server and client uses UDP poet 19132 to make a game able to join.
If you really sure you only have one PC, open your server at another port instead
(My personal opinion)

**Comment by Creeperface01** [comment]
it still doesn't work :D

**Comment by MagicDroidX** [comment]
UWP application has a network loopback. So the MCWIN10E cannot access to the LAN server unless you disable the loopback.
