### ISSUE TITLE
Add someone active?

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1490]
What about adding somebody who is active and can help us to improve nukkit and MERGE PULL REQUESTS

for example: @MrPowerGamerBR

**Comment by Creeperface01** [comment]
@MagicDroidX @Pub4Game @Snake1999

**Comment by MrPowerGamerBR** [comment]
I'm maintaining my own Nukkit fork here: https://github.com/PocketDreams/SequinLand

**Comment by Pub4Game** [comment]
It makes no sense.

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX sent me an organization invite, I will probably accept it later. (first I want to see if I can add MCPE support to Paper 1.11.2 or Glowstone... I already added a very WIP MC 1.11.2 support to Nukkit so doing the inverse should be easy)
