### ISSUE TITLE
Server stuck at 100% with no lag

### ISSUE THREAD

**Issue by DaMatrix** [Nukkit/Nukkit#1494]
### Issue description

Since about last night, my Nukkit server has been at 100% load. There's no noticeable lag ingame, but the server itself is showing CPU throttles due to overheating in the log. I've tried removing all plugins to no avail. Here's the timings report:
[https://timings.aikar.co/?id=0176cfc8fc914be8a9e7bc218de72549](https://timings.aikar.co/?id=0176cfc8fc914be8a9e7bc218de72549)

### Steps to reproduce the issue

1. Start the server? I'm not sure, it just kinda happened

### OS and versions

* Nukkit Version: 85f02d5f1a1b8a5d49ab0461b7e87376aec63e75 
 
* Java Version: openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

* Host OS: Ubuntu Server 16.04

* Host Configuration: 8 GB RAM, 2 TB ??(SSD/HDD/...) drive, 2 core CPU from Intel, 1 Gb internet upload

* Client Edition: None, it happens even with no clients connected

* Client Version: blank

**Comment by DaMatrix** [comment]
Here's a better timings report:
https://timings.aikar.co/?id=0176cfc8fc914be8a9e7bc218de72549

**Comment by DaMatrix** [comment]
[dump.txt](https://github.com/Nukkit/Nukkit/files/800932/dump.txt)
Here's the thread dump

**Comment by MrPowerGamerBR** [comment]
It seems it is Nukkit struggling to load the chunk data for players, you aren't using Anti Xray, right? (that increases the chunk data lag)

Another thing would be decreasing the view distance to send less packets for players.

I need to see if it is possible to async load that chunk data.

**Comment by DaMatrix** [comment]
I may have found the issue, the HDD wasn't fully connected to the motherboard and might have been causing Nukkit some issues.

**Comment by Snake1999** [comment]
Huh huh :) @DaMatrix 
BTW, Should a file system error should be announced to console as a WARNING message?

**Comment by DaMatrix** [comment]
Yeah, it's definitely that. I just tried to run `ifconfig` and got a similar freeze and 100% CPU load until I Ctrl+C'd it. :/

**Comment by DaMatrix** [comment]
I'm getting this again, copying the map onto another computer also results in the same thing.

**Comment by DaMatrix** [comment]
Here's the timings report with no players online:
https://timings.aikar.co/?id=3e10db9b9f5d449a839e5d3a0f052854
The CPU is still at 100% load and overheating.

**Comment by DaMatrix** [comment]
Just tried generating a whole new world and I'm STILL getting this.
