### ISSUE TITLE
Time out when join the server

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1495]
Can not join the server.
Reason:Time out
### Issue description
When entering the server,console prompts players to log in
But after a few seconds will prompt logout game: timeout

Client tip: disconnecting from server
### Steps to reproduce the issue

1. Join server

### OS and versions

* Nukkit Version: 1.0 dev latest version
 
* Java Version: 8

* Host OS: Linux

* Host Configuration: 6 GB RAM, 50 GB SSD drive, 4core CPU from intel, 10 Mb internet upload

* Client Edition: All

* Client Version: 1.0.3

**Comment by Snake1999** [comment]
Are you... trying to join 1.0.4 server with 1.0.3 client?

**Comment by lsw46** [comment]
No...

**Comment by PocketHDJ** [comment]
i have this problem too

**Comment by sero583** [comment]
@Snake1999 I think he has some plugins loaded which does weird things, that happened for me too, but only as my plugin had some bugs.
@Isw46 disable all plugins (rename the plugin folder basically), if some are there and try it again.

**Comment by lsw46** [comment]
But there are no plugins in the test server that sometimes

**Comment by sero583** [comment]
Did you ever try re-installing maybe, I don't think it would affect much/anything but give it a try atleast

**Comment by lsw46** [comment]
Yes....I've tried.....
