### ISSUE TITLE
Plains of dirt 

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1496]
This is what I found in the world .. its normal?

* Nukkit Version: 1.0.0 
* Java Version: 8
* Host OS: Wndows
* Client Edition: Windows 10
* Client Version: 1.0.3

![2017-02-25](https://cloud.githubusercontent.com/assets/19613582/23332157/6ad0aa5c-fb75-11e6-9d18-1beac35e44a6.png)

**Comment by vzlomka76** [comment]
I also found this, this new generator bug
