### ISSUE TITLE
Achievements is broken?

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1497]
Achievements is broken?

* Nukkit Version: 1.0.0
* Java Version: 8
* Host OS: Windows
* Client Edition: W10edition
* Client Version: 1.0.3

![2017-02-25 4](https://cloud.githubusercontent.com/assets/19613582/23333714/b2ef971a-fb90-11e6-8bb3-550fa37fccff.png)

**Comment by sero583** [comment]
Seems to be a language error

**Comment by PikyCZ** [comment]
how to fix..?

**Comment by sero583** [comment]
@PikyCZ I'm not sure, maybe you aren't on the latest version or have edited the language configuration. Maybe you replaced variabels in the string which shouldn't be replaced. Try reseting and updating, if that don't works take a look in that:
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Achievement.java there are the TranslationContainer etc. which handles the messages I think

**Comment by chillerkraft** [comment]
this is still broken
please fix!
it says the same message for me on my screen that it does on his
{%0} has just earned the achievement {%1}
im using the latest nukkit 587

**Comment by chillerkraft** [comment]
YAY :D
