### ISSUE TITLE
Server.getLevelByName(String name); don't works how expected

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#1500]
### Issue description
If you try to do for example Server.getLevelByName(this.getServer().getDefaultLevel().getName()); I get returned null at onEnable() and I think it's not only at onEnable() like that.

### Steps to reproduce the issue

1. Try using Server.getLevelByName(String name); on a exsistent level
2. Hope that it doesn't returns null, if it doesn't
3. Try it on onEnable() then.

### OS and versions
* Nukkit Version: server is running Nukkit version 1.0dev "??(Apple)?(Pie)" (API 1.0.0)
 
* Java Version: openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode) (doesn't matter)

* Host OS: Ubuntu 16.04.1 LTS
* Host Configuration: Dosen't matter
* Client Edition: PE
* Client Version: 1.0.3.0

### Crashdump, backtrace or other files
See the whole issue history at: #1498 (Closed)

**Comment by caoli5288** [comment]
The level's name is equal to the level's FOLDER name. check your code plz.

**Comment by OverTook** [comment]
it works for me

**Comment by sero583** [comment]
@OverTook try to get the default level during onEnable();

**Comment by Snake1999** [comment]
Use lambda to help you
get all levels as list, list.stream().filter(l -> Objects.equals(l.getName(),name)).findAny().ifPresent(l -> ....);

**Comment by sero583** [comment]
@Snake1999 what do you mean with lambda? The greek symbol?
Also improving that function would be actually better than doing such methods in https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Server.java#L1527 it uses Server.getLevels(); which returns the variable levels from Server.java and that levels variable/array only contains loaded Levels, I know now that I have to load them before but sometimes it just don't works as expected and always trying to load something which maybe doesn't exist throws notices which you could prevent.

**Comment by Snake1999** [comment]
@sero583
1. Lambda Expressions is a feature of Java 8. It can be used to replace anonymous inner classes as well as functional interfaces. Use Google to help you.
2. Function `getLevelByName(...)` performs likes: search world in all levels, return null if not found, no thread-safety protected.
`getLevels().stream().filter(l -> Objects.equals(l.getName(),name)).findAny().ifPresent(l -> ....);` only does the searching operation when `findAny()` is called. It is FASTER and SAFE (probably we can improve the implementation of `getLevelByName(...)` into using this kind of code)

**Comment by sero583** [comment]
@Snake1999 Implement that code in ```Server.getLevelByName(String name);``` please and please fully load the default level and then activate the plugins, that would be better.

**Comment by Snake1999** [comment]
@sero583 Didn't you know that plugin can be loaded at start-up OR after all worlds loaded?
Just edit the `load` key in your `plugin.yml`: it can be `STARTUP` or `POSTWORLD`.

**Comment by sero583** [comment]
@Snake1999 Oh totally forgot that, used to often ```STARTUP``` thats why, anyways thanks.
