### ISSUE TITLE
Doesn't work DATA_INTERACTIVE_TAG

### ISSUE THREAD

**Issue by Ivanzar** [Nukkit/Nukkit#1504]
Hi, I  have some problem with this code:
```java
this.dataProperties.putString(DATA_INTERACTIVE_TAG, "GO!");
```
I wrote it in the EntityBoat#initEntity(), but nothing doesn't work.
May be anyone has any idea ?

**Comment by Creeperface01** [comment]
i think you should add some flag together with this data

**Comment by Ivanzar** [comment]
Hmmm... I tried it, but nothing.

**Comment by Sandertv** [comment]
You have to set it to the entity to whom you want to see it, not the entity that will show it.
