### ISSUE TITLE
I have some problem

### ISSUE THREAD

**Issue by PocketHDJ** [Nukkit/Nukkit#1507]
1.my vps is 2h2g5mbps。but，server is so laggy
2.offen into the server will timeout
#my nukkit is no plugin and one level

**Comment by Creeperface01** [comment]
and if you use PC world for example?

**Comment by Snake1999** [comment]
https://github.com/Nukkit/Nukkit/issues/1495

**Comment by Creeperface01** [comment]
@Snake1999 can you merge pull requests?
