### ISSUE TITLE
Nukkit block me when i try to join my server

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1512]
### Issue description

2017-3-4 21:16:59 [NOTICE] Blocked 0:0:0:0:0:0:0:1 for 300 seconds
any time when i try to join

### OS and versions

* Nukkit Version: Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.0.3 (protocol version 101)

* Java Version: Java 8 Update 101

* Host OS: Windows

* Host Configuration: 4 GB RAM, 500 GB HDD drive, 2 core CPU from Intel, 60 Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.0.3

**Comment by Creeperface01** [comment]
try to use IPv4 :D
