### ISSUE TITLE
Docker (Unraid Host) stops at select language on startup

### ISSUE THREAD

**Issue by clowrym** [Nukkit/Nukkit#1515]
I have added the docker image to my unraid server, upon starting docker Nukkit never full starts unless i manually log into the docker container & manually rung the java file. In my docker logs I have only the following:

Is there a vaiable to add to the docker run command that will automatically select a language?

`starting Nukkit Server For Minecraft: PE> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] [0;32;1mWelcome! Please choose a language first![m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] eng => English[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] chs => ??????[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] cht => ??????[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] jpn => ???[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] rus => Pycc???[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] spa => Espa?ol[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] pol => Polish[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] bra => Portugu?s-Brasil[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] kor => ???[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] ukr => ??????????[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] deu => Deutsch[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] ltu => Lietuvi?kai[m[m
> [1G[K[0;36;1m14:22:33 [m[0;37;1m[INFO] idn => Indonesia[m[m`

**Comment by jonathanpeppers** [comment]
I am running nukkit in docker, I just added server.properties and YAML file to my image where I selected this stuff.

**Comment by Tee7even** [comment]
^ Yes. Add configuration files: `server.properties` and `nukkit.yml`.

**Comment by clowrym** [comment]
I just ended up attaching the dockers and selecting the language, everything is good now, would be nice to add this to the dockers setting prior to start to simplify things
