### ISSUE TITLE
 Other players are not working

### ISSUE THREAD

**Issue by kazuemon** [Nukkit/Nukkit#1519]
### Issue description
It seems that the player you are manipulating does not seem to be moving from other people, and it seems that you are not moving from others.

I do not know because I have not logged in to anything other than my server, but it works normally with Wi-Fi multi.

### Steps to reproduce the issue

1. join server

### OS and versions

* Nukkit Version: #1517 

* Client Edition: Android

* Client Version: 1.0.4

**Comment by imjack** [comment]
Caused by my fix for 0.14. I didn't test  0.14 with multiple players so that's the issue. Likely me changing around the player movement packet. I'm at a hotel currently so I can't look into the issue. Hopefully someone else can.

**Comment by kazuemon** [comment]
If you set the entityId of addPlayerMovement to entityId, other players will work, but you can not operate normally

**Comment by Tee7even** [comment]
Maybe the move packet now has to be sent to all other players but not to the player moving? I'll check this.

**Comment by Tee7even** [comment]
Yep, it works: https://youtu.be/nanoStD1PRQ
I don't like my temporary fix though:
```
//in doTick
for (long index : this.playerMoveToSend.keySet()) {
    int chunkX = getHashX(index);
    int chunkZ = getHashZ(index);
    for (MovePlayerPacket packet : this.playerMoveToSend.get(index).values()) {
        //this.addChunkPacket(chunkX, chunkZ, packet);

        List<Player> players = new ArrayList<>();
        for (Player player : getChunkPlayers(chunkX, chunkZ).values()) {
            if (player.getId() == packet.eid) {
                continue;
            }

            players.add(player);
        }
        Server.broadcastPacket(players, packet);
    }
}
this.playerMoveToSend.clear();
```

As you can notice, sound is also broken.

**Comment by kazuemon** [comment]
https://github.com/SOTEDev/Nukkit/commit/e162393e4ef590e871f1c5a64ed641d0bc30fff2

As a result of trying this fix, other players now work properly

**Comment by kazuemon** [comment]
Oops, correctly I am doing this correction based on it
https://github.com/kazuemon/Nukkit/commit/928fffa3d82ef1b817fad39d5b684968e628e365

**Comment by Tee7even** [comment]
The easiest way to fix this is to remove the overriden move method in `Player`. Probably that's what I am going to do. I will also study this problem a little more.

**Comment by kazuemon** [comment]
nice :)
