### ISSUE TITLE
No ItemBlazeRod.java

### ISSUE THREAD

**Issue by Leonidius20** [Nukkit/Nukkit#1520]
There is no ItemBlazeRod.java in the lastest (560) nukkit build, so if i want to get Blaze Rod's name (getName()), I get "Unknown". Maybe this file need to be just like, for example, ItemLeather.java, but with other ID and name. Please, add this file. Thanks

**Comment by kazuemon** [comment]
Is this problem only solved by adding ItemBlazeRod.java which copied ItemEgg.java and rewritten?

**Comment by kazuemon** [comment]
https://github.com/kazuemon/Nukkit/commit/5be073578649d34e9feb456834be1a473b9b3e17
https://github.com/kazuemon/Nukkit/commit/2d3c02a0f27e4f1bc5df77d2567bfb6de03bf5ec

like this

**Comment by Leonidius20** [comment]
@kauzemon yes
