### ISSUE TITLE
Sound is broken

### ISSUE THREAD

**Issue by Tee7even** [Nukkit/Nukkit#1525]
No sounds completely.  Works fine in singleplayer and LAN games.
See (or hear (OR NOT)) it here: https://youtu.be/nanoStD1PRQ

**UPD:** No sounds for placing blocks, etc.

**Comment by MrPowerGamerBR** [comment]
This happens because Nukkit is using a LOT of wrong packets for sounds, most of them are using LevelEventPackets where it should be LevelSoundEventPackets

**Comment by imjack** [comment]
Supposedly due to the resource pack not been sent correctly.

**Comment by Tee7even** [comment]
@MrPowerGamerBR There's another opinion:
https://twitter.com/dktapps/status/840225707208896512

**Comment by MrPowerGamerBR** [comment]
@Tee7even yeah, I was confusing with another issue (where Nukkit doesn't play sounds when placing blocks, etc), whoops!

**Comment by Tee7even** [comment]
Seems like resource pack support has to be implemented.

**Comment by Creeperface01** [comment]
https://github.com/pmmp/PocketMine-MP/commit/d41bdfc31c4875dccec0d572d747acde8bc232de

**Comment by Tee7even** [comment]
Resource pack support solved this problem in general, but there is still some sounds missing. Like sound for placing blocks. I guess this is what @MrPowerGamerBR was talking about.

**Comment by PikyCZ** [comment]
https://github.com/PocketDreams/SequinLand-Abandoned/commit/6a14d54e562bf11f3f522033276bc3325bdf38d8 ?

**Comment by Tee7even** [comment]
This makes every placed block sound like wooden planks

**Comment by PikyCZ** [comment]
any idea?

**Comment by Tee7even** [comment]
Yes. What @MrPowerGamerBR called `volume` in SequinLand isn't actually volume, but an extra data, in case of block place sound - block ID. So with value of 100 it was playing a sound of placing a [mushroom block](http://minecraft.gamepedia.com/Pocket_Edition_data_values), which sounds like placing wood.

**Comment by MrPowerGamerBR** [comment]
@Tee7even blame PocketMine-MP and the documentation that I was reading 😋

**Comment by tiNsLeY799** [comment]
Thank you @Tee7even for fixing sound!
