### ISSUE TITLE
Server freezing when players join too fast.

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#1535]
### Issue description

When 20 or more players join the server it is known to hang. I'm not too sure if its my plugins problem or the servers. I can't really get 20 players to instantly join a vanilla server either unless there is a bot created?

### Steps to reproduce the issue

1. Have a server restart and players will join back
2. Server will freeze and no error is thrown. Although the server is shown as online
3. ...

### OS and versions

* Nukkit Version: Append 0.14 on wards. 
 
* Java Version: 8

* Host OS: ubuntu

### Crashdump, backtrace or other files
None

**Comment by tiNsLeY799** [comment]
I used to have this error, but not like this. A crash dump says the server has stopped but Minecraft says it's still online. It was an annoying painful error when I wasn't near the physical server.

**Comment by cloud9350** [comment]
> 15:08:05 [INFO] Loading nukkit.yml...
> 15:08:05 [INFO] Loading server properties...
> 15:08:05 [INFO] Selected English (eng) as the base language
> 15:08:05 [INFO] Starting Minecraft: PE server version v1.0.4
> 15:08:05 [INFO] Opening server on 0.0.0.0:19132
> 15:08:05 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
> 15:08:05 [INFO] Nukkit is distributed under the LGPL License
> 15:08:05 [INFO] Successfully loaded 0 resource packs
> 15:08:05 [INFO] Loading AnyVersion v0.0.5
> 15:08:05 [INFO] Preparing level "world"
> 15:08:05 [INFO] Enabling AnyVersion v0.0.5
> 15:08:05 [INFO] [AnyVersion] Server protocol version: 102
> 15:08:05 [INFO] Starting GS4 status listener
> 15:08:05 [INFO] Setting query port to 19132
> 15:08:05 [INFO] Query is running on 0.0.0.0:19132
> 15:08:05 [INFO] Default game type: Survival Mode
> 15:08:05 [INFO] Done (0.893s)! For help, type "help" or "?"
> 15:08:26 [INFO] [AnyVersion] Gureumi use protocol version 101 (server version: 102)
> 15:08:26 [INFO] [AnyVersion] Warning! Using outdated/outrunning client could damage your server.
> 15:08:26 [INFO] [AnyVersion] Use it on your own risk
> 15:08:26 [INFO] [AnyVersion] Kara use protocol version 101 (server version: 102)
> 15:08:26 [INFO] [AnyVersion] Warning! Using outdated/outrunning client could damage your server.
> 15:08:26 [INFO] [AnyVersion] Use it on your own risk
> 15:08:46 [NOTICE] Player data not found for "kara", creating new profile
> 15:08:46 [INFO] Kara[/58.235.163.77:19135] logged in with entity id 1 at (world, 128.0, 70.0, 128.0)
> 15:08:46 [NOTICE] Player data not found for "gureumi", creating new profile
> 15:08:46 [INFO] Gureumi[/58.230.240.197:19132] logged in with entity id 2 at (world, 128.0, 0.0, 128.0)
> 15:08:46 [INFO] Kara[/58.235.163.77:19135] logged out due to client disconnect
> 15:08:46 [INFO] Gureumi[/58.230.240.197:19132] logged out due to client disconnect
> 15:09:06 [INFO] [AnyVersion] Gureumi use protocol version 101 (server version: 102)
> 15:09:06 [INFO] [AnyVersion] Warning! Using outdated/outrunning client could damage your server.
> 15:09:06 [INFO] [AnyVersion] Use it on your own risk
> 15:09:26 [INFO] Gureumi[/58.230.240.197:19132] logged in with entity id 3 at (world, 128.0, 0.0, 128.0)
> 15:09:46 [INFO] Gureumi[/58.230.240.197:19132] logged out due to timeout
> 15:09:47 [INFO] [AnyVersion] Gureumi use protocol version 101 (server version: 102)
> 15:09:47 [INFO] [AnyVersion] Warning! Using outdated/outrunning client could damage your server.
> 15:09:47 [INFO] [AnyVersion] Use it on your own risk
> 15:10:06 [INFO] Gureumi[/58.230.240.197:19132] logged in with entity id 4 at (world, 128.0, 0.0, 128.0)
> 15:10:26 [INFO] Gureumi[/58.230.240.197:19132] logged out due to timeout

But **Windows OS is working** nukkit.

**Comment by PetteriM1** [comment]
cloud9350 try without  AnyVersion plugin.

**Comment by cloud9350** [comment]
@PetteriM1 Already solved (MCPE Client problem)
