### ISSUE TITLE
Please implement ClientBoundMapItemDataPacket

### ISSUE THREAD

**Issue by vzlomka76** [Nukkit/Nukkit#1540]
### Issue description

Please implement ClientBoundMapItemDataPacket

### Steps to reproduce the issue

1. open https://github.com/pmmp/PocketMine-MP/blob/api3/network/src/pocketmine/network/mcpe/protocol/ClientboundMapItemDataPacket.php
2. Rewrite code for Nukkit

**Comment by PikyCZ** [comment]
it's implemented yet
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/network/protocol/ClientboundMapItemDataPacket.java

**Comment by vzlomka76** [comment]
@PikyCZ check code from pmmp and look at Nukkit code

**Comment by Tee7even** [comment]
Why wouldn't you do this yourself and make a _pull request_? It's easy.

**Comment by vzlomka76** [comment]
@Tee7even I tried, but the colors (picture) of the client were not displayed. So I'm here

**Comment by Tee7even** [comment]
As far as I know, @Creeperface01 is busy with this right now.

**Comment by vzlomka76** [comment]
well

**Comment by kazuemon** [comment]
Completed by CreeperFace
