### ISSUE TITLE
Q: How can I use nukkit.yml to override Generator?

### ISSUE THREAD

**Issue by tiNsLeY799** [Nukkit/Nukkit#1546]
I have tried asking on the Nukkit forums, but the advice I was given made my nukkit.yml to stop working and have seizures.

Is there any way to load multiple levels using nukkit.yml? Or give an example? I am trying to load all of my world because no plugin loads all the worlds (that exists yet.)

Sorry if I'm spamming, I'm just at a loss with this one.

**Comment by PikyCZ** [comment]
In nukkit.yml is worlds
Example:
worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 world:
 # seed: 404
 generator: FLAT or DEFAULT

**Comment by tiNsLeY799** [comment]
OH, THANK YOU.

**Comment by tiNsLeY799** [comment]
_ahem_ Thank you, I was trying to figure this one out. I was trying to get help on this, but some instructions were vague.

**Comment by PikyCZ** [comment]
Worlds:
 world:
  seed:
