### ISSUE TITLE
After destroying, minecarts don't seems to disappear like it be in clients

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1550]
Minecarts
minecarts after destruction  not disappear

![2017-03-19](https://cloud.githubusercontent.com/assets/19613582/24080729/2a6763f2-0ca5-11e7-83ef-c3e0e21fb719.png)

* Nukkit Version: 1.0.0
* Java Version: 8
* Client Edition: Windows10edition
* Client Version: 1.0.4.11

**Comment by NycuRO** [comment]
Not need disappear,lol.

**Comment by PikyCZ** [comment]
![2017-03-19 1](https://cloud.githubusercontent.com/assets/19613582/24081404/0779fc70-0cb3-11e7-9eb6-80d57dc95bca.png)

**Comment by Snake1999** [comment]
Another TO-DO :)
Looking forward to catching network packets :)

**Comment by PikyCZ** [comment]
fixed .
