### ISSUE TITLE
client-side death bug

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1555]
Client-side death bug

Player after spawn  
![2017-03-19 7](https://cloud.githubusercontent.com/assets/19613582/24116508/520ddf82-0da7-11e7-9d79-230953d54dd1.png)
player is in death event for others player 

screenshot is from my nukkit server.

here fix? : https://github.com/pmmp/PocketMine-MP/commit/06f2a9c6745f804e4ef68a562853e163bf64ae13

* Nukkit Version: 1.0.0
* Java Version: 8
* Client Edition: Win10Edition
* Client Version: 1.0.4

**Comment by Tee7even** [comment]
Could you provide a little more detailed description? What happens in the screenshot?

**Comment by Creeperface01** [comment]
I think there are smoke particles everywhere around you like if you are on fire and in a water

**Comment by kvetinac97** [comment]
That's because of onfire data flag isn't sent with false parameter after dying.

**Comment by PikyCZ** [comment]
Yep .. @kvetinac97
