### ISSUE TITLE
Command arguments are working sometimes and sometimes not really

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#1564]
### Issue description

Write a plugin and a class which extends Command class from Nukkit and make it only useable with arguments.

### Steps to reproduce the issue

1. As I already described

### OS and versions

* Nukkit Version: This server is running Nukkit 1.0dev ???(Apple)?(Pie)? implementing API version 1.0.0 for Minecraft: PE v1.0.4 (protocol version 102)
 
* Java Version: 8

* Host OS: Ubuntu 16.04.01

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: PE 

* Client Version: doesnt matter

**Comment by kvetinac97** [comment]
Do you define parameters with this.commandParameters.put("default", new CommandParameter[]{…}); ? If you do it with overloads, it won't work well.

**Comment by sero583** [comment]
@kventinac97 I'm defining them not like that, what if I dont even define them?
``My code for defining them:
this.commandParameters.put("<password>", new CommandParameter[0]);``, its probably wrong.

**Comment by Tee7even** [comment]
You could take a look ath the default commands to see how to use it. Here's some explanation:
```
this.commandParameters.put("default", //Here you define one option of how to use the command, because there may be others
                new CommandParameter[]{ //This is an array of parameters
                        new CommandParameter("player", CommandParameter.ARG_TYPE_TARGET, false), //THESE are actual parameters
                        new CommandParameter("reason", true)
                });
```

**Comment by sero583** [comment]
Oh thanks @Tee7even

**Comment by sero583** [comment]
@Tee7even By the way what about making the Item frame image sending async at big images it can kinda freeze the server

**Comment by Tee7even** [comment]
If you're talking about @Creeperface01's map API, I think it needs some optimizations anyway, we'll see about that.

**Comment by sero583** [comment]
@Tee7even Yeah I was talking about that API

**Comment by Snake1999** [comment]
Let's discuss about that BY THE WAY in another issue. Ok? @sero583
