### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1568]
I turn around and player highlights?

* Nukkit Version: latest
* Java Version: 8
* Host OS: ??
* Client Edition: w10
* Client Version: 1.0.4

![2017-03-26 1](https://cloud.githubusercontent.com/assets/19613582/24333418/ff71d9ee-1257-11e7-8cde-b7a396cc2461.png)

**Comment by Tee7even** [comment]
This is barely a server-side issue.
