### ISSUE TITLE
saveResource() bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#157]
PluginBase.saveResource() creates an empty file

**Comment by Snake1999** [comment]
saveResource(String fileName) instead

**Comment by Creeperface01** [comment]
I use saveResource("config.yml") config.yml is in resources folder 
https://github.com/Creeperface01/AdvancedAuth/tree/master/src/resources

**Comment by MagicDroidX** [comment]
Check your jar and find out if the file is currectly put in which it should be. As normal, this file should be in the root path in your jar.

**Comment by Creeperface01** [comment]
So not in resources folder?

**Comment by MagicDroidX** [comment]
Java normally put all resources into the root path. You can refer to Nukkit.jar :)
