### ISSUE TITLE
Is cn.nukkit.test (AngleTest) necessary?

### ISSUE THREAD

**Issue by kazuemon** [Nukkit/Nukkit#1572]

**Comment by Tee7even** [comment]
What do you mean? No, you can build nukkit without it. In fact, it is not included in the building process. https://en.m.wikipedia.org/wiki/Unit_testing
P.s. Use gitter to ask questions instead of creating new issues.

**Comment by kazuemon** [comment]
sorry

**Comment by Snake1999** [comment]
_Test classes_ are created for developers to test _platform dependency_ and _function availability_. Typically for users, builder website, platform or software ignores test classes for production use.
