### ISSUE TITLE
Error when plugin.yml is incorrect

### ISSUE THREAD

**Issue by grzegorz2047** [Nukkit/Nukkit#1576]
### Issue description

If plugin.yml doesn't contains api:["1.0.0"] plugin won't load and it throws nullPointerException for line:

https://github.com/Nukkit/Nukkit/blob/5b39ea552ada801b22af88a1dd723794baa2858c/src/main/java/cn/nukkit/plugin/PluginManager.java#L179

In my opinion there should be user-friendly message that plugin.yml doesn't contains required field.
So to do that there should be check whether version variable is null or not and if it is then do sth and print error. 

### Steps to reproduce the issue

Don't place api:["1.0.0"] in plugin.yml

### OS and versions
ANY
### Crashdump, backtrace or other files

* 
```
https://gist.github.com/grzegorz2047/67c20b720ae0766d2f1dac3c181015db
```
* ...

**Comment by Snake1999** [comment]
Of course it be :/
As far as I know, Nukkit is normally used by big teams or enterprise users, who has basic knowledge of the maintenance and development of Nukkit itself. For myself, I'll consider add user-friendly message if more users have the demand.
If you are hunger for the messages now, you can contribute to Nukkit code by yourself

**Comment by Hunyahemee** [comment]
do you have any space between api: and ["1.0.0"] in your plugin.yml? If not, adding that "might" fix the the problem

**Comment by grzegorz2047** [comment]
I figured it out, but when you don't add api field in plugin.yml it throws nullpointerexception what is considered to be bug. I would fix it by myself, but I don't have  workspace prepared with nukkit xd
