### ISSUE TITLE
Item doesn't show in hotbar

### ISSUE THREAD

**Issue by Bluplayz** [Nukkit/Nukkit#1578]
Sometimes after set an item to the player's Inventory, the item doesnt show directly, only after open and close the Inventory lol

### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... set Item in hotbar (Inventory.setItem(2/* 0-8 here for hotbar slot */, item /* new Item(Item.STICK) */));
2. ... item sometimes doesnt exist
3. ... open and close the inv
4. ... item now appear
5. ... if item still never disappear, than try to add 3-5 items at the same time and try again 

### OS and versions

* Nukkit Version: 1.0Dev | 1.0.5 MCPE
 
* Java Version: 8

* Host OS: Windows

* Host Configuration: localhost

* Client Edition: Windows 10 & Android & IOS

* Client Version: 1.0.5

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by sero583** [comment]
@Bluplayz I tested it and it works fine, I think you just don't send the inventory contents to the player/-s.

**Comment by Snake1999** [comment]
Read the javadoc carefully. Hotbar is a set of INDEX not a CONTENT STORAGE. You should 1. set item in inventory, 2. set the hotbar index.

**Comment by Bluplayz** [comment]
i thought that if i send it to slot 0-8 then its automaticly in the hotbar lol
