### ISSUE TITLE
Interact Sound from Client?

### ISSUE THREAD

**Issue by Bluplayz** [Nukkit/Nukkit#1579]
How i can remove the sound which comes when i interact with anything lol

### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: ??

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by sero583** [comment]
@Bluplayz Not a issue, anyone close this please.

**Comment by Snake1999** [comment]
Muted you outside this project for the `lol`.

**Comment by Bluplayz** [comment]
@Snake1999 Okay, sry therefore :/
