### ISSUE TITLE
Can't use "day" and "night" in "/time set" command

### ISSUE THREAD

**Issue by Leonidius20** [Nukkit/Nukkit#1581]
/time set command's parameter type is int, so i can't type "day" or "night" instead of the number.
![screenshot_2017-04-03-17-19-51](https://cloud.githubusercontent.com/assets/25536411/24624200/b77ac026-18b3-11e7-9f1f-a6ac2590280b.png)
![screenshot_2017-04-03-17-19-54](https://cloud.githubusercontent.com/assets/25536411/24624207/c090581a-18b3-11e7-951b-4e1265c38316.png)

**Comment by JackboyPlay** [comment]
Look at #1582

**Comment by Snake1999** [comment]
Fixed in #1582
