### ISSUE TITLE
Entity initialization

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1586]
if i have class that extends Entity, and create some variables and define them in initEntity() all these variables becomes null when constructor ends so for example in onUpdate() or any other method they are null

**Comment by Creeperface01** [comment]
@Tee7even what can cause this? it happens even if this variable is static

**Comment by Tee7even** [comment]
Code example, please?

**Comment by Creeperface01** [comment]
https://www.hastebin.com/yewadekelo.scala EntityData class is my class that extends EntityMetadata class and implements Cloneable so i can clone entity metadata. but it throws NPE on line 23

**Comment by Creeperface01** [comment]
also when i spawn an entity (animal, monster, villager) for first time player sees it 2 blocks higher than it should be, after reconnect player sees it normally

**Comment by Tee7even** [comment]
```
protected final EntityData dataProperties = (EntityData) (new EntityData()).putLong(0, 0L).putShort(7, 400).putShort(44, 400).putString(4, "").putLong(38, -1L).putFloat(39, 1.0F);
```
Wait, wut... EntityData is an abstract class. It's `cn.nukkit.entity.data.EntityData`, right?

**Comment by Creeperface01** [comment]
No, its my class that extends EntityMetadata and implements Cloneable. Unfortunately it has same name like EntityData in nukkit but i think it doesnt matter

**Comment by Tee7even** [comment]
It pretty much does. I don't think it is a Nukkit bug, most likely it's not, probably it's something wrong with your code.

**Comment by Creeperface01** [comment]
But now i only removed this variable and change Entity variable directly to EntityData (in initentity() metod)  and now it works

**Comment by Creeperface01** [comment]
So i think it is nukkit bug and if not, i absolutely do not know why it happens

**Comment by Tee7even** [comment]
If you don't know how it happens, it doesn't mean it's a Nukkit bug. Think about it just one time: *you* have defined a field of *your* custom type in *your* class. It is most likely *not* a Nukkit bug.

**Comment by Creeperface01** [comment]
I'll try to create example plugin and you can test it

**Comment by Xwaffle1** [comment]
Try re initializing your dataProperties object

dataProperties = new EntityData()

do that inside of  the initEntity method and see if that fixes it.

**Comment by Creeperface01** [comment]
@Xwaffle1 but my variable is final

**Comment by Xwaffle1** [comment]
Yep, but my suggestion if it works would show you some possible reasons for why it may not be working

**Comment by Creeperface01** [comment]
@Tee7even ok, I recommend you to test it by yourself, there are steps to reproduce
1) modify EntityItem class and print puckupDelay at the end of the constructor
2) run this code https://www.hastebin.com/izinezosul.lisp
3) output should be:
pickupDelay from the end of the constructor: 20
puckupDelay printed after: 0

**Comment by Creeperface01** [comment]
no, if you print puckupdelay at the end of initEntity() method its still 20, but if you print it at the end of constructor its 0..

**Comment by Creeperface01** [comment]
OK on the last line of constructor in Entity class its 20 and on the last line of EntityItem constructor (that is called after last line of Entity constructor) its 0, so you can check it. Its really strange

**Comment by Creeperface01** [comment]
@Tee7even can you test it? :D or reply

**Comment by Tee7even** [comment]
I don't understand what you want me to do. It would be nice if you could make a plugin that illustrates the problem.

**Comment by Creeperface01** [comment]
But its in nukkit, as i said pickupDelay in EntityItem unexpectedly losts its value

**Comment by Tee7even** [comment]
Sorry, I can't help.

**Comment by Creeperface01** [comment]
Why? Just check it, you said its bug in plugin but similar things happen in nukkit too, so i wanted to show you some example

**Comment by Tee7even** [comment]
>I don't understand what you want me to do. It would be nice if you could make a plugin that illustrates the problem.

**Comment by Creeperface01** [comment]
OK again i have this problem in plugin too. But only sometimes, so better would be if you can check this with existing and similar bug in nukkit.

if you create new EntityItem instance (with pickupDelay in NBT), you can see that pickupDelay variable is set to value from nbt. But when initEntity() method ends, this variable will unexpectedly become 0

**Comment by Creeperface01** [comment]
It would be good if you can check it, just debug EntityItem a bit, and print pickupDelay variable on some lines

**Comment by Tee7even** [comment]
![image](https://cloud.githubusercontent.com/assets/6763610/25670796/85351072-3036-11e7-8ca9-a6c9f297ffef.png)
And?

**Comment by Creeperface01** [comment]
how did it lose value 20 and got value 0?

**Comment by Tee7even** [comment]
In `onUpdate`:
```
if (this.pickupDelay > 0 && this.pickupDelay < 32767) {
    this.pickupDelay -= tickDiff;
    if (this.pickupDelay < 0) {
        this.pickupDelay = 0;
    }
}
```

**Comment by Creeperface01** [comment]
...

**Comment by Creeperface01** [comment]
onUpdate method is called 20 times between initEntity() debug and constructor debug?

**Comment by Tee7even** [comment]
Look, I don't see any problem here, there's no real bugs reported in this issue. And I'm not going to waste my time in search for nothing, in particular - learning what goes on there and why this value may become 0. If you feel like that there really is something wrong in Nukkit that causes problems with the fields of your custom classes (highly unlikely, almost impossible, sounds ridiculous), then investigate it yourself and create an issue, **if you really find something**.

**Comment by Creeperface01** [comment]
but this is real issue... if you look properly at the code and put debug at the end of init method and at the end of constructor the output will be different but there's nothing between these two debugs.

**Comment by Creeperface01** [comment]
Ok i can call this issue, Item pickup delay is immediately 0 so if you drop an item you will pickup it immediately. But I avoid this by setting item delay after initialization again. But its still an issue and probably not only with item

**Comment by Creeperface01** [comment]
so should I create new issue or can you reopen this one?

**Comment by Tee7even** [comment]
>Ok i can call this issue, Item pickup delay is immediately 0 so if you drop an item you will pickup it immediately.

Somehow I can't reproduce this.

**Comment by Creeperface01** [comment]
You already reproduced. Look at your screenshot. The delay become 0 always during initialization. 
The reason why items work is, because I set pickup delay after new instance creation again. But its not solution.

**Comment by Tee7even** [comment]
This
>Ok i can call this issue, Item pickup delay is immediately 0 so if you drop an item you will pickup it immediately.

doesn't happen. I don't see any problem here.

**Comment by Creeperface01** [comment]
@Tee7even yes now it seems to be working because I did workaround for items https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/level/Level.java#L1630 but as I said its not solution, if you remove this line, the delay will be always 0 even if item reads the PickupDelay correctly and also set this value to variable PickupDelay, and from your debug you can see that this variable really has certain value in initEntity() method, but after this method it will become 0

**Comment by Tee7even** [comment]
Create an issue for this (if it is not created yet) and maybe sometime it
will be fixed.

05 мая 2017 г. 15:36 пользователь "Creeperface01" <notifications@github.com>
написал:

**Comment by Creeperface01** [comment]
@Tee7even it is created.. it is this issue, look at the title and the first message, so you should reopen this

**Comment by Tee7even** [comment]
No, it's not, in this issue you complain about Nukkit being the cause of
some changes going on in your plugin.

2017-05-06 1:12 GMT+03:00 Creeperface01 <notifications@github.com>:

**Comment by Creeperface01** [comment]
But its the same issue.. Its not only with item entity.. Some variables lose their value if they are initialized in contructor (or methods called in constructor), so its nukkit issue, so it causes issues in plugins too
