### ISSUE TITLE
Connection Problems > Cant join

### ISSUE THREAD

**Issue by xHFx** [Nukkit/Nukkit#161]
I cannot join the nukkit server , i downloaded the Nukkit.jar executed it and still after that the server started on port 19139 and I see it in my list , I try to join and it just sits on loading screen.

root@68-168-96-206:~/Nukkit# java -jar Nukkit.jar
22:02:37 [INFO] Loading nukkit.yml...
22:02:37 [INFO] Loading server properties...
22:02:37 [INFO] Selected English (eng) as the base language
22:02:37 [INFO] Starting Minecraft: PE server version v0.13.0 alpha
22:02:37 [INFO] Opening server on 0.0.0.0:19139
22:02:37 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
22:02:37 [INFO] Nukkit is distributed under the LGPL License
22:02:37 [INFO] Preparing level "world"
22:02:37 [INFO] Starting GS4 status listener
22:02:37 [INFO] Setting query port to 19139
22:02:37 [INFO] Query running on 0.0.0.0:19139
22:02:37 [INFO] Default game type: Survival Mode
22:02:37 [INFO] Done (0.687s)! For help, type "help" or "?"
22:03:36 [NOTICE] Player data not found for "mack", creating new profile
22:03:36 [INFO] Mack[/x:19132] logged in with entity id 1 at (world, 128.0, 70.0, 128.0)
> Exception in thread "Asynchronous Worker" java.lang.NullPointerException
        at cn.nukkit.level.format.generic.BaseChunk.setBlock(BaseChunk.java:67)
        at cn.nukkit.level.format.generic.BaseChunk.setBlock(BaseChunk.java:60)
        at cn.nukkit.level.generator.Normal.generateChunk(Normal.java:176)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:84)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:20)
        at cn.nukkit.scheduler.AsyncWorker.run(AsyncWorker.java:41)
op Mack
22:03:40 [INFO] [CONSOLE: Opped Mack]
> kick ma
22:04:06 [INFO] Mack[/x:19132] logged out due to Kicked by admin.
22:04:06 [INFO] [CONSOLE: Kicked Mack from the game]
22:04:11 [INFO] Mack[/x:19132] logged in with entity id 2 at (world, 128.0, 70.0, 128.0)
22:04:36 [INFO] Mack[/x:19132] logged out due to timeout
22:04:40 [INFO] Mack[/x:19132] logged in with entity id 3 at (world, 128.0, 70.0, 128.0)

**Comment by MagicDroidX** [comment]
This should be fixed now, try more plz.

**Comment by xHFx** [comment]
Hmm ,, Could you contact me via Kik or Twitter 

Twitter: @DarkRealmsPE
KiK: db_mack


I have a somethings me and my devs want to talk over with you!

**Comment by MagicDroidX** [comment]
I have nor Twitter neither KiK thanks to the power of GFW. I can simply send email to me. :)
email: magicdroidx@vip.qq.com
