### ISSUE TITLE
Improvement /give

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#166]
Please make an opportunity to give things using name and not ID

/give pub4game apple 16

**Comment by ItsLucas** [comment]
Looking through this, maybe I can finish it in this weekend.

**Comment by caoli5288** [comment]
Sound need a ItemMapping.

**Comment by ItsLucas** [comment]
Yeah, asking Milkice to fix this. 

The basic idea is to use a HashMap<String,int> to give each item ID a name

**Comment by fromgate** [comment]
I think better to use ENUM instead of HashMap. Enum is faster and more flexible

**Comment by Snake1999** [comment]
![](http://fuzhi.co/system/items/940/original/QQ%E5%9B%BE%E7%89%8720160121145436.png)
Now added. :+1:

**Comment by Pub4Game** [comment]
@Snake1999  @Angelic47  Thanks :D
