### ISSUE TITLE
Suggestion: built in jdbc-drivers for MySQL and SQLite

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#168]
Hello!
I'm now working on plugin this uses MySQL or SQLite databases.
But nukkit did not provides access to any database engine.
I think it's a good idea to built-in something like Ebean or ORMLite and most populard JDBC-drives (MySQL, SQLite).
This will be very heplful to plugin developers to use built-in libraries instead of including libraries into plugin.

**Comment by Snake1999** [comment]
It's a good idea, but I prefer put the driver jar files into lib folder, which will be loaded by Nukkit. Lib file loader. Gson and other libraries can be provided from plugin developers, are told to plugin users that they should be placed into lib folder, or download automatically. That's even a good way for Nukkit load its libraries for Nukkit itself :3

See this: https://github.com/Nukkit/Nukkit/commit/1201ec0d86719a04efd00e26d70a2c8e8c1d3a1a
