### ISSUE TITLE
Outdated Server error with Build #583 and PE 1.0.5

### ISSUE THREAD

**Issue by ianridd** [Nukkit/Nukkit#1682]
I see from other people's comments that they are connecting to Nukkit servers using 1.0.5.

I have downloaded the latest stable build (#583) and it runs on my Ubuntu server without error.  However, when I attempt to connect using iPhone Pocket Edition 1.0.5, I get an "Outdated Server" message.

I am confused.  Can someone help me to understand what is happening?

Thank you,
Ian

### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: ??

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Tee7even** [comment]
>I am confused. Can someone help me to understand what is happening?

You've downloaded an old version. It should show which version of MCPE it supports on startup.
