### ISSUE TITLE
Player teleport bug

### ISSUE THREAD

**Issue by Ozelord757** [Nukkit/Nukkit#1686]
If I teleport a player, he is stucking in the air and no chucks are loaded.

Code:
this.owner.getServer().loadLevel("Skywars2");
skywarsLevel.loadChunk((int)skywarsLevel.getSafeSpawn().getX(), (int)skywarsLevel.getSafeSpawn().getZ());
entry.getValue().teleport(skywarsLevel.getSafeSpawn());

### OS and versions
* Nukkit Version: This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.0.6 (protocol version 106)

* Java Version: java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

* Host OS: Linux (Debian 8.0)

* Host Configuration: 4 GB RAM, 50 GB (HDD), CPU Core 3 x 3,40 Ghz, 100 MBit/s

* Client Edition: Windows 10

* Client Version: v1.0.6

**Comment by Snake1999** [comment]
Correct code:
```java
skywarsLevel.loadChunk(((int)skywarsLevel.getSafeSpawn().getX()) << 4, ((int)skywarsLevel.getSafeSpawn().getZ()) << 4);
```
Hint: Chunk X = Block X / 16

**Comment by Ozelord757** [comment]
Okay thanks, I tested it and the player is still stucking. :/

**Comment by Creeperface01** [comment]
sometimes happens that player gets stuck in unloaded chunks even if they are already sent to the client

**Comment by Goodstuff4UonYT** [comment]
And how to fix that @Creeperface01 ?

**Comment by Ozelord757** [comment]
:/

**Comment by Creeperface01** [comment]
I don't know

**Comment by Creeperface01** [comment]
ask @MagicDroidX or @Snake1999 or @Tee7even

**Comment by Creeperface01** [comment]
and teleportImmediate() works?

**Comment by vzlomka76** [comment]
@Creeperface01 I know how to solve this, I will soon make pull request
