### ISSUE TITLE
walking on stairs is bad

### ISSUE THREAD

**Issue by PikyCZ** [Nukkit/Nukkit#1689]
In CreativeMode moving on stairs is good but in SurvivalMode is bad

* Nukkit Version: 1476fa7
* Java Version: 8
* Client Edition: W10 ~ MCPE 
* Client Version: 1.0.6

<Console>

![2017-04-16](https://cloud.githubusercontent.com/assets/19613582/25073302/eccf2656-22e3-11e7-9403-5d85a1c4bd8a.png)

<Video>
https://youtu.be/22pyjhhqoyI

**Comment by Creeperface01** [comment]
cancel PlayerInvalidMoveEvent or disable movement checks

**Comment by Tee7even** [comment]
#1685

**Comment by Creeperface01** [comment]
@Tee7even #1693
