### ISSUE TITLE
Issue connecting with latest client

### ISSUE THREAD

**Issue by TheModdersDen** [Nukkit/Nukkit#1694]
# Issue description
Client says "Unable to connect to world" upon attempting to load server. Client also can't seem to retrieve server version (I'm running the 1.0.7 client, by the way). 
# Steps to reproduce the issue
Load up a 1.0.7 client, I'm using an iPad running iOS 10.3.1 with the latest Minecraft app version and a Windows 10 Edition (also the latest client), and try to connect to a server with the latest Nukkit. 
# OS and versions
Nukkit Version: 1.0-SNAPSHOT
Java Version: 8
Host OS: Windows 10 (Creators Update), iOS
Client Edition: 1.0.7
Client Version: 1.0.7

**Comment by teflontoni** [comment]
You must compile nukkit to mirror the client's number.
File: src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java

Replace
```
    byte CURRENT_PROTOCOL = 106;
    String MINECRAFT_VERSION = "v1.0.6";
    String MINECRAFT_VERSION_NETWORK = "1.0.6";
```

with



```
    byte CURRENT_PROTOCOL = 107;
    String MINECRAFT_VERSION = "v1.0.7";
    String MINECRAFT_VERSION_NETWORK = "1.0.7";
```

Then compile with JDK and Maven (like stated inREADME.md) and replace your nukkit-1.0-SNAPSHOT.jar with the compiled one and restart the server.

Don't know if it's allowed but here's a link to my compiled file:

[nukkit-1.0-SNAPSHOT.jar 1.0.7 enabled](https://www.file-upload.net/download-12452282/nukkit-1.0-SNAPSHOT.jar.html)

**Comment by Snake1999** [comment]
= =

**Comment by teflontoni** [comment]
As I stated above, I am a total Noob regarding the Do's and Dont's around here.

I doubt my "hack" is that different from the TODO's outcome, @Snake1999 
as far as I can see the update brings only a new resource pack, and they just needed to bump the version number. And so did I.

My kids can play and that was my primary intention, sorry if my input is bad/inappropriate.

**Comment by Leonidius20** [comment]
You can use "AnyVersion" plugin till nukkit will be updated

**Comment by TheModdersDen** [comment]
Neither AnyVersion nor the edited Nukkit jar fix the problem for me. I try to connect with the Windows 10 Beta client, and still see the error.

**Comment by teflontoni** [comment]
That's strange, I played on Windows 10 today. Where do you get a beta build? And which Version number does it have? 

Although if there are new features just fixing the version number won't probably do the trick.

**Comment by TheModdersDen** [comment]
Got the build from here: http://ci.mengcraft.com:8080/job/nukkit/. Nukkit says that its version is:  "1.0dev "??(Apple)?(Pie)" (API 1.0.0)". Is it possible that the build from mengcraft is outdated?

**Comment by TheModdersDen** [comment]
Nevermind... Got it to work. Turns out I had to connect using my outside IP. :)
