### ISSUE TITLE
Signs are not block entity's on restart

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#1700]
### Issue description

Write a short description about the issue
Create a sign it is an block entity. Restart and add code to check if the block is a block entity and the result is false. I checked by getting the block entity at the location and it returns null.
### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: ??

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Tee7even** [comment]
What? Your code please? I don't get what you mean, _block_ is **never** a _block entity_.
