### ISSUE TITLE
cant place end rods

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1705]
### Issue description

read title

### Steps to reproduce the issue

get a end rod
place it

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: ??

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by vzlomka76** [comment]
It's not implemented

**Comment by Snake1999** [comment]
Fixed in bleeding branch
