### ISSUE TITLE
Installation tutorial?

### ISSUE THREAD

**Issue by XDqrkneZ** [Nukkit/Nukkit#1706]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... title says everything.
2. ...
3. ...

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: ??

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Snake1999** [comment]
read readme
