### ISSUE TITLE
can't place redstone related blocks

### ISSUE THREAD

**Issue by chillerkraft** [Nukkit/Nukkit#1709]
### Issue description

Write a short description about the issue
can't place redstone related blocks
### Steps to reproduce the issue

1. ...try to place repeater
2. ...try to place dispenser
3. ...

### OS and versions

* Nukkit Version: ?? #587
 
* Java Version: 8

* Host OS: multicraft idk

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ?? ipad

* Client Version: ??.??.?? 1.0.7

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by vzlomka76** [comment]
@chillerkraft please use branch "changes-04-17"

**Comment by Tee7even** [comment]
Not implemented yet.
