### ISSUE TITLE
Bug - give command

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#171]
![image](https://cloud.githubusercontent.com/assets/11244874/11823202/dc6b1940-a383-11e5-9ecd-34d7c2157a88.png)

**Comment by Pub4Game** [comment]
Name item - "Unknown"

**Comment by Pub4Game** [comment]
@MagicDroidX please fix it

**Comment by Pub4Game** [comment]
@MagicDroidX won't fix
![image](https://cloud.githubusercontent.com/assets/11244874/11913228/6d1f235e-a66e-11e5-9898-00be454819b5.png)

**Comment by MagicDroidX** [comment]
@Pub4Game Oh I haven't got your point. I thought the issue is about the name of the item sry.
