### ISSUE TITLE
Client witch logged in with XBOX will not send LoginPacket when connecting server in version 1.0.8

### ISSUE THREAD

**Issue by boybook** [Nukkit/Nukkit#1716]
### Issue description

Client witch logged in with XBOX will not send LoginPacket when connecting server in version 1.0.8
I added some debug in RakNet but it shows the client didn't send any MCPE DataPackets.

### Steps to reproduce the issue

1. Join server with XBOX account in version 1.0.8
2. I added some debug in raknet, there is no any MCPE DataPacket received.

### OS and versions

* Nukkit Version:  https://github.com/Nukkit/Nukkit/commit/f74b705a166aa3d45872e2f1a5b7eec711a4c5c5
 
* Java Version: 1.8

* Host OS: MacOS / Linux

* Host Configuration: 16 GB RAM, 512 GB SSD drive, 8 core CPU from Intel, 100 Mb internet upload

* Client Edition: Windows 10 and Android

* Client Version: 1.0.8

**Comment by undrfined** [comment]
Reproduced with MiNET.

**Comment by Tee7even** [comment]
Is it surely fixed? It doesn't happen anymore? I have experienced this problem too.

**Comment by Creeperface01** [comment]
Mojang auth servers was down today so maybe its the reason

**Comment by Tee7even** [comment]
@Creeperface01 just showed us that he doesn't understand what's written here once again.

**Comment by Creeperface01** [comment]
It was just idea..

**Comment by boybook** [comment]
Yes, it because Mojang auth servers was down.
