### ISSUE TITLE
Syncing pack with server.

### ISSUE THREAD

**Issue by twixi** [Nukkit/Nukkit#1721]
latest build nukkit on [circleci](https://circleci.com/gh/Nukkit/Nukkit/2048)
always Syncing pack with server... and not join on server
* Java Version: 1.8.0_121
* Host OS: win 7 x64
* Host Configuration: 8 GB RAM, 80 GB HDD 2 core CPU from AMD, 100 Mb internet upload
* Android 6
* Client Version: 1.1.0.8

**Comment by kvetinac97** [comment]
Nukkit DOES NOT support, by now, beta versions (1.1.0+). Downgrade to 1.0.8 in order to join your server.
