### ISSUE TITLE
BossEventPacket

### ISSUE THREAD

**Issue by CraftYourBukkit** [Nukkit/Nukkit#1723]
Please implement this:
https://github.com/pmmp/PocketMine-MP/blob/69f64dd802bc4ffbe3f75841052e919630a10283/src/pocketmine/network/mcpe/protocol/BossEventPacket.php

**Comment by Snake1999** [comment]
:( Instead of asking, why dont you do by yourself?

**Comment by Creeperface01** [comment]
is it real CraftYourBukkit? :D BTW this packet has been added since 1.1

**Comment by VCraftMCPE** [comment]
great support lmao

**Comment by Creeperface01** [comment]
xD
