### ISSUE TITLE
Why this when I try to load a pre-made world?

### ISSUE THREAD

**Issue by tiNsLeY799** [Nukkit/Nukkit#1727]
### Issue description
I have been trying to load four worlds, recently, and although I get this error, I usually work around it. Now, this time, I can't work around it or Nukkit will generate it weirdly.

### Steps to reproduce the issue
1. Get a world from PE
2. Convert it over to Nukkit format
3. Load it.

### OS and versions
* Nukkit Version: 592 (from Jenkins)
* Java Version: ??
* Host OS: Windows 7
* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: Android's 1.0.8
* Client Version: 1.0.8

### Crashdump, backtrace or other files
![why-does-this-happen](https://cloud.githubusercontent.com/assets/12755193/26185907/b013f120-3b42-11e7-8215-a09927141901.JPG)

**Comment by poustmal** [comment]
It supports 0.16 world convert and older versions for now.

**Comment by Snake1999** [comment]
Not GZIP Format. Did mojang updated compressing format or you've got a corrupted world file?

**Comment by tiNsLeY799** [comment]
Well, it's been happening to three other maps. Would this mean I have to convert maps to an older version?
