### ISSUE TITLE
block does not break on the first try

### ISSUE THREAD

**Issue by twixi** [Nukkit/Nukkit#1738]
often when break any block, the block does not break the first time, only the second or third attempt!

**Comment by Snake1999** [comment]
Cannot reproduce.
Use template to provide detailed information, so that our developers could reduce the problem happened on your device.

**Comment by Creeperface01** [comment]
its due to speedmine protection

**Comment by elfin8er** [comment]
Would you mind elaborating @Creeperface01 ? I believe I'm experiencing the same issue. What's speedmine protection? Is there a way to disable it?

**Comment by Creeperface01** [comment]
Yes, there is but only with plugin, but we could add option to the nukkit directly
