### ISSUE TITLE
the site is down

### ISSUE THREAD

**Issue by ICHx** [Nukkit/Nukkit#174]
nukkit.cn

**Comment by MagicDroidX** [comment]
It is not ready yet.

**Comment by fromgate** [comment]
If you have any plugin that you going to suggest to community you can upload it at nukkit.ru :)

**Comment by ICHx** [comment]
<! actually, I found quite few servers on forums support 0.11+, while I see some of them support authentication, I can find the plugin AuthMe for nukkit nowhere. blah blah blah... -->
thx @fromgate
