### ISSUE TITLE
Problems with forums.nukkit.io

### ISSUE THREAD

**Issue by DxDen1004** [Nukkit/Nukkit#1741]
Hello, 

I know that this is not the right place where to ask for help about the forum, but I have no idea about where should I ask... Basically, after creating a nice server with this awesome piece of sotware, I decided to put some plugins in the "plugins" folder. So, I went on the website "https://forums.nukkit.io" and registered. Anyway, after waiting a couple hours, I didn't receive the confirmation email, and now I can't download plugins from the forum. Any help about this issue would be nice, I hope you can understand why I'm writing here.

Thanks in advance.

**Comment by augustoeliezer** [comment]
**Same problem.**

I report at [Contact Us](https://forums.nukkit.io/misc/contact) and comment about this post.

**Comment by KairusDarkSeeker** [comment]
@DxDen1004 @augustoeliezer Check your trash/spam

**Comment by DxDen1004** [comment]
Already checked. There are no messages from forums.nukkit.io

**Comment by KairusDarkSeeker** [comment]
@DxDen1004 oh

**Comment by augustoeliezer** [comment]
@KairusDarkSeeker This was the first thing I done.

**Comment by robotnikthingy** [comment]
I never received a confirmation email either for the forums

**Comment by robotnikthingy** [comment]
Why did you close this, you cant even register on the forums because of this, this is a major bug!
