### ISSUE TITLE
Bug with skins 

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#175]
When you log on to the server 0.13.1 says "invalid skin"

**Comment by Snake1999** [comment]
Uh, our team have found this bug too. There might be mojang edited the protocol. Will fix soon. :D

**Comment by fromgate** [comment]
I think there's a new skin format. Looks for hats of skins:
![Christmas skins](http://minecraftmain.ru/wp-content/uploads/2015/12/mcpe-0-13-1-768x432.png)

**Comment by TexusDark** [comment]
I have fix this but can you add my pull request for fix code of Nukkit ?

**Comment by MagicDroidX** [comment]
Already fixed,but i have not pushed it yet.

**Comment by Snake1999** [comment]
There is a new structure, and yes, we have adapted it tonight. Codes are finshed, but will merge to master branch later after our final check. 
Thanks for reporting bugs :3 @fromgame @Pub4Game

For @TexusDark , our work is done, although I know deleting the limit does not solve the real problem, thanks for caring about Nukkit Project.

**Comment by MagicDroidX** [comment]
It is fixed about 4 hours ago, but I am sleepy and forgot to push it sry :P. BTW, what do you guys think of saving skin data in NBT, is it useful or only using more disk spaces? I'm deciding to remove it from player's nbt.

**Comment by MagicDroidX** [comment]
It is fixed about 4 hours ago, but I am sleepy and forgot to push it sry :P. BTW, what do you guys think of saving skin data in NBT, is it useful or only using more disk spaces? I'm deciding to remove it from player's nbt.

**Comment by xxFlare** [comment]
@MagicDroidX I think it would just use more disk space. Save it to memory?

**Comment by TexusDark** [comment]
@xxFlare @MagicDroidX Look this, It is in PHP so convert in Java : https://github.com/PocketMine/PocketMine-MP/commit/90c3e66e6b87ad8763669850d70c108f364dcaa2

**Comment by MagicDroidX** [comment]
@TexusDark Nukkit is not doing converting works, we have fixed it earlier than PM, plz don't worry about it.

**Comment by fromgate** [comment]
@MagicDroidX 
I think ability to save skin in to NBT will be great if it will grant full skin-control to plugin developers: forcing to change skin in mine-games, for example.
Or creating skin-library for server community.

**Comment by MagicDroidX** [comment]
@fromgate I mean the skin data in player data files such as `players/magicdroidx.dat`. You will still be able to change online players' skins by using API if we remove them from offline players' data files.

**Comment by xxFlare** [comment]
@MagicDroidX What's the point of it though? You still need to update the skin each time a player joins.

**Comment by fromgate** [comment]
Oh! During the night MCW10E updated to 0.13.1 too.... :(
