### ISSUE TITLE
Trapped chests dont do a redstone effect

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#1755]
Unimplemented feature or forgotten to implement probably.

**Comment by PeratX** [comment]
Included in Redstone rewrite.

**Comment by sero583** [comment]
@PeratX I thought this re-write is like the PR multi-threaded nukkit unfortunately dead and I wanted to notice the devs in some way well yeah

**Comment by PeratX** [comment]
Than we should write a issue about TODO list.

**Comment by sero583** [comment]
@PeratX would be the best way just need some active people who arent gone after some months in general nukkit is great but if it had active devs it would be much better, because someone needs to update the list always

**Comment by PeratX** [comment]
Yes of course. MDX has just entered a famous university in China, so he has lots of things to deal with.

**Comment by sero583** [comment]
@PeratX I would like to contribute in Nukkit but I don't know any way to build a nukkit JAR file without using servers like circle-ci. I would like to fix for example a important bug which isnt really that hard to fix (#1508) I think I know also why it does not work, you can read my theory in that issue commented currently as the last comment.

**Comment by SupremeMortal** [comment]
@sero583 
Clone the repo locally. `git clone https://github.com/Nukkit/Nukkit.git` 
Update and initialize the language submodule `git submodule update --init --recursive`
Then initialize all the project files with Maven `mvn eclipse:eclipse` for Eclipse IDE and `mvn idea:idea` for Intellj.
When you've finished adding stuff, compile the project  with `mvn clean package`
The .jar will be in the `target/` folder.
