### ISSUE TITLE
Farmland bug

### ISSUE THREAD

**Issue by CraftYourBukkit** [Nukkit/Nukkit#1756]
I found a bug

Nukkit version: newest and the versions before

Description:
If I cancel the BlockBreakEvent and a player jumps on farmland the farmland gets destroyed.

**Comment by sero583** [comment]
Close your issue...🤦‍♂️ @CraftYourBukkit

**Comment by sero583** [comment]
Hint for you: No block gets broken

**Comment by Snake1999** [comment]
Banned @CraftYourBukkit out from this project.
