### ISSUE TITLE
CircleCI page won't load

### ISSUE THREAD

**Issue by SuperOP535** [Nukkit/Nukkit#1757]
The page at https://circleci.com/gh/Nukkit/Nukkit/tree/master doesn't load, it only keeps loading forever, for both me and some others.. idk if it happens to everyone. I need nukkit 1.1 snapshot

**Comment by Snake1999** [comment]
No snapshots available on Nukkit/Nukkit branch at present :)
BTW, you can compile by yourself. This program is in EARLY DEVELOPMENT for 1.1 .

**Comment by SuperOP535** [comment]
I have no idea how and where to do this, can ou please tell me how to? I have Windows 10

**Comment by SuperOP535** [comment]
@Snake1999

**Comment by Alex0Plays** [comment]
@SuperOP535 
https://yadi.sk/d/boYDtSDs3KJzn8

**Comment by Alex0Plays** [comment]
@SuperOP535 https://yadi.sk/d/aauzyakd3KJzvH

**Comment by SuperOP535** [comment]
Doesn't work @Alex0Plays

**Comment by Snake1999** [comment]
DEVELOPMENT VERSIONS are not stable enough for production use. They are only available to developers who have the ability of compiling java programs.

**Comment by PetteriM1** [comment]
Is there new builds coming?
