### ISSUE TITLE
Jenkins fork from @Angelic47 doesn't work

### ISSUE THREAD

**Issue by SuperOP535** [Nukkit/Nukkit#1758]
I know that this is an unofficial link but you should remove the button at nukkit.io because of the page at Angelic47 only says The requested URL /job/Nukkit/ was not found on this server.

**Comment by Angelic47** [comment]
Sorry about that... Well my server got hacked and this CI has been put offline, which didn't exist anymore. We will remove the link soon, thanks for your reporting!

**Comment by Snake1999** [comment]
@Angelic47 :)

**Comment by SuperOP535** [comment]
@PeratX Why did you close the issue? The button is still there...

**Comment by SuperOP535** [comment]
How long does this take XD

**Comment by SupremeMortal** [comment]
@SuperOP535 https://ci.potestas.xyz/job/Nukkit

**Comment by SuperOP535** [comment]
wow

**Comment by SuperOP535** [comment]
I give up

**Comment by SupremeMortal** [comment]
@SuperOP535 We moved the link to https://ci.nukkitx.com/job/NukkitX/job/master/

**Comment by SuperOP535** [comment]
@SupremeMortal That's NukkitX and please read the issue, your comment does not seem to relate to this in any way

**Comment by SupremeMortal** [comment]
No one active has access to the website. You can see this by taking a look at the forums with all the spam bot mayhem. Nothing will change anytime soon.

**Comment by SuperOP535** [comment]
Closed since Nukkit site is dead (not maintained anymore)

**Comment by SupremeMortal** [comment]
@SuperOP535 https://nukkitx.com

**Comment by SupremeMortal** [comment]
What's the point in posting here if you can see the repo is dead? Seems rather pointless.
