### ISSUE TITLE
Bugs found by our QQ group members

### ISSUE THREAD

**Issue by Snake1999** [Nukkit/Nukkit#176]
Fixing these following bugs and enhancements will be in to-do. Thanks for our group members to report these bugs :3

- [x] Place a sign on a grass block will turn it into dirt.
- [x] Fire on players' bodies will not go out
- [ ] Arrows direct to wrong directions
- [ ] Use bone meal on a grass might produce "grass on grass" or "floating grass"
- [x] No /tp command
- [x] All fishes are the same

**Comment by Pub4Game** [comment]
- [ ] The grass grows under water

**Comment by Pub4Game** [comment]
@MagicDroidX Can  you fix it? :smiley:
