### ISSUE TITLE
Death Card Map（死亡卡地图）

### ISSUE THREAD

**Issue by Rsplwe** [Nukkit/Nukkit#1766]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1.  Death on other maps will lead to Stuck maps（在其他地图死亡会卡住地图）
2. https://user-images.githubusercontent.com/25134114/27757432-f66cb72e-5e33-11e7-99e1-899e538b299b.png

### OS and versions

* Nukkit Version: 1.0dev 
 
* Java Version: 1.8.0_131

* Host OS: Windows 10 Pro

* Host Configuration:

| Item | Value |
|:----:|:-----:|
| Memory(RAM) | 4 GB |
| Storage size | 465.76 GB |
| Storage type | HDD (SSD/HDD) |
| CPU core count | 4 cores |
| CPU provider | Intel (Intel/AMD/...) |
| Internet upload | Mbps (Mbps/Gbps) |

* Client Configuration: what?

| Item | Value |
|:----:|:-----:|
| Client edition | Windows 10 (Windows 10/Andriod/Simulator/...) |
| Client version | 1.1.2 (1.1.1/...) | 

### Crashdump, backtrace or other files

NO

NO
![ss](https://user-images.githubusercontent.com/25134114/27757432-f66cb72e-5e33-11e7-99e1-899e538b299b.png)

**Comment by Angelic47** [comment]
Just speak Chinese if you really can't speak English. Do not use online translator please :)
The title means "Death on other level will cause the level hang up".
Sorry but we can't reproduce it. It seems that you are using a lot of plugins we don't have.
Try to start a new server and just create a new level. Will the problem reproduce again?
----------------
Chinese version:
如果你确实不会英语的话，说中文也可以，不要用机翻（翻译错误太多了），
这个问题我们这里没有办法复现，从图上看你的服务器使用了很多第三方插件。
建议你创建一个新服，只添加一个新的地图，看一下问题是否仍然存在。

**Comment by Snake1999** [comment]
Use proper English
