### ISSUE TITLE
The client often crashes in version 1.1

### ISSUE THREAD

**Issue by WetABQ** [Nukkit/Nukkit#1769]
### Issue description
The client often crashes in version 1.1.
More than me alone, as well as server players.
Sometimes not crashing, sometimes crashing.
No error on the console.
No plugins installed.

### Steps to reproduce the issue
Join the server, but not always crash

### OS and versions
* Nukkit Version: e2f02348b8cc1a38dbab621b4c64a650c16d3fb4
* Java Version: 1.8.0_131
* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu | 
| Memory(RAM) | 2 GB | 
| Storage size | 50 GB | 
| Storage type | SSD | 
| CPU type |Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz | 
| CPU core count | 1 core ?? thread | 
| Internet upload | 100Mbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client edition | Android&IOS | 
| Client version | 1.1.2 |

**Comment by Snake1999** [comment]
It couldn't blame you but, how could I look into your issue?
Are there any ability if you could join any Minecraft PE server?

**Comment by Snake1999** [comment]
The word 'crash' contains everything but information.

**Comment by WetABQ** [comment]
The client crashes before the server map is displayed after the server resource bundle is synchronized.
Not all players crash.
You can try to get into my server.

**Comment by WetABQ** [comment]
But the replacement name will not crash.(Maybe)

**Comment by tigerza117** [comment]
https://github.com/yescallop/Nukkit/pull/41

**Comment by tigerza117** [comment]
fix

**Comment by Creeperface01** [comment]
@tigerza117 your fix only adds invisible chunks... and this issue is related to the crash on join, not during gameplay, and teleport betweeen levels happens only during gameplay.

**Comment by Guillaume351** [comment]
Same problem. Crash after Syncing pack with server, but before Building Terrain. Even with no plugins, on iOS & Android

**Comment by Fleynaro** [comment]
I have also this issue. When I join my server, Minecraft client closes via a strange cause

**Comment by kpwnh** [comment]
Client bug #MCPE-4422045 Internal Bug Reporting of Mojang, this is a client-side bug, however, it doesn't happen with PocketMine or MiNET by some reason.

**Comment by kpwnh** [comment]
The only way to fix is waiting for Mojang to release the new MCPE, in the beta, it's fixed

**Comment by WetABQ** [comment]
Reply upstairs. Why PocketMine and MiNET do not cause the client to crash while Nukkit will cause the client to crash.

**Comment by Goodstuff4UonYT** [comment]
@kpwnh @WetABQ Loaded the new minecraft 1.1.3 version and the client crashed again.

**Comment by Guillaume351** [comment]
Yes I still have the issue. No plugins, with a map I used for the last year with Nukkit.

**Comment by BiGUNMAN** [comment]
@WetABQ Hi, I'm using the following version: http://i.imgur.com/WloupxO.png (most recent Nukkit version), and the crashes are occurring on my Android phone, and Windows 10 Edition. Not consistently, but I'd say 50% of the times I try to connect.

**Comment by Snake1999** [comment]
@Goodstuff4UonYT @Guillaume351 @BiGUNMAN https://github.com/Nukkit/Nukkit/issues/1764
