### ISSUE TITLE
Unable to craft furnaces in survival mode

### ISSUE THREAD

**Issue by Seth8277** [Nukkit/Nukkit#1770]
### Issue description

There is no furnace choice if open the crafting table.
<a href="https://pic.freejishu.com/image/vcTL3"><img src="https://piccdn.freejishu.com/images/2017/07/01/vcTL3.md.png" alt="vcTL3.png" border="0" /></a>

### OS and versions

* Nukkit Version: [e2f0234](https://github.com/Nukkit/Nukkit/commit/e2f02348b8cc1a38dbab621b4c64a650c16d3fb4)
* Java Version: 180_131

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu（Docker） |  
| Memory(RAM) | 1 GB | 
| Storage size | 50 GB | 
| Storage type | SSD | 
| CPU type | unknow | 
| CPU core count | 1 core  | 
| Internet upload | unknow | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client edition | Android | 
| Client version | 1.1.1 |

**Comment by Snake1999** [comment]
Pardon my poor English translation :)

**Comment by deathspawn** [comment]
I noticed you can't even craft them with the Classic UI. After you try to get the furnace out of the crafting table, the 8 cobblestone shows back up in your inventory and the furnace disappears.

**Comment by Creeperface01** [comment]
I think you can craft furnace with classic UI

**Comment by Seth8277** [comment]
Eh... What is the classic UI? How do I get into the classic UI?I'm using a new client that is not configured.

什么是经典界面？怎样进入？我使用的是一个没有配置过的新的客户端
（英语部分来自机翻 ...）

**Comment by Snake1999** [comment]
This is able to be crafted. However, unable to use

**Comment by algiuxass** [comment]
Not working on MC PE 1.4.1, Nukkit latest (stable?) version

**Comment by algiuxass** [comment]
This actually solved the problem: https://github.com/Nukkit/Nukkit/issues/1978
