### ISSUE TITLE
Android : Client crashes after second join.

### ISSUE THREAD

**Issue by pitichampi** [Nukkit/Nukkit#1781]
### Issue Description

Starting the server, the player can join it without any problem. If it quits the game, then, when he'll rejoin, the game crashes and the player is disconnected of the server due to timeout.
If the server is restarted, then the player can join the game again (until he quits it again).

### Steps to Reproduce the Issue
1. Start the server
2. Join the server
3. Quit the server
4. Join again the server

optional :
5. Restart the server
6. Go to step 2.

### OS and Versions
Debian 4.9.30-2 x86_64 / Debian GNU/Linux 9.0

This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.1.3 (protocol version 113)* Nukkit Version: ?? 

* Java Version: 
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

* Host Configuration: Kimsufi server (KS-3C) 8 GB RAM, 2 cores (4 threads)  i3-2130 @ 3.40GHz CPU,100Mb internet connexion. 

| Item | Value |
|:----:|:-----:|
| Host OS |  Linux Debian 9.0 |
| Memory(RAM) | 8 GB | 
| Storage Size | 2048 GB | 
| Storage Type | HDD |
| CPU Type | i3-2130 @ 3.40GHz  | 
| CPU Core Count | 2 cores 4 threads | 
| Upstream Bandwidth | 100Mbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android | 
| Client Version | 1.1.3.1 | 

### Crashdump, Backtrace or Other Files

```
sorry... don't know how to get it...
```

**Comment by CraftYourBukkit** [comment]
Windows 10 also Crashes very often if I leave the server or reader to another one

**Comment by ScraM-Team** [comment]
I see similar behavior.  Doesn't seem to impact iOS clients.

**Comment by Snake1999** [comment]
https://github.com/Nukkit/Nukkit/issues/1781

**Comment by dycdyy** [comment]
This problem continues
