### ISSUE TITLE
Missing dependencies.

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#179]
When trying to build Nukkit the following will appear:

Failed to execute goal on project nukkit: Could not resolve dependencies for project cn.nukkit:nukkit:jar:1.0-SNAPSHOT: Could not find artifact com.tinfoiled.mcpe.leveldb:leveldb:jar:0.8

You are not specifying a repository from which leveldb should be downloaded from.

**Comment by MagicDroidX** [comment]
Read the build guide in README.MD

**Comment by ProjectInfinity** [comment]
Already did. That's how the error happened. Are you certain that you do not have leveldb.jar cached in your m2 repository and as a result it works because of that? Clear your m2 repo and try building from scratch.

![Screenshot](http://puu.sh/lYRCh/4b609dd6e1.png)

**Comment by fromgate** [comment]
@ProjectInfinity 
I use IDEA to build jar. When I met the same problem I found leveldb.jar in the "lib" folder. I added this file to libraries and nukkit.jar was successfully compiled.

**Comment by ProjectInfinity** [comment]
@fromgate That's fine, I did that myself to make it build but it's incorrect usage of maven and there really should be a repository to draw from.

**Comment by MagicDroidX** [comment]
It works fine in my local test as well as TravisCI and circleCI. :s

**Comment by ProjectInfinity** [comment]
@MagicDroidX Did you ensure that you had deleted the library from your m2 cache before trying to build?
