### ISSUE TITLE
When someone enters the server the game crashes but the server stays online and there is no error in the console

### ISSUE THREAD

**Issue by victorpk1999** [Nukkit/Nukkit#1794]
### Issue Description

Write a short description about the issue

### Steps to Reproduce the Issue

1. ...
2. ...
3. ...

### OS and Versions

* Nukkit Version: ?? 

* Java Version: 
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Debian |  
| Memory(RAM) | 2 GB | 
| Storage Size | 30 GB | 
| Storage Type | SSD | 
| CPU Type | AMD| 
| CPU Core Count | 1 cores ?? threads | 
| Upstream Bandwidth | 1 Gbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | 1.1.3| 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by ZizzyZizzy** [comment]
Having the same problem with a server today. Join first time, client crashes. Nothing in the server log other than normal connection messages.

Join the second time, it seems to be fine. I suspect it's a plugin, but with no log data to go from, it would require disabling them one at a time and testing each time.

**Comment by cloud9350** [comment]
#1764

**Comment by victorpk1999** [comment]
Thanks.
Maybe AnyVersion...I used this plugin in all my servers and all do the same.
(Sorry for bad english)
