### ISSUE TITLE
Damage by Projectile items

### ISSUE THREAD

**Issue by asyven** [Nukkit/Nukkit#1795]
### Issue Description

All of items who enxtends EntityProjectile give damage for player or entity.

### Steps to Reproduce the Issue

1. Get XPbottle, Snowball or Enderperl, etc
2. Direct on player or entity and use item

**Comment by ScraM-Team** [comment]
Is there a complete list (on the Minecraft wiki, perhaps), of which projectiles shouldn't cause damage?  When making this change it would be easier to have the complete list so it can be fixed all at once.

**Comment by asyven** [comment]
@ScraM-Team
only bow must cause damage
but some items set knockback

**Comment by sero583** [comment]
Potion also don't makes effect afaik, it just makes a hit

**Comment by Angelic47** [comment]
Fixed by @ScraM-Team
