### ISSUE TITLE
Minecraft client Crash

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1805]
### Issue Description
If you join a server and timeout and try to reconnect your minecraft PE crashes (TESTED with WIndows10 Edition)

### Steps to Reproduce the Issue
1. Join the server
2. Close your Minecraft Windows 10 Edition
3. Try to reconnect

**Comment by cloud9350** [comment]
#1764

**Comment by jrodr10** [comment]
Confirmed
