### ISSUE TITLE
Sign cannot input color words

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1807]
### Issue Description

Write a short description about the issue
use § 
When you exit the edit, the word on the sign will become black color
### Steps to Reproduce the Issue

1. Input something on the sign with color
2. Exit the edit

### OS and Versions

* Nukkit Version: [b190802](https://github.com/Nukkit/Nukkit/commit/b190802a4a3f67064ceae824dbddae16d4974fb5)
Do not just write "latest" or "1.0dev" here. Write compile time is also fine. -->

* Java Version: 8

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Win |  
| Memory(RAM) | 32GB | 
| Storage Size | 250 GB | 
| Storage Type | SSD | 
| CPU Type | Intel | 
| CPU Core Count | 24 cores  38 threads | 
| Upstream Bandwidth | 20M | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Win | 
| Client Version | 1.1.3 |

**Comment by Creeperface01** [comment]
you must be a OP

**Comment by lsw46** [comment]
yes..but when i exit the edit , the color will become black

**Comment by lsw46** [comment]
emmm.......you can try it ..

**Comment by lsw46** [comment]
fixed in 1.1.4

**Comment by PetteriM1** [comment]
Works if you are op, close this.
