### ISSUE TITLE
While using PC map...

### ISSUE THREAD

**Issue by shanwer** [Nukkit/Nukkit#1818]
### Issue Description

Write a short description about the issue
PC Item list is different from PE Item list,so while using PC map,some blocks will be strange.
### Steps to Reproduce the Issue

1. ...
2. ...
3. ...

### OS and Versions

* Nukkit Version: ZXDA #195 2017-7-23 

* Java Version: Jre1.8.0_141-b15
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | CentOS(Linux) |  
| Memory(RAM) | 1 GB | 
| Storage Size | 65 GB | 
| Storage Type | ?? | 
| CPU Type | Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz | 
| CPU Core Count | 4 cores ?? threads | 
| Upstream Bandwidth | UPLOAD SPEED is more than 10MB/S| 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android(ARM) | 
| Client Version | 1.1.3 | 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
![screenshot_20170726-103451](https://user-images.githubusercontent.com/16631550/28602165-2a7be64c-71ef-11e7-9ed0-78ee96fea7c7.png)

```

**Comment by shanwer** [comment]
I don't know how to upload a picture in text box,so I gave a link.

**Comment by cloud9350** [comment]
Item code problem :)

**Comment by kvetinac97** [comment]
This is not Nukkit bug. Problem is caused because in MCPE and MCPC, there are different IDs of blocks and items (wooden slab => detector rail...) CreeperFace made a plug-in called WorldFixer on PocketMine, so you can have a look how it works.

**Comment by shanwer** [comment]
All right.But why not add the fuction into core?It's quite difficult to fix all the blocks like my server's map--APTERRA.It is as large as 700MB.

**Comment by jrodr10** [comment]
I have a world fixer type plugin for nukkit

**Comment by shanwer** [comment]
Really?Can you send it to me?

**Comment by Creeperface01** [comment]
WorldFixer plugin is for nukkit too

**Comment by Creeperface01** [comment]
but it only works like world edit, if you need to convert large world, use some better converter instead

**Comment by shanwer** [comment]
Thanks.I will try it after getting home.
