### ISSUE TITLE
move wrongly

### ISSUE THREAD

**Issue by UNIvErSeKO** [Nukkit/Nukkit#1819]
I'm korean, so i weak engilsh. I searched many site and this github issues. but I don't solved this problem.
player go stairs and half block, console said "'PlayerName' moved wrongly!"
so I try this code
`@EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = false)
public void onPlayerInvalidMoveEvent(PlayerInvalidMoveEvent event) {
        event.setRevert(false);
}`
but I don't know this code where put in.
how put in this code?

 OS and Versions

 Nukkit Version: apple pie

* Java Version: newest verision
* Host Configuration: intel I7-3770, 12GB ram, 500M internet.

| Item | Value |
|:----:|:-----:|
| Host OS | window 10 |  
| Memory(RAM) | 12 GB | 
| Storage Size | 500 GB | 
| Storage Type | hdd | 
| CPU Type | I7-3770 | 
| CPU Core Count | 4 cores 8(MAYBE) threads | 
| Upstream Bandwidth | 500 | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ANDROID | 
| Client Version | 1.1.4 | 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by shanwer** [comment]
You should try to edit server.properties first before you do that,there's a line allow-flight=off,change off to on.

**Comment by UNIvErSeKO** [comment]
allow-flight? As far as i know is.  If i on this, player can fly?

**Comment by UNIvErSeKO** [comment]
my sever is survival server

**Comment by shanwer** [comment]
Ennnnnnnnn.This is the best method to solve the problem and if the players don't use cheat tools, they can't fly.

**Comment by UNIvErSeKO** [comment]
really? so, you say, if player haven't cheat tool, players don't fly allow-flight on?

**Comment by shanwer** [comment]
Yes.

**Comment by UNIvErSeKO** [comment]
oh thank you, I test my sever
