### ISSUE TITLE
PC地图块转换错误

### ISSUE THREAD

**Issue by wjrlxa** [Nukkit/Nukkit#1824]
用PC地图开服，末地烛和用铲子打平的黄色土地转换会互换。白色半砖会变成深棕色半砖。

**Comment by wjrlxa** [comment]
![image](https://user-images.githubusercontent.com/7100522/28744284-f23082ae-748f-11e7-9c52-73250f46701c.png)
![image](https://user-images.githubusercontent.com/7100522/28744299-8181781e-7490-11e7-970c-f509111941ac.png)

**Comment by PetteriM1** [comment]
In english?

**Comment by kvetinac97** [comment]
这不是Nukkit的错误。 您将需要制作或找到一个WorldEdit插件。
(:D google translate)
This is not bug of Nukkit. You will need to make or find a WorldEdit plugin.

**Comment by Angelic47** [comment]
> In English:
> While start a server by using Minecraft PC level, there are some blocks went wrong. For example, end rod will become grass road, and grass road will become end rod. (See the picture 2)

That's a block id compatibility problem, some blocks between MinecraftPC and MinecraftPE have different block id.
To solve this problem, I think there needs a block id mapper, which turns MinecraftPC block into MinecraftPE's. Or you will need a WorldEdit plugin to replace the wrong blocks manually.

(楼主原文的英文翻译略)
这是方块id的兼容性问题, PC地图和PE地图有些方块的方块id是不一样的.
我认为要解决这个问题的话, 需要一个方块id的转换器, 把PC的方块转换成PE的方块. 否则的话, 你需要一个WorldEdit插件来手工替换错误的方块.

**Comment by wjrlxa** [comment]
ok thanks
