### ISSUE TITLE
We want to row boats!

### ISSUE THREAD

**Issue by shanwer** [Nukkit/Nukkit#1825]
### Issue Description

Write a short description about the issue
You can't compose boats and you can't row a boat either.
### Steps to Reproduce the Issue

1. Join the server.
2. Get the enough things to make a boat.
3. You will find the wood pulp is grey and you can't compose a boat.
4./gamemode 1,then find the boat and set it.Get into the boat then you will subside for 1 block.

### OS and Versions

* Nukkit Version: 2017-7-29 

* Java Version: JDK8 Release，JRE 8 Release
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | All |  
| Memory(RAM) | 4 GB | 
| Storage Size | 128 GB | 
| Storage Type | SSD | 
| CPU Type | Intel i3 2.26GHz | 
| CPU Core Count | 4 cores ?? threads | 
| Upstream Bandwidth | 100Mbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | All | 
| Client Version | 1.1.4 | 

### Crashdump, Backtrace or Other Files

NONE

```

**Comment by larryTheCoder** [comment]
@shanwer We are working on Minecarts and Boats vehicle AI
take a look at this [pull request](https://github.com/Nukkit/Nukkit/pull/1763)
