### ISSUE TITLE
Compile failure - BrewStand.java

### ISSUE THREAD

**Issue by Flirble** [Nukkit/Nukkit#183]
Can't compile the latest version

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project nukkit: Compilation failure: Compilation failure:
[ERROR] /data//ukkit/src/main/java/cn/nukkit/tile/BrewingStand.java:[91,20] error: list has private access 
in ListTag
[ERROR] 
[ERROR] /data/Nukkit/src/main/java/cn/nukkit/tile/BrewingStand.java:[122,46] error: list has private access
 in ListTag
[ERROR] 
[ERROR] /data/Nukkit/src/main/java/cn/nukkit/tile/BrewingStand.java:[125,46] error: list has private access
 in ListTag
[ERROR] 
[ERROR] /data/Nukkit/src/main/java/cn/nukkit/tile/BrewingStand.java:[127,67] error: list has private access
 in ListTag
[ERROR] 
[ERROR] /data/Nukkit/src/main/java/cn/nukkit/tile/BrewingStand.java:[129,67] error: list has private access
 in ListTag

**Comment by Pub4Game** [comment]
@Creeperface01 please fix it

**Comment by Creeperface01** [comment]
I am working on this :)
