### ISSUE TITLE
nbt items failure problem

### ISSUE THREAD

**Issue by juzi5201314** [Nukkit/Nukkit#1836]
When carrying nbt items，such as PlayerInteractEvent, PlayerItemHeldEvent ...Will the failure.
get player Items on hand should return air. and that Can't switch to in addition to the first case outside the location of the shortcut bar.

**Comment by WetABQ** [comment]
I also have the same problem
我也存在同样的问题
And if the player holding the items nbt more will cause the console error
而且如果玩家手持物品的nbt越多会造成控制台报错
Players use the item click will be error
玩家使用该物品点击也会报错

**Comment by WetABQ** [comment]
![image](https://user-images.githubusercontent.com/25319400/28913729-a93a262e-786b-11e7-9429-3aba886b664c.png)
![image](https://user-images.githubusercontent.com/25319400/28913744-b2c8ee5a-786b-11e7-844f-f665c956820c.png)

**Comment by juzi5201314** [comment]
是的，我也有同样的报错

**Comment by BlockForWhale** [comment]
我的好像没问题
