### ISSUE TITLE
Minecart bug

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1839]
### Issue Description
(sorry bad english, google translated)

The player appears to be in the minecart until it is broken. (invisible for other players)

### Steps to Reproduce the Issue
1. Go to ride in minecart.
2. Left from minecart.
3. Ask someone to look where you are.
4. Player see you are in minecart. (You are not in minecart.)
5. Other player break minecart and see where you really are.

### OS and Versions
* Nukkit Version: 1.1.3 and 1.2
* Java Version: 1.8_131

**Comment by larryTheCoder** [comment]
Checked riding base and no problems.. Any bright ideas @Creeperface01

**Comment by Creeperface01** [comment]
mm idk I haven't tested minecarts yet
