### ISSUE TITLE
OP join problem

### ISSUE THREAD

**Issue by EvilPupil** [Nukkit/Nukkit#1843]
### Issue Description
When a player join the server, if that player is op, minecraft crashed

**Comment by PetteriM1** [comment]
In my server it crash also without op.

**Comment by EvilPupil** [comment]
# xD gg

**Comment by dycdyy** [comment]
i have the same problem,my players tried many times,but nothing work.it just crushed again again.So now i just use Pocketminepm ...i hope the problem can solve soon

**Comment by cloud9350** [comment]
#1764

**Comment by ZephyrThomasY** [comment]
emmmm, i solve the problem by making a plugin, you can record the op info of player when they quit and cancel his op , and when player join , read the config , if the player was op , give him op

**Comment by PeratX** [comment]
You guys should look into what makes op and normal player different when entering server.

**Comment by shanwer** [comment]
Now my server doesn't crash when op join.So...Try to close?(Use Nukkit core later than Aug 27th)

**Comment by Snake1999** [comment]
Problem still available?

**Comment by EvilPupil** [comment]
It still happening

**Comment by shanwer** [comment]
Maybe it's a plugin crash.My server never crashes like what you said.

**Comment by shanwer** [comment]
Please close it.I tested many servers but never crashed.Use the latest core to fix it.

**Comment by EvilPupil** [comment]
Allright I go have try.
