### ISSUE TITLE
Uncrafting gold blocks

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#1849]
### Issue Description

Gold blocks can't be uncrafted.

### Steps to Reproduce the Issue

Get gold blocks and put them into a crafting table - they won't be converted to gold ingots 
This has been confirmed on pocket GUI and the classic GUI,

### OS and Versions

* Nukkit Version: https://github.com/Nukkit/Nukkit/commit/b190802a4a3f67064ceae824dbddae16d4974fb5

* Java Version: 8

**Comment by PeratX** [comment]
#1868
