### ISSUE TITLE
Level.getBlockIdAt(parameters); only returns 0 on not generated blocks.

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#1852]
### Issue Description

Im generating a random x and z in a specific range and want to get a safe place for y but getBlockIdAt(); only returns 0 for me on not generated chunks somehow. I also forced server to generate them and used loadChunk none of these attempts made another effect. On spawn for example my code works fine.

### Steps to Reproduce the Issue

1. Create an plugin and just use some high X and Z instead of generating them
2. Try to gather a safe Y
3. fail...

### OS and Versions
Nukkit version:  `` Nukkit Version: This server is running Nukkit 1.0dev ???(Apple)?(Pie)? implementing API version 1.0.0 for Minecraft: PE v1.1.3 (protocol version 113)``
Java version: ``
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
``

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu |  
| Memory(RAM) | 512 MB | 
| Storage Size | 50 GB | 
| Storage Type | HDD | 
| CPU Type | vCore (uses Intel Xeon [dont know exactly which]) | 
| CPU Core Count | 1  cores ?? threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android | 
| Client Version | 1.1.0 | 

### Crashdump, Backtrace or Other Files
Example code (may contain errors such as forgot a semi-colon)
```
Level level = this.getServer().getDefaultLevel();
int x = 99999; //just using an irrelevant position which COULD be generated
int z = 99999;
level.generateChunk(x, z, true); //optional wont make any effect unfortunately
level.loadChunk(x, z); //also optional wont make any effect unfortunately
int y;
for(y = 127; y > 0; --y) {
   if(b!=Block.AIR&&b!=Block.LEAVES&&b!=Block.LEAVES2&&b!=Block.SNOW_LAYER) {
       y++;
   }
}
this.getLogger().info("Y: " + String.valueOf(y));
```

**Comment by NycuRO** [comment]
@Creeperface01

**Comment by NycuRO** [comment]
#1846 @sero583 Can you test if work? 👍

**Comment by sero583** [comment]
@NycuRO will do ASAP

**Comment by sero583** [comment]
Update to other reading people: @NycuRO's try does not also unfortunately work.

**Comment by PeratX** [comment]
Of course you should generate chunks before you getBlockIdAt

**Comment by sero583** [comment]
@PeratX ofcourse I do, but unfortunately it has not any effect for me I even called the function by myself (``Level.generateChunk(int x, int z, boolean force)``). Do you know how I could solve this by myself?

**Comment by PeratX** [comment]
As you see, generateChunk is async. You should submit a task to wait until the chunk has been gererated.

**Comment by sero583** [comment]
@PeratX Ah I get what you mean calling it my by own async task and checking it onCompletion of the task. Thanks will test out and probably close this!

**Comment by PeratX** [comment]
You are welcome : )

**Comment by sero583** [comment]
A huge thanks to @PeratX. I extended the GenerationTask class and executed my code by using super.onRun(); and super.onCompletion(server); on the task

**Comment by NycuRO** [comment]
@sero583  <3
