### ISSUE TITLE
setMotion is now broken

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [Nukkit/Nukkit#1853]
### Issue Description

set motion is random, sometimes it is very strong, often the player will be bugged back, some players will bug very extremely after this

### Steps to Reproduce the Issue

1. use player.setMotion()
2. set motion is random, sometimes it is very strong, often the player will be bugged back, some players will bug very extremely after this

I tested it with an older version of nukkit, and there setMotion works fine.
I think it is since the minecarts were added.

### https://youtu.be/fFooBMZdP2U

**Comment by Goodstuff4UonYT** [comment]
The first motion is normal, the second one is stronger, the third one is extremly stronger and after this the player will be bugged back.

**Comment by sero583** [comment]
@Goodstuff4UonYT I think thats just the antifly protection by nukkit, maybe enable it in server.properties flying to enabled and test again

**Comment by Goodstuff4UonYT** [comment]
@sero583 If I change the nukkit.jar all is normal. I dont change anything else.

**Comment by Goodstuff4UonYT** [comment]
@sero583 https://www.youtube.com/watch?v=fFooBMZdP2U&feature=youtu.be Same properties, same plugins, old nukkit

**Comment by sero583** [comment]
@Goodstuff4UonYT Oh well then hope it gets fixed asap

**Comment by larryTheCoder** [comment]
Argh, i know there something wrong

**Comment by PeratX** [comment]
Does the recent pull request fix this?

**Comment by Goodstuff4UonYT** [comment]
@PeratX Yes, I think so.
