### ISSUE TITLE
Players fight back very far

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1867]
### Issue Description

Players fight back very far
打人自带击退膜法
### Steps to Reproduce the Issue

1. Fight
找两个人来PVP
2. Attached to hit a few times
连着打几下，玩家就会退的很远，甚至是卡退

### OS and Versions

* Nukkit Version: [81eb29d](https://github.com/Nukkit/Nukkit/commit/81eb29dc71e6a408ce1bf33f58c0305515800632) [b190802](https://github.com/Nukkit/Nukkit/commit/b190802a4a3f67064ceae824dbddae16d4974fb5)   
Test in these two commits

* Java Version: 8

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Windows Server 2016 |  
| Memory(RAM) | 32GB | 
| Storage Size | 280GB | 
| Storage Type | SSD | 
| CPU Type | Intel Xeon | 
| CPU Core Count | 24 cores 48 threads | 
| Upstream Bandwidth | 20 Mbps| 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Win10 Android| 
| Client Version | 1.1.3-1.1.5 |

**Comment by PeratX** [comment]
然而，并没有人鸟。。@Snake1999

**Comment by lsw46** [comment]
奇怪的问题o(╥﹏╥)o

**Comment by lsw46** [comment]
It seems to have been fixed in the latest version
Close....
xD

**Comment by Snake1999** [comment]
XD
