### ISSUE TITLE
Some items cannot be crafted or uncrafted

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1868]
### Issue Description

Cannot craft or uncraft some items
部分物品不能合成或分解

Cannot craft :
不能合成的有：
玻璃板 Glass panes
石英台阶 Quartz Slabs
染料  Dye
除了白床以外的床  Bed with other colors     
铁砧 Anvil
花盆  Flower Pot
所有的铁轨 All Rail

Cannot uncraft:
不能被分解的有：
钻石块 Block of diamond
金块  Block of Gold
绿宝石块  Block of Emerald
铁块  Block of Iron
煤炭块 Block of Coal
红石块  Block of Redstone
青金石块 Lapis Lazuli Block
所有的矿物

It can uncraft in Classic UI. But uncrafting Block of Gold in classic UI ,It will disappear
这能在经典UI中分解，但是金块不能，会被吞

Other:
其他
Potatoes cannot be grown
土豆不能种植

### OS and Versions

* Nukkit Version: [b7f73ab](https://github.com/Nukkit/Nukkit/commit/b7f73abd9be810b0ccf601a27752b1c6b678dfc6) 

* Java Version: 8

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition |  Win10 Android| 
| Client Version | 1.1.3-1.1.5 | 

![image](https://user-images.githubusercontent.com/16436412/29391654-65393d14-832b-11e7-8ada-34548d60b024.png)
![image](https://user-images.githubusercontent.com/16436412/29391658-6a6b6a46-832b-11e7-910b-340d108f9651.png)
![image](https://user-images.githubusercontent.com/16436412/29391664-6ec34280-832b-11e7-9d8e-306f1dac067a.png)

**Comment by WetABQ** [comment]
I have same issue.
我也有相同的问题

**Comment by PikyCZ** [comment]
I mean crafting is fixed in creeperface improvements > #1834

**Comment by lsw46** [comment]
@PikyCZ I will test that PR

**Comment by lsw46** [comment]
It fix in that PR ...
all items can craft or uncraft

**Comment by Creeperface01** [comment]
still?

**Comment by lsw46** [comment]
It seems to be fixed in 1.2
