### ISSUE TITLE
Unable to break iron ore blocks

### ISSUE THREAD

**Issue by ZizzyZizzy** [Nukkit/Nukkit#1873]
### Issue Description
I looked around the open and closed issues, but I do not see anything related to this issue.

When using a wooden pickaxe, you are unable to break iron ore blocks. The breaking pattern appears, but when the final hit is issued, it goes back to a normal iron ore block graphic and nothing drops.

Coal ore mines and drops fine.

### Steps to Reproduce the Issue
Find iron ore, attempt to mine with wooden pickaxe.

### OS and Versions
CentOS 6.9
[INFO] This server is running Nukkit 1.0dev-20170821 (Apple) (Pie) implementing API version 1.0.0 for Minecraft: PE v1.1.3 (protocol version 113)

(Compiled this morning)

* Java Version: 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

* Host Configuration: 
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
128GB RAM, 4GB assigned to Nukkit

* Client Configuration: 
Android Client v1.1.5

### Crashdump, Backtrace or Other Files
N/A

![iron_ore_oops](https://user-images.githubusercontent.com/5203624/29529269-3d3ff10c-865c-11e7-8b43-b5c8fc7988c6.gif)

**Comment by SupremeMortal** [comment]
You're clearly using a wooden pickaxe which is below the required level that can be used to mine Iron Ore. Stone or better is needed.

**Comment by ZizzyZizzy** [comment]
Derp. Of course.
