### ISSUE TITLE
Some problem about  | Enchantment Table | Brewing Stand | Cauldron

### ISSUE THREAD

**Issue by lemon31277** [Nukkit/Nukkit#1875]
Some problem about  | Enchantment Table | Brewing Stand | Cauldron
有关关于 附魔台 酿造台 炼药锅 的问题

| Enchantment Table | 
1.After the completion of the enchantment, lapis lazuli will not decrease
附魔完成后青金石不会减少

 | Brewing Stand | 
1.After finished, it will not stop
炼药完成后不会停止
![image](https://user-images.githubusercontent.com/16436412/31044640-9f227f52-a605-11e7-859b-add9c27f3934.png)

 | Cauldron |
1.Fill the water with glass, and the water in the Cauldron will not decrease
用玻璃片装水，炼药锅里面的水不会减少
![image](https://user-images.githubusercontent.com/16436412/29607763-df020038-8824-11e7-8379-f90e89ee8b31.png)

### OS and Versions

* Nukkit Version: [b04061b](https://github.com/Nukkit/Nukkit/commit/b04061b912ec16c4c9c753f2e475f6e2e9514402)

* Java Version: 8

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition |Win10 and Android| 
| Client Version |1.2.3|

**Comment by NycuRO** [comment]
@Creeperface01 Your creations

**Comment by Creeperface01** [comment]
Brewing works, cauldron idk and enchant and anvil its a MCPE bug
