### ISSUE TITLE
Error when you run the command 

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#188]
![image](https://cloud.githubusercontent.com/assets/11244874/11914777/aeb3d1a4-a699-11e5-94d2-b9a372fa7ad0.png)

**Comment by xpyctum** [comment]
А мы Ванги должны гадать твой код.

**Comment by Pub4Game** [comment]
@xpyctum Какой код?

**Comment by xpyctum** [comment]
Ошибся. Думал ты плагин накосячил.

**Comment by Pub4Game** [comment]
@xpyctum Бывает))
