### ISSUE TITLE
World not loading correctly

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1883]
![image](https://user-images.githubusercontent.com/26197131/29751728-fcdc99a0-8b59-11e7-942d-db0979458147.JPG)

World not loading correctly. I use last build (27.8.2017).

**Comment by NycuRO** [comment]
I don't have this issue. Probably your world it's corupted or visual bug. Closed.

**Comment by shanwer** [comment]
If you're sure that there is nothing wrong with your world,you can use Unofficial-Nukkit-Patch to fix it XD

**Comment by PetteriM1** [comment]
What patch?

**Comment by PetteriM1** [comment]
I don't think it is world corruption because it happens with all worlds also just created worlds. 

Edit: There is no problem if no same spawn point with all worlds. Still sometimes some chunks don't load.

**Comment by NycuRO** [comment]
@PetteriM1 I don't have any bug.

**Comment by NycuRO** [comment]
Cannot reproduce, @PeratX you can close.
