### ISSUE TITLE
Crash OutOfMemory

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#189]
![image](https://cloud.githubusercontent.com/assets/11244874/11915035/f3ab39c6-a6a5-11e5-80ae-192a45156870.png)

: /
on a dedicated server 
4gb RAM

The server turns on, I go and he eats all of RAM on and off

**Comment by imjack** [comment]
Try joining without any plugins?

**Comment by xpyctum** [comment]
How you run nukkit?

**Comment by Pub4Game** [comment]
@imjack Yes. It's weird... Because sometimes I can log in, sometimes not.

**Comment by Pub4Game** [comment]
@xpyctum java - jar nukkit.jar :smiley:

**Comment by xpyctum** [comment]
@Pub4Game you need use -Xms param.

**Comment by xpyctum** [comment]
@Pub4Game http://stackoverflow.com/questions/1493913/how-to-set-the-maximum-memory-usage-for-jvm

**Comment by Pub4Game** [comment]
@xpyctum He has to determine the amount of resources....

**Comment by xpyctum** [comment]
@Pub4Game but try.

**Comment by Pub4Game** [comment]
@xpyctum But not generated map...

**Comment by MagicDroidX** [comment]
Looks like there is something wrong with the player's data file.

**Comment by Pub4Game** [comment]
@MagicDroidX 

when you log on to the server Nukkit consumes all available RAM and crashes

**Comment by MagicDroidX** [comment]
@Pub4Game Plz upload your player data file.

**Comment by Pub4Game** [comment]
And oh, by the way, I noticed that he constantly says that the file is damaged the player

**Comment by Pub4Game** [comment]
https://www.dropbox.com/s/g17m2n8s99yl3in/pub4game.zip?dl=0

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/11917872/aeed5ad2-a72a-11e5-81e7-c33120782a11.png)

Always the same coordinates.Please fix, because this is a pretty important problem!

**Comment by xpyctum** [comment]
I confirm the bug
