### ISSUE TITLE
problem with plugins

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1894]
### Issue Description

Client crash most times when joining if plugins enabled. Tested with SimpleLogin and many other plugins.

### Steps to Reproduce the Issue

1. Enable plugin like SimpleLogin.
2. Try to join to server.

### OS and Versions

* Nukkit Version: 1.0dev (last) 

* Java Version: 
```
1.8.0_131
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Linux |  
| Memory(RAM) | ?? GB | 
| Storage Size | ?? GB | 
| Storage Type | HDD | 
| CPU Type | ?? | 
| CPU Core Count | ?? cores ?? threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Windows 10 | 
| Client Version | 1.1.5 | 

### Crashdump, Backtrace or Other Files

```
player logged out due to timeout
```

**Comment by NycuRO** [comment]
It's not bug by plugins. It's bug by packets.

Fixed in 1.2.

**Comment by PetteriM1** [comment]
Do you know when 1.2 come?

**Comment by NycuRO** [comment]
No @PetteriM1 .

**Comment by rusinc** [comment]
i had problem like this. For fix i remove CommandParameter(s) from some plugins.

**Comment by PetteriM1** [comment]
@rusinc  Can you tell how?
