### ISSUE TITLE
Nukkit live

### ISSUE THREAD

**Issue by Donquih0te** [Nukkit/Nukkit#1898]
Do you want to abandon the development Nukkit or are you just fed up?

//don't ban)

**Comment by Creeperface01** [comment]
none of that.

**Comment by sero583** [comment]
Nukkit is a great project, but well yes development is very inactive. Nukkit ain't a software, which you should abandon.

**Comment by PeratX** [comment]
The Nukkit Development Team will continue this project.
The community is now supporting the development of Nukkit.
Sooner or later, @MagicDroidX @boybook @Snake1999 will be active.
