### ISSUE TITLE
splash potion bugs

### ISSUE THREAD

**Issue by Megalunchbox** [Nukkit/Nukkit#1899]
### Issue Description

Write a short description about the issue

Have not tested these in pe. Shouldnt matter though

Here are several problems with (splash) potions...

1 - Potions travel too far horizontal. (fixed)
2 - You cannot throw a potion while a block is in your breaking reach. (fixed)
3 - When potions collide with an entity they disappear.

### Steps to Reproduce the Issue

for issue 1 (fixed)
issue 2 (fixed)
issue 3 -

1. Spawn any mob
2. Throw a potion at the mob
3. the potion will disappear when it should give effects.

### OS and Versions

* Nukkit Version: ?? 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.1.3 (protocol version 113) Compile time : Irrelevant
* Java Version: 
```
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
```
* Host Configuration:  8GB Ram i7

**Comment by sero583** [comment]
3. is #1508

**Comment by Megalunchbox** [comment]
update - when using the builds by creeperface 2 and 1 were fixed

**Comment by sero583** [comment]
@Megalunchbox 3rd is a code-side bug, the collision check on the entity does not work as it should. I researched that, but I was too lazy to fix it though.

**Comment by Megalunchbox** [comment]
Yeah I had the guy who worked on levelry fix it, could we use that code?

**Comment by sero583** [comment]
@Megalunchbox I guess Levelry is a PocketMine-MP Spoon. The code could be converted from PHP to Java but the bug is a small mistake so we do not really need to overtake any code. Just fix the small mistake

**Comment by sero583** [comment]
Also by the way can be closed as this now counts reportedly as a duplicate from #1508, since other bugs are fixed and the only thing what bugs is collision

**Comment by Megalunchbox** [comment]
true, lets get this fixed :)
