### ISSUE TITLE
在Java9下运行Nukkit会出现问题

### ISSUE THREAD

**Issue by Rsplwe** [Nukkit/Nukkit#1901]
系统：Linux
Java版本：Java 9
![image](https://user-images.githubusercontent.com/25134114/30779479-a9487b3e-a124-11e7-9407-88b919f46e98.png)

**Comment by pkt77** [comment]
This is not a problem, and is only shown by Java 9 on startup. Nothing can be done about this except going back to Java 8.

**Comment by Snake1999** [comment]
We should not force users to remain java 8 as java 9 is now on the way; however we'd face on this issue

This issue is caused by netty. There are some issues on netty project hosted at github. Sometimes the direct memory buffer used by netty is not accessible in some platforms. Checking them out.

**Comment by PeratX** [comment]
Nukkit has not officially switched to Java 9, please be patient.
