### ISSUE TITLE
 Please give me a solution

### ISSUE THREAD

**Issue by rio2108** [Nukkit/Nukkit#1902]
### Issue Description

Write a short description about the issue
1.Monsters and animals are not spawned and do not move when spawned in creative mode
2.Even if I modify the server.properties file, it does not apply in some cases.
3.I can not go to hell and Enderworld

### Steps to Reproduce the Issue

1. ...Server Installation
2. ...Execution
3. ...End

### OS and Versions

* Nukkit Version: ?? 
*PE1.1.3 API

* Java Version: 1.8.0_144
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | ?? |  
Windows
| Memory(RAM) | ?? GB | 
*4GB
| Storage Size | ?? GB | 
*120GB
| Storage Type | ?? | 
*SSD
| CPU Type | ?? | 
* CORE2 DUO
| CPU Core Count | ?? cores ?? threads | 
| Upstream Bandwidth | ?? | 
*wifi/100 Mbps

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
*Android
| Client Version | ?? | 
*1.1.5

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by PetteriM1** [comment]
If you want animals or monsters you need to use plugin example this: https://github.com/CoreXDevelopmentTeam/NovaMobs

Nether and end are not implemented yet but you can create nether world using this plugin: http://forums.voxelwind.com/resources/universal.124/

**Comment by sero583** [comment]
Unimplemented features, close issue please.
