### ISSUE TITLE
1.2.0 Error

### ISSUE THREAD

**Issue by HaNiTLG** [Nukkit/Nukkit#1904]
Hey guys!
Firstly, I just want to report that the newest Nukkit version does not work with Minecraft PE v. 1.2.0.
Therefore, my question is, when do you will release the next Nukkit update for the 1.2.0 version? 
Secondly, I have a small question about the Java support. Does Nukkit also support Java 9 or is it in plan?
Thanks for your answer!
Best regards,
HaNiTLG :)

**Comment by SupremeMortal** [comment]
Support for Java 9 will be done once Netty has been updated to a compatible version.
Experimental support for 1.2.0 can be found here: https://github.com/Creeperface01/Nukkit/tree/GT1.2
Binaries can be found here: https://ci.potestas.xyz/job/Nukkit-GT1.2/

**Comment by HaNiTLG** [comment]
Ok, thanks for the information! :)
