### ISSUE TITLE
Support for 1.2.1 and up

### ISSUE THREAD

**Issue by TechieBlort** [Nukkit/Nukkit#1907]
add support for 1.2

**Comment by Megalunchbox** [comment]
Its being worked on

**Comment by PetteriM1** [comment]
You can try this beta build: https://circleci.com/gh/PetteriM1/Nukkit/tree/GT1.2

**Comment by AlexCreeper25** [comment]
how to doownload it? i tried everything but maybe i'm a noob...

**Comment by SupremeMortal** [comment]
https://ci.potestas.xyz/job/Nukkit-GT1.2/
There was only client-side changes in 1.2.1 so server versions are still on 1.2.

**Comment by AlexCreeper25** [comment]
Btw, i still cant download it although i’m logged in in circleci.com, any help? @PatteriM1

**Comment by AlexCreeper25** [comment]
@PetteriM1 *

**Comment by SupremeMortal** [comment]
Did you see the link I sent @AlexCreeper25

**Comment by PetteriM1** [comment]
Try this direct link to last build: https://230-104362932-gh.circle-artifacts.com/0/tmp/circle-artifacts.P3Sev6E/nukkit-1.0.jar

**Comment by Snake1999** [comment]
Working.

NO WHAT SO-CALLED 'BETA-BUILD' IS RELEASED BY WE OFFICIALS - BE CAREFUL ON VIRUS THAT MIGHT EXISTS IN BUILDS PROVIDED NON-OFFICIAL.

**Comment by sero583** [comment]
@Snake1999 I do not think on @Creeperface01's branches are any viruses though
