### ISSUE TITLE
Minecraft v1.2.2

### ISSUE THREAD

**Issue by gonetoplaid74** [Nukkit/Nukkit#1913]
Hi There,

Just wondering when you might have a Nukkit version that is compatible with Minecraft PE V1.2.2

The latest online I can find is for 1.1.3

thank you!

**Comment by SupremeMortal** [comment]
Unofficial experimental builds:
https://ci.potestas.xyz/job/Nukkit-GT1.2/

**Comment by gonetoplaid74** [comment]
thanks..  sorry is there one for 1.2.0 as well?

the Experimental one is working but no animlas or zombies at the moment.

Thanks again!

**Comment by SupremeMortal** [comment]
That is 1.2.0, the latest version.

**Comment by gonetoplaid74** [comment]
Ah ok.. i spawned some animals but they were just frozen in place, not moving..  

It's my first foray into doing a Minecraft server at home for my daughter and myself..

Thanks for your help

**Comment by Frago9876543210** [comment]
@SupremeMortal where I can found source?

**Comment by SupremeMortal** [comment]
Creeperface01's branch GT1.2

**Comment by Frago9876543210** [comment]
@SupremeMortal thanks

**Comment by sero583** [comment]
Close this^
