### ISSUE TITLE
Won't start on latest build.

### ISSUE THREAD

**Issue by lethalgta815** [Nukkit/Nukkit#1916]
### Issue Description

Won't start due to error in code. (I'm not really sure, but I'm pretty sure it's an error in code)

### Steps to Reproduce the Issue

1. ... Make a start.cmd file with the following code:
**"chcp 65001 
java.exe -Dfile.encoding=UTF8 -jar nukkit-1.0-SNAPSHOT.jar"**
2. ... Run the command file.
3. ... There is a existing problem with builds from Mengcraft and Angelic47 sources (I only had a chance to test the two latest builds from those sources since I don't care for login screens at the moment)

### OS and Versions

* Nukkit Version: v1.1.3 (MengC Build Version: #634) 

* Java Version: 1.8.0_144

* Host Configuration: 16GB RAM, 6-core Intel Xeon E5-1650 v2 @ 3.50GHz 11.8MB/s Internet Upload

| Item | Value |
|:----:|:-----:|
| Host OS | Windows 10 |  
| Memory(RAM) | 16 GB | 
| Storage Size | 250 GB | 
| Storage Type | SSD | 
| CPU Type | Intel Xeon E5-1650 v2 | 
| CPU Core Count | 6 cores, 12 threads | 
| Upstream Bandwidth | 11.8MB/s | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Windows 10 | 
| Client Version | 1.2.2. | 

### Crashdump, Backtrace or Other Files

https://drive.google.com/open?id=0B7BRDrbJWQp0US10MVF0eklBZDg

**Comment by Snake1999** [comment]
https://github.com/Nukkit/Nukkit/pull/1912
