### ISSUE TITLE
Shitposters on Nukkit forums

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1922]
Forums admin should check and ban users that spam ads.

**Comment by SupremeMortal** [comment]
Nothing will get done since all the staff accounts on the forum haven't been active for 2 months+

**Comment by PetteriM1** [comment]
There is over six pages full of ads in general discussion category and more coming.

**Comment by PetteriM1** [comment]
Now over 20 pages...

**Comment by larryTheCoder** [comment]
Please do something... I hate ads. This might be a solution: `Temporary shutdown forum for a while` or `delete the ads user and block any people from signing up`

**Comment by SupremeMortal** [comment]
@larryTheCoder If no one _active_ has access to remove these post from the forums, I doubt anyone has access to shutdown the website.

**Comment by SupremeMortal** [comment]
There is 255 pages of spam now in the General forum. @NuclearSteven , as you seem to be the only active person with access to the repository around here, do you think anything about it?

**Comment by larryTheCoder** [comment]
Obviously we cannot do anything to block this ads user. Please add a new staff for this website (me) or others that is more experience on blocking ads user.

**Comment by SupremeMortal** [comment]
Who's going to add you when all the existing staff are inactive 😕

**Comment by larryTheCoder** [comment]
close forums are no ads
