### ISSUE TITLE
Nukkit 1.2 does not let me join

### ISSUE THREAD

**Issue by Smartjer123** [Nukkit/Nukkit#1928]
I am trying to connect from 1.2.3 on windows 10. I also tried a tablet and that still does not work.
Nukkit says that I am connected but on my end it says "locating server". After a bit it times me out.

Steps to reproduce the issue:
1. Join using 1.2.3

**Comment by lsw46** [comment]
The latest version ??

**Comment by Smartjer123** [comment]
Yes

**Comment by SupremeMortal** [comment]
You're going to need to give use more detail than that. I can connect fine on windows 10 to Nukkit.

**Comment by Smartjer123** [comment]
On 1.2.3 ?

**Comment by Smartjer123** [comment]
![capture](https://user-images.githubusercontent.com/26175394/32406211-82e0818a-c14a-11e7-8cdb-e69edd557a25.PNG)

**Comment by Smartjer123** [comment]
Its stuck at that

**Comment by Smartjer123** [comment]
![capture1](https://user-images.githubusercontent.com/26175394/32406221-bf47497e-c14a-11e7-9376-cbf1e7abbba2.PNG)
And the server looks like that

**Comment by SupremeMortal** [comment]
`java -jar Nukkit.jar --verbosity debug`

**Comment by Smartjer123** [comment]
Could it be that I am using an old world file from 1.1.x ?

**Comment by SupremeMortal** [comment]
Doubt it but you could try. Create a clean area and try starting the server without any plugins or an imported world.

**Comment by Smartjer123** [comment]
It let me join

**Comment by SupremeMortal** [comment]
It should work. I don't think there were any world breaking changes.

**Comment by Smartjer123** [comment]
Does it use a new world system or something ?

**Comment by SupremeMortal** [comment]
No. Same system just new blocks/items which don't overlap the existing so your world shouldn't be an issue.

**Comment by Smartjer123** [comment]
I might have to ask a dev of nukkit

**Comment by Smartjer123** [comment]
Are you using an old world ?

**Comment by Smartjer123** [comment]
Is there any way that I can repair/update worlds ?

**Comment by PetteriM1** [comment]
You can try MCEdit 2 http://www.mcedit.net

**Comment by Smartjer123** [comment]
There is a bunch of missing textures but I can see the world

**Comment by Smartjer123** [comment]
That might be because it is using blocks for the java edition. Is there a windows 10 version of it ?

**Comment by Smartjer123** [comment]
Ok is there anyway that I can make it so I can join using that world ?

**Comment by PetteriM1** [comment]
It is hard to fix world if you don't know what is the problem. Can you upload world file?

**Comment by Smartjer123** [comment]
Yes I have multiple. I will upload them all

**Comment by Smartjer123** [comment]
Want me to put them in zip files ?

**Comment by Smartjer123** [comment]
[worlds.zip](https://github.com/Nukkit/Nukkit/files/1443307/worlds.zip)

**Comment by Smartjer123** [comment]
When you are done send the the repaired/edited worlds back

**Comment by PetteriM1** [comment]
Wich is main world?

**Comment by PetteriM1** [comment]
All worlds work without any problems. It is not world problem. Can you give your nukkit.yml, server.properties and list of plugins you use?

**Comment by Smartjer123** [comment]
[configs.zip](https://github.com/Nukkit/Nukkit/files/1443576/configs.zip)
[pluginlist.txt](https://github.com/Nukkit/Nukkit/files/1443577/pluginlist.txt)

**Comment by PetteriM1** [comment]
Ok, issue is in configs, I check them tomorrow.

**Comment by Smartjer123** [comment]
I fixed it. I just re did the server properties file and it worked. I guess they changed it. Thanks for the help. I thought it had to do with the worlds.
