### ISSUE TITLE
GPL and Plugins' License

### ISSUE THREAD

**Issue by min050820** [Nukkit/Nukkit#1934]
According to [GNU's official site](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins), is host program is licensed under GPL, the plugin also has to be licensed GPL.

Nukkit and its plugin share lots of things including data structure. So what they say should also apply to Nukkit.

Is it true for Nukkit?

**Comment by NuclearSteven** [comment]
Nope, and please start a discussion in our forums the next time. BTW, Nukkit is LGPL licensed.
