### ISSUE TITLE
Ads are back on Nukkit forums

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1942]
Someone should delete them again...

**Comment by PetteriM1** [comment]
And how long it takes to get new plugin released? Uploated four days ago and still moderated.

**Comment by larryTheCoder** [comment]
🔻 Nukkit Forum: -5.45

**Comment by augesrob** [comment]
Kinda wish they had active staff. I want to apply. Right now nothing is moving forward on the forums/plugins.

**Comment by PetteriM1** [comment]
Nukkit needs more staff.

**Comment by zzz1999** [comment]
yeah
