### ISSUE TITLE
give command issue

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#195]
it still gives Item instance instead of specified item instance.

**Comment by MagicDroidX** [comment]
Give an example plz :)

**Comment by Creeperface01** [comment]
379

**Comment by Creeperface01** [comment]
And it says unknown and i can not place it and i got full stack

**Comment by MagicDroidX** [comment]
I have tried 379 and I can place it on the ground.

**Comment by Creeperface01** [comment]
Hmmmmmmm

**Comment by Creeperface01** [comment]
But giving by item name still doesnt work

**Comment by MagicDroidX** [comment]
This is not implemented yet.
