### ISSUE TITLE
Java error on startup

### ISSUE THREAD

**Issue by mstrop** [Nukkit/Nukkit#1965]
## Nukkit Bug Report

(DO NOT OPEN A ISSUE IF THIS IS A PLUGIN ERROR)

PLUGIN ERROR: FALSE

### Issue Description

I get this error just after vanila installation, when I run the server like 

 sudo java -Xms512M -Xmx512M -jar nukkit-1.0-SNAPSHOTara

### OS and Versions
* Nukkit Version: 1.0dev 
* Git Commit Abbrev: b04061b
* Java Version: 
```
Java HotSpot(TM) 64-Bit Server VM (9.0.1+11)
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | CentOS [6.9] |  
| Memory(RAM) | 2.1 GB | 
| Storage Size | 86.4 GB | 
| Storage Type | VMware_Virtual_IDE_CDROM_Drive Virtual_disk Unknown  | 
| CPU Type | Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz | 
| CPU Core Count | 1 cores 1 threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at cn.nukkit.item.Item.initCreativeItems(Item.java:863)
	at cn.nukkit.item.Item.init(Item.java:838)
	at cn.nukkit.Server.<init>(Server.java:376)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 4 more

```

**Comment by PetteriM1** [comment]
Try to delete creativeitems.json from Nukkit folder

**Comment by mstrop** [comment]
It's the same.

------ Původní zpráva ------
Od: "Petteri" <notifications@github.com>
Komu: "Nukkit/Nukkit" <Nukkit@noreply.github.com>
Kopie: "mstrop" <marek@foxtrot.cz>; "Author" <author@noreply.github.com>
Odesláno: 08.12.2017 14:36:47
Předmět: Re: [Nukkit/Nukkit] Java error on startup (#1965)

**Comment by SupremeMortal** [comment]
Nukkit does **NOT** support Java 9

**Comment by pkt77** [comment]
An easy fix if you still want to use Java 9 - Add this to the pom:
`<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>`
I'm assuming and hope you know where to put that.

**Comment by mstrop** [comment]
I placed it to pom.xml under maven/cn.nukkit - to dependecies section - I hope, it's the right one - I still get the  exception. I'll reinstall Java ....

**Comment by SupremeMortal** [comment]
Pom with edited value. It's only a temp fix for now till the legacy code is removed.
https://hastebin.com/junovobave.xml

**Comment by SupremeMortal** [comment]
This workaround isn't needed anymore since I removed all legacy packages from Nukkit.
