### ISSUE TITLE
NK弃坑了么？？

### ISSUE THREAD

**Issue by lsw46** [Nukkit/Nukkit#1969]
超过两个月没更新了。。。。

**Comment by pkt77** [comment]
https://github.com/NukkitX/Nukkit
Thanks to very active @SupremeMortal <3

**Comment by liach** [comment]
@pkt77 That fork lacks updates, too

**Comment by SupremeMortal** [comment]
Updates such as what. Suggestions are welcome.

**Comment by PeratX** [comment]
As you see, every one of the them is busy with their lessons.
Two in University, me and another two are in Grade 3 Senior.

**Comment by liach** [comment]
Yeah, school is always more important than extracurricular coding. Glad to see a reply!

**Comment by NuclearSteven** [comment]
Intriguing question
