### ISSUE TITLE
PlayerCommandPreprocessEvent fires before PlayerChatEvent

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#197]
When you type message in chat it controlled by two kind of events:
1st - PlayerCommandPreprocessEvent
2nd - PlayerChatEvent
If you cancel  PlayerCommandPreprocessEvent you will find that PlayerChatEvent will not fire.

I think this events must be separated: 
* PlayerChatEvent — for chat only
* PlayerCommandPreprocessEvent — for commands only (messages started with "/").

How to reproduce:
```
    @EventHandler (priority = EventPriority.NORMAL)
    public void onChat(PlayerChatEvent event){
        event.getPlayer().sendMessage("PlayerChatEvent");
    }

    @EventHandler (priority = EventPriority.NORMAL)
    public void onCommandPre (PlayerCommandPreprocessEvent event){
        event.getPlayer().sendMessage("PlayerCommandPreprocessEvent");
    }
```

Register this event handlers, type something in chat and you will see messages:
1. PlayerCommandPreprocessEvent
2. PlayerChatEvent

**Comment by WilliamGao1** [comment]
PlayerCommandPreprocessEvent includes PlayerChat

**Comment by ProjectInfinity** [comment]
This sounds like it is intended. If Nukkit works the same way as PocketMine in this regard, then all chat messages are a command.

**Comment by fromgate** [comment]
I'm not sure that it's a correct. Looks like PlayerChatEvent became worthless.

I think this tasks must be divided:
1. All commands (messages started by "/") must be controlled by PlayerCommandPreprocessEvent
2. All chat message (messages that started by any symbol except "/") must be controlled by PlayerChatEvent.

**Comment by PEMapModder** [comment]
PlayerCommandPreprocessEvent is fired for messages without a `/` prefix such that a plugin can, for example, allow using commands without a slash.

**Comment by fromgate** [comment]
@PEMapModder 
Wrong way.
Command is a command. You must register it and execute.

If you going to organize commands without slash you must understood that commands - normal commands - must be defined in plugin.yml or registered manually. 

If you going to execute this command without slash - you must catch PlayerChatEvent, analize the message and manually dispatch plugin command. Something like this:
https://github.com/fromgate/Space2Slash/blob/master/src/main/java/ru/nukkit/space2slash/Space2Slash.java#L17-L22

If you did not register your commands and just defining it in event listeners - it's not an real command it just chat message, handled by your plugin.
No one will have access to such command and for example if someone going to add an alias to your command he will not be able to do it. Oh! And your command will not be listed by /help command!

Anyway you can (and must) handle your "command" using PlayerChatEvent. Please leave PlayerCommandPreprocessEvent for real commands.

@MagicDroidX  I don't see any reason why nukkit fires different events for single action. I think
PlayerCommandPreprocessEvent  must fire for commands (message started with "/")
PlayerChatEvent for every message that not started with "/"

**Comment by PEMapModder** [comment]
@fromgate you mentioned "must" multiple times, but you fail to explain why it "must" instead of you are used to.

**Comment by fromgate** [comment]
Shoghi created PocketMine using php. And this is why we are here now :)

These different events has different purposes. Mixing them is a big mistake. Mixing the different things - commands and chat messages is a bad practice.
Why we didn't mix BlockBreakEvent and BlockPlaceEvent? Block placing is about placing "AIR" block, isn't it?  
And what about single class Event - we can handle only on event instead all of these chat-, player-, blocks-related events? 

I think good reference here is not PocketMine, but BukkitAPI. Check what will bukkit do - if you try same code in bukkit:
```
	@EventHandler (priority = EventPriority.LOW)
	public void onChat (AsyncPlayerChatEvent event){
		event.getPlayer().sendMessage("AsyncPlayerChatEvent");
	}
	
	@EventHandler (priority = EventPriority.LOW)
	public void onCmd (PlayerCommandPreprocessEvent event){
		event.getPlayer().sendMessage("PlayerCommandPreprocessEvent");
	}
```
You will see only one message according to input string - command or chat message.

Now the only one careless action while processing command-events could break all events associated with the chat and break all plugins that trying to handle chat-events. And this is about your example: about your example.  Your actions about name name converting is acceptable for chat only. If you will converting, colorizing, etc. player names in commands - you will break another plugins that did not try to catch event and just using registered commands. 

Plugin developer must be sure that if player typing a chat message - it could be handled by chat-event.
If player type a command - it could be handled by command-event.

**Comment by PEMapModder** [comment]
I said, PlayerCommandPreprocessEvent is not related to commands.
Not sure, but I thought this projects models PocketMine rather than Bukkit?

**Comment by caoli5288** [comment]
@PEMapModder Yes. It is.

**Comment by fromgate** [comment]
Pocketmine is based on the Bukkit model. It's could "not official" but anyone familiar with bukkit will find similarities :) 

**Why nukkit must implement bugs provided by PocketMine?**

Firing the PlayerCommandPreProccess event for messages and PlayerChatEvent for same messages is a structural error, that breaking single responsibility principle of programming.

**Comment by caoli5288** [comment]
I think command is a subclass of chat.

**Comment by PEMapModder** [comment]
So you think it is a bug when it is intended?

Fine, I would not argue on such an issue, I just wanted to point out that it is intended on PocketMine, rather than a bug.

**Comment by xxFlare** [comment]
@PEMapModder Is correct. I saw shoghicps posts about this because people always think this is a bug.

**Comment by fromgate** [comment]
Yes technically commands are something, that we type in chat. 

But at the first, command is order to server to perform programmed operations.

It's a sublclass of CommandExecutor: https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/command/CommandExecutor.java

Yes you type comand in chat. But the similarity ends. Commands always started with symbol "/". 
If you going to turn ordinary chat message into command - you can easily do it. But you need to use tools related to the chat commands.

You can't register command without "/", so if you catching "some-command" string and perform some actions - this is not a command. This is a chat listener.

What plugin developer needs of PlayerCommandPreprocessEvent?
He must be able to get access to command before it will be executed by onCommand method of CommandExecutor.

Replacing placeholders, controlling the commands of another plugins, loggin, canceling commands in some situations (WHERE CHAT ALLOWED!)

I don't understand why developer must be able to acces to chat mesages in PlayerCommandPreprocessEvent?

Can you provide example when you'll need to modify chat message before executing command?! In PlayerCommandPreprocessEvent?
And why you can't do it in PlayerChatEvent?


And what about chat messages?
Chat message at the first is a message that one player send to another or to everyone. 
Chat message cannot contain slash in first position: try to chat "/hello" in vanilla minecraft - this will not working.

Chat message must be controlled by Plugin developer when he need work with text, with format, prefixes. Creating private chanels, etc. 


If you want to join PlayerCommandPreprocessEvent with something, you have more reason to do it with ServerCommandEvent. It is at least logical.


I'm not saying that all this is a bug. This is just an example of bad programming. Why bad practice must be translated from php to java here? Maybe we conversely need something better?

And please do not deify Shoghi, he created PocketMine using php - that says a lot :)

**Comment by ProjectInfinity** [comment]
@fromgate You can seriously bypass this entire (non) issue by just doing 

```
if(!event.getMessage().startsWith("/")) return;
```
Voilà, no longer will the rest of your code execute on chat.

**Comment by fromgate** [comment]
It's not about what can do single plugin developer (you, me, anyone else).
It's about the bad practice, which was inherited from the PocketMine. 

Please answer to question, that I asked earlier:
*Can you provide example when you'll need to modify* **chat message** *before* **executing command***?! In PlayerCommandPreprocessEvent? And why you can not do it in PlayerChatEvent?*

**Comment by PEMapModder** [comment]
I understand @fromgate's point. I'd like to use an analogy of IRC clients, which is a likely origin of Minecraft commands. In an IRC client, if you type an unknown command (or always with commands), the client should directly send the message to the server without the leading slash, while if it doesn't have a slash, the client would PRIVMSG it. Although this isn't how it works in Minecraft, we can see that commands have no relationship with chat messages.

However, for compatibility purpose, we should keep it the same as people are used to it.

**Comment by Snake1999** [comment]
OK, just have this argue later. We have decided this problem and solve like this:

1. Add an abstract event named PlayerMessageEvent, let PlayerChatEvent and PlayerCommandPreprocessEvent extend it.

2. Improve the event system in order to give plugin listeners an ability to listen abstact events.

3. If you want to listen both command and chat, listen message event. If you want chat only, listen chat. If command only, listen command.

:D

**Comment by PEMapModder** [comment]
Actually, the main thing I'm concerned about is the compatibility. Because PlayerCommandPreprocessEvent was expected by PocketMine users to be for both chat and commands.

**Comment by PEMapModder** [comment]
Just as a side note, check out @shoghicp's comment in PocketMine/PocketMine-MP#2201. I guess that isn't that important since the project is written in Java, though.

**Comment by MagicDroidX** [comment]
So, what's the result of this discussion?

**Comment by ProjectInfinity** [comment]
I don't think there's a universally accepted solution so far. But if we wish to stay compatible then nothing should be done, it works like intended. The issue started with one guy not understanding the event, it ain't a widespread issue.

**Comment by fromgate** [comment]
@ProjectInfinity 
I think you don't understand possible problems that could get plugin users when some guy who really don't understand this event will cancel it. It will be funny when we users will report you about bugs, when issue source will be in another plugin.
I think both event must be separated according to it's goals.

**Comment by ProjectInfinity** [comment]
@fromgate Both Bukkit and PocketMine works this way, the fact that you want it changed is the exception to the rule. Besides it's a commonly known fact that a message is interpreted in the same way as a command until it is ensured that the command actually starts with a "/".

Separating the two is just going to make Nukkit have weird quirks compared to other minecraft server software.

**Comment by PEMapModder** [comment]
@fromgate if that makes plugin developers confused, add docs for them. No need to change the semantics of the event to create confusion when people talk about two standards.

See also: HTTP protocol, `Referer` header instead of `Referrer`

**Comment by 64FF00** [comment]
@ProjectInfinity @PEMapModder :+1:

**Comment by fromgate** [comment]
@PEMapModder 
I think preventing confusing will be more helpful than docs.

@ProjectInfinity 
You're not right. In bukkit this events are separated. So PocketMine is "bad-copy" of bukkit. Again. 

Here's part of crafbukkit code (you can find it at net.minecraft.server.v1_8_3.PlayerConnection:
```
public void chat(String s, boolean async)                                                          
{                                                                                                  
  if ((s.isEmpty()) || (this.player.getChatFlags() == EntityHuman.EnumChatVisibility.HIDDEN)) {    
    return;                                                                                        
  }                                                                                                
  if ((!async) && (s.startsWith("/")))                                                             
  {                                                                                                
    handleCommand(s); 
  }                                                                                                
  else if (this.player.getChatFlags() != EntityHuman.EnumChatVisibility.SYSTEM)                    
  {                                                                                                
    Player player = getPlayer();                                                                   
    AsyncPlayerChatEvent event = new AsyncPlayerChatEvent(async, player, s, new LazyPlayerSet());  
////////////////////// I think it's enough for example
```
handleCommand(s) is calling PlayerCommandPreprocessEvent 

Anyway. Now it works as expected. Like it work in bukkit. Chat is chat, command is command:
https://github.com/Nukkit/Nukkit/commit/223d791747077c6ed3e7cb3558d80b98ba2c3a1b

**Comment by PEMapModder** [comment]
*Sigh*
Most people who come here are more familiar with PocketMine API than Bukkit API. So the issue is we already have two standards. There is no "right" or "wrong", because just "earlier" and "later". But since right now both are happening, since this project models the PocketMine API, it should just follow what PocketMine does. When something has become a well-recognized API that has existed for almost two years, you can't call it "wrong" anymore because it has already become a standard.

**Comment by 64FF00** [comment]
@PEMapModder It depends heheh

**Comment by MrPowerGamerBR** [comment]
@64FF00 yeah, it really depends, I almost never used PocketMine: MP, but I'm familiar with the Bukkit API.

Anyway, back on topic, while PocketMine: MP used the "PlayerCommandPreprocessEvent" firing for chat messages, this feels very strange for a Bukkit developer, because, on Bukkit, Commands are Commands and Chat Messages are Chat Messages, and not Commands are Commands and "maybe" a Chat Message.

But, as long as the docs says that a "PlayerCommandPreprocessEvent also fires with a chat message", then it wouldn't be a issue (well, at least for me).

**Comment by fromgate** [comment]
@PEMapModder I'm agree with you:  "there is no "right" or "wrong", because just "earlier" and "later". 
But if it was wrong (because of possible misunderstandings, problems, confusing) it must be fixed.

PocketMine API is well-recognized for you. And I think bukkit API is well-recognized too ;) - there's about 14000 plugins uploaded to BukkitDev only ;)

Anyway Java have something that could made code more useful or effective than php.

For example, there no any ENUMs used in nukkit. But it's a great tool, which could save lot of time, prevent wrong using of constants. Why not use it nukkit? 

Check how items and blocks was implemented in bukkit and in pocketmine. If you did not see it before - you will be surprised.

I thinks we don't need to copy anything only because if was "earlier". Code must be useful and possibly optimized. 

I believe that sometime nukkit will be more popular that pocketmine and no one will remember what was in pocketmine API :)

**Comment by PEMapModder** [comment]
@fromgate the main issue we are having is to prevent confusion, and either way we do it it is going to bring confusion anyway. So maybe we should simply have an RFC and let people who use this repo to decide which method to adopt.

And again, PocketMine didn't misunderstand it, I have already pointed out the problem and there is a reason for that ;)
