### ISSUE TITLE
How long plugin moderation takes at Nukkit forums?

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1970]
I uploaded my plugin to Nukkit forums about month ago and its status is still moderated. How long it takes? And also someone should delete ads again. Is Nukkit forums dead?

**Comment by PeratX** [comment]
Almost dead. All administrators is busy with their lessons.

**Comment by PetteriM1** [comment]
And anything except ads have deleted now.

**Comment by SupremeMortal** [comment]
The forum was hacked.
