### ISSUE TITLE
NoSuchMethodError in events

### ISSUE THREAD

**Issue by Donquih0te** [Nukkit/Nukkit#1975]
### Issue Description

When working with events, crash occurs.
Crash: https://pastebin.com/JTjAQZQQ
Code: https://pastebin.com/ztMEy1VG

### OS and Versions
Nukkit Version: latest( v1.2.2)
Java Version: openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu |  
| Memory(RAM) | 1 GB | 
| Storage Size | 20 GB | 
| Storage Type | ssd | 
| CPU Type | Intel Xeon E5 | 
| CPU Core Count | 2 cores 2 threads | 
| Upstream Bandwidth | 100 | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Win10 | 
| Client Version | 1.2.7 |

**Comment by SupremeMortal** [comment]
The API changed for that lately and that jar you are using as a dependency is most likely outdated.
