### ISSUE TITLE
Important questions!!!!

### ISSUE THREAD

**Issue by Dmitri233** [Nukkit/Nukkit#1983]
1.If you try to use the instructions that need to provide the player's name in this version, you will not find the player. But the player is online and the name is correct. For example, if you use /give Steve 1 64., the problem will appear immediately.

2.This version of the board cannot be modified. And cannot be displayed at the bottom of the plug-in.

Nukkit Version: #640 (2017-12-17 1:16:32)

**Comment by SupremeMortal** [comment]
This repository is dead. Please use https://github.com/NukkitX/Nukkit
Latest build: https://ci.nukkitx.com/job/NukkitX/job/master/

**Comment by Dmitri233** [comment]
Thank you for sending a message late at night
