### ISSUE TITLE
THIS REPOSITORY IS INACTIVE. READ BEFORE CREATING NEW ISSUES

### ISSUE THREAD

**Issue by SupremeMortal** [Nukkit/Nukkit#1984]
Due to all staff members being inactive and the website being hacked, the development of Nukkit has been moved to a new temporary repository till members of this main repository become active again. 

Temporary GitHub repository:
[https://github.com/NukkitX/Nukkit](https://github.com/NukkitX/Nukkit)

Latest Download:
[https://ci.nukkitx.com/job/NukkitX/job/master](https://ci.nukkitx.com/job/NukkitX/job/master/)

Forums:
[https://nukkitx.com](https://nukkitx.com/)

**Comment by Snake1999** [comment]
Wow, looks like the world has changed while I'm having a surgery :)
C'mon

**Comment by SupremeMortal** [comment]
Community was just left to die. Someone had to do something in the mean time. ¯\_(ツ)_/¯

**Comment by Snake1999** [comment]
@SupremeMortal Would you like to be a member yourself?

**Comment by SupremeMortal** [comment]
Sure. If it means we can keep the community alive.
