### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by BurritoMan46** [Nukkit/Nukkit#1988]
### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by SupremeMortal** [comment]
You should look at the readme https://github.com/Nukkit/Nukkit/blob/master/README.md
