### ISSUE TITLE
Host on a VPS?

### ISSUE THREAD

**Issue by Vrysed** [Nukkit/Nukkit#1991]
Hello, I was wondering how I can host a Nukkit server on a VPS?
And if it's possible please leave direction's below!

**Comment by Megalunchbox** [comment]
Depends on your vps some may not even be able to use it.

**Comment by PeratX** [comment]
Install OpenJDK(jre-headless) and you are all done!

**Comment by Vrysed** [comment]
What are the commands to install Nukkit on a VPS?

**Comment by PeratX** [comment]
What is your os type? CentOS(yum) Fedora(dnf) Debian/Ubuntu(apt) Windows (download from Oracle)

**Comment by Vrysed** [comment]
Linux OS

**Comment by PeratX** [comment]
Linux is the kernel of these distributions.

**Comment by Vrysed** [comment]
Debian

**Comment by PeratX** [comment]
Then use apt install openjdk-8-jre-headless and you are ready to use Nukkit with java -jar Nukkit.jar
You can get pre-built jars from Jenkins server or build it by yourself using maven (instructions are provided in README).

**Comment by Vrysed** [comment]
Alright thanks and I was also wondering if theres a way to run the server off of the src instead of the .jar file is that possible?

**Comment by PeratX** [comment]
Yes, of course. Use maven `mvn exec:java -Dexec.mainClass="cn.nukkit.Nukkit"

**Comment by PeratX** [comment]
Oops! Remember to `mvn compile` before you execute from src~

**Comment by Vrysed** [comment]
What does that mean?

**Comment by Vrysed** [comment]
And do i rename the start.cmd to start.txt and put this information in?

**Comment by PeratX** [comment]
emmmm? You can modifiy start.sh directly
