### ISSUE TITLE
How can I run the server off of the SRC?

### ISSUE THREAD

**Issue by Vrysed** [Nukkit/Nukkit#1994]
Is there any way to run the server off of the SRC? I don't know how to MVM compile on Linux Debian 9, and could you please link me a download link of the start.cmd to run it off of the SRC instead of the .jar?

**Comment by SupremeMortal** [comment]
Download from Jenkins
https://ci.nukkitx.com/job/NukkitX/job/master/lastSuccessfulBuild/artifact/target/

**Comment by Vrysed** [comment]
Do I download the zip?

**Comment by SupremeMortal** [comment]
No. Just the jar

**Comment by Vrysed** [comment]
Ok but when i convert the .jar to src it doesnt work

**Comment by SupremeMortal** [comment]
Why are you trying to convert a jar to source? You need to run the jar with Java since it's a compiled binary.
`java -jar nukkit-1.0-SNAPSHOT.jar`

**Comment by Vrysed** [comment]
I want to run it from source because I want to edit the items without having to convert it many times. So there's no way to run it from source?

**Comment by Megalunchbox** [comment]
You can compile the source yourself.

**Comment by Vrysed** [comment]
How?
