### ISSUE TITLE
Console spam on Pterodactyl Panel

### ISSUE THREAD

**Issue by newbie029** [Nukkit/Nukkit#1997]
![screenshot_227](https://user-images.githubusercontent.com/35466184/37044581-6f74adb8-2196-11e8-83b6-a0efec3a117f.jpg)
console spam every i use command on console... please fix

**Comment by newbie029** [comment]
it cause by the title of terminal... is there any way to disable terminal title?

**Comment by SupremeMortal** [comment]
Add `-disable-ansi` as an argument for Nukkit.

**Comment by Snake1999** [comment]
your console seems does not support ansi, and cannot be detected by neither jansi nor jline. disable jansi and it might solve (the side-effect is, colored texts will be no longer colored in console).

btw what do you mean by "please fix"? it's not a pleasant way to begin an ISSUE, is it?

**Comment by sero583** [comment]
He has to report that to his Multicraft provider as it seems, since this looks most likely to a hosted server without full console access.

**Comment by newbie029** [comment]
its not multicraft... 
i try -disable-ansi but its not work...
or i wrong put the -disable-ansi
where should i put that?
sorry for my bad english

**Comment by newbie029** [comment]
![whatsapp image 2018-03-07 at 12 15 23 am](https://user-images.githubusercontent.com/35466184/37471492-7a1906ee-289c-11e8-8cc2-d3f7c0a4106e.jpeg)
the title spam to console... 
![screenshot_51](https://user-images.githubusercontent.com/35466184/37471519-8bca44fc-289c-11e8-87d8-06706305d8f9.png)

**Comment by SupremeMortal** [comment]
Yes. `-disable-ansi` will stop this error. You need it in your Java arguments for the jar.
