### ISSUE TITLE
This repository is dead

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#2001]
Developement of Nukkit will be continued here: [https://github.com/NukkitX/Nukkit]( https://github.com/NukkitX/Nukkit)

**Comment by bonnedav** [comment]
Your not even a contributor.

**Comment by PeratX** [comment]
WARNING: DO NOT POST ANY NUKKIT FORKS WITCH SAYS TO CONTINUE THE WORK AND THIS REPO HAS NOT DEAD YET.

**Comment by SupremeMortal** [comment]
We're only trying to keep this server software alive. If it wasn't for us, no one would be using Nukkit at all since it would still be on version 1.2.3.
