### ISSUE TITLE
Can't connect to world

### ISSUE THREAD

**Issue by jraspiprojects** [Nukkit/Nukkit#2018]
### Expected Behavior

To connect to nukkit.

### Actual Behavior

This error: Outdated Server!

![capture1](https://user-images.githubusercontent.com/30187911/41486458-7334ef4c-7099-11e8-9a7b-0d44a2a293c1.JPG)

### Steps to Reproduce

Use Minecraft beta 1.5 and connect to  nukkit server
make server-ip 127.0.0.1

**Comment by jraspiprojects** [comment]
maybe because of new beta 1.5

**Comment by jraspiprojects** [comment]
#2018 !!!

**Comment by jraspiprojects** [comment]
wow i had to change the ip i am weird

**Comment by jraspiprojects** [comment]
or not.

**Comment by jraspiprojects** [comment]
now i get this: 

![erroro](https://user-images.githubusercontent.com/30187911/41486820-e43633f8-709a-11e8-836f-0ebe90628109.JPG)

**Comment by SupremeMortal** [comment]
If you are hosting a server on the same computer you're playing: https://nukkitx.com/threads/fix-cannot-connect-to-servers-hosted-on-the-same-computer-with-windows-10-edition.41/

**Comment by jraspiprojects** [comment]
I am, but it's still not working.

**Comment by SupremeMortal** [comment]
Nukkit is not compatible with the beta

**Comment by jraspiprojects** [comment]
dang it. It works with update 1.5 but no luck with 1.6

**Comment by SupremeMortal** [comment]
You are using an outdated download link and the current version is 1.6. Here is the latest link:
https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/master/lastSuccessfulBuild/artifact/target/nukkit-1.0-SNAPSHOT.jar
