### ISSUE TITLE
class：Player  2334~2336  miss break;

### ISSUE THREAD

**Issue by 258513813** [Nukkit/Nukkit#2021]
the sources code exist bug
class：Player  2334~2336
`
 case PlayerActionPacket.ACTION_ABORT_BREAK:
                            this.lastBreak = Long.MAX_VALUE;
                            this.breakingBlock = null;
                        case PlayerActionPacket.ACTION_STOP_BREAK:
                            LevelEventPacket pk = new LevelEventPacket();
                            pk.evid = LevelEventPacket.EVENT_BLOCK_STOP_BREAK;
                            pk.x = (float) pos.x;
                            pk.y = (float) pos.y;
                            pk.z = (float) pos.z;
                            pk.data = 0;
                            this.getLevel().addChunkPacket(pos.getFloorX() >> 4, pos.getFloorZ() >> 4, pk);
                            this.breakingBlock = null;
                            break;

`
case PlayerActionPacket.ACTION_ABORT_BREAK:   miss break; 

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by SupremeMortal** [comment]
The break is missed on purpose so the code passes through to the next statement.

**Comment by captainleviftw** [comment]
:facepalm:🤦‍♀️
