### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Abjust** [Nukkit/Nukkit#2055]
### Expected Behavior

I used my world that is created from Minecraft: Bedrock Edition, and I expect it to work properly.

### Actual Behavior

Not working for me. It automatically abandoned my world and created a new one.

### Steps to Reproduce

1. (Probably) Use the world from Minecraft: Bedrock Edition
2. Start the server

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

[https://hastebin.com/sipikutuxe.css](https://hastebin.com/sipikutuxe.css)
**Checklist**:

- [ ] I included a `/debugpaste` link
- [ ] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of Nukkit
- [X] I Made sure the bug/error is not caused by a plugin

**Comment by SupremeMortal** [comment]
Bedrock worlds are not supported in 1.0. They will be in 2.0

This repository is abandoned, please use the new one:
https://github.com/NukkitX/Nukkit
