### ISSUE TITLE
scheduleAsyncTask deprecated, no replacement available?

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#208]
Isn't it a bit early to deprecate scheduleAsyncTask when no alternative is provided?

**Comment by caoli5288** [comment]
It still work. New API scheduleTask(Runnable task, boolean asynchronous) here.

**Comment by ProjectInfinity** [comment]
Why such an odd choice? This breaks both PocketMine and Bukkit conventions. Where both specifically mention "Async" in the name of the method call. 

What's the goal of Nukkit, to be PocketMine-like, Bukkit-like or a bastardization of the two?

**Comment by caoli5288** [comment]
Why you think this project MUSH follow PocketMine and Bukkit's  conventions?

**Comment by ProjectInfinity** [comment]
I can list a few reasons.

* The name of the software is Nukkit, very similar to Bukkit.
* The code is remarkably similar to that of Bukkit.
* README.md "Having a similar structure with PocketMine-MP, because of this it's easy to contribute to Nukkit's development. And it is also easy to rewrite PocketMine-MP plugins into Nukkit plugins."
* It is important to keep Bukkit and Nukkit pretty similar in order to 1. attract more people and 2. be able to capitalize on Bukkit's large repository of plugins with minimal effort required to port plugins.

**Comment by caoli5288** [comment]
I agree with some of your lists. So it mark as deprecate, not removed. This is an independent project, it will be carefully considered compatible with other popular project, but not an re-implemented.

**Comment by MagicDroidX** [comment]
I've removed the annotation.
