### ISSUE TITLE
Fire Issue

### ISSUE THREAD

**Issue by ClanEmo** [Nukkit/Nukkit#213]
Fire gives tons of damage that is enough to kill the player for less than 2 seconds

**Comment by beetree** [comment]
It seems that fire damage is ticking every tick rather than every 20 ticks or so.

**Comment by ProjectInfinity** [comment]
Can confirm that.

**Comment by Pub4Game** [comment]
Yes, with fire a lot of problems.... For example the animation doesn't disappear when you're not burning

**Comment by MagicDroidX** [comment]
This is confirmed.

**Comment by Pub4Game** [comment]
this already fixed
