### ISSUE TITLE
Implement Thunder

### ISSUE THREAD

**Issue by ClanEmo** [Nukkit/Nukkit#219]
The Weather Rain+Thunder has an issue, you can hear nor see a thunder... Just all rain

**Comment by MagicDroidX** [comment]
Yes, we have not implemented thunder yet.

**Comment by Snake1999** [comment]
Added in https://github.com/Nukkit/Nukkit/commit/ae3e8c9e5ed63d17a7b79dcc4c3f565d0b38b2cc
:+1:
