### ISSUE TITLE
"Invalid player data"

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#222]
![image](https://cloud.githubusercontent.com/assets/11244874/12005575/35874602-abbd-11e5-8232-ce4b722cb074.png)

There is a problem with the data of the player

https://www.dropbox.com/s/udwxuasqcwmz9jn/breakdata.zip?dl=0

**Comment by MagicDroidX** [comment]
Well... Because of the GFW, I cannot download from dropbox
And ...........I cannot read russian letters in the picture :D

**Comment by Pub4Game** [comment]
@MagicDroidX I'm sorry, I didn't know. Where can I download the player?

**Comment by Pub4Game** [comment]
Where can I put the data of the player?

**Comment by MagicDroidX** [comment]
You can attach files while commenting :D. Right here. On GitHub.

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/12006857/94c18254-abf9-11e5-83f2-ddc7893c0915.png)

**Comment by MagicDroidX** [comment]
why not pack it as a zip?

**Comment by Pub4Game** [comment]
@MagicDroidX Please look closely.....

**Comment by xpyctum** [comment]
@Pub4Game dropbox,rghost.

**Comment by Pub4Game** [comment]
у них нет доступа к Dropbox и rghost!

**Comment by xpyctum** [comment]
@Pub4Game дай файл, я загружу..

**Comment by xpyctum** [comment]
I really didn't know, maybe it can helps.
Original player.dat file has 20 entries, but player.dat.bak has 24 
![A](http://pp.vk.me/c630120/v630120517/a19d/UhvRQLHSw88.jpg)
=======
![B](http://pp.vk.me/c630120/v630120517/a1a5/FCM2uz5cv4A.jpg)
And file can download here: http://xpyctum.ru/breakdata.zip

**Comment by xpyctum** [comment]
It seems inventory writing bug, because 4 unnecessary element (24 - 20 = 4 :hand: )
unnecessary elements are: Count,Damage,Id and Slot.

**Comment by Pub4Game** [comment]
This is most likely the problem "NBTIO"

**Comment by MagicDroidX** [comment]
I wonder if this problem still happen?
