### ISSUE TITLE
The problems with crafting

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#223]
![image](https://cloud.githubusercontent.com/assets/11244874/12005621/3155b9ee-abc0-11e5-8834-973c0c031877.png)
As far as I remember, crafts have already been implemented?!

**Comment by MagicDroidX** [comment]
It happens randomly :( And IDK what is wrong!!!

**Comment by MagicDroidX** [comment]
Still randomly happen.

**Comment by Creeperface01** [comment]
I think this happens if player recieve recipe list too soon because i had same problem in pocketmine but if i send recipesList later in game it works always!

**Comment by MagicDroidX** [comment]
@Creeperface01 Thanks a lot. It is the direct answer!

**Comment by caoli5288** [comment]
_(:3」∠❀)_

**Comment by Pub4Game** [comment]
@MagicDroidX 
![image](https://cloud.githubusercontent.com/assets/11244874/12161879/144de772-b50c-11e5-89b4-e373f7e6986d.png)
