### ISSUE TITLE
Time\Weather

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#225]
The weather changes too dramatically. It looks very ugly...

**Comment by xpyctum** [comment]
АААА
Ещё один.

**Comment by Pub4Game** [comment]
@xpyctum 

Bye bye
![image](https://cloud.githubusercontent.com/assets/11244874/12005661/c92b2432-abc2-11e5-8cfc-a764526e9f81.png)

**Comment by xpyctum** [comment]
@Pub4Game no no no no pls :<

**Comment by Pub4Game** [comment]
@xpyctum :cry:

**Comment by MagicDroidX** [comment]
You mean that the weather should change more smoothly?

**Comment by Pub4Game** [comment]
@MagicDroidX yes
