### ISSUE TITLE
Softdepend error:  Circular dependency detected

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#227]
Hello!
Here is my plugin.yml:

```
name: Welcome
main: ru.nukkit.welcome.Welcome
version: "0.0.3"
author: fromgate, nukkit.ru
api: ["1.0.0"]
softdepend: [DbLib]
description: User authentication plugin
```

If plugin DbLib is present in plugin folder - all works fine. But when I'm trying to use my plugin without DbLib it not loading and I receive error:
"[CRITICAL] Could not load plugin 'Welcome': Circular dependency detected"

**Comment by Pub4Game** [comment]
@MagicDroidX Please fix this bug! :angry:

**Comment by MagicDroidX** [comment]
I am busy, don't rush me anymore.

**Comment by Angelic47** [comment]
Don't worry, I'm still working on this bug :D @Pub4Game

**Comment by fromgate** [comment]
Yahooo!!!!
Thank you :)
:+1:
