### ISSUE TITLE
Error snowball

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#229]
![image](https://cloud.githubusercontent.com/assets/11244874/12007134/bec13e56-ac07-11e5-8279-e629f8dc50f7.png)

**Comment by caoli5288** [comment]
But this pull closed?

**Comment by Pub4Game** [comment]
@caoli5288 https://github.com/Nukkit/Nukkit/commit/913b47f4ed845ddca3963bc20a061d7824ff6004#diff-70123dd1213ca150336e2fda95e45a1aR2003

**Comment by caoli5288** [comment]
Okay :+1:
