### ISSUE TITLE
Many flaws

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#230]
3)
![image](https://cloud.githubusercontent.com/assets/11244874/12007168/3819ba5c-ac09-11e5-961f-82287e5cd02c.png)
8)Bug with bed (
![image](https://cloud.githubusercontent.com/assets/11244874/12007223/d2118bec-ac0b-11e5-8010-e4dd81853c15.png)
![image](https://cloud.githubusercontent.com/assets/11244874/12007224/d4dad07c-ac0b-11e5-8269-3659fca8e35b.png)

**Comment by ProjectInfinity** [comment]
Not all of these seem 100% clear, perhaps you should add a small description to each of them describing what you did, the outcome and what you expected it to result in.

**Comment by Pub4Game** [comment]
If necessary, write the number, and I will describe this in more detail

**Comment by ProjectInfinity** [comment]
Number 9.

**Comment by MagicDroidX** [comment]
No.7 is a client-side bug.

**Comment by Pub4Game** [comment]
in a single game texture looks fine ...

**Comment by MagicDroidX** [comment]
@pub4game please look closely...

**Comment by MagicDroidX** [comment]
3) is fixed!

**Comment by Pub4Game** [comment]
@MagicDroidX Good job :D

**Comment by Pub4Game** [comment]
@MagicDroidX Ohh....

![image](https://cloud.githubusercontent.com/assets/11244874/12362209/240e02a0-bbd3-11e5-8997-182a60b01ca6.png)

**Comment by Pub4Game** [comment]
and...

![image](https://cloud.githubusercontent.com/assets/11244874/12362625/7153f004-bbd5-11e5-85aa-5c46b97aaba3.png)

**Comment by MagicDroidX** [comment]
By the way, what's wrong with the bed?
