### ISSUE TITLE
UUID not identical to PocketMine equivalent

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#237]
I noticed today that the UUID produced in Nukkit is just slightly different than the one PocketMine produces, now this is problematic when you share data across different servers and it turns out that Nukkit gets it wrong somehow.

I have ensured that both servers locally are identical in settings, they do not run at the same time for the sake of being 100% consistent in testing.

For my current settings, PocketMine would produce b2634a7a-a536-7153-8c1d-0c16a7c214e2
whereas Nukkit would produce b2634a7a-a536-7153-**a**c1d-0c16a7c214e2

I have made the part that Nukkit gets wrong bold. It is a 1 character difference, unfortunately just enough to make cross server platform data sharing unreliable.

I have to stress this, **every** setting were identical between the two servers. If Nukkit claim to handle UUIDs in the same way as PocketMine then the end result should have been the same.

**Comment by ProjectInfinity** [comment]
Also claiming that skin has anything to do with the UUID is wrong. Changed skin and PocketMine still reports b2634a7a-a536-7153-8c1d-0c16a7c214e2. Whereas Nukkit wasn't so lucky. #238

**Comment by MagicDroidX** [comment]
if($this->version !== null){
			return substr($hex, 0, 8) . "-" . substr($hex, 8, 4) . "-" . hexdec($this->version) . substr($hex, 13, 3) . **"-8"** . substr($hex, 17, 3) . "-" . substr($hex, 20, 12);
}

From the PM's code, it seems to be forced to be "8".

**Comment by ProjectInfinity** [comment]
Perhaps it should be replicated? The benefits are not insignificant. Firstly we'll be able to import data by PocketMine which will still be valid and secondly cross server platform services or plugins will be able to use uuid reliably.

**Comment by fromgate** [comment]
I think it will be great (i don't know it possible or not) to give ability to setup uuid using plugin (for example by authentication plugin).
It will allow to link single uuid for all player devices (tablets, phones, pc) if he enters a valid password.

**Comment by ProjectInfinity** [comment]
I think you misunderstand. Plugins shouldn't alter or set uuids. Only nukkit should. You can use uuids without creating them. Your tablet will not have the same uuid as your phone and that's how it already works.

**Comment by fromgate** [comment]
@ProjectInfinity 
I understood you. But I'd like to solve other issue :)

But I think it will be solve only when (if) Mojang will implement enable mojang accounts system of MCPE/MCW10E.

**Comment by ProjectInfinity** [comment]
I still think you misunderstand. There is no other issue....

**Comment by ProjectInfinity** [comment]
@MagicDroidX any word on this? Can we use UUID reliably despite this one issue here?

**Comment by MagicDroidX** [comment]
@ProjectInfinity I think you should judge the UUID string by ignoring this letter. It is not a correct implement of UUID of PocketMine I think..(?)

**Comment by markkrueg** [comment]
This is just a general philosophical suggestion:

It is important that that Nukkit and PocketMine UUID match for cross server compatibility. This is because many servers may migrate data from PocketMine to Nukkit or share data between PocketMine and Nukkit servers.

So Nukkit should implement PocketMine's identical code, unless there is some performance problem with doing so.

**Comment by Snake1999** [comment]
What I think is, we nukkit keep the correct UUID, and if you want to adapt old wrong data, ignore this wrong letter in plugin. By this way, both compatibility and correction are OK.
