### ISSUE TITLE
Sign Killer!

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#241]
![bug](http://xpyctum.ru/1.gif)

**Comment by Tee7even** [comment]
With inWall message it seems like a Sign is treated as a solid block.

**Comment by Pub4Game** [comment]
Я добавил блок "WallSign"

**Comment by Pub4Game** [comment]
#235

**Comment by xpyctum** [comment]
@Pub4Game  Его еще не добавили.

**Comment by xpyctum** [comment]
#235 Fixes this. Please add.

**Comment by Pub4Game** [comment]
@xpyctum ждем... Видимо пока заняты, скоро добавят)

**Comment by Pub4Game** [comment]
Закрой пожалуйста....
