### ISSUE TITLE
Dark world. 

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#243]
I didn't know. Bug in game or on server. 
![image](https://cloud.githubusercontent.com/assets/6584811/12014812/deca4ac8-ad54-11e5-99dd-bf183271ad95.png)
![image](https://cloud.githubusercontent.com/assets/6584811/12014813/decc15b0-ad54-11e5-9d31-6df5093e685d.png)

**Comment by ProjectInfinity** [comment]
Not experiencing this, try generating a new map.
