### ISSUE TITLE
No start.cmd

### ISSUE THREAD

**Issue by Lucario2** [Nukkit/Nukkit#257]

**Comment by Lucario2** [comment]
Help

**Comment by Angelic47** [comment]
just run command "java -jar nukkit.jar" and no need for start.cmd

**Comment by Lucario2** [comment]
I did

**Comment by Lucario2** [comment]
That didn't work either.

**Comment by Lucario2** [comment]
Error: Unable to acces jarfile nukkit.jar

**Comment by Angelic47** [comment]
Oh, what's your jar's name? If you renamed it already, you should use the jar name which you named
For example, if your nukkit jar named "nukkit123.jar", then you should use:
java -jar nukkit123.jar
That would be right.

**Comment by Lucario2** [comment]
I don't know where the Jar is located at

**Comment by Angelic47** [comment]
Please download the lastest build jar from our jenkins:
http://ci.mengcraft.com:8080/job/nukkit/

**Comment by Lucario2** [comment]
What do i do with it? Where do I put it? I use it with "java -jar nukkit.jar?"

**Comment by imjack** [comment]
Download the jar and place it into an empty folder and rename the jar to nukkit. Then create a bat file and put into the file java -jar nukkit.jar . Then run the file.

**Comment by ProjectInfinity** [comment]
Feel free to take this to the help forum. http://forums.nukkit.cn/index.php?forums/help-and-faq.8/

Github Issues is not the place to get basic help on how to run a Java application.

**Comment by LargeArt7338551** [comment]
There is no file.
I cannot find it.
Could you possibly drag the file into this conversation
