### ISSUE TITLE
While loading world: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by number44** [Nukkit/Nukkit#267]
Dear all. I have a MCPE world that worked fine (!) under the Nukkit build for 0.13.0.

But since the Nukkit build for 0.13.1 it gives me a ava.lang.OutOfMemoryError: Java heap space error, once I try to enter the world.

I tried all Nukkit snapshot builds (#50 - #77) but all gives the same error. I made the world available for download at: http://www.expertgroepontwikkelingsvoorsprong.nl/20160103.hotel_backup.tar.gz

Can someone help? Because it took many weeks of a group of school kids to make this world, and they are quite upset that their world is gone now ;)

Thanks in advance for your help. Jasper.

**Comment by number44** [comment]
Additional information: the server quites once the client shows it is busy "generating world / building terrain" at approx 15%.

**Comment by ProjectInfinity** [comment]
Try to delete the player profile.

**Comment by number44** [comment]
Tried it (let Nukkit create whole new profiles) .. but it did not solve the issue.

Does anyone feels to try the world on his own server? Just to check?

**Comment by grzegorz2047** [comment]
When I loaded your map and added some debug info then it showed that heightmap is null. I don't know what is the reason, but maybe i'll help to fix this problem.
> setHeightMap x: 0 z: 0 value: 3 heightmap == null
Exception in thread "Nukkit Asynchronous Task Handler #1" java.lang.NullPointerException
        at cn.nukkit.level.format.generic.BaseFullChunk.setHeightMap(BaseFullChunk.java:223)
        at cn.nukkit.level.format.generic.BaseFullChunk.getHighestBlockAt(BaseFullChunk.java:291)
        at cn.nukkit.level.format.generic.BaseFullChunk.recalculateHeightMap(BaseFullChunk.java:230)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:103)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by number44** [comment]
Hi grzegorz2047 - thanks - any idea where I can change this?

I checked the spc.settings file. Many settings, but not heightmap. Or is there any tool I can use?

**Comment by grzegorz2047** [comment]
I think you should look at commits where it started to crash server find last build which loads world fine and then check what changed in commit.  I can't find when heightmap is null.  We have to track which commit broke your world.

**Comment by grzegorz2047** [comment]
@number44 could you tell me which last build works with your map? 49 build?

**Comment by number44** [comment]
Hi grzegorz2047. My map broke once MCPE 0.13.1 was launched. And I immediatly downloaded the new nukkit release. 

So it was broke starting build #50 and worked before. But whether it was exactly #49, or #48, or #47 I am not quite sure.
And I have a hard time to downgrade to 0.13.0 (this includes me as well as all the school kids around me, who upgraded theirs to 0.13.1).

**Comment by grzegorz2047** [comment]
@number44 I managed to load map on Minecraft PC, on bukkit server, and mcedit software. You have few options:
1. hope that nukkit will fix this(if possible).
2. downgrade to 0.13.0
3. Recover map using .schematics by copying and pasting using mcedit or worldedit plugin in bukkit server. So for example generate new world in nukkit, load few chunks, and paste schematic using mcedit.

**Comment by number44** [comment]
@grzegorz2047 thanks for checking. I think I'll have to find myself a way through MCedit ;-)

One question, the heightmap == null thing you found .. that is in the map right? is this something that was changed once 0.13.1 was introduced?

**Comment by grzegorz2047** [comment]
@number44 This is something chunk loading related probably, because it throw error when player joins server and gets placed in specific chunk. Probably something was changed with  loading chunks from file and it broke compability with some old maps. Hard to say because I just started to involve in this project recently and didn't follow commits.

**Comment by MagicDroidX** [comment]
I am glad to tell you that this issue has been fixed and I have successfully entered your world. What a nice world!!! XD

**Comment by number44** [comment]
Hi @MagicDroidX I just tested the world and indeed the world works fine again.
Many thanks for the effort, with which you make several weeks of work available again to a group of elementary school kids.  greetings from nl.
