### ISSUE TITLE
Interesting bug with slots.

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#269]
Gif [Imgur](http://i.imgur.com/WpGnqyU.gifv)

**Comment by ProjectInfinity** [comment]
Try to explain this in text format. What's going on? Are you trying to say that another player touching a action bar slot, causes yours to change?

**Comment by xpyctum** [comment]
@ProjectInfinity 
If another player selects the first slot, then I will change it too, as with the other slots in his inventory

**Comment by xpyctum** [comment]
@MagicDroidX pridi pliz

**Comment by Pub4Game** [comment]
@xpyctum no, I killed him

**Comment by xpyctum** [comment]
@Pub4Game But, but, WHY?

**Comment by Pub4Game** [comment]
@xpyctum He didn't want to do bug fixes for Nukkit, and so I killed him.

**Comment by MagicDroidX** [comment]
@pub4game I am working hard for the final examination :/. And I have been working on bug fixing for months. I hope you can understand D:

**Comment by xpyctum** [comment]
@MagicDroidX How much for this time?

**Comment by Pub4Game** [comment]
@MagicDroidX This is a JOKE, nothing more, if I offended you, I apologize

**Comment by Pub4Game** [comment]
Fixed #306
