### ISSUE TITLE
Bugs with door and TrapDoor

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#279]
1)![image](https://cloud.githubusercontent.com/assets/11244874/12117550/8e334568-b3d2-11e5-861c-f5dcc02d3739.png)
To reproduce very easily, just open it and close the top part of the door

2)If you break the block under the door, then she  don't falls, as a item
3)Try to open and close the trapdoor, he behaves strangely
4)I can use a hoe on a snow block
![image](https://cloud.githubusercontent.com/assets/11244874/12117902/8caca5b6-b3d4-11e5-986d-7294407a5282.png)

**Comment by MagicDroidX** [comment]
Close #212

**Comment by MagicDroidX** [comment]
Door has been fixed. I'm going to test the trapdoor.

**Comment by Snake1999** [comment]
Fixed in https://github.com/Nukkit/Nukkit/issues/279 :D
