### ISSUE TITLE
Chests not working correctly

### ISSUE THREAD

**Issue by markkrueg** [Nukkit/Nukkit#290]
Testing build #82

You can now place items in a chest, but when you open the chest again they are no longer there. If you log out and back in again they are still not in the chest; but have returned to your inventory.

**Comment by Pub4Game** [comment]
The chests are not implemented yet!

**Comment by markkrueg** [comment]
Testing build #91 

Chests are getting better

**Comment by MagicDroidX** [comment]
Now in todo list in #385
