### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#293]
Hi i made a test server!

IP: play.minetox.cz
PORT: 25565

**Comment by Pub4Game** [comment]
omg :-1:

**Comment by Creeperface01** [comment]
what? :D

**Comment by Creeperface01** [comment]
why not? :D

**Comment by Pub4Game** [comment]
Cheap pr... my God...

**Comment by Creeperface01** [comment]
what do you mean? :D im not so good in english

**Comment by xpyctum** [comment]
piar blyad

**Comment by Pub4Game** [comment]
Ahah

**Comment by MagicDroidX** [comment]
This is not forum. You can share your server at http://forums.nukkit.cn
