### ISSUE TITLE
Code contribution

### ISSUE THREAD

**Issue by grzegorz2047** [Nukkit/Nukkit#333]
Is there somewhere a list of this which features are implemented or not? I'm not super expierenced,  but I wish to try. Are there any specific rules about pulling requests or sth? I think there should be some information about it on github or website.

**Comment by Angelic47** [comment]
Yeah. As you see, there are many bugs which need to be fix, you can view it on issues. And, there are some features are not implemented, such as nether, chest, redstone(I'm working on here now) and so on. You can easy to find it while playing in games.
We welcome contributions and there is no specific rules. It would be grateful if you helping us to make nukkit better :D

**Comment by grzegorz2047** [comment]
Thank you for information. But I think you could use Trello or simillar to manage what is todo, what is actually implemented what is in work etc. Simple and can avoid writing redundance code potentially.

**Comment by kamcio96** [comment]
Why that project is without SpongeAPI?
