### ISSUE TITLE
Very quickly exhausted hunger.

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#344]
Very quickly exhausted hunger. Clamping twice W and 2 minutes of running, we can already get a complete exhaustion of hunger. We want to eat.
![2016-01-15 1](https://cloud.githubusercontent.com/assets/6584811/12334652/e3b114d8-bb1c-11e5-96b6-f973ad11ee9f.png)

**Comment by Snake1999** [comment]
The player food contains food level and saturation level. After your saturation level lower to 0, your food level begin to lower quickly. Remember to feed yourself, and running uses more honger than usual :D
