### ISSUE TITLE
Potions

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#347]
![image](https://cloud.githubusercontent.com/assets/11244874/12341692/725215d6-bb34-11e5-9ddd-393ffc68be8f.png)

I drank a potion of "Instant cure 2"

**Comment by Snake1999** [comment]
Fixed at https://github.com/Snake1999/Nukkit/commit/0b8b13a2beb931fc09c95399b1895cc426dce370    ,waiting for further update :D

**Comment by Pub4Game** [comment]
@Snake1999 Potion poisoning has damage the player in creative
