### ISSUE TITLE
Can't join the server when it opens for the first time

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#352]
You cannot go into the world when you first start the server
1)Remove all files and folder
![image](https://cloud.githubusercontent.com/assets/11244874/12361669/966a60f8-bbd0-11e5-9f48-ba6eadc140b5.png)
Last build Nukkit
2)Run start.bat
![image](https://cloud.githubusercontent.com/assets/11244874/12361750/fc1d9e60-bbd0-11e5-9546-761dfba44907.png)
3)The game freezes... If you restart the game, then still not go, only after you restart the server
![image](https://cloud.githubusercontent.com/assets/11244874/12361804/3e3dae7a-bbd1-11e5-8a8b-54725c8641b3.png)

**Comment by Rlxzmdd** [comment]
Oh, I thought it was normal.. Didn't think it was a mistake..
