### ISSUE TITLE
Bug with double message in chat

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#353]
I use last build Nukkit

Game chat
![image](https://cloud.githubusercontent.com/assets/11244874/12361923/f3648fee-bbd1-11e5-945a-42b227537ced.png)

Console 
![image](https://cloud.githubusercontent.com/assets/11244874/12361943/14321fde-bbd2-11e5-80b4-d22b0e67f526.png)

**Comment by MagicDroidX** [comment]
I cannot confirm if this is a bug or not.

**Comment by xpyctum** [comment]
Client side bug. Timeout connection can repeat latest messages. Same on others cores.
