### ISSUE TITLE
Strange bug with items

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#354]
I use last build Nukkit

I join to server set gamemode 1 and got the right items in hot-bar
![image](https://cloud.githubusercontent.com/assets/11244874/12362037/7fc0c0f2-bbd2-11e5-8df6-7619e3663808.png)

rejoin to server
![image](https://cloud.githubusercontent.com/assets/11244874/12362065/9d5d5c9c-bbd2-11e5-8aef-aa6e96f2bc6d.png)

also there is a bug, if you had things in survival and you have turned on the creative, they will turn into standard creative blocks (hot-bar slots)

**Comment by Pub4Game** [comment]
@MagicDroidX please fix

**Comment by milkice233** [comment]
Maybe needs to seperate the survival and creative slot

**Comment by Creeperface01** [comment]
i may be fixed now

**Comment by xpyctum** [comment]
@Creeperface01 pull with number ...?

**Comment by Creeperface01** [comment]
My pull

**Comment by Creeperface01** [comment]
No sorry :D bad issue xD

**Comment by Pub4Game** [comment]
No longer relevant
