### ISSUE TITLE
MCPE crash

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#366]
when player death so MCPE crashes for all viewers

you can confirm this bug here: play.minetox.cz:25565

**Comment by xpyctum** [comment]
Maybe player has crash item in inventory?

**Comment by Creeperface01** [comment]
probably

**Comment by Creeperface01** [comment]
but i have same items and it crashes just sometimes

**Comment by Creeperface01** [comment]
I want to open server with annihilation minigame but i can't due to this :( and i tried to print all drops ids but all are right so problem is in dropItem() i think
