### ISSUE TITLE
Setting a Fake Player Skin doesn't work (or I'm doing something wrong)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#374]
My friend created a NPC plugin for Nukkit, it creates fake players.

Well, that part works perfectly fine, however, no matter what he (and I) try, we just can't set a skin for the NPC.

I don't know if it is a issue with Nukkit, or a issue with the code:
```
BufferedImage img = null;
						try {
							((Player)sender).sendMessage("Loading skin...");
							img = ImageIO.read(new File(getDataFolder() + "/" + args[2] + ".png"));
							Skin s = p.getSkin();
							s.parseBufferedImage(img);
							player.putSkinData(s);
						} catch (IOException e) {
							((Player)sender).sendMessage("Skin failed to load!");
						}
```
Even after trying to do this, the skin fails to load.

I also tried using ```Skin s = new Skin(img);``` but also didn't work.

The image exception isn't thrown, so no error happens, but, when the NPC spawns, it comes with the player skin instead of the custom skin.

Here is the complete code:
```
					AddPlayerPacket player = new AddPlayerPacket();
					player.username = nome;
					player.uuid = UUID.randomUUID();
					player.eid = Entity.entityCount + 1;
					player.metadata = new HashMap<Integer, EntityData>();
					player.speedX = 0;
					player.speedY = 0;
					player.speedZ = 0;
					player.item = p.getInventory().getItemInHand() != null ? p.getInventory().getItemInHand() : Item.get(0);
					
					if (args.length == 3) {
						BufferedImage img = null;
						try {
							((Player)sender).sendMessage("Loading skin...");
							img = ImageIO.read(new File(getDataFolder() + "/" + args[2] + ".png"));
							Skin s = p.getSkin();
							s.parseBufferedImage(img);
							player.putSkinData(s);
						} catch (IOException e) {
							((Player)sender).sendMessage("Skin failed to load!");
						}
					}
					
					player.yaw = (float) p.getYaw();
					player.pitch = (float) p.getPitch();
					player.x = (float) p.getX();
					player.y = (float) p.getY();
					player.z = (float) p.getZ();


					for(Entry<String, Player> packets : getServer().getOnlinePlayers().entrySet()) {
						packets.getValue().dataPacket(player);
					}
```
So, it is a issue with Nukkit, or some error in the code? Thanks!

**Comment by MagicDroidX** [comment]
I think you should send a PlayerListPacket to add the skin. There is no skin element in AddPlayerPacket.

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX so, why does the player has a ".putSkinData(Skin s);" function? (Maybe it is unused/broken?)

I'm asking because, when I was viewing some skin changing plugins for PocketMine: MP, the skin was set with the "putSkinData", anyways, I will test the PlayerListPacket, thanks!

**Comment by MagicDroidX** [comment]
The `player` is a packet.

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX 

```
					PlayerListPacket plp = new PlayerListPacket();
					Skin s = new Skin(img);
				        PlayerListPacket pk = new PlayerListPacket();
				        pk.type = PlayerListPacket.TYPE_ADD;
				        pk.entries = new PlayerListPacket.Entry[]{new PlayerListPacket.Entry(player.uuid, player.eid, player.username, s)};
				        
						for(Entry<String, Player> packets : getServer().getOnlinePlayers().entrySet()) {
							packets.getValue().dataPacket(plp);
						}
```

I tried doing this (by reading how Nukkit adds players to the Server List), however, the fake player doesn't appear on the list and the skin doesn't work.

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX fixed the problem, thanks a lot! (The other comment problem was that I was creating two PlayerListPacket, setting all the values on just one, and then sending the empty PlayerListPacket packet... I'm dumb sometimes :stuck_out_tongue_closed_eyes: )
