### ISSUE TITLE
Let's discuss about Position, Location and Vector3

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#379]
Hi!

Now we have three way to determine a location point:
1. Vector 3  — double x, y, z
2. Position (extends Vector 3) — double x,y,z + level
3. Location (extends Position) — level, double x,y,z + yaw and pitch

I think using three types to for a location point is making development slightly chaotic. Some time you need to use vector, sometime - location and sometime position.

I created a pull request to combine Position and Location classes: https://github.com/Nukkit/Nukkit/pull/370
First it was accepted well, but then rejected.

@MagicDroidX [said](https://github.com/Nukkit/Nukkit/commit/da449474e8890b2bb7cbf27c3e4870373c54bbab):
> Each class has its respective use. Position is generally used as a point in a level while Location is used by an entity to point out its direction.

But this did not describes why we need special way to determine a block? Using THREE different classes as a way to determine points - it's too much.

In bukkit there was only one class - Location. And there never was problem about it. 

I don't know why in php used three classes, may be it related to language. But we need to transfer chaos from PocketMine to Nukkit? I really don't know it. 

I think all of this classes: Location, Position, Vector3 must be combined in one class that will used everywhere to determine coordinates.

**Comment by MagicDroidX** [comment]
In that way, blocks may have yaws and pitchs, I don't like these kind of imprecise use. In my opinion, it will misleads developers.

**Comment by fromgate** [comment]
@MagicDroidX 
What about blocks have double in coodinates? 
Three type of coordinate - that what misleading developers.
Check nukkit's code how often you using lines:
```
if (pos instanceof Position) {

} else {

}
```
That's a real misleading ;)

**Comment by MagicDroidX** [comment]
What about remove the Location class and put `yaw` and `pitch` into Entity?

**Comment by fromgate** [comment]
I think we will lost universality. Sometime, in plugin we need to use Location collections to store yaw/pitch (for example to teleport player with predefined yaw pitch).


I have some thoughts about Block type too :)

I think better way is to remove Position and modify Block: it must not extend the location, vector or position.

Block must contain it's own fields for level and x,y,z/ Block's x,y,z - must be integer type.

Player will not use new Block() constructor normally. The must use level.getBlock(x,y,z) // level.getBlock(location) and location.getBlock() methods. 

Block must not contain any methods that allows to modify it's coordinates - block must be fixed in ti's coordinates (so if you'd like to create block (0,0,0) you will not be able to it cooordinates (1,1,1) using setters.  You'll need to create or get new blocks if you need to access to block in another location)

```
public class Block {
private Level level; 
private int x;  // insted double 
private int y;
private int z;

// When we need location...
public Location getLocation (){
   return new Location (level, x, y, z, 0, 0);
}

/////////////////////////
In location class:

public Block getBlock(){
   return this.level.getBlock(this.getFloorX(), this.getFloorY(), this.getFloorZ());
}

```

**Comment by MagicDroidX** [comment]
Okay. I'll remove Position, wait for my commit :D.

**Comment by MagicDroidX** [comment]
No, this is a respective feature of PocketMine-style API and this is not bad. I'll keep this.

**Comment by fromgate** [comment]
@MagicDroidX 
Ok. I still think that it's not good idea but you're boss ;)

What you think about made x,y,z in positions integer?
