### ISSUE TITLE
Compile Failure - utils.Random

### ISSUE THREAD

**Issue by Flirble** [Nukkit/Nukkit#380]
Been getting this problem compiling the source for about the last 2 weeks.

INFO] Finished at: Wed Jan 20 08:27:00 UTC 2016
[INFO] Final Memory: 13M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on pro
ject nukkit: Compilation failure: Compilation failure:
[ERROR] /data/pocketmine/Nukkit-Backup/src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java:[120,40] error: ref
erence to Random is ambiguous
[ERROR] 
[ERROR] both class java.util.Random in java.util and class cn.nukkit.utils.Random in cn.nukkit.utils match
[ERROR] /data/pocketmine/Nukkit-Backup/src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java:[114,45] error: ref
erence to Random is ambiguous
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by xpyctum** [comment]
Hm... You can download jar in last build from circle ci
