### ISSUE TITLE
Add command /xp

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#384]
To add a command to the changes of the experience

**Comment by rcsupermanjob** [comment]
Not useful..

**Comment by Pub4Game** [comment]
Maybe you not useful, but it is in Bukkit, why not add in Nukkit? Moreover, it is not very difficult

**Comment by Snake1999** [comment]
Should be added :D Thanks for advice

**Comment by MagicDroidX** [comment]
@Snake1999 Just do it. Remember, no lambda.

**Comment by Pub4Game** [comment]
@Snake1999 :D

**Comment by ProjectInfinity** [comment]
@MagicDroidX What's the problem with lambdas? I thought Nukkit was targeting Java 1.8?

**Comment by MagicDroidX** [comment]
I don't like lambdas. Lambda is not the only new feature in Java1.8.

**Comment by Snake1999** [comment]
:D https://github.com/Angelic47/Nukkit/pull/66

**Comment by Pub4Game** [comment]
:+1:

**Comment by xpyctum** [comment]
:+1:
