### ISSUE TITLE
Players can't connect to server

### ISSUE THREAD

**Issue by patry77** [Nukkit/Nukkit#388]
Hey, I have a problem with connecting to server with my android device, minecraft pe 0.13. When I was trying to join to server, the the game stucked on "Locating server" screen and than it crashed. Other players can't join too.

There is log from console:
15:44:50 [NOTICE] Player data not found for "patry77", creating new profile
15:44:50 [INFO] Patry77[/...:19132] logged in with entity id 1 at (world, 128.0, 0.0, 128.0)
15:45:07 [INFO] Patry77 joined the game

**Comment by MagicDroidX** [comment]
Restart the server. This is a bug and we are trying to fix.

**Comment by MagicDroidX** [comment]
duplicate #352
