### ISSUE TITLE
Encoding problem cause build failed

### ISSUE THREAD

**Issue by bamboowind** [Nukkit/Nukkit#39]
I tried to clone this git and build with maven, but failed for encoding problems. Mostly like this:
/data/sourcecode/Nukkit/src/main/java/cn/nukkit/scheduler/PluginTask.java:[7,17] error: unmappable character for encoding ASCII

Please use UTF-8 for all files.

**Comment by MagicDroidX** [comment]
All files are using UTF-8. Please check out if you add UTF-8 encoding parameter while compiling.
