### ISSUE TITLE
plugin depend bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#398]
i have 2 depending plugins but events are not called in main plugin first.

**Comment by xpyctum** [comment]
What are you mean?

**Comment by Creeperface01** [comment]
i have 2 plugins (MTCore and Annihilation) in annihilation in plugin.yml i have depend: ["MTCore"]
so it should be loaded after MTCore and it is. But when server call an event it shoould be called in MTCore first and then in Annihilation and it isn't

**Comment by xpyctum** [comment]
@Creeperface01 
```
depend:
 - DbLib
```

**Comment by Creeperface01** [comment]
ok thx :)

**Comment by Creeperface01** [comment]
no still doesn't work

**Comment by MagicDroidX** [comment]
Use `priority` in the EventHandler.
This is not a bug.

**Comment by Creeperface01** [comment]
Ok thx
