### ISSUE TITLE
jump bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#399]
when player jump, it should be like this:
![image](https://cloud.githubusercontent.com/assets/10363500/12532718/de6bc676-c21a-11e5-9190-0c130de89368.png)

but on nukkit it is like this:
![image](https://cloud.githubusercontent.com/assets/10363500/12532720/02f6e110-c21b-11e5-9646-b9b0539c71f6.png)

(photoshop level 5000 xD)

**Comment by xpyctum** [comment]
Hm. I understand you and confirm this xD

**Comment by MagicDroidX** [comment]
It should be calculated by the client. :\ Hmm...

**Comment by Rlxzmdd** [comment]
This is supposed to be nukkit's anti cheating lead, you can try to turn it off :)

**Comment by shanwer** [comment]
The bug now fix.
