### ISSUE TITLE
Can't drown.

### ISSUE THREAD

**Issue by SirMiner** [Nukkit/Nukkit#404]
I was testing some stuff on nukkit, found out you can't drown.

**Comment by Pub4Game** [comment]
Read more describe the problem... We can't guess

**Comment by Pub4Game** [comment]
Read more describe the problem... We can't guess

**Comment by SirMiner** [comment]
If you stay under water, and you spend all bubbles you start drowning normally, but that didn't happen on nukkit.

**Comment by Pub4Game** [comment]
Confirmed. If the air under the water ends, the player does not receive damage
