### ISSUE TITLE
Chunk generation queue not include chunk where spawn located

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#405]
Hello!
I created simple (empty ;)) generator and I notice that every time when worlds created for first time player cannot login. You need to stop server and start it again. After restarting all works fine.

I tried to locate what could be possible source of problem and find that when server is starting it generating some chunks... but not spawn chunks.

How to reproduce:
1. Create empty generator with this method:

```
    @Override
    public void generateChunk(int chX, int chZ) {
        int spChX = getSpawn().getFloorX() >> 4;
        int spChZ = getSpawn().getFloorZ() >> 4;
        Server.getInstance().getLogger().info((spChX == chX && spChZ == chZ ? TextFormat.RED : "") + "Generating chunk " + chX + ", " + chZ + " spawn chunk: " + spChX + ", " + spChZ);
    }
```

Remove worlds and players. Start server and login. 
You will see something like this:

```
18:41:53 [INFO] Default game type: Survival Mode
18:41:53 [INFO] Done (0.638s)! For help, type "help" or "?"
18:41:53 [INFO] Generating chunk 5, 10 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 4, 9 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 5, 9 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 6, 9 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 4, 10 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 6, 10 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 4, 11 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 5, 11 spawn chunk: 8, 8
18:41:53 [INFO] Generating chunk 6, 11 spawn chunk: 8, 8
18:42:03 [INFO] fromgate[/127.0.0.1:19132] logged in with entity id 1 at (world, 138.084, 2.0359, 123.6098)
18:42:14 [INFO] fromgate[/127.0.0.1:19132] logged out due to timeout
```

You can see in log that chunk 8, 8 (chunk where spawn point located) was not generated. And it will not generate until server restarted.

**Comment by Pub4Game** [comment]
:+1:

**Comment by MagicDroidX** [comment]
Same with #352 , but I have no idea about this.
It sometimes generate successfully for the first time.
However, no matter if the level have any chunk, it will surely manage to be generated after the server is restarted while it randomly fail to generate when the server runs for the first time.
That's really weird and I cannot find where is wrong. :|
