### ISSUE TITLE
Implement teleportation to other worlds

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#410]
![image](https://cloud.githubusercontent.com/assets/11244874/12563955/14a3cc28-c3c6-11e5-8185-3f02e459d5f0.png)

I can not understand, it is my mistake or yours please help me

In PocketMine all is well

![image](https://cloud.githubusercontent.com/assets/11244874/12564131/083b734a-c3c7-11e5-9955-2910dbaa8719.png)

**Comment by MrPowerGamerBR** [comment]
Maybe I'm totally wrong, but you should use Location instead of Vector3.

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/12564256/b3af20a0-c3c7-11e5-8ee6-5690ce95efa5.png)

**Comment by MrPowerGamerBR** [comment]
@Pub4Game :smile:

**Comment by Pub4Game** [comment]
He does not teleport to another world and remains in the same world

**Comment by MrPowerGamerBR** [comment]
@Pub4Game then that's a issue. (I never tried teleporting a player to another world tho, did you try using "Position" instead of "Location"? (I don't know if Position has a Level argument.))

**Comment by MagicDroidX** [comment]
Where did you call the method?

**Comment by Pub4Game** [comment]
Command /lobby

**Comment by fromgate** [comment]
@MrPowerGamerBR 
It will work for Position, for Location and for Vector3.
In teleport method it checking is provided Vector is instance of Position or location and casting to determine level, yaw and pitch. 
Missmash of classes - that was one reason of my [suggestion to combine all type of location classes into single one](https://github.com/Nukkit/Nukkit/issues/379).

**Comment by Pub4Game** [comment]
Hmm...@MagicDroidX you can help me?)

**Comment by fromgate** [comment]
@MagicDroidX Help with what? Teleportation is to another worlds is working fine. Yesterday I created a new test world and teleported to spawn of that world.

**Comment by Pub4Game** [comment]
@fromgate Hmm... doesn't work for me, provide example

**Comment by Pub4Game** [comment]
@MagicDroidX Also there is a bug with the teleportation, it lasts a very long time 7-12 seconds. (Tested on a new EMPTY world, where no blocks at all)

**Comment by MagicDroidX** [comment]
That's because the chunk in generating.

**Comment by Pub4Game** [comment]
@MagicDroidX In PM it works much faster

**Comment by xpyctum** [comment]
Async
