### ISSUE TITLE
0.14 branch

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#411]
Do you create a 0.14.0  branch?

**Comment by xpyctum** [comment]
:+1:

**Comment by Rlxzmdd** [comment]
mdx said "We will update 0.14 until the 0.14 official version was update or no bug can be repaired"

**Comment by Creeperface01** [comment]
@MagicDroidX Please create a 0.14.0 branch i want to test some thing like colored armor etc

**Comment by Snake1999** [comment]
**Not yet.**

**Comment by Creeperface01** [comment]
Why?

**Comment by MagicDroidX** [comment]
We are working on minecart, enchanting and generator which PocketMine has not implemented and adjustment on structure to provide a clearer API style.
We are now deciding to update Nukkit to adapt to 0.14.0 after the first formal version of 0.14.0 released.

**Comment by ProjectInfinity** [comment]
It would be ideal to fasttrack 0.14 support. The lack of it is making development difficult when you do no longer have access to a 0.13 client.

**Comment by yescallop** [comment]
I created a 0.14.0 branch, it is on https://github.com/yescallop/Nukkit/tree/0.14. You can try it

**Comment by Pub4Game** [comment]
🙄

**Comment by Creeperface01** [comment]
thx

**Comment by Creeperface01** [comment]
Why you removed 0.14 support?

**Comment by yescallop** [comment]
I reset it

**Comment by fromgate** [comment]
@yescallop 

Thanks to you - I can login to server now.

Good job!

Compiled version (if someone need it) located here: https://github.com/fromgate/Nukkit/releases/tag/0.0.1-test-0.14.0

@yescallop  How you find what was changed in 0.14.0 protocol? 

Do you think your version is ready to use? What about pull-request?

**Comment by Creeperface01** [comment]
From pocketmine :D

**Comment by yescallop** [comment]
I'm not sure, because @MagicDroidX tell me addHead function will affect efficiency, I'll discuss it with him.

**Comment by yescallop** [comment]
@fromgate I'm not sure, because @MagicDroidX told me addHead function will affect performance, I'll discuss it with him.

**Comment by Pub4Game** [comment]
@Snake1999
