### ISSUE TITLE
Bug or my mistake?

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#413]
I create config
![image](https://cloud.githubusercontent.com/assets/11244874/12593558/1d09a804-c48b-11e5-8292-7d005168bed7.png)

![image](https://cloud.githubusercontent.com/assets/11244874/12593584/3d4d276c-c48b-11e5-86d8-2ff458982bf8.png)

**Comment by MrPowerGamerBR** [comment]
@Pub4Game I used this on my plugin:
```
Config config = new Config(new File(this.getDataFolder(), "dreemurr.yml"));
```

![http://i.imgur.com/ONPIotY.png](http://i.imgur.com/ONPIotY.png)

No issues here, using the latest Nukkit build.

The only difference between mine and your code is that you added ", Config.YAML", try removing it, maybe that will fix it (and, if it does fix, then it is a issue)

**Comment by ProjectInfinity** [comment]
For datafolder path I always get absolute path, does that make a difference?

**Comment by MagicDroidX** [comment]
Try to initialize the config Object in onLoad or onEnable.

**Comment by Pub4Game** [comment]
@MagicDroidX @Snake1999 @Angelic47 please open issue.

![image](https://cloud.githubusercontent.com/assets/11244874/12874760/c7269630-cdeb-11e5-9ff5-9406b3d7bbd0.png)

![image](https://cloud.githubusercontent.com/assets/11244874/12874762/d4167626-cdeb-11e5-9fd9-2622b311745a.png)

**Comment by xpyctum** [comment]
Plus. Get the same issue. Fixed by @fromgate code

**Comment by xpyctum** [comment]
@Pub4Game try https://github.com/fromgate/Borders/blob/master/src/main/java/ru/nukkit/borders/Borders.java#L22

**Comment by ProjectInfinity** [comment]
I'm not getting this issue. It's likely your own fault.

**Comment by Pub4Game** [comment]
@ProjectInfinity If you use the same code in the main class, everything works fine

**Comment by Pub4Game** [comment]
@xpyctum I don't want to try to do "Patch" I want a normal solution

**Comment by Pub4Game** [comment]
@MagicDroidX it's Nukkit bug, please fix
