### ISSUE TITLE
when i swimming in the deep water,i can use “up” key to jump up to the surface

### ISSUE THREAD

**Issue by Efforto** [Nukkit/Nukkit#414]
plz fix→_→
中文翻译:我在游泳时候如果想游上去的话会Duang→_→蹦到水面上poi

**Comment by Rlxzmdd** [comment]
this look like so cool,i think this is nukkit "characteristic"

**Comment by Efforto** [comment]
haha,right
but i think it must fix

**Comment by MagicDroidX** [comment]
I cannot reproduce this.

**Comment by Efforto** [comment]
well i think it's in the low hunger(3 points)
