### ISSUE TITLE
Change how the "invalid movement" works.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#420]
The invalid movement check, while useful, affects a lot of simple vanilla functions.

**Example:**
- Sprinting on a slab causes rubberbanding
- Recieving damage causes rubberbanding

Yes, I know that you can disable the check, but it would be better to just fix the check than disable it. :+1:

**Comment by Pub4Game** [comment]
:+1:

**Comment by Snake1999** [comment]
:+1:

**Comment by xxFlare** [comment]
@MrPowerGamerBR Yes, Invalid movement does not take sprinting into consideration because it was created in MCPE 0.10 (based off PocketMine).

Though disabling it will allow a lot of hacks on the server such as NoClip.

**Comment by MrPowerGamerBR** [comment]
Yeah, disabling invalid movement is totally a bad option, but the invalid
movement check must be changed to not affect simple things like sporting or
damage knockback.
Em 8 de fev de 2016 11:34, "xFlare" <notifications@github.com> escreveu:

**Comment by Guillaume351** [comment]
How to disable it ? I allowed flight in the config, but still rubberband ;/ Thanks

**Comment by Pub4Game** [comment]
@MagicDroidX Please fix it. This is a very important issue.

**Comment by Pub4Game** [comment]
I think this is what you need.
```
@EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = false)
public void onPlayerInvalidMoveEvent(PlayerInvalidMoveEvent event) {
        event.setRevert(false);
}
```

**Comment by Tee7even** [comment]
Nope, he doesn't request to disable it, but to fix how it works.

**Comment by Pub4Game** [comment]
Oops.. I wanted to reply to the last comment
