### ISSUE TITLE
Anti Hack(?) blocking blocks in reach of the MCPE client.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#427]
I made this:

```
	@EventHandler
	public void onCreate(SignChangeEvent e) {
		System.out.println("aaa " + e.getLine(0));
	}
```

And I found a issue.

When I was testing the code (by setText(0, "wow");) some signs wouldn't change to "wow" at all, then, after some tests, I found that the server cancels some blocks when they are distant (maybe a reach Anti Hack?), however it is blocking blocks IN REACH of the MCPE client.

So, I think the reach anti hack (if it does have one?) should be changed to be more distant, because, as of now, it is blocking blocks placed by a vanilla MCPE client.

**Comment by xxFlare** [comment]
@MrPowerGamerBR What gamemode where you in?

**Comment by MrPowerGamerBR** [comment]
Creative
Em 8 de fev de 2016 14:37, "xFlare" <notifications@github.com> escreveu:

**Comment by xxFlare** [comment]
@MrPowerGamerBR Yeah.. Creative has a more far reach and I don't think Nukkit knows that.

**Comment by MrPowerGamerBR** [comment]
Already fixed in the latest Nukkit build after merging @Creeperface01 pull request.
