### ISSUE TITLE
Item Custom Names doesn't work (or I'm doing something wrong)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#428]
```
Item i = new Item(Item.STONE_SWORD);
		
i.setCustomName("test");
		
e.getPlayer().getInventory().addItem(i);
```

It gives a Stone Sword with the default name (instead of a sword with the name "test")

**Comment by Creeperface01** [comment]
compound tag is wrong ( i think )

**Comment by xpyctum** [comment]
in Genisys... same bug :(

**Comment by MrPowerGamerBR** [comment]
@Creeperface01 strange, I seen the ImagicalMine source and the compound tag is exactly the same (unless ImagicalMine also has a broken custom name implementation)

**Comment by Creeperface01** [comment]
yes because all these projects copied it from pocketmine :P

**Comment by MrPowerGamerBR** [comment]
@Creeperface01 yeah, I know about that (that's why it is easy to port PocketMine-MP plugins to Nukkit :yum: , also I'm more familiar with Java than PHP), someone should test if custom names are broken in ImagicalMine too (Well, @xpyctum said it also wasn't working in Genisys, and Genisys is also a fork of PocketMine-MP)

**Comment by Creeperface01** [comment]
yes but enchants works so coumpound tag sending is good so just structure is wrong but i dont know how :/

**Comment by Creeperface01** [comment]
i tried:
tag->display->name
tag->display->Name
tag->display->customName
tag->display->CustomName

but doesn't work

**Comment by MrPowerGamerBR** [comment]
@Creeperface01 well, you could try loading a Minecraft PC world with a item with custom name inside a chest, if the name is shown correctly in MCPE, then names are supported, but the API is a bit broken.

**Comment by Creeperface01** [comment]
but in PC it is tag->display->name too, but i'll test it

**Comment by MrPowerGamerBR** [comment]
Yeah, probably it won't work, but we don't have anything to lose by testing
that, right?
Em 2 de fev de 2016 11:50, "Creeperface01" <notifications@github.com>
escreveu:

**Comment by MrPowerGamerBR** [comment]
@Creeperface01 also, another thing we can test.

Create a world in MCPE with a renamed item in a chest and open it in Nukkit, if the name stays in Nukkit, then there is a issue in the tag on Nukkit, after doing that, we can create a code in Java to see every tag the item has.

**Comment by Creeperface01** [comment]
Yes and nukkit can use maps from MCPE?

**Comment by MrPowerGamerBR** [comment]
@Creeperface01 yes! Nukkit supports LevelDB maps (I never tested it, but you can use it if you change on the config file from "mcregion" to "leveldb")

**Comment by Creeperface01** [comment]
I can not open the chest xD and i think API is wrong because when i use setCustomName() and then hasCustomName() it returns false

**Comment by Creeperface01** [comment]
So tiles are not implemented in nukkit leveldb loader

**Comment by 2300206764** [comment]
Oh!It is a little Bug,I will fixed it as soon as possible.

**Comment by MrPowerGamerBR** [comment]
Thanks, I seen your pull request, I can't test it at the moment because I'm
travelling, but when I come back to my home (tomorrow) I will test the new
Nukkit build with your fix 😊
Em 7 de fev de 2016 23:45, "2300206764" <notifications@github.com> escreveu:

**Comment by MrPowerGamerBR** [comment]
@2300206764 fixed! Thanks!

**Comment by Creeperface01** [comment]
But in 0.14 it doesn't work

**Comment by MrPowerGamerBR** [comment]
It works in 0.13.1, that what matters.

Also, you did test 0.14 with this commit? Right?
Em 10 de fev de 2016 03:13, "Creeperface01" <notifications@github.com>
escreveu:

**Comment by Snake1999** [comment]
@Creeperface01
NUKKIT DOES NOT SUPPORT 0.14 NOW, ALL UNOFFICIAL BRANCHES ARE NOT SUPPORTED BY OFFICIAL GROUP YET.
We will test this after mojang's 0.14(not 0.14 beta) come out :3
