### ISSUE TITLE
TnT dont explode with water

### ISSUE THREAD

**Issue by SirMiner** [Nukkit/Nukkit#429]
Hi, I found a bug: Normally when you put tnt and lava together it explodes but when I do this nothing happens. [IMG]http://i.imgur.com/9wfsbdY.jpg[/IMG]

**Comment by SirMiner** [comment]
Lava dont affect anything around it http://i.imgur.com/zp6GEOD.jpg

**Comment by Pub4Game** [comment]
The burning of the fire has yet to be realised!

**Comment by shanwer** [comment]
OK.I know.That's a interesting bug.I will fix it.And I think you want to make a  TNT cannot.
