### ISSUE TITLE
Request: RaspberryJuice for Nukkit?

### ISSUE THREAD

**Issue by number44** [Nukkit/Nukkit#441]
Hi guys, I am not quite sure whether this is the right location to put a new request. If there is another location, please feel free to let me know.

So, I wondered whether it is possible to port the RaspberryJuice API from Bukkit to Nukkit. With this, I could start teaching my childern Python which will result in their Nukkit worlds on their iPads.

Would this be a big effort?

The reference I use is : https://www.nostarch.com/programwithminecraft
And ofcourse: http://dev.bukkit.org/bukkit-plugins/raspberryjuice/

Big thanks for replying.

**Comment by number44** [comment]
If course any other solution to a Python/Scratch -> Nukkit connection is welcome as well ;-)

**Comment by ProjectInfinity** [comment]
Of course you can port it yourself. Github issues is **not** the place to ask though.

**Comment by ItsLucas** [comment]
+1
You can port it using the nukkit API yourself.

**Comment by number44** [comment]
Thanks, I'll take the challange to give it a try. Does anyone from the Nukkit community wants to be a reviewer/tester for me?
