### ISSUE TITLE
Allow cancelling a repeating task inside the task.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#456]
In Bukkit, you could use ```this.cancel()``` to stop the task, however, in Nukkit, there is no method to do this.

I tried using ```return;```, but that didn't work.

(Maybe just BukkitRunnables allows cancelling, whatever)

**Comment by Snake1999** [comment]
See this,
`TaskHandler th = getServer().getScheduler().schedultRepeatingTask(.....);`
And if you want to operate this task, do something on that `TaskHandler`. Example:
`th.cancel();`

**Comment by MrPowerGamerBR** [comment]
Oh... So there is a way to cancel, thanks! I will test later. (I didn't
know about that, I just tried "this.cancel();", but that didn't work.)
Em 3 de fev de 2016 23:39, "Peter Jiang" <notifications@github.com>
escreveu:

**Comment by MrPowerGamerBR** [comment]
@Snake1999 sadly, that doesn't work.

![The local variable th1 may not have been initialized](http://i.imgur.com/TeAQAMr.png)

**Comment by Snake1999** [comment]
@MrPowerGamerBR Oh, to cancel a task, the handler should be stored into a variable. If a variable may not been initalized, initalize it with:
`private TaskHandler th = null;`
And you can give value to this variable:
```
public void onEnable(){
    th = getServer().gerScheduler().schedule......(..);
}
```
Remember to check if the variable is null before cancelling :D

**Comment by MrPowerGamerBR** [comment]
@Snake1999 

Example:
```
final TaskHandler th = m.getServer().getScheduler().scheduleRepeatingTask(new Runnable() {
	public void run() {
		m.getServer().broadcastMessage("Hello!");
		th.cancel();
	}
}, 20);
```
Doesn't work because "The local variable th may not have been initialized"

The only way to this to work would be creating a global variable called ```private TaskHandler th;```, yeah..., that would work, but it would be a mess if I have a lot of delayed repeating tasks.

Another way is just creating a function that runs a delayed task, and, when the task ends, the function is called again, like this:

```
	public void countdown(final int count) {
		m.getServer().getScheduler().scheduleDelayedTask(new Runnable() {
			public void run() {
                                if (0 >= count) {
                                    return;
                                }
				int mCount = count;
				mCount = mCount - 1;	
				countdown(mCount );
			}
		}, 20);
	}
```

**Comment by Snake1999** [comment]
@MrPowerGamerBR Oh, you are creating a **one-time** task instead of a **repeating** task. This task will be closed itself when cancelled itself is called. You can use scheduleTask or scheduleDelayedTask to do this :)
And delayed task will be only executed *once* if I'm right

**Comment by MrPowerGamerBR** [comment]
@Snake1999 that's why I said "example code".

My code isn't like that, my repeating task is a broadcast message which shows the amount of blocks broken inside a location, and, if all of the blocks broken, the repeating task stops.

I can do that on Bukkit, by creating a repeating task and then using "this.cancel();" when the amount of blocks is 0, however, in Nukkit, there isn't a "this.cancel();" method.
