### ISSUE TITLE
Update to 0.13.2

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#459]

**Comment by ProjectInfinity** [comment]
Considering 0.14 is very close to release (and is already in beta circles), surely efforts should be focused on that instead?

**Comment by Pub4Game** [comment]
23333, just update protocol...

**Comment by ProjectInfinity** [comment]
If that's the case, just make a PR?

**Comment by Pub4Game** [comment]
Hmm... How do I know what version of the protocol now?

**Comment by applqpak** [comment]
I already made a PR to update it to 0.13.2 for now, as many users have updated.

**Comment by applqpak** [comment]
And, @Pub4Game 0.13.2's protocol is 39.

**Comment by Pub4Game** [comment]
Okay :3

**Comment by fromgate** [comment]
@applqpak Are you sure that only protocol version was changed? If version is changed - there could be another additions that must be implement too...
