### ISSUE TITLE
no create file

### ISSUE THREAD

**Issue by haniokasai** [Nukkit/Nukkit#46]
i built nukkit in maven,and run it.
but server.properties,worlds,players and ban.txt .....have not been created.
why?

**Comment by Snake1999** [comment]
Really? I have all required files and folders created, as well as the default world.
Check if your user have the permission to create a file, or any error occurred :P

**Comment by haniokasai** [comment]
i'll try again

**Comment by haniokasai** [comment]
in debian,and files were created.
(in windows,files werent created.)

thanks:)
