### ISSUE TITLE
Revert block structure update

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#460]
Why was this even done in the first place? What purpose does it serve, why are we screwing up naming?

We have packages in Java for a reason, hence cn.nukkit.block.Block. Surely you all understand cn.nukkit.block.BlockBlock is redundant, yeah?

Let's not screw this further up, you can clearly see people not understanding the point of this commit in the commit comments itself.
https://github.com/Nukkit/Nukkit/commit/4538f62bbbfcc5cf6ae107316528d0f8d4b623ee

**Comment by Creeperface01** [comment]
:+1:

**Comment by Snake1999** [comment]
I understand what you mean. Here something in Java, we have many thing already defined in Java core(`String`and`ItemString`), and something will conflict(`BlockSkull`and`ItemSkull`). In PHP we can `use xxx\XX as XXX`, but in Java this can not be changed, conflicts can only be solved as `cn.nukkit.block.XXX` if we does not update this structure. 
You can continue on using `Block.get(int id)`, and this will not inflect the result of something like `Block.get(Block.SKULL_BLOCK)`. 
:D

**Comment by ProjectInfinity** [comment]
@Snake1999 If Bukkit could deal with it without screwing up naming conventions, then so can Nukkit.

**Comment by Snake1999** [comment]
@ProjectInfinity Here, Nukkit is almost completely writing whole minecraft PE again, not only an API based on something that exists.And if we does not deal with these conflicts, we will miss this chance to edit the API and will have headaches in dealing with conflicts in the future.
Sorry for inconvenience, and we won't revert this change. Thanks for focusing in Nukkit :3

**Comment by MagicDroidX** [comment]
That's how Bukkit deal with the naming conventions

**Comment by ProjectInfinity** [comment]
@MagicDroidX Doesn't look like it, feel free to explain if you think I don't get it.

https://github.com/Bukkit/Bukkit/tree/master/src/main/java/org/bukkit/block
https://github.com/Bukkit/Bukkit/tree/master/src/main/java/org/bukkit/material

**Comment by Snake1999** [comment]
@ProjectInfinity **Here, Nukkit is almost completely writing whole minecraft PE again**, and here are **many** classes, **much more** than what bukkit has. And cause **more conflict**, and we do this rename. Thanks for understanding us. :3

**Comment by MagicDroidX** [comment]
This is not acatully the block classes' location. As we all known that bukkit is just a interface. What I mean is those contained Minecraft's codes.

**Comment by MagicDroidX** [comment]
This has been predicted when we were making the hard decision. Although it may be a very bad commit for most of the developers, we must do this before it is too late. Thanks for everyone who pays however great attetion on Nukkit. Thanks!

**Comment by fromgate** [comment]
you don't understand what @ProjectInfinity  trying to bring to you.
There's no real reason to produce huge amount of "block" classes. 
You can created a Block object with fields id/data and created a specific blocks only when these blocks has an specific characteristics.
(Doors need to provide open/close state, etc.).
Yes. Bukkit is an interface. But there's no "stone", "dirt" and other block-classes in NMS-packages too. 
Sorry, but you making your life harder :disappointed:

**Comment by fromgate** [comment]
> I understand what you mean. Here something in Java, we have many thing already defined in Java core(StringandItemString), and something will conflict(BlockSkullandItemSkull). 

No.
1.
If you using cn.nukkit.blocks.Skull it will never be conflicted with cn.nukkit.items.Skull
If you need to use it inside single class you can fully define class with name of package:
```
cn.nukkit.items.Skull skullItem = new cn.nukkit.items.Skull();
cn.nukkit.block.Skull skullBlock = new cn.nukkit.block.Skull();
```

2. If you use combined Material list (like in bukkit) you don't need to separated items from blocks.
You can use torch item (for example) and torch block. It will be defined as one line in Material class and you can define a field that returns could this material used as block or not:
Material.STONE.isBlock() - will return true;
but Material.IRON_SWORD.isBlock() will return false;.

**Comment by MagicDroidX** [comment]
No1 is how we used to deal with conflict but it is not quiet friendly.
And the material seems to be a larger change than renaming.

**Comment by ProjectInfinity** [comment]
Let's be frank, I'd rather we deal with it using fully qualified names than having to make these stupid redundant naming conventions.

**Comment by MrPowerGamerBR** [comment]
I also agree that it is a bit redundant keeping "Block*BlockName*", they are inside a package called "block" for a reason.

(Also, it is also a bit redundant having Block and Item, most of them share the same ID, so, why not just merge the two classes into one called "Material" like @fromgate said? Yeah, maybe it will be difficult to implement it, but at least it will not have confusion :) )

**Comment by Pub4Game** [comment]
@MrPowerGamerBR I totally agree with you.

@MagicDroidX Better to do that once well, than everyone will suffer because of the problems

**Comment by fromgate** [comment]
I'm agree with @ProjectInfinity that BlockBlockName is excrescent. 
Random was to NukkitRandom but...  before renaming there was no any problem for me to determine which class I used in my plugin - java's Random or Nukkit's. 

Anyway I'm going to say that you, that **you are trying to treat the symptoms when you need to remove the cause.**

Nukkit has now 140+ item classes. But you can use classes:
Item - for basic items;
Sword - for swords (Or event Breakable for all swords, pickaxes and other tools)
Food for all food 

You have 170+ classes for block.
But it could be one class Block for simple blocks  and some classes for specific:
Doors, Lever, Buttons, Bed, etc. 

I don't understand why you making your own life harder.

Imagine, for example in 0.1x.0 mojang adding a new block named Moonstone.
If you using a material class you will be able to add ONLY ONE LINE:
```
MOONSTONE (<id>,<data>,<resistance>,<another parameters if you need>);
```

Or create class: BlockMoonstone:
```
package cn.nukkit.block;

import cn.nukkit.item.Item;
import cn.nukkit.math.AxisAlignedBB;

/**
 * author: MagicDroidX
 * Nukkit Project
 */
public class BlockMoonstone extends BlockSolid {

    public BlockMoonstone () {
        this(<id>);
    }

    public BlockMoonstone (int meta) {
        super(<id>);
    }

    @Override
    public int getId() {
        return MOONSTONE;
    }

    @Override
    public String getName() {
        return "Moonstone";
    }

    @Override
    public int getId() {
        return MOONSTONE;
    }

    @Override
    public double getHardness() {
        return 3;
    }

    @Override
    public double getResistance() {
        return 1313;
    }

    @Override
    public int getToolType() {
        return ItemTool.TYPE_PICKAXE;
    }

    @Override
    public int[][] getDrops(Item item) {
        if (item.isPickaxe() && item.getTier() > ItemTool.TIER_WOODEN) {
            return new int[][]{{Item.END_STONE, 0, 1}};
        } else {
            return new int[0][];
        }
    }

    @Override
    public boolean canBePlaced() {
        return false;
    }

    @Override
    public boolean canBeReplaced() {
        return true;
    }

    @Override
    public boolean isSolid() {
        return false;
    }

    @Override
    public AxisAlignedBB getBoundingBox() {
        return null;
    }

    @Override
    public double getHardness() {
        return 0;
    }

    @Override
    public double getResistance() {
        return 0;
    }
}
```

As a plugin developer I don't need a BlockAir() class.
For example, I'm trying to check what is located under player's feet:
```
Block block = player.getLocation().add(0,-1,0).getBlock();
if (block.getId()==0) // 
```

But I will never use 
```
if (block instanceof BlockAir) //
```
Placing block? 
```
Block block = new BlockAir()?
```
STOP! BLOCK WITHOUT COORDINATES??? 
So it will be more useful and "bugless" to use something like this:
```
level.getBlock().setId(0);
level.getBlock().setType(Material.AIR);
```

**Comment by MagicDroidX** [comment]
So how many solutions do we have now?

**Comment by ProjectInfinity** [comment]
@MagicDroidX One. The one that Bukkit decided to use and that @fromgate mentioned.

Thing is here that we need to stop putting the idea that doing what bukkit did is bad because "this ain't bukkit". Bukkit implements a lot of things in a specific way because it is a **good** way of doing it. The way they handle blocks & material is really good. No question about that.

**Comment by Snake1999** [comment]
org.bukkit.block and org.bukkit.material, only contains some simple API to operate server easier. I think it might be good to add these to Nukkit.

**Comment by Snake1999** [comment]
If agree, we might need to disguss in a new issue :D
