### ISSUE TITLE
BlockEntity bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#461]
After you refactored tile to BlockEntity, signs dont show to player. (maybe other blockentities too)

**Comment by MrPowerGamerBR** [comment]
I think only signs placed before the refactoring were lost, because I placed a sign and it did appear correctly...

(Maybe that explains why every sign from my Server suddenly dissapeared)

**Comment by Snake1999** [comment]
Confirmed in flower pots. Maybe client-side or server-side, need to be figured out. :D

**Comment by MagicDroidX** [comment]
I've seen that one commit removed some codes with sign. Is that the cause?

**Comment by MagicDroidX** [comment]
I'll fix this after I return to China. :D I'm travelling in Thailand now.

**Comment by Creeperface01** [comment]
But i have the same bug in pocketmine so maybe it is because im testing in 0.14

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX should this be fixed for previously broken BlockEntities? Because I was using the new build and the invisible chest was still there. :neutral_face:
