### ISSUE TITLE
Teleport won't work on PlayerJoinEvent

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#468]
I think Nukkit first calls PlayerJoinEvent then teleports the player to the last location. Please fix this because it's impossible to teleport players on PlayerJoinEvent.

**Comment by xpyctum** [comment]
:+1:

**Comment by Snake1999** [comment]
Need to confirm. It's Chinese new year in China, and everyone is busy, but I'll figure this out tomorrow :3

**Comment by xxFlare** [comment]
@Snake1999 Alright, thanks!

**Comment by Creeperface01** [comment]
it is in pocketmine too

**Comment by Snake1999** [comment]
@xxFlare Try use `player.setPosition(Vector3 pos)`. That's because player class have not been initialized yet on joining games. :)

**Comment by xxFlare** [comment]
@Snake1999 I'll try that, but mane make it initialize the player class on PlayerPreLoginEvent? 👍

**Comment by Snake1999** [comment]
@xxFlare It initializes in PlayerCreationEvent. You can event replace the player class in this event! 

To show why it works:
```
public class ExamplePlugin extends PluginBase {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new ExampleListener(), this);
    }

    class ExampleListener implements Listener {
        @EventHandler
        public void onPlayerCreation (PlayerCreationEvent event) {
            event.setPlayerClass(ExamplePlayer.class);
        }
    }

    public static class ExamplePlayer extends Player {

        public ExamplePlayer(SourceInterface interfaz, Long clientID, String ip, int port) {
            super(interfaz, clientID, ip, port);
            getServer().getLogger().info("replaced to " +this.getClass().getName());
        }

    }

}
```

**Comment by xxFlare** [comment]
Ooohh. Ok, thanks! :D

**Comment by MagicDroidX** [comment]
You can use PlayerRespawnEvent instead. :D
