### ISSUE TITLE
Server did not detect when MCW10E was closed using Alt+F4

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#473]
How to reproduce:
1. Start server and connect to it using Minecraft Windows 10 Edition
2. Play some time and close MCW10E using Alt+F4
3. Check server log - you will not find nothing about disconnecting player.
4. You can use commands for this player (for example you can kick player):
```
> kick fromgate
13:27:00 [INFO] fromgate left the game
13:27:00 [INFO] fromgate[/127.0.0.1:19132] logged out due to Kicked by admin.
13:27:00 [INFO] [CONSOLE: Kicked fromgate from the game]
> kick fromgate
13:30:04 [INFO] That player cannot be found
```
First "kick" was performed after closing client (server still think that player is online)

**Comment by MagicDroidX** [comment]
Alt+F4 will force the client to shut down without sending a Disconnect Packet which is used to tell the server that the client is disconnecting.

**Comment by fromgate** [comment]
Ok. I'll create a ticket on mojang's bug tracker

**Comment by xxFlare** [comment]
@MagicDroidX The server will timeout the client anyways, right?

**Comment by MagicDroidX** [comment]
@xxFlare Of course.
