### ISSUE TITLE
Infinity water.

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#474]
As I was trying not to close the water, she appeared out of nowhere.
![minecraft_ windows 10 edition beta 07 02 2016 19_38_22](https://cloud.githubusercontent.com/assets/6584811/12873053/e66ad97c-cdd5-11e5-95a7-cac8fc18f875.png)
or watch video
https://youtu.be/zGRzDkLWkog

**Comment by Creeperface01** [comment]
But when you change blocks around the water by plugin so this happens right?

**Comment by xpyctum** [comment]
@Creeperface01 no
