### ISSUE TITLE
Generating player.dat is too slow.

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#478]
Nukkit is generating the player.dat very slowly, first join can take more then 10 seconds. Second join is much faster if the data was saved. PocketMine can generate it faster too.

**Comment by MagicDroidX** [comment]
Cos Nukkit is generating spawn chunks, I think.

**Comment by JackNoordhuis** [comment]
PocketMine creates the player data when a player leaves.

**Comment by xxFlare** [comment]
@JackNoordhuis No, it makes it into objects upon join and just saves it on quit.
