### ISSUE TITLE
Black grass

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#480]
So black grass is a problem I can fix, but there are a couple ways we can do it.

1: Revert PocketMine's commit that caused this problem.
2: Force the color always be green.

Which way would be the best?

**Comment by Snake1999** [comment]
That's what called **Biome**, that is a *feature* instead of a *bug*. You can even use this to create pink grass and white leaves. :3

**Comment by xxFlare** [comment]
@Snake1999 Yes, but it's glitched out causing converted maps to be black. So we can force it to be green or try to find a solution.

**Comment by xxFlare** [comment]
@Snake1999 https://github.com/PocketMine/PocketMine-MP/commit/cbb1c55a06f3H74f5eefd46e3a08f8ddff0db9341

**Comment by Creeperface01** [comment]
so change defaullt color to green instead of black

**Comment by xxFlare** [comment]
@Creeperface01 It takes the color from the world, if we force it green that will cause other problems. The problem is when you convert a world, that data goes away.

**Comment by Creeperface01** [comment]
But grass color is not black in the PC worlds so black must be default color

**Comment by xxFlare** [comment]
As I said, the problem is when you **covert** the world, the **color tag gets lost** and Nukkit makes it black.

**Comment by Creeperface01** [comment]
Yes, but why does nukkit make it black? Because black is default color

**Comment by xxFlare** [comment]
Oops, what was I thinking >.<

Sorry, you are right :)

**Comment by Tee7even** [comment]
I guess, this should be closed?

**Comment by Pub4Game** [comment]
@Tee7even please stop flood!

**Comment by Tee7even** [comment]
@Pub4Game **Flood (_flʌd_)** is a a bunch of messages that don't make sense, often one is a copy of another. Well, I at least try to write on the subject.

**Comment by Pub4Game** [comment]
**This may not exactly what we're talking about, but I still think it's worth mentioning here.**

I can confirm the bug, sometimes I respawn and I have "no light".
![image](https://cloud.githubusercontent.com/assets/11244874/14766574/a8a79592-0a18-11e6-959a-dcf4e1a13ce9.png)

**_There is no light source, but the whole cave is very well lit._**
![image](https://cloud.githubusercontent.com/assets/11244874/14766608/0bd5ddee-0a1a-11e6-9baa-e857a179f5f4.png)

**Comment by Pub4Game** [comment]
@MagicDroidX please help fix light.
