### ISSUE TITLE
'for' for add more particles.

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#481]
```
 at cn.nukkit.level.Level.addChunkPacket(Level.java:492)
        at cn.nukkit.level.Level.addParticle(Level.java:406)
        at cn.nukkit.level.Level.addParticle(Level.java:393)
        at BlockPartyPE.AreaStyler.onRun(AreaStyler.java:39)
        at cn.nukkit.scheduler.ServerScheduler.lambda$addTask$46(ServerScheduler.java:147)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
18:16:30 [CRITICAL] Could not tick level "world": java.util.ConcurrentModificationException
18:16:50 [CRITICAL] Could not tick level "world": java.util.ConcurrentModificationException
18:17:25 [CRITICAL] Could not tick level "world": java.util.ConcurrentModificationException

```

**Comment by Snake1999** [comment]
Is this the whole call stack? I wonder which kind of exception this program throws :3

**Comment by Snake1999** [comment]
Seems like thread-safety problem. Need to confirm.

**Comment by MagicDroidX** [comment]
How to reproduce?

**Comment by xpyctum** [comment]
Create cycle to add many particles in plugintask. (Async = true)

**Comment by MagicDroidX** [comment]
You should never do this asynchronously.

**Comment by xpyctum** [comment]
Why not?

**Comment by MagicDroidX** [comment]
Asynchronous tasks are made for IO operations or huge calculations that will not affect the main thread.  
If you want to do something with the main thread, you should learn how to use the `synchronized`.

**Comment by xpyctum** [comment]
@MagicDroidX 
>Huge calculations that will not affect the main thread. 
For this.

**Comment by MagicDroidX** [comment]
`addParticle` is on main thread of course.

**Comment by xpyctum** [comment]
@MagicDroidX 
I want do a big cycle for '''addParticle'''  with calculating x,y,z in async task.

**Comment by MagicDroidX** [comment]
You should store the positions of the particles you have calculated and add them in `onCompletion(Server)`.

**Comment by xpyctum** [comment]
@MagicDroidX a large array of vectors can inhibit server

**Comment by MrPowerGamerBR** [comment]
Calculate the coords in the async task and, when spawning the particles,
create a sync task. (Just create a synchronized task inside the async task
when you need to spawn them)
Em 11 de fev de 2016 06:08, "Oleg Basalyga" <notifications@github.com>
escreveu:
