### ISSUE TITLE
Argument type mismatch in EntityDamage(ByEntity)Event

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#489]
```
2016-2-2 20:46:59 [CRITICAL] Não foi possível passar o evento 'cn.nukkit.event.entity.EntityDamageEvent' para 'SparklyWorldGuard v1.0.0': argument type mismatch em com.mrpowergamerbr.sparklyworldguard.listeners.MoveListener
2016-2-2 20:46:59 [ALERT] java.lang.IllegalArgumentException: argument type mismatch
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:24)
    at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:50)
    at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
    at cn.nukkit.entity.Entity.attack(Entity.java:651)
    at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:107)
    at cn.nukkit.Player.attack(Player.java:3471)
    at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:863)
    at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:184)
    at cn.nukkit.Player.onUpdate(Player.java:1400)
    at cn.nukkit.level.Level.doTick(Level.java:606)
    at cn.nukkit.Server.checkTickUpdates(Server.java:892)
    at cn.nukkit.Server.tick(Server.java:954)
    at cn.nukkit.Server.tickProcessor(Server.java:757)
    at cn.nukkit.Server.start(Server.java:737)
    at cn.nukkit.Server.<init>(Server.java:441)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

With my testings, it seems that this error is caused when the source of the damage is a fire (I'm still testing what causes this error), using "instaceof Player" doesn't work, for some reason.

The code has a "if (e.getEntity() instanceof Player && e.getEntity().getDamager() instanceof Player) {", so it isn't a missing instance verification.

**Comment by MagicDroidX** [comment]
I wonder if you are listening for EntityDamageByEntityEvent  directly?

**Comment by MrPowerGamerBR** [comment]
Uh... How I listen "directly"?

I'm using public void entity(EntityDamageByEntityEvent e), but the same
thing happens with EntityDamageEvent
Em 12 de fev de 2016 10:48, "极夜暗芒使" <notifications@github.com> escreveu:

**Comment by xxFlare** [comment]
@MrPowerGamerBR You should be using EntityDamageEvent, then using:

`if(event.getPlayer() instancof Player){`
`/execute code`

EntityDamageByEntityEvent is very buggy.

**Comment by MrPowerGamerBR** [comment]
But the same error happened to another person with the EntityDamageEvent,
anyway, I will test later with the EntityDamageEvent.
Em 12 de fev de 2016 10:54 AM, "xFlare" <notifications@github.com> escreveu:

**Comment by MagicDroidX** [comment]
The correct way is to listen to the EntityDamageEvent, then use `if(event instanceof EntityDamageByEntityEvent)`.
I'm going to check the EntityDamageEvent, and i wonder if we have other events that have this exception?

**Comment by gacus007** [comment]
So how get instance of  Damager from EntityDamageEvent?

**Comment by xxFlare** [comment]
@gacus007 

Use: `if(event.getDamager() instance of Player){`

**Comment by MagicDroidX** [comment]
@gacus007 
```
@EventHandler
public void onEntityDamage(EntityDamageEvent event){
if(event instanceof EntityDamageByEntityEvent){
Entity damager = ((EntityDamageByEntityEvent) event).getDamager();
}
}
```

**Comment by gacus007** [comment]
@MagicDroidX  thx a lot

**Comment by gacus007** [comment]
@MagicDroidX  Could you give me exmaple @eventhandler on player death event?

**Comment by gacus007** [comment]
@EventHandler(priority = EventPriority.HIGHEST)
    public void playerDeath(EntityDeathEvent event) {
		    if(event instanceof PlayerDeathEvent){
		    	PlayerDeathEvent en =(PlayerDeathEvent) event;
	
        if (en.getEntity().getKiller() instanceof Player && en.getEntity().getPlayer() !=null) {
        	 Player player =en.getEntity().getPlayer();
            Player killer= (Player)en.getEntity().getKiller() ;
}}}

Is it correct?

**Comment by xxFlare** [comment]
@gacus007 It's PlayerDeathEvent :3

**Comment by gacus007** [comment]
I know but I ask that is it correct solution to player death event :-) We are my master in nukkit plugins .

**Comment by fromgate** [comment]
@gacus007 
Use highest priority only when you really know why you need HIGHEST priority
@EventHandler(priority = EventPriority.HIGHEST)

Usually it's enough to use NORMAL priortity:
```
@EventHandler(priority = EventPriority.NORMAL)
public void onXXXEvent (XXXEvent event){...
````

If you need to skip cancelled events, you need to add to annotation "ignoreCancelled" parameter:
```
@EventHandler(ignoreCancelled=true, priority = EventPriority.NORMAL)
public void onXXXEvent (XXXEvent event){...
````
