### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#49]
Can do detailed instructions for obtaining nukkit.jar? Catch the buy going up I think it would be useful) Thanks!

Asked this question here because no one answers gitter(

**Comment by Snake1999** [comment]
Nukkit is still in developing, and didn't release its first version yet.

**Comment by Snake1999** [comment]
And take a better title next time, only a "Question" confuses others. :D

**Comment by Pub4Game** [comment]
Can step by step to explain? Preferably with screenshots

**Comment by Snake1999** [comment]
1.Jar can be downloaded from official website in the future.
2.If you want it now, use an IDE to compile by yourself.
:D

**Comment by Pub4Game** [comment]
I mean step by step to explain the compilation in the IDE

**Comment by Snake1999** [comment]
1.Install Java 8
turn to www.java.com

2.Install IDEA Community
turn to www.jetbrains.com/idea/

3.Configurate IDEA
Open IDEA,
VCS->Checkout from Version control->GitHub->set Repo URL to https://github.com/nukkit/nukkit.git ->Clone->....->New window->wait before maven download
File->Project Structure->Artifacts->"+"->JAR->From module with dependencies->set module to Nukkit->set Main Class to cn.nukkit.Nukkit ->OK
set Output Directory to where nukkit.jar be stored->click Build on Make->OK
Build->Make Project->have a cup of tea->done!

reply if you have any problem...i'd go sleep now

**Comment by Pub4Game** [comment]
Thank you)) good night

**Comment by Pub4Game** [comment]
@Snake1999 <3
![image](https://cloud.githubusercontent.com/assets/11244874/11276236/50b26336-8ef2-11e5-9002-f6c0656e505d.png)

Yay
