### ISSUE TITLE
All BlockEntities are not loading correctly.

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#492]
Not a client bug, Block Entities don't load correctly even though the client knows it's there. I think there is something wrong with the ChunkLoader.

**Comment by MagicDroidX** [comment]
I have generated a world with Minecraft 1.8 and put it into Nukkit. All Block Entities have been loaded successfully. I cannot reproduce this.

**Comment by xxFlare** [comment]
@MagicDroidX Can I give you a map you can test on?

**Comment by xxFlare** [comment]
@MagicDroidX 

The map I am using was converted to MCregion from Anvil. Maybe that's why?

**Comment by MagicDroidX** [comment]
Then it should be missed during converting

**Comment by xxFlare** [comment]
Though, it works on PocketMine. o.o

**Comment by xxFlare** [comment]
@MagicDroidX This commit fixed it! https://github.com/Nukkit/Nukkit/commit/cc7ad101cb29ce40cf8f004b5e1ad5a1d0be70a9

Good job! :+1:
