### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#496]
Hello!

I was working on my mini-game plugin; and I need to refill chests. This won't be an issue but there is no getTiles() API function. Would it be possible you guys can add it? Thanks.

**Comment by Snake1999** [comment]
First, Tile is renamed by mojang to Block Entity. And you should use: `level.getBlockEntity(Vector3 pos)` :D

**Comment by xxFlare** [comment]
I should use, getBlockEntities?

**Comment by Snake1999** [comment]
For now, use `getBlockEntity`. And remember to check if it `instanceof BlockEntitySign`.    
         
BTW, we are making an easier way to edit sign or do other thing, we are discussing it on gitter. Will add a bukkit-like api in the future.

**Comment by xxFlare** [comment]
@Snake1999 However, I need to get all tiles using a for loop to restock chests; not just a single tile.

Anything possible for that at this moment?

**Comment by MagicDroidX** [comment]
`getBlockEntities`
