### ISSUE TITLE
Players become "invisible" after being teleported 

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#499]
Teleport players to 2 locations, then teleport back to spawn, and they will not be able to see each other on their clients.

**Comment by Guillaume351** [comment]
Confirmed, same issue here :/

**Comment by ProjectInfinity** [comment]
This needs to be resolved. I can confirm that users are invisible until they try to move, then on the other player's screen they will be moved across the screen to the location they were teleported to.

**Comment by MagicDroidX** [comment]
I don't know how to reproduce. It works fine for me.

**Comment by ProjectInfinity** [comment]
You probably moved/turned on the client which fixes the issue, but unless that person moves or looks around it will not show that they were moved.

For instance, I made a gamemode plugin for Nukkit. When users are teleported to the arena the users will have their movement frozen for a number of seconds while it counts down to match start. If the player remains still and does not touch their device, they will remain invisible and show standing where they used to be prior to being teleported. I can confirm this happening every single time with no exceptions.

**Comment by MagicDroidX** [comment]
Both my WIN10E and PE were not being operated when I type the `teleport` command.
The command seems to be fine.

**Comment by MagicDroidX** [comment]
@ProjectInfinity Which teleport method are you using?

**Comment by ProjectInfinity** [comment]
@MagicDroidX I tried both .teleport() and .teleportImmediate(). Both with the same results.

**Comment by MagicDroidX** [comment]
@ProjectInfinity And what are the arguments?

**Comment by ProjectInfinity** [comment]
@MagicDroidX Location is passed to the teleportation method.

**Comment by MagicDroidX** [comment]
@ProjectInfinity I see, I will check it tomorrow. :)

**Comment by MagicDroidX** [comment]
@ProjectInfinity I've reproduced the issue by using `teleportImmediate` but `teleport` works well.

**Comment by ProjectInfinity** [comment]
@MagicDroidX The issue occurs with both teleportImmediate and teleport. If you do what I described further above, it happens every single time.
