### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#5]
Hi i think your project is good because it is almost rewrited pocketmine to JAVA and java is better than php and pocketmine is good too (just laggy) so in java it would be great! so how can i contribute, because i don't know what should i do. I think, i know pocketmine API well.

**Comment by MagicDroidX** [comment]
You can fork our project and write something you want to contribute, and then just open a pull request! :D

**Comment by Creeperface01** [comment]
Ok so i can do anything?

**Comment by Creeperface01** [comment]
And how Compound works? Java has not array_acces like PHP

**Comment by 2300206764** [comment]
Don't worry。Everything will be better.(^_^)

**Comment by MagicDroidX** [comment]
In my opinion, shoghicp's purpose is to make NBT much easier to read and write just like yaml, which enables developers to use array to read and write NBT, but it become much harder because NBT requires a very clear type of variable.

**Comment by Creeperface01** [comment]
Can i add handleDataPacket? (some of them)  i translated LoginPacket for now

**Comment by MagicDroidX** [comment]
Of course you can!

**Comment by Creeperface01** [comment]
Ok :) for 0.12.1 right?

**Comment by MagicDroidX** [comment]
Yea!

**Comment by Snake1999** [comment]
Good job! and i will write best multi-language javadoc for your work :P @Creeperface01

**Comment by boybook** [comment]
Wa Hahahaha
