### ISSUE TITLE
Error:(152, 51) java: -source 1.6 中不支持 diamond 运算符

### ISSUE THREAD

**Issue by dbaflight** [Nukkit/Nukkit#50]
IDEA 提示如下错误Error:(152, 51) java: -source 1.6 中不支持 diamond 运算符
  (请使用 -source 7 或更高版本以启用 diamond 运算符)

server.java

**Comment by Snake1999** [comment]
You should use Java8 instead of 6.
还用Java6啊，是时候升到8了

**Comment by Snake1999** [comment]
不过IDEA的话，File，Project Structure，有个Project Language还是啥的，下拉列表选Java8-lambdas,...
