### ISSUE TITLE
Lag and errors

### ISSUE THREAD

**Issue by gacus007** [Nukkit/Nukkit#504]
Hi
Today I opened server for player , server was full 35/35 and after some time players said that it is a lot of lags,some errors:
1.2016-2-14 12:18:33 [ALERT] java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
    at cn.nukkit.Server.tick(Server.java:955)
    at cn.nukkit.Server.tickProcessor(Server.java:756)
    at cn.nukkit.Server.start(Server.java:736)
    at cn.nukkit.Server.<init>(Server.java:440)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
2. Players said that their item from inventory disappeared sometimes
3.It is a lot of warnings: [WARNING] player 10 moved incorrectly!
My server: Linux Debian 8,RAM 2GB
Some tips for no lags and disappeared items?

**Comment by xxFlare** [comment]
@gacus007 How much memory? Home hosted, VPS, dedicated server?

**Comment by gacus007** [comment]
@xxFlare 
2GB,VPS from DigitalOcean

**Comment by Snake1999** [comment]
Thread-safety problem... Trying to fix

**Comment by xxFlare** [comment]
@gacus007 Ah, in that case there probably is a memory leak. Though first we need to fix the bug.

**Comment by gacus007** [comment]
@xxFlare 
Thx a lot so I waiting for patch

**Comment by ProjectInfinity** [comment]
@gacus007 what's your startup options? And lag with 35/35 is very normal, Nukkit isn't ready to be used on production servers.

**Comment by gacus007** [comment]
java -Xmx 2G -jar nukkit.jar

**Comment by ProjectInfinity** [comment]
I don't see anything inhertently wrong about that. What kind of CPU are you sporting and how many cores? If memories serve me right that should be 2 cores (unknown clock speed or generation) and that's not very good. Combine that with Nukkit being incomplete and you got yourself lag. Also, are you running any plugins?

**Comment by gacus007** [comment]
Third option from top :https://www.digitalocean.com/pricing/    
I've got 4 plugins ,all plugins is base on files txt
Do you recommend dedicated server?

**Comment by gacus007** [comment]
What means errors above and  player move incorrectly?

**Comment by ProjectInfinity** [comment]
Player move incorrectly could be a lot of things, including lag. However
the concurrent modification exception sounds like a mistake was made in one
of the later commits. I recall something about slots being changed just
recently.

**Comment by gacus007** [comment]
Could you  speak about it authors plugin?

**Comment by MrPowerGamerBR** [comment]
The move incorrectly is a bit broken, even a "touch" in a player causes a move incorrectly warning (because of the damage knockback).

For the ConcurrentModificationException, the error you shown doesn't show what plugin causes this, so... yeah.
