### ISSUE TITLE
Why is getNested() depreciated?

### ISSUE THREAD

**Issue by AndreyNazarchuk** [Nukkit/Nukkit#509]
Why is getNested() depreciated? it was really useful!

**Comment by MrPowerGamerBR** [comment]
Because you just need to use "getString/Integer/Whatever" to get values from config, even a nested one.

In my opinion it is way better now.

**Comment by AndreyNazarchuk** [comment]
What is the protocol for getting a nested string? getString("1"+"2")?

**Comment by MrPowerGamerBR** [comment]
@AndreyNazarchuk  getString("user.toriel.stats")

(It is just a example)

**Comment by AndreyNazarchuk** [comment]
Would that get 19374 in this case?
User:
  toriel:
    stats: 19374

**Comment by MrPowerGamerBR** [comment]
@AndreyNazarchuk exactly! (Also, use getInteger() if you are going to get a Integer)

**Comment by AndreyNazarchuk** [comment]
Great thanks!
