### ISSUE TITLE
MCPE 0.14.0 ?

### ISSUE THREAD

**Issue by Nidish** [Nukkit/Nukkit#515]
IS there a jar file for this version?

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/issues/411

Compiled version (if someone need it) located here: https://github.com/fromgate/Nukkit/releases/tag/0.0.1-test-0.14.0

**Comment by fromgate** [comment]
FIrst nukkit (official) build for 0.14.0 released: http://ci.mengcraft.com:8080/job/nukkit/196/
