### ISSUE TITLE
Duplication of items when close() entity

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#516]
![image](https://cloud.githubusercontent.com/assets/11244874/13183998/821fda84-d74a-11e5-9b87-5345319f52e8.png)

I don't know why it happens, but this is not the first time.

**Comment by ProjectInfinity** [comment]
Have you tried iterating them and outputting the class name to see what kind of entity it is?

**Comment by Pub4Game** [comment]
@ProjectInfinity no

**Comment by ProjectInfinity** [comment]
Then perhaps you should. :P

**Comment by xxFlare** [comment]
@Pub4Game Your server up time says 2 says... It's actually recommended to restart servers once every hour or two.

**Comment by MrPowerGamerBR** [comment]
@xxFlare every hour? I know that Nukkit is unstable, but restarting the server every 1 hour is a bit overkill, isn't it?

**Comment by Snake1999** [comment]
Use **/gc** instead of restarting whole kernel. Nukkit is not build to make you restart your server and kick all players out while playing.

**Comment by Pub4Game** [comment]
Okay :3
