### ISSUE TITLE
chunks don't load

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#519]
in 0.14 chunks don't load properly

**Comment by MagicDroidX** [comment]
Confirmed. This may be caused by the hack.

**Comment by beetree** [comment]
This is a major issue. PocketMine also has the issue. Would be really really awesome if you can fix this!

**Comment by beetree** [comment]
To reproduce, start a new server, then fly straight north for like 20 chunks, then back straight south.

**Comment by 64FF00** [comment]
O.O

**Comment by Guillaume351** [comment]
Same problem here. Maybe it's a client issue, since 0.14 update..

**Comment by DarrellJMartin** [comment]
repro'd too

**Comment by onebone** [comment]
Same on teleportation.

**Comment by MrPowerGamerBR** [comment]
I'm not sure if this is a 0.14.0 specific issue, because I had the same problem in 0.13.1, sometimes a chunk wouldn't load at all, relogging would fix the issue.

**Comment by Snake1999** [comment]
Confirmed

**Comment by Pub4Game** [comment]
@Snake1999 Pay attention to the new packages https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/network/protocol/Info.php#L92-#L93
