### ISSUE TITLE
ITALIAN LANGUAGE FOR NUKKIT SERVER 

### ISSUE THREAD

**Issue by robozeri** [Nukkit/Nukkit#52]
Language translated by Robozeri & Alex11
# Language file compatible with Minecraft: Pocket Edition identifiers
#
# A message doesn't need to be there to be shown correctly on the client.
# Only messages shown in Nukkit itself need to be here
# Using the language property from PocketMine-MP

language.name=Italiano
language.selected=Seleziona {%0} ({%1}) come la lingua di base

multiplayer.player.joined={%0} è entrato in gioco
multiplayer.player.left={%0} ha lasciato il gioco

chat.type.text=<{%0}> {%1}
chat.type.emote=* {%0} {%1}
chat.type.announcement=[{%0}] {%1}
chat.type.admin=[{%0}: {%1}]
chat.type.achievement={%0} ha conquistato l'obbiettivo {%1}

disconnectionScreen.outdatedClient=Client Obsoleto!
disconnectionScreen.outdatedServer=Server Obsoleto!
disconnectionScreen.serverFull= Il Server è pieno!
disconnectionScreen.noReason=Disconesso dal server
disconnectionScreen.invalidSkin=Skin non valida!
disconnectionScreen.invalidName=Nome non valido!

death.fell.accident.generic={%0} si è schiantato al suolo
death.attack.inFire={%0} è andato in fiamme
death.attack.onFire={%0} è bruciato a morte
death.attack.lava={%0} ha provato a nuotare nella lava
death.attack.inWall={%0} è soffocato in un muro
death.attack.drown={%0} è annegato
death.attack.cactus={%0} è stato bucato a morte
death.attack.generic={%0} è morto
death.attack.explosion={%0} è esploso
death.attack.explosion.player={%0} è stato fatto esplodere da {%1}
death.attack.magic={%0} è stato ucciso dalla magia
death.attack.wither={%0} è stato witherato
death.attack.mob={%0} è stato ucciso da {%1}
death.attack.player={%0} è stato ucciso da {%1}
death.attack.player.item={%0} è stato ucciso da {%1} usando {%2}
death.attack.arrow={%0} è stato trafitto da {%1}
death.attack.arrow.item={%0} è stato trafitto da {%1} usando {%2}
death.attack.fall={%0} si è spiaccicato al suolo
death.attack.outOfWorld={%0} è caduto fuori dal mondo

gameMode.survival=Survival Mode
gameMode.creative=Creative Mode
gameMode.adventure=Adventure Mode
gameMode.spectator=Spectator Mode
gameMode.changed=La tua modalità è stata aggiornata

potion.moveSpeed=Speed
potion.moveSlowdown=Slowness
potion.digSpeed=Haste
potion.digSlowDown=Mining Fatigue
potion.damageBoost=Strength
potion.heal=Instant Health
potion.harm=Instant Damage
potion.jump=Jump Boost
potion.confusion=Nausea
potion.regeneration=Regeneration
potion.resistance=Resistance
potion.fireResistance=Fire Resistance
potion.waterBreathing=Water Breathing
potion.invisibility=Invisibility
potion.blindness=Blindness
potion.nightVision=Night Vision
potion.hunger=Hunger
potion.weakness=Weakness
potion.poison=Poison
potion.wither=Wither
potion.healthBoost=Health Boost
potion.absorption=Absorption
potion.saturation=Saturation

commands.generic.exception=C'è stato un errore dovuto a questo comando
commands.generic.permission=Non hai i permessi per usare questo comando
commands.generic.notFound=Comando sconosciuto. Prova /help per la lista dei comandi
commands.generic.player.notFound=Questo giocatore non è stato trovato
commands.generic.usage=Usage: {%0}

commands.time.added=Aggiunto {%0} al tempo
commands.time.set=Il tempo è stato settato a {%0}
commands.time.query=Il tempo è {%0}

commands.me.usage=/me <action ...>

commands.give.item.notFound=Non esiste un item con questo nome{%0}
commands.give.success=Dato {%0} * {%1} a {%2}
commands.give.tagError=Tag di dati di analisi non è riuscita: {%0}

commands.effect.usage=/effect <player> <effect> [seconds] [amplifier] [hideParticles] OR /effect <player> clear
commands.effect.notFound=Non c'è nessun effetto con questo ID {%0}
commands.effect.success=Dato {%0} (ID {%1}) * {%2} a {%3} per {%4} secondi
commands.effect.success.removed=Rimosso l'effetto {%0} da {%1}
commands.effect.success.removed.all=Rimossi tutti gli effetti da {%0}
commands.effect.failure.notActive=Non posso dare l'effetto {%0} da {%1} in quanto essi non hanno un effetto
commands.effect.failure.notActive.all=Non posso dare alcun effetto da {%0} in quanto loro non ne hanno.

commands.enchant.noItem=The target doesn't hold an item
commands.enchant.notFound=There is no such enchantment with ID {%0}
commands.enchant.success=Enchanting succeeded
commands.enchant.usage=/enchant <player> <enchantment ID> [level]
commands.particle.success=Playing effect {%0} for {%1} times
commands.particle.notFound=Unknown effect name {%0}
commands.players.usage=/list
commands.players.list=Ci sono {%0}/{%1} giocatori online:
commands.kill.successful=Ha killato {%0}
commands.banlist.ips=Ci sono {%0} indirizzi ip bannati:
commands.banlist.players=Ci sono {%0} player bannati totali:
commands.banlist.usage=/banlist [ips|players]
commands.defaultgamemode.usage=/defaultgamemode <mode>
commands.defaultgamemode.success=La gamemode del mondo in questo momento è {%0}

commands.op.success={%0} è ora un operatore
commands.op.usage=/op <player>

commands.deop.success={%0} non è più un operatore
commands.deop.usage=/deop <player>

commands.say.usage=/say <message ...>

commands.seed.usage=/seed
commands.seed.success=Seed: {%0}

commands.ban.success= {%0} è stato bannato
commands.ban.usage=/ban <name> [motivazioni ...]

commands.unban.success= {%0} è stato sbannato
commands.unban.usage=/pardon <name>

commands.banip.invalid=Hai immesso un indirizzo IP errato oppure di un giocatore offline
commands.banip.offline.invalid=Non vi è alcun indirizzo IP nei dati del giocatore o l'indirizzo IP non è valido
commands.banip.success=L'indirizzo ip {%0} è stato bannato
commands.banip.success.players=L'indirizzo IP bannato {%0} appartiene a {%1}
commands.banip.usage=/ban-ip <address|name> [motivazioni ...]

commands.unbanip.invalid=Hai immesso un indirizzo IP errato
commands.unbanip.success=L'indirizzo IP {%0} è stato sbannato
commands.unbanip.usage=/pardon-ip <address>

commands.save.usage=/save-all
commands.save-on.usage=/save-on
commands.save-off.usage=/save-off
commands.save.enabled= È stato attivato l'auto-salvataggio del mondo
commands.save.disabled=È stato disattivato l'auto-salvataggio del mondo
commands.save.start=Salvataggio...
commands.save.success=Il mondo è stato salvato

commands.stop.usage=/stop
commands.stop.start=Sto stoppando il server

commands.kick.success={%0} è stato cacciato dal gioco
commands.kick.success.reason= {%0}è stato cacciato dal gioco, motivazione : '{%1}'
commands.kick.usage=/kick <player> [motivazione ...]

commands.tp.success={%0} è stato teletrasportato da {%1}
commands.tp.success.coordinates= {%0} è stato teletrasportato a {%1}, {%2}, {%3}
commands.tp.usage=/tp [inserisci giocatore] <giocatore di destinazione> oppure /tp [inserisci giocatore] <x> <y> <z> [<y-rot> <x-rot>]

commands.whitelist.list=Ci sono {%0} (fuori dalla lista {%1} ) nella lista bianca:
commands.whitelist.enabled=è stata attivata la lista bianca
commands.whitelist.disabled=è stata disattivata la lista bianca
commands.whitelist.reloaded=è stata ricaricata la lista bianca
commands.whitelist.add.success={%0} è stato aggiunto alla lista bianca
commands.whitelist.add.usage=/whitelist add <player>
commands.whitelist.remove.success={%0} è stato rimosso dalla lista bianca
commands.whitelist.remove.usage=/whitelist remove <player>
commands.whitelist.usage=/whitelist <on|off|list|add|remove|reload>

commands.gamemode.success.self=è stata settata la modalita a {%0}
commands.gamemode.success.other=la modalita di gioco di {%0} è stata settata a {%1}
commands.gamemode.usage=/gamemode <mode> [player]
commands.help.header=--- mostra la help page {%0} di {%1} (/help <page>) ---
commands.help.usage=/help [page|command name]
commands.message.usage=/tell <player> <messaggio privato ...>
commands.message.sameTarget=Non puoi mandare un messaggio privato a te stesso!

commands.difficulty.usage=/difficulty <new difficulty>
commands.difficulty.success=è stata settata la difficolta a {%0}

commands.spawnpoint.usage=/spawnpoint [player] [<x> <y> <z>]
commands.spawnpoint.success=è stato settato lo spawn point di {%0} a ({%1}, {%2}, {%3})
commands.setworldspawn.usage=/setworldspawn [<x> <y> <z>]
commands.setworldspawn.success=è stato settato lo spawn point del mondo a ({%0}, {%1}, {%2})
# -------------------- Nukkit language files, only for console --------------------
nukkit.data.playerNotFound=Player data not found for "{%0}", creating new profile
nukkit.data.playerCorrupted=Corrupted data found for "{%0}", creating new profile
nukkit.data.playerOld=Old Player data found for "{%0}", upgrading profile
nukkit.data.saveError=Could not save player "{%0}": {%1}
nukkit.level.notFound=Level "{%0}" not found
nukkit.level.loadError=Could not load level "{%0}": {%1}
nukkit.level.generationError=Could not generate level "{%0}": {%1}
nukkit.level.tickError=Could not tick level "{%0}": {%1}
nukkit.level.chunkUnloadError=Error while unloading a chunk: {%0}
nukkit.level.backgroundGeneration=Questo terreno "{%0}" è stato generato in background
nukkit.level.defaultError=Il livello non default è stato caricato
nukkit.level.preparing=Preparing level "{%0}"
nukkit.level.unloading=Unloading level "{%0}"
nukkit.server.start=Starting Minecraft: PE server version {%0}
nukkit.server.networkError=[Network] Stopped interface {%0} due to {%1}
nukkit.server.networkStart=Opening server on {%0}:{%1}
nukkit.server.info=This server is running {%0} version {%1} "{%2}" (API {%3})
nukkit.server.info.extended=This server is running {%0} {%1} 「{%2}」 implementing API version {%3} for Minecraft: PE {%4} (protocol version {%5})
nukkit.server.license={%0} è stato distibuito sotto la licenza LGPL 
nukkit.server.tickOverload=Il server è in sovraccarico?
nukkit.server.startFinished=Done ({%0}s)! For help, type "help" or "?"
nukkit.server.defaultGameMode=Default game type: {%0}
nukkit.server.query.start=Starting GS4 status listener
nukkit.server.query.info=è stata settata la porta query {%0}
nukkit.server.query.running=Query è settato alla porta {%0}:{%1}

nukkit.command.alias.illegal=Could not register alias {%0} because it contains illegal characters
nukkit.command.alias.notFound=Could not register alias {%0} because it contains commands that do not exist: {%1}
nukkit.command.exception=Unhandled exception executing command '{%0}' in {%1}: {%2}

nukkit.command.plugins.description=Gets a list of plugins running on the server
nukkit.command.plugins.success=Plugins ({%0}): {%1}
nukkit.command.plugins.usage=/plugins

nukkit.command.reload.description=Reloads the server configuration and plugins
nukkit.command.reload.usage=/reload
nukkit.command.reload.reloading=Reloading server...
nukkit.command.reload.reloaded=Reload complete.

nukkit.command.status.description=Reads back the server's performance.
nukkit.command.status.usage=/status
nukkit.command.gc.description=Fires garbage collection tasks
nukkit.command.gc.usage=/gc
nukkit.command.timings.description=Records timings to see performance of the server.
nukkit.command.timings.usage=/timings <reset|report|on|off|paste>
nukkit.command.timings.enable=Enabled Timings & Reset
nukkit.command.timings.disable=Disabled Timings
nukkit.command.timings.timingsDisabled=Please enable timings by typing /timings on
nukkit.command.timings.reset=Timings reset
nukkit.command.timings.pasteError=An error happened while pasting the report
nukkit.command.timings.timingsUpload=Timings uploaded to {%0}
nukkit.command.timings.timingsRead=You can read the results at {%0}
nukkit.command.timings.timingsWrite=Timings written to {%0}
nukkit.command.version.description=Gets the version of this server including any plugins in use
nukkit.command.version.usage=/version [plugin name]
nukkit.command.version.noSuchPlugin=This server is not running any plugin by that name. Use /plugins to get a list of plugins.
nukkit.command.give.description=Gives the specified player a certain amount of items
nukkit.command.give.usage=/give <player> <item[:damage]> [amount] [tags...]
nukkit.command.kill.description=Commit suicide or kill other players
nukkit.command.kill.usage=/kill [player]
nukkit.command.particle.description=Adds particles to a world
nukkit.command.particle.usage=/particle <name> <x> <y> <z> <xd> <yd> <zd> [count] [data]
nukkit.command.time.description=Changes the time on each world
nukkit.command.time.usage=/time <set|add> <value> OR /time <start|stop|query>
nukkit.command.ban.player.description=Prevents the specified player from using this server
nukkit.command.ban.ip.description=Prevents the specified IP address from using this server
nukkit.command.banlist.description=View all players banned from this server
nukkit.command.defaultgamemode.description=Set the default gamemode
nukkit.command.deop.description=Takes the specified player's operator status
nukkit.command.difficulty.description=Sets the game difficulty
nukkit.command.enchant.description=Adds enchantments on items
nukkit.command.effect.description=Adds/Removes effects on players
nukkit.command.gamemode.description=Changes the player to a specific game mode
nukkit.command.help.description=Shows the help menu
nukkit.command.kick.description=Removes the specified player from the server
nukkit.command.list.description=Lists all online players
nukkit.command.me.description=Performs the specified action in chat
nukkit.command.op.description=Gives the specified player operator status
nukkit.command.unban.player.description=Allows the specified player to use this server
nukkit.command.unban.ip.description=Allows the specified IP address to use this server
nukkit.command.save.description=Saves the server to disk
nukkit.command.saveoff.description=Disables server autosaving
nukkit.command.saveon.description=Enables server autosaving
nukkit.command.say.description=Broadcasts the given message as the sender
nukkit.command.seed.description=Shows the world seed
nukkit.command.setworldspawn.description=Sets a worlds's spawn point. If no coordinates are specified, the player's coordinates will be used.
nukkit.command.spawnpoint.description=Sets a player's spawn point
nukkit.command.stop.description=Stops the server
nukkit.command.tp.description=Teleports the given player (or yourself) to another player or coordinates
nukkit.command.tell.description=Sends a private message to the given player
nukkit.command.whitelist.description=Manages the list of players allowed to use this server
nukkit.crash.create=An unrecoverable error has occurred and the server has crashed. Creating a crash dump
nukkit.crash.error=Could not create crash dump: {%0}
nukkit.crash.submit=Please upload the "{%0}" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
nukkit.crash.archive=The crash dump has been automatically submitted to the Crash Archive. You can view it on {%0} or use the ID #{%1}.
nukkit.debug.enable=LevelDB support enabled
nukkit.player.invalidMove={%0} moved wrongly!
nukkit.player.logIn={%0}[/{%1}:{%2}] logged in with entity id {%3} at ({%4}, {%5}, {%6}, {%7})
nukkit.player.logOut={%0}[/{%1}:{%2}] logged out due to {%3}
nukkit.player.invalidEntity={%0} tried to attack an invalid entity
nukkit.plugin.load=Loading {%0}
nukkit.plugin.enable=Enabling {%0}
nukkit.plugin.disable=Disabling {%0}
nukkit.plugin.restrictedName=Restricted name
nukkit.plugin.incompatibleAPI=Incompatible API version
nukkit.plugin.unknownDependency=Unknown dependency
nukkit.plugin.circularDependency=Circular dependency detected
nukkit.plugin.genericLoadError=Could not load plugin '{%0}'
nukkit.plugin.spacesDiscouraged=Plugin '{%0}' uses spaces in its name, this is discouraged
nukkit.plugin.loadError=Could not load plugin '{%0}': {%1}
nukkit.plugin.duplicateError=Could not load plugin '{%0}': plugin exists
nukkit.plugin.fileError=Could not load '{%0}' in folder '{%1}': {%2}
nukkit.plugin.commandError=Could not load command {%0} for plugin {%1}
nukkit.plugin.aliasError=Could not load alias {%0} for plugin {%1}
nukkit.plugin.deprecatedEvent=Plugin '{%0}' has registered a listener for '{%1}' on method '{%2}', but the event is Deprecated.
nukkit.plugin.eventError="Could not pass event '{%0}' to '{%1}': {%2} on {%3}

**Comment by Snake1999** [comment]
Awesome! and please help us in Nukkit/Multi-language next time.

**Comment by robozeri** [comment]
ok I like your project are very good at Java I'd like to program something
Il giorno 20/nov/2015 14:26, "Peter Jiang" <notifications@github.com> ha
scritto:

**Comment by robozeri** [comment]
hello you send me the jar files can not fill me from mistakes

**Comment by AryToNeX** [comment]
Some translated strings are missing. If you want to correctly translate nukkit please complete all the strings

Anyway good work

**Comment by robozeri** [comment]
ma okaka
Il giorno 24/nov/2015 13:32, "Anthony" <notifications@github.com> ha
scritto:

**Comment by MagicDroidX** [comment]
Would you please open pull request directly in Nukkit/Multi-language? :D
