### ISSUE TITLE
Golden Apples working only once

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#525]
When I eat a Golden Apple, I get Resistance and regeneration.
If later I eat an other one, I get nothing.
Lastest build.
(Sometime, they do not work at all even on first try ; I receive only absorption (and even if I get the effect, no extra hearts showing)

**Comment by Snake1999** [comment]
Confirmed the first. This is a problem that, after new effect with same id but longer time applied to an entity(a player), the old effect won't be replaced. This won't happen if old one disappeared after time got 0:00.
For absorption , I can't reproduce. Try use /effect command to give effect and find out if there is effect or not.
