### ISSUE TITLE
Chests in 0.14.0

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#527]
Hello! I rewrite my BedWars for Nukkit, and for 0.14.0. I have one problem - in 0.14.0 chest can't be opened by server, only by client. But, in 0.13.1 it working. It is MCPE bug, or Container Packets hasn't updated in Nukkit(I has that problem with PocketMine 0.14.0).

**Comment by MagicDroidX** [comment]
You mean, send a packet to the client to make the chest looks like being opened?

**Comment by MrGenga** [comment]
Yep

**Comment by MrGenga** [comment]
Chest look like it open, but window not showing

**Comment by MrGenga** [comment]
I open inv by tap on Villager, and it not working. But normal chest works awesome

**Comment by MagicDroidX** [comment]
Duplicate with #529
