### ISSUE TITLE
High load when join to server.

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#532]
![image](https://cloud.githubusercontent.com/assets/6584811/13251354/83ccce50-da51-11e5-9e2c-011b8d5196dc.png)
![image](https://cloud.githubusercontent.com/assets/6584811/13251371/9df457a8-da51-11e5-8b82-dc115bacb524.png)

And you can't join to server. ;c

**Comment by Guillaume351** [comment]
Is it generating the world or it's not the first time you join ?

**Comment by Pub4Game** [comment]
@Guillaume351 No, that map was made long time ago
