### ISSUE TITLE
Chests

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#550]
Hi! I have one more problem: in 0.14.0 was added distance checker on ContainerOpenPacket, I have idea for fix it, create new chest near player, but new chests opens only after death. How to fix bug(in plugin) with chest & death?

**Comment by MrGenga** [comment]
P. S. My friend create BedWars on MiNET using this algorithm, but he don't have this problem

**Comment by MagicDroidX** [comment]
I have placed a chest near me and open it.
Everything works fine.

**Comment by MrGenga** [comment]
No, I say about addWindow method

**Comment by MagicDroidX** [comment]
I cannot understand :(

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX if I understand correctly, he wants to open a chest to a player with a plugin, however, due to the new check on 0.14.0, you can't open a chest with a plugin if the chest is not near the player.

**Comment by MagicDroidX** [comment]
Then I am afraid that it is not a nukkit issue.

**Comment by Tee7even** [comment]
Should be closed too.

**Comment by Snake1999** [comment]
Maybe your plugin caused this.
