### ISSUE TITLE
Populator not generating trees for certain biomes

### ISSUE THREAD

**Issue by Niall7459** [Nukkit/Nukkit#557]
I have generated a new world with the latest build as of yesterday, and I noticed that trees were only generated in a certain biome, I am not that good with minecraft and do not know which biomes they were but it is quite annoying.

Good work on this, A lot more stable and faster than pocket mine

It runs at 5% cpu on my Raspberry Pi

**Comment by MagicDroidX** [comment]
We are working on a new generator. It's definitely hard and the progress is pretty slow. :)

**Comment by Niall7459** [comment]
Whoops, I just added a pull request to add lots more features.

I will be happy to help out with making the new generator.

**Comment by PeratX** [comment]
If you view the Populators and you will know. Check out the new generators.
