### ISSUE TITLE
Bug with water

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#565]
![image](https://cloud.githubusercontent.com/assets/11244874/13546548/115b903a-e2c2-11e5-8615-127e4d6f98c8.png)

Water cannot flow properly...

**Comment by MagicDroidX** [comment]
What have you done?

**Comment by Pub4Game** [comment]
Ahah))) Try to take one unit of water bucket, it needs to become a back water, but it is not happening
