### ISSUE TITLE
Nope desired function

### ISSUE THREAD

**Issue by Varfalomey** [Nukkit/Nukkit#568]
no functions
p.getInventory().getItemInHand()
and
p.getInventory().setItemInHand()

how use ?

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/13564630/1b79a3a4-e45c-11e5-8383-03824a1f23be.png)

**Comment by Varfalomey** [comment]
![Image alt](http://cs633222.vk.me/v633222835/1a2b5/OhZzQmWMQkY.jpg)
![Image alt](http://cs633222.vk.me/v633222835/1a2bd/4orLMRxdQp8.jpg)

**Comment by Varfalomey** [comment]
I go UPDATED

**Comment by Varfalomey** [comment]
fixed, close :)
