### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#570]
1) Bug with boat 
![image](https://cloud.githubusercontent.com/assets/11244874/13567401/25dd5c36-e46c-11e5-934c-2de8ded2daf4.png)
2) [Bug with the table of enchantments](https://youtu.be/mq5OoDcmXYs)
3)Items in creative can be broken. You can play using a hoe (But they are not removed from the cell)

**Comment by shanwer** [comment]
For the bug (2)
You only can use /enchantment to enchantment.
