### ISSUE TITLE
hasPlayedBefore() should be false on PlayerJoinEvent and PlayerLoginEvent on first join, not true

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#573]
```
	@EventHandler
	public void onJoin(PlayerJoinEvent e) {
		if (!e.getPlayer().hasPlayedBefore()) {
			System.out.println(e.getPlayer().getName() + " never played before." + e.getEventName());
		
			e.getPlayer().getInventory().addItem(new Item(1));
		}
	}
	
	@EventHandler
	public void onPreLogin(PlayerPreLoginEvent e) {
		if (!e.getPlayer().hasPlayedBefore()) {
			System.out.println(e.getPlayer().getName() + " never played before. " + e.getEventName());
			
			e.getPlayer().getInventory().addItem(new Item(1));
		}
	}
	
	@EventHandler
	public void onLogin(PlayerLoginEvent e) {
		if (!e.getPlayer().hasPlayedBefore()) {
			System.out.println(e.getPlayer().getName() + " never played before. " + e.getEventName());
			
			e.getPlayer().getInventory().addItem(new Item(1));
		}
	}
```
This code only triggers the `PlayerPreLoginEvent` instead of triggering the three events.

On Bukkit, when a player first joins, the hasPlayedBefore() returns `false` instead of `true` (which is, in my opinion, better) in the `PlayerJoinEvent`.

Maybe that's the intended purpose, but I think hasPlayedBefore() in `PlayerJoinEvent `and `PlayerLoginEvent` SHOULD return `false` when the player joins the server for the first time, NOT `true` (after all, "has *player* played before? no.", it makes no sense to just return `false` in the `PlayerPreLoginEvent` and return `true` in the other 2 events)

**Comment by xpyctum** [comment]
+
