### ISSUE TITLE
Error with crafting (Windows 10)

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#576]
![image](https://cloud.githubusercontent.com/assets/11244874/13603235/c3b23ea0-e54c-11e5-998b-f948463df431.png)

```
[ALERT] java.lang.ArrayIndexOutOfBoundsException: 0
    at cn.nukkit.Player.handleDataPacket(Player.java:2672)
    at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
    at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
    at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
    at cn.nukkit.network.Network.processInterfaces(Network.java:73)
    at cn.nukkit.Server.tick(Server.java:961)
    at cn.nukkit.Server.tickProcessor(Server.java:768)
    at cn.nukkit.Server.start(Server.java:748)
    at cn.nukkit.Server.<init>(Server.java:445)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)

[DEBUG] Packet cn.nukkit.network.protocol.CraftingEventPacket 0x8EBB0000000001FCB5B0D1A9D93F55BBF743FD08DB1DA3000000000000000100050400000000
```

**Comment by xpyctum** [comment]
Wow :D 
strange that I have not tried to do

**Comment by Pub4Game** [comment]
fixed #579

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/13858883/a81c0ab2-ec91-11e5-91f8-4ff2633844d7.png)


![image](https://cloud.githubusercontent.com/assets/11244874/13858894/b2a76a8a-ec91-11e5-8fa2-acaec43c3a8b.png)


Bug with craft in inventory

**Comment by MagicDroidX** [comment]
I've captured the CraftEventPacket both on PE and WIN10E and found that WIN10E never send what was being used to craft.
I am going to say that this might be a client-side issue.
The only way to fix is to ignore input items which will definitely make the server unsafe.

**Comment by Tee7even** [comment]
Needs to be discussed with devs themselves, if there's any possibility to do it.

**Comment by kkzhang** [comment]
Same problem with WIN10 edition.

**Comment by stayandwait** [comment]
I really hope they fix this

**Comment by MagicDroidX** [comment]
This is a client-side issue.
2016年5月18日 上午8:15，"stayandwait" <notifications@github.com>写道：

**Comment by stayandwait** [comment]
I know, I read the conversation above

**Comment by Snake1999** [comment]
Such a bad win10 (even without an official bug tracker) :/

**Comment by stayandwait** [comment]
@Snake1999 How's this for official? http://bugs.mojang.com/browse/MCPE The bugs reported there are for BOTH editions.

**Comment by stayandwait** [comment]
@Snake1999 and look who closes the issue without a logical explanation.

**Comment by imjack** [comment]
A possible "fix" would be to just check if the player contains the items needed to make the item?

**Comment by JackboyPlay** [comment]
@imjack thats a really nice idea ^^

**Comment by Creeperface01** [comment]
and realms are unsafe?

**Comment by animator013** [comment]
Have the same problem. Without crafting it is unplayable :)

**Comment by Creeperface01** [comment]
yes it is

**Comment by animator013** [comment]
This is fully working in Genisys PHP7 server. Maybe some inspiration from them will make things easier.

**Comment by Creeperface01** [comment]
its easy... we must check all craft recipes with this output and check if player has all required items to craft

**Comment by Pub4Game** [comment]
Need test. https://github.com/Nukkit/Nukkit/pull/1033

**Comment by raulgbcr** [comment]
Same problem. Compiled last version. @Pub4Game 

https://gyazo.com/2b053e257953cf31ba6be90937cfd04f

**Comment by stayandwait** [comment]
It was said that you fixed crafting in 438
http://ci.mengcraft.com:8080/job/nukkit/438/
I'm still not able to permanently keep the workbench I had just crafted. The wooden planks I used to make the workbench also turn back into logs when reopening my inventory.

**Comment by Creeperface01** [comment]
IT was fixed in #1040

**Comment by Pub4Game** [comment]
Nope. Workbench don't fized

**Comment by File14** [comment]
:0

**Comment by stayandwait** [comment]
It works now! :)

**Comment by stayandwait** [comment]
However, crafting sticks still does the same thing. My sticks once crafted turn back into wood again.

**Comment by Creeperface01** [comment]
Yes its strange

**Comment by animator013** [comment]
Partially working. When I craft it at least crafts wood to planks. But if I move the wood from my hand, wood stays there and also in crafting space. It gets cloned. Also after crafting I have 8 planks from 1 wood because of the strange cloning.

**Comment by cyberjudge** [comment]
I'm using the Jenkins file from Maven build 467 and having the crafting issue on Windows 10. I'm assuming a workaround for the way Windows 10 Edition works is not in place yet.

**Comment by Creeperface01** [comment]
Fixed...

**Comment by LeeTheENTP** [comment]
Still an issue on 1.1.3 and 1.2.

**Comment by algiuxass** [comment]
Still an issue on 1.4

**Comment by NathanKassab** [comment]
problem with 1.11
