### ISSUE TITLE
Console flood after ~6 hours work server

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#584]
```
18:25:46 [CRITICAL] Could not execute taskHandler Unknown: null
18:25:46 [ALERT] java.lang.NullPointerException
18:25:46 [CRITICAL] Could not execute taskHandler Unknown: null
18:25:46 [ALERT] java.lang.NullPointerException
18:25:46 [CRITICAL] Could not execute taskHandler Unknown: null
18:25:46 [ALERT] java.lang.NullPointerException
18:25:46 [CRITICAL] Could not execute taskHandler Unknown: null
18:25:46 [ALERT] java.lang.NullPointerException
18:25:46 [CRITICAL] Could not execute taskHandler Unknown: null
18:25:46 [ALERT] java.lang.NullPointerException
```
Can we detect this NullPointerException?

**Comment by mepeisen** [comment]
Any stack trace that is logged?

**Comment by xpyctum** [comment]
@mepeisen  No, only flood

**Comment by mepeisen** [comment]
http://stackoverflow.com/questions/2411487/nullpointerexception-in-java-with-no-stacktrace
see Roland Illings answer.

That should help to get the stack trace. I already filled a push request with better exception logging on several situations. But the code where your null pointer exception is recorded it should already print out the complete stack trace.

**Comment by xpyctum** [comment]
@mepeisen Hm, i will try! c:

**Comment by yescallop** [comment]
See this https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/scheduler/ServerScheduler.java#L199-L204

**Comment by xpyctum** [comment]
@yescallop Will try

**Comment by MagicDroidX** [comment]
It think its a plugin-related issue.
You can try to turn on the debug mode in `nukkit.yml` and see what's wrong.
