### ISSUE TITLE
how use i it?

### ISSUE THREAD

**Issue by erkam2002** [Nukkit/Nukkit#589]

**Comment by MrPowerGamerBR** [comment]
[Reading the README](https://github.com/Nukkit/Nukkit/blob/master/README.md)

**Comment by erkam2002** [comment]
i have downloaded it from jenkins and i have clicked on the nukkit-1.0-SNAPSHOT.jar and then??? no console?

**Comment by erkam2002** [comment]
not work

**Comment by MrPowerGamerBR** [comment]
@erkam2002 yes, it does work, it is written on the readme how to start the Nukkit JAR from the command prompt.

**Comment by erkam2002** [comment]
how pls say it

**Comment by xpyctum** [comment]
If you don't know how to run it, not use, please...
