### ISSUE TITLE
PlayerInventory dont changes

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#604]
Hey! I working on BedWars, and has a problem: Player Inventory dont changes, not from setItemInHand, not from give command, not from setContents

**Comment by Pub4Game** [comment]
Check simple example https://github.com/NukkitRu/ToolsPro/blob/master/src/main/java/ToolsPro/commands/RepairCommand.java#L57-#L59

**Comment by MrGenga** [comment]
Noo, re-read my issue please. Я написал что инвентарь игрока НИКАК не изменяется

**Comment by MrGenga** [comment]
And: it can changes, if it not empty, but to get item i need enter gamemode. Functions or commands not working. Please fix it

**Comment by Pub4Game** [comment]
Боже, твой английский - это тихий ужас) Пиши лучше по русски

**Comment by Pub4Game** [comment]
Напиши по русски, я не понимаю твой английский)

**Comment by MrGenga** [comment]
Во смотри: инвентарь пустой: я пишу либо setContents, либо addItem, либо setItemInHand. Так вот, это не работает. А вот, если я возьму что-нибудь из креатива, перейду в выживание, это работает. Такое ощущение, что если инвентарь пустой, то и PlayerInventory нету.... Хотя ошибок в консоли нет. Хелп ми)

**Comment by Pub4Game** [comment]
@MrGenga 
![image](https://cloud.githubusercontent.com/assets/11244874/13766565/f98bf3e6-ea73-11e5-9ec0-26a5835616f8.png)

Для `setItemInHand` предмет должен быть в инвентаре

**Comment by MrGenga** [comment]
Даже addItem не работает

**Comment by Pub4Game** [comment]
У меня все работает

**Comment by ProjectInfinity** [comment]
English. Speaking Russian here is literally causing harm by confusing other contributors who otherwise could help.

**Comment by Pub4Game** [comment]
What's the difference? You can use the translator as it does the majority of the Russian people.

Especially since the problem is already there in the description

**Comment by ProjectInfinity** [comment]
When native speaking Russians are just around 160 million in the world, whereas English is over 365 million that speaks for itself. That is also not including almost every single country having English as their second language. It's ignorant to say that the majority of the world should adjust to the minority.

Besides, I'm guessing there's SOME value to whatever you're saying in Russian which is lost to people not speaking Russian. If not, then why comment at all.

**Comment by Pub4Game** [comment]
If he doesn't know English, how can we help? I couldn't understand his sentences before he wrote them in Russian.

I'm not arguing that ENGLISH is more priority than Russian.

**Comment by MrGenga** [comment]
Wait, wait: I have idea: login plugin(I downloaded it from nukkit.ru) can cancel EntityInventoryChangeEvent.... NOO! Ok.... I'll write my own login system :)

**Comment by MagicDroidX** [comment]
中华文化博大精深 :+1:

**Comment by Pub4Game** [comment]
😂

**Comment by mepeisen** [comment]
@Pub4Game I suggest helping russioans that cannot speak english at the russian Forum (http://nukkit.ru/forums/) and f.e. you can than fill a bug request here and translate the problem or a pull request etc.

It is only a matter of communication not a matter of nationality.

I do it the same way with my team. There is a young team member still going to school to learn something (I hope). He only learn French at the Moment (don't ask me why) and is - hmmm - sometimes happy if he can speak his native language ;-)

Back to Topic: I experience some strange Problems with Windows 10 too. But they are not present on my Samsung. What device are you using?
