### ISSUE TITLE
teleporting bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#618]
when i teleport to unloaded or new chunks i stuck in the air. and teleport takes +/- 5 seconds but it shouln't.

**Comment by MagicDroidX** [comment]
The chunks are generating I am afraid.

**Comment by Creeperface01** [comment]
no they are already generated

**Comment by Creeperface01** [comment]
you can test it here: play.minetox.cz

**Comment by Creeperface01** [comment]
BTW why server loads around 2000 chunks before player join? o.O

**Comment by Creeperface01** [comment]
and probably before teleport

**Comment by Creeperface01** [comment]
i got it!
