### ISSUE TITLE
Superflat bug :D

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#632]
I have this bug on superflat maybe related to chunks. :D
![screenshot_2016-03-23-15-02-32](https://cloud.githubusercontent.com/assets/10363500/13987589/92bb1854-f108-11e5-87a6-e41ef0806beb.png)

**Comment by Tee7even** [comment]
It's not a bug, but rather a custom generator installed.

**Comment by Creeperface01** [comment]
-,-it isn't custom generator

**Comment by Creeperface01** [comment]
it is really bug
