### ISSUE TITLE
If player beat player items is destroy

### ISSUE THREAD

**Issue by kentikzlo** [Nukkit/Nukkit#637]
Fix it pls

**Comment by Pub4Game** [comment]
For more info, unclear you described the error.

**Comment by kentikzlo** [comment]
If player beat player and items (Axe, sword, shoel...) is destroy if player beat player

**Comment by xpyctum** [comment]
I think it isn't a bug.

**Comment by kentikzlo** [comment]
No, its a bug.

**Comment by kentikzlo** [comment]
Because plugin cant clear inventory with breaked weapons.
