### ISSUE TITLE
New Builds : Teleport to a different world doesn't work

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#638]
Hello,
I have two levels with different names and folder names : world and KitPvP

I am using : 
player.teleport(this.getLevelByName("KitPvP").getSpawnLocation());

With an older Nukkit version (2-3 weeks old), it was working correctly. Now it spawns me in the world's spawn.

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/14064707/40a1601c-f416-11e5-946e-315219da49cb.png)

I think this should be Location

**Comment by MagicDroidX** [comment]
Should be fixed by https://github.com/Nukkit/Nukkit/commit/b84558ac2c91f2e152fb7b9c2d2df86dc2b89b5c

**Comment by Pub4Game** [comment]
:+1:
