### ISSUE TITLE
Add all biomes

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#640]
Add all biomes pls :+1:

**Comment by Tee7even** [comment]
Can't see why it's reopened, it's not even an enchancement request, since it's really obvious.

**Comment by NycuRO** [comment]
Because is not added all biomes :P need add Jungle, Savanna, ROOFED Forest and Mushroom Island :P

**Comment by NycuRO** [comment]
![screenshot_2016-04-25-12-00-09](https://cloud.githubusercontent.com/assets/13573011/14779704/12e16108-0ae2-11e6-92bb-fb19e8e2dcfb.png)

**Comment by NycuRO** [comment]
And is very easyy

**Comment by MagicDroidX** [comment]
Please help us add it as it is an easy thing.

**Comment by Niall7459** [comment]
If its so easy you can write it yourself!

**Comment by Snake1999** [comment]
Do it yourself.
