### ISSUE TITLE
Sending unnecessary packets in loop

### ISSUE THREAD

**Issue by net32** [Nukkit/Nukkit#643]
I am printing all event packages DataPacketSendEvent and 1 still online players and are printing it in loop, the day version Nukkit 3/22/2016 this is not happening.

> 18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@3337d04c]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@6de6faa6]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@3cad68df]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@14998e21]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@1921994e]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@43c87306]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@14f40030]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@4c447c09]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@593a6726]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@596a7f44]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@6dab01d9]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@2e09c51]: 92
18:39:40 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@869d87c]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@2f3166a]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@37637a24]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@31e76a8d]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@770beef5]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@6dd1f638]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@414f13fc]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@4b76aa5a]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@63a28987]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@120d3fd]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@38c9e0d6]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@4693a9ef]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@310aee0b]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@36327cec]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@410ae5ac]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@1a8df0b3]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@7c112f5f]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@5961e92d]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@4fd05028]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@3a2d3909]: 92
18:39:41 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@4fb392c4]: 92
18:39:42 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@194d329e]: 92
18:39:42 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@54d1608f]: 92
18:39:42 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@7e7fe6d]: 92
18:39:42 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@541179e7]: 92
18:39:42 [INFO] [PECore] NeT32X SEND [cn.nukkit.network.protocol.BatchPacket@24386839]: 92

>

**Comment by MagicDroidX** [comment]
Were you moving when the events were called?

**Comment by net32** [comment]
with stationary player this occurs

```
import cn.nukkit.Player;
import cn.nukkit.event.EventHandler;
import cn.nukkit.event.Listener;
import cn.nukkit.event.server.DataPacketSendEvent;
import cn.nukkit.network.protocol.DataPacket;

/**
 *
 * @author NeT32
 */
public class NList implements Listener {

    @EventHandler
    public void onDataPacketSend(DataPacketSendEvent event)
    {
        Player p = event.getPlayer();
        DataPacket datapack = event.getPacket();
        System.out.println(p.getName() + " SEND [" + datapack.toString() + "]: " + datapack.pid());
    }
}

```
