### ISSUE TITLE
Cannot use Vector3 as a hashed collection key

### ISSUE THREAD

**Issue by pcbeard** [Nukkit/Nukkit#646]
I see two flaws with the Vector3 class:

It doesn't implement these methods:

    boolean equals(Object o);
    int hashCode();

I tried adding them,

    public boolean equals(Object o) {
      if (o instanceof Vector3) {
        Vector3 v = (Vector3)o;
        return v != null && this.x == v.x && this.y == v.y && this.z == v.z;
      }
      return false;
    }

    public int hashCode() {
      // consider http://www.beosil.com/download/CollisionDetectionHashing_VMV03.pdf
      return (int)(Double.doubleToLongBits(x) ^ Double.doubleToLongBits(y) ^ Double.doubleToLongBits(z));
    }

However, I could no longer log-in to the server after making these changes. Something may be relying on the default behaviors of these methods.

I worked around by creating my own class to represent block locations using integer coordinates. Technically, only entities need floating point coordinates.

**Comment by libarclite** [comment]
Just noticed this in the commit:

    @Override
    public int hashCode() {
        int hash = 7;

        hash = 79 * hash + (int) (Double.doubleToLongBits(this.x) ^ Double.doubleToLongBits(this.x) >>> 32);
        hash = 79 * hash + (int) (Double.doubleToLongBits(this.y) ^ Double.doubleToLongBits(this.y) >>> 32);
        hash = 79 * hash + (int) (Double.doubleToLongBits(this.z) ^ Double.doubleToLongBits(this.z) >>> 32);
        return hash;
    }

You can speed this up a little bit by calling Double.doubleToLongBits() only once per coordinate:

        long xBits = Double.doubleToLongBits(this.x);
        long yBits = Double.doubleToLongBits(this.y);
        long zBits = Double.doubleToLongBits(this.z);
        hash = 79 * hash + (int) ((xBits ^ xBits) >>> 32);
        hash = 79 * hash + (int) ((yBits ^ yBits) >>> 32);
        hash = 79 * hash + (int) ((zBits ^ zBits) >>> 32);
