### ISSUE TITLE
[FEATURE REQUEST] Disabling PlayerMove revert

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#653]
Hello,
I would like to be able to disable PlayerMove revert + the invalid move message. Reason : huge lag when trying to walk on stairs.

Thanks

**Comment by Pub4Game** [comment]
dublicate #420

**Comment by Guillaume351** [comment]
#420 says you can disable it, but in fact, you can't without editing the source

**Comment by Pub4Game** [comment]
And? Why repeat the questions? The change is not likely to be added. It's better to fix it.
