### ISSUE TITLE
Bug with doors

### ISSUE THREAD

**Issue by pcbeard** [Nukkit/Nukkit#661]
Build a small structure with a 2x2 opening in creative mode. Try to insert doors into the structure. Only the lower half of the door will be placed, and a broken door block will appear. Here's a screen shot:

![img_0485](https://cloud.githubusercontent.com/assets/793781/14232051/8c46c4ba-f94f-11e5-93fe-214c8ca63ea4.PNG)

**Comment by pcbeard** [comment]
I think I've found the cause:

When the door blocks get placed in BlockDoor.place(), during the middle of the call to Level.setBlock(), BlockDoor.onUpdate() gets called, which checks to see if the block below is an AIR block. For some reason, this if statement fires, and the upper block gets broken:

            if (this.getSide(0).getId() == AIR) {
                if (this.getSide(1) instanceof BlockDoor) {
                    this.getLevel().setBlock(this.getSide(1), new BlockAir(), false);
                }

                this.getLevel().useBreakOn(this);
                return Level.BLOCK_UPDATE_NORMAL;
            }

Commenting out the call to useBreakOn() works around the bug.

**Comment by pcbeard** [comment]
I don't know if this is the best fix, but it does work. I'm mystified as to why the onUpdate() method sees a stale AIR block. Perhaps caches aren't being invalidated?

**Comment by pcbeard** [comment]
I wonder if #647 is related.

**Comment by Pub4Game** [comment]
@pcbeard I can't reproduce this bug
![image](https://cloud.githubusercontent.com/assets/11244874/14823717/2e72356e-0bdc-11e6-80da-c69e9f3c9621.png)
![image](https://cloud.githubusercontent.com/assets/11244874/14823752/506f9d28-0bdc-11e6-99c8-8146411db3b2.png)
