### ISSUE TITLE
Messages not appearing whatsoever

### ISSUE THREAD

**Issue by Twister915** [Nukkit/Nukkit#667]
No matter how messages are sent to the client, they do not appear in the ingame chat.

https://tmg.pw/WVSNLFoaqMWv this is a video demonstration of the issue

I'm running a version compiled from 03d0e and one from the latest 9fa13 and both are having this issue.

I have only tested the windows 10 edition.

I have disabled all plugins.

**Comment by ProjectInfinity** [comment]
Top right corner, click the hide button.

**Comment by Twister915** [comment]
I did that in the video

**Comment by Twister915** [comment]
Changed when I updated my client.
