### ISSUE TITLE
Movment.

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#67]
Hello!

Movement: There is a glitch with movement. It does not actually show the player walking (animation).. but it shows it teleport to where it walked to. Also sometimes they go invisible when walking.

Knockback: Let's say player1 joins and then player2. Player1 can't hit player2 but player 2 can hit player1.

When using commands like /gamemode etc, It always says player not found. [Fixed!]

That's all for now.

**Comment by caoli5288** [comment]
> When using commands like /gamemode etc, It always says player not found.
May fix on #68 .

**Comment by xxFlare** [comment]
@caoli5288 I think that is fixed now. :D

**Comment by xxFlare** [comment]
Update: Movment is not the problem. The problem is players are despawning from other players. I spawned two players. At first both can see each other move. Then when I move a player a little bit more from the worlds spawn point he despawns. When I move closer to spawn he re-appears.

**Comment by xxFlare** [comment]
Just test the latest build and it seems to be fixed! Good job guys.
