### ISSUE TITLE
Bug with ID items

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#679]
Bucket - 325
Bucket of water - 326
Bucket of lava - 327
Bucket of milk - 335

But in Nukkit implemented via meta, which is incorrect

Bucket - 325:0
Bucket of water - 325:8
Bucket of lava - 325:10
Bucket of milk - 325:1

**Comment by HmHmmHm** [comment]
Incorrect issue, item code 326 327 335 is not using in MC:PE

**Comment by Pub4Game** [comment]
Hmm... In this case it is a bug of the client.
