### ISSUE TITLE
chunk loading issue

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#688]
after few minutes chunks don't load

**Comment by ProjectInfinity** [comment]
I'm still not getting this. Can you confirm this happens on a *completely* fresh Nukkit server with the latest JAR from ci.regularbox.com/job/nukkit ?

**Comment by Creeperface01** [comment]
Should i link my world here?

**Comment by ProjectInfinity** [comment]
All of your server files. Everything from plugins to settings. Your world alone isn't very useful.
