### ISSUE TITLE
Java lang level issue

### ISSUE THREAD

**Issue by caoli5288** [Nukkit/Nukkit#7]
You defined java lang level in build.gradle is 5, but you use a lot of java 8's syntax.

**Comment by caoli5288** [comment]
Still no depend defined in build.gradle. NO possible to build by gradle.

**Comment by MagicDroidX** [comment]
I will check it out and nukkit.iml contains the lib :/

**Comment by caoli5288** [comment]
See #8 , I write a maven pom.xml to manage project. put IDE's config file on git is not suitable.

**Comment by MagicDroidX** [comment]
Yes. I dont know much about these. I will check it out.

**Comment by MagicDroidX** [comment]
build.gradle now compile dependencies :D, and the language level is right now.

**Comment by caoli5288** [comment]
qq2732000916, friend me please :D
