### ISSUE TITLE
Bug with water bucket

### ISSUE THREAD

**Issue by ZpixThaTurtle** [Nukkit/Nukkit#700]
[https://www.youtube.com/watch?v=ihwnej0LZ1s](https://www.youtube.com/watch?v=ihwnej0LZ1s)

To reproduce:
Place a bucket of water

**Comment by HmHmmHm** [comment]
OMG

**Comment by Tee7even** [comment]
Wow, that was hypnotizing. When it's get fixed, there's should be a plugin to do this.

**Comment by stayandwait** [comment]
It's endless!
