### ISSUE TITLE
null in online players

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#702]
for (Player player : new ArrayList<>(getServer().getOnlinePlayers().values())) {
            if (player.getName().toLowerCase().equals(p.getName().toLowerCase()) && p != player) {
                e.setCancelled();
                e.setKickMessage(TextFormat.RED + "The same nick is already playing");
                return;
            }
        }

this is my code and it thows nullPointerException on second line..
variable p is Player from PreLoginEvent

**Comment by ZpixThaTurtle** [comment]
![image](https://cloud.githubusercontent.com/assets/2630843/14752790/a220dde8-08d1-11e6-9307-21b8dc0d5d3b.png)

**Comment by Creeperface01** [comment]
how to paste this code window? :D and this isn't solution

**Comment by ZpixThaTurtle** [comment]
Well, Its a picture so you kinda need to type it out..
And if you're trying to block a user from logging in while a user with the same name is on the server, Then yes. It is the solution

**Comment by Creeperface01** [comment]
no, player from loginEvent is null or player in OnlinePlayers is null

**Comment by ZpixThaTurtle** [comment]
I have tested the code and it works just fine.
Can you take a screenshot of the error you are getting?

**Comment by Creeperface01** [comment]
NullPointerException... but it happens randomly.. and only if there are lots of players

**Comment by Creeperface01** [comment]
some players in onlinePlayers haven't name... Why?

**Comment by Pub4Game** [comment]
@Creeperface01 I think this can be closed :D
