### ISSUE TITLE
Can I join Nukkit Dev Team?

### ISSUE THREAD

**Issue by deotern** [Nukkit/Nukkit#706]
Hi, :D

I'm deot, well-experienced PocketMine-MP developer..
Recently, I noticed Nukkit is getting better day by day :)

As a developer, I wanted to contribute to Nukkit too! :smile: 
I have written start.sh and start.cmd for Nukkit, and that should be my first commit to Nukkit...
Can you guys let me join and have access to Nukkit Github Repo? So that I can do commit anytime without waiting for PR Request....

I'm a real developer, I know every part of PocketMine-MP very well, hope you guys can accept me as a part of your team...

Once again, thank you

**Comment by HmHmmHm** [comment]
:PI want it too!

I developed PlayHarder and some organization plugins in PocketMine
I also from now started DBShare Account System in Nukkit
(-> https://github.com/organization/ParfaitAuth)

**Comment by rcsupermanjob** [comment]
HaHaHa，You cant,unless you are very good at using java to write nukkit @MagicDroidX Do you think so？

**Comment by Tee7even** [comment]
@rcsupermanjob not only that, I guess.

**Comment by rcsupermanjob** [comment]
Yes，you are right @Tee7even

**Comment by deotern** [comment]
@rcsupermanjob
Its that really funny? You're such an *******...
Can you use your brain before judging everyone?

Im better in PHP, doesnt mean that I knew nothing about Java...
Well, if @MagicDroidX reject my request, its okay...

Im asking to join because i just wanted to help Nukkit, I can make Nukkit even better as I know both PHP and Java... and I saw Nukkit is welcoming us to contribute..

**Comment by rcsupermanjob** [comment]
Every programmer know java，your meaning is I dont know java or I cant use java to write nukkit？
 
You are funny, You are so*** HaHaHa！

And PHP can compare with Java？ HaHaHa ！

Why don't you try to join PocketMine HaHaHaHa！

If you still think you are right,Please solve nukkit's issuses by your hands 。

**Comment by MagicDroidX** [comment]
Well, I wonder if it would it be better if everyone can join.

**Comment by deotern** [comment]
@rcsupermanjob 
First, not every programmer know Java, there're many programming languages around the world
Second, can u understand English? When did I compared? I said, I know PHP and Java, this mean I can transfer code from PHP to Java as I can deeply understand PHP Code...
Third, PocketMine-MP has enough of dev, and that dont really asking for contribution in README.md
Fourth, your thinking is very childish, laughing at others, arrogant, and solve all Nukkit Issue = Qualify to be a Nukkit Team?

@MagicDroidX 
Nope... Check ImagicalMine.. every join = mess up code

**Comment by rcsupermanjob** [comment]
I don't want to spend too much time on primary school students.   This is getting us nowhere！

**Comment by deotern** [comment]
@rcsupermanjob 
Well, same as me, i dont want to waste my time with you too.. but you are the one started these... And wow! Delete all your comments? Well done! :+1:

**Comment by HmHmmHm** [comment]
@rcsupermanjob 
@rcsupermanjob So see your posts I was feeling weird...
I'm just hobby and i spends time about pe coding,
because i love sandbox game and i think..
You need to respect other people's hobbies...
Just enjoy the hobby (like a coding) without personal attacks...

**Comment by deotern** [comment]
@HmmHmmHmm
Agreed. He is just keeping laughing at others, criticize at others...

Back to topic, so @MagicDroidX, may i know about your decision? :smile:

**Comment by MagicDroidX** [comment]
Yes, I am considering of allowing everyone to join and open pulls to contribute. :)

**Comment by deotern** [comment]
@MagicDroidX 
Nice! :+1: May I know how can I join as Nukkit Member?
And my first commit will be start.sh and start.cmd :)

**Comment by rcsupermanjob** [comment]
@deotern Sorry,I Understand what you mean. Welcome to Join Nukkit Dev Team！ Sorry！

**Comment by rcsupermanjob** [comment]
Feel very sorry! @deotern

**Comment by deotern** [comment]
@rcsupermanjob 
Its okay :)

**Comment by Tee7even** [comment]
>I am considering of allowing everyone to join
Not the best decision... Probably.
