### ISSUE TITLE
Strange drop behaviour

### ISSUE THREAD

**Issue by Tee7even** [Nukkit/Nukkit#715]
Dropped items bounce on top of chests (and End Portals). 
Nukkit server:
![2](https://cloud.githubusercontent.com/assets/6763610/14805258/e2e11408-0b72-11e6-8532-716d31934845.png)
Singleplayer:
![default](https://cloud.githubusercontent.com/assets/6763610/14805296/5115e30e-0b73-11e6-9d9d-e22f531f5ed2.png)

**Comment by Tee7even** [comment]
[This](https://youtu.be/UvgNO457gJs) isn't right behaviour too.

**Comment by Pub4Game** [comment]
I know this bug from PocketMine
