### ISSUE TITLE
Sometimes items in hotbar randomize repetitively

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#719]
I'm using Minecraft Windows 10 Edition to connect to the server I created. When I change to a different item in my hotbar using scroll on the mouse, it will randomly scroll/select between 2 items repetitively.

**Comment by Pub4Game** [comment]
I think this is a bug on the client side

**Comment by stayandwait** [comment]
Might be, I think I also experienced this issue in Pocketmine

**Comment by Tee7even** [comment]
@Pub4Game It's not present in MiNET, by the way. If only there was a server to show it now... I noticed  this when their test server and Hypixel PE were up.

**Comment by Pub4Game** [comment]
@Tee7even okay

**Comment by net32** [comment]
i solved this using listener class with this code:

```
    @EventHandler
    public void onDataPacketSend(DataPacketSendEvent event)
    {
        Player p = event.getPlayer();
        DataPacket datapack = event.getPacket();
        if (event.getPacket() instanceof MobEquipmentPacket)
        {
            MobEquipmentPacket pk = (MobEquipmentPacket) event.getPacket();
            if (pk.eid == 0 || pk.eid == p.getId())
            {
                event.setCancelled(true);
            }
        }
     }
```

**Comment by fromgate** [comment]
@net32 :+1:

**Comment by Pub4Game** [comment]
@net33 Great! I will check it :+1:

**Comment by TTexx** [comment]
Please fix it... This bug is very annoying on Win10

**Comment by Pub4Game** [comment]
Fixed https://github.com/Nukkit/Nukkit/commit/3124ead15c153dcc78f21c80edfb72074e711098
