### ISSUE TITLE
Spawning!

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#72]
You should update players spawn cords if the level is new, otherwise they glitch into the old world spawn until you delete there data profile.

**Comment by MagicDroidX** [comment]
Hard to judge if the world has been replaced by another same name world.

**Comment by xxFlare** [comment]
Yes, different world same name... So a solution may be hard, but PM does it successfully.

Just spawn them to the worlds actual spawn then getting it from there data?
