### ISSUE TITLE
Cows and Sheep don't burn when set on fire

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#720]
Cows and Sheep don't burn when you set them on fire
![2016-04-26_2049](https://cloud.githubusercontent.com/assets/15825041/14841247/df068fba-0bf0-11e6-8587-a5023d83f98c.png)

**Comment by Pub4Game** [comment]
@stayandwait Mobs not implemented yet

**Comment by stayandwait** [comment]
Why can I spawn them?

**Comment by Pub4Game** [comment]
In PocketMine you too can spawn mobs, but to interact, they will not

**Comment by stayandwait** [comment]
So this works as intended then for now and should I leave this open or close it?
