### ISSUE TITLE
Spawning a wolf or ocelot crashes the game making the world unplayable

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#721]
When you spawn a wolf or ocelot with a spawn egg the game crashes making the game unplayable again.

I'm using Minecraft Windows 10 Edition. (When you rejoin the server the wolf will be spawned.)
![2016-04-26_2100](https://cloud.githubusercontent.com/assets/15825041/14841380/14950c50-0bf2-11e6-9642-2fe00dcc0893.png)

**Comment by Niall7459** [comment]
YOU CAN GET OCELOTS?

**Comment by stayandwait** [comment]
@Niall7459 Yes in creative mode. Just spawn them with a spawn egg. but it might crash your game.

**Comment by stayandwait** [comment]
When

**Comment by Pub4Game** [comment]
Ever :D

**Comment by Pub4Game** [comment]
I'll probably fix it today 😏

**Comment by stayandwait** [comment]
@Pub4Game :)
