### ISSUE TITLE
Items crafted in workbench/crafting table disappear from inventory once crafted

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#727]
After crafting oak wood plants the items crafted disappear from the inventory seconds later. I'm using Minecraft Windows 10 Edition.

Steps to duplicate
-Start a completely new map in Survival.
-Make sure your inventory is empty when you first start. (start with no previous player data)
-Switch to Creative.
-Place down a workbench/crafting table.
-Switch to Survival.
-Get wood from a tree.
-Craft wood planks in the workbench/crafting table.
-Close the crafting screen and open it a few times.
-The item you just crafted will disappear after a few seconds.

**Comment by Pub4Game** [comment]
Dublicate https://github.com/Nukkit/Nukkit/issues/576
