### ISSUE TITLE
Minecraft PE 0.14.2 / can not connect

### ISSUE THREAD

**Issue by Hobbabobba** [Nukkit/Nukkit#728]
on one of my devices, an automatic update made it impossible to connect to my nukkit server (0.14.1).
The device (iPad mini 2) is running Minecraft PE 0.14.2

Is there any way to fix it fast?

**Comment by Pub4Game** [comment]
I will update protocol version tonight

**Comment by Niall7459** [comment]
Hi, I have attempted to update the protocol version and all was well, except I could not break/place any blocks it would just say "You cannot place blocks here"

**Comment by Pub4Game** [comment]
Yes.. This is a new problem. I don't know how to solve it

**Comment by Niall7459** [comment]
Do you have any idea on whats causing it, client or server-side?

**Comment by Creeperface01** [comment]
i think it is something like adventure mode

**Comment by Creeperface01** [comment]
server must send some packet to disable it

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/commit/8f18813820c241190f3ba18d54dc1119cb89303d

**Comment by Niall7459** [comment]
Nice work!
