### ISSUE TITLE
Taking damage put me down to 0.5 heart

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#731]
Even if I get a single Wooden Sword hit (and I have a leather armor), I will have 0.5 hearts.
Golden Apple don't work when this happen.
(I have the issue with the lastest 0.14.2 build, but it was already there in the build before that)
Wasn't happening with an older build (which was 5 - 6 days old)

**Comment by DoomhawkRu** [comment]
Fix it, plz
