### ISSUE TITLE
Health doesn't regenerate

### ISSUE THREAD

**Issue by DyirondenRu** [Nukkit/Nukkit#732]
When I get damage my health set to 1 and doesn't regenerate.
![screenshot_2016-04-28-13-11-42](https://cloud.githubusercontent.com/assets/18498646/14878034/b0cc4100-0d42-11e6-86b3-9db0066e2020.png)

**Comment by Guillaume351** [comment]
Sam issue (see #731 ) : put me down top 0.5 and don't heal
