### ISSUE TITLE
Tips don't send

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#734]
Send a tip, doesnt work. wabam.

**Comment by boybook** [comment]
From the decompile, Mojang rewrote the GUI system. And the TIP maybe have been removed or in error. So the Launcher also can not show the tip. It is a big problem!!

**Comment by boybook** [comment]
![9619c5c415e9548d9d2a1bb4b5ad5779](https://cloud.githubusercontent.com/assets/8210983/14918576/4ef679fc-0dea-11e6-8a68-fbb153c397e2.jpg)
![45f110f35a499d01ac8eb1b78f6643d3](https://cloud.githubusercontent.com/assets/8210983/14918586/6068f75a-0dea-11e6-883a-3ef0d2963779.jpg)

**Comment by MrPowerGamerBR** [comment]
Does the Popup still work in 0.14.2?

**Comment by Pub4Game** [comment]
@MrPowerGamerBR Yes.

**Comment by Creeperface01** [comment]
Hm i know about new popup feature which allow to how popup higher like tip but tip's show delay is longer than popup's

**Comment by Creeperface01** [comment]
Btw how to decompile MCPE?

**Comment by Tee7even** [comment]
@Creeperface01 You can't decompile it, you only can disassemble it and read some ASM code (and also class/method names).

**Comment by Snake1999** [comment]
CLIENT ISSUE. What you can only do is to ask mojang for why.

**Comment by Creeperface01** [comment]
But now you can do this with popups too

**Comment by MrPowerGamerBR** [comment]
@Creeperface01 wow, how did you do that "Map: Cliffs"? That's awesome!
