### ISSUE TITLE
Middle clicking certain items doesn't permanently add them to hot bar

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#737]
### Issue description

In an attempt to adding torches, ladders or grass items to my inventory in creative, I middle clicked the item but the item disappears from my hot bar within seconds after doing so.
- When testing make sure you don't have a ladder, torch or grass item in your inventory.
### Steps to reproduce the issue
1. Middle click a torch, ladder, or grass item with your mouse.
2. Notice that the item isn't permanently added to your hotbar.
### OS and versions

*Nukkit: build 444 (current build)
*OS: Windows 10
*Device: PC

![2016-04-29_2118](https://cloud.githubusercontent.com/assets/15825041/14933856/62198e7c-0e51-11e6-88ce-296952e1726f.png)

**Comment by Snake1999** [comment]
Minecraft PE does not have the operation named 'middle click'. You can send issue to Microsoft or Mojang.

**Comment by stayandwait** [comment]
Minecraft Windows 10 edition IS MCPE. 'middle click' is affected in this version of Minecraft when playing the game using mouse and keyboard, so why close this?

**Comment by stayandwait** [comment]
and as long as nukkit runs in Minecraft Windows 10 edition then this is a bug.

**Comment by Snake1999** [comment]
'Windows 10 edition' is not what we focused on because this is a client-full-of-bug version.

**Comment by Tee7even** [comment]
@Snake1999 MCPE and MCW10E are almost the same, actually.

**Comment by stayandwait** [comment]
@Snake1999 It's actually the same thing. So the "client-full-of-bug" is out of the question. What your really saying is you rather not fix any issues that happen in Minecraft Windows 10 edition so you close this bug report. Why? What you're really saying is you're not supporting it. Then what about other people that connect using Minecraft Windows 10 Edition. You're not just going to leave me and everyone else in the dark are you? Please advise. If Nukkit is for developers then you might want to support both platforms. I do all development work on a computer not an iPad or Android device. I haven't even concidered anything yet because my wish is/was to see a stable Nukkit server and would/have gladly supported/recommend it to others more than PocketMine. Now I think we need a second opinion on this issue @Pub4Game @fromgate

**Comment by Pub4Game** [comment]
I think this is likely a bug Nukkit... In MiNET it work fine.

**Comment by stayandwait** [comment]
@Pub4Game Thank you :)

**Comment by MagicDroidX** [comment]
@pub4game Does MiNet check what you are going to craft?

**Comment by Pub4Game** [comment]
@MagicDroidX What? 

It is obvious that the problem is Nukkit. Because all not transparent blocks no have this problem
