### ISSUE TITLE
Spruce trees in taiga biomes look strange

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#738]
Spruce trees in taiga biomes look strange. (see photo attached.) Everywhere I go they look like this it's not just this one picture or world. I created multiple worlds and they look this way. They don't look like this in vanilla MC.

Steps to reproduce
* Create a new world
* Observe the trees in taiga biomes (they don't look like what you see in MC)

![2016-04-29_2240](https://cloud.githubusercontent.com/assets/15825041/14934123/c8471b2e-0e5b-11e6-8375-b6272db2447c.png)

**Comment by Niall7459** [comment]
I will put in a pull request tomorrow.

Hopefully can fix it

**Comment by Niall7459** [comment]
https://github.com/Nukkit/Nukkit/pull/854
