### ISSUE TITLE
Random crashes that cause the game to close

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#739]
I'm experiencing random crashes where my Minecraft Windows 10 edition game closes at times. No error message displays in the console the game just closes disconnecting me and I have to keep reconnecting. I'm using the current Nukkit #309 I was playing in a custom map. Anyone else experiencing this?

**Comment by Niall7459** [comment]
Think I encountered it yesterday, the user would randomly disconnect, then reconnect and it would close mcpe, after a few trys it fixes its self (MCPE Ipad)

**Comment by Pub4Game** [comment]
There is no information available, unable to reproduce.
