### ISSUE TITLE
Future issue, what will happen when more features are added.

### ISSUE THREAD

**Issue by Niall7459** [Nukkit/Nukkit#740]
This is  not really a bug, but could potentially be a future issue.

I have tested out genisys (php) It is extremely slow at loading chunks, I believe because it has alot of populators.

When nukkit has populators will it become slow?
Is there any way we can replicate the PC MC generator in the future (never slow for me)

**Comment by Pub4Game** [comment]
No, it will not affect the generation of the world.

In the future can be optimised chunks, which will lead to even greater stability.

For such questions use the forum.

English: http://forums.nukkit.cn/

Russian: http://nukkit.ru/forums/
