### ISSUE TITLE
Enchantment items in chest

### ISSUE THREAD

**Issue by DyirondenRu** [Nukkit/Nukkit#745]
When I put enchantement items to chest and restart the server - items will be lost enchantment.

Before restart:
![screenshot_2016-05-01-10-31-30](https://cloud.githubusercontent.com/assets/18498646/14940107/4a501b48-0f88-11e6-9784-3b1ec285484b.png)

After restart:
![screenshot_2016-05-01-10-32-59](https://cloud.githubusercontent.com/assets/18498646/14940109/6252e0f4-0f88-11e6-8771-8996a968da6a.png)

**Comment by wasted123** [comment]
That's a bug
