### ISSUE TITLE
Crash when teleport and has Item in players' hand.

### ISSUE THREAD

**Issue by boybook** [Nukkit/Nukkit#754]

**Comment by boybook** [comment]
![screenshot_2016-04-13-23-12-12_com miui bugreport](https://cloud.githubusercontent.com/assets/8210983/15001276/eb6276dc-115b-11e6-9d21-459599ef20de.jpg)

**Comment by Creeperface01** [comment]
can you tell me how to get this backtrace?

**Comment by boybook** [comment]
It always happens when server send you other player's item in hand.
It easily happened when players teleport.
Then I tried to set air in players' hands when they teleport, the crash eased.
But sometimes it still happens.
And this crash is uncertain.
Only happens in a big number of player count.
May more than 10 players teleport in the same time and they are really close.
So I can't reproduce this bug to find the reason.

**Comment by Creeperface01** [comment]
Oh :/ And can you tell be how to get this backtrace? It will really hell me and other people to solve these problems

**Comment by boybook** [comment]
May more than 10 players teleport in the same time and they are really close.
So I can't reproduce this bug to find the reason.
Now I'm trying to reproduce it by a lot of NPC!

**Comment by Creeperface01** [comment]
Please
