### ISSUE TITLE
Some adventure settings packet offsets.

### ISSUE THREAD

**Issue by Shevchik** [Nukkit/Nukkit#755]
0x1 - adventure mode.
0x2 - cant attack mobs.
0x4 - cant attack players.
0x10 - dontticktime (no idea why this exists, because set time packet overrides this anyway)
0x40 - autojump enabled
0x80 - mayfly;
0x100 - flying;

Also there exist 2 other offsets
0x8: something damage related, see Player::hurt.
0x20: no idea - couldn't find any usages in a code.

**Comment by Pub4Game** [comment]
?

**Comment by Shevchik** [comment]
Related to
https://github.com/Nukkit/Nukkit/issues/115

Now you can implement those gamemodes.

**Comment by MagicDroidX** [comment]
Great!
