### ISSUE TITLE
Joining server can cause MCPE to crash

### ISSUE THREAD

**Issue by Niall7459** [Nukkit/Nukkit#756]
I'm currently experiencing a problem where my mcpe client will close just after the "Building Terrain" or "Done!" Message when joining my nukkit server.

On the IPAD I have found that after about 4 or 5 goes it will finally let me on.
On Android it will never let me on

Even with new player names and stuff.
I can connect to other servers like pocketmine

**Comment by Pub4Game** [comment]
I can't reproduce this bug. (iPhone 5s, iPhone 6s, iPad mini 2, iPad Air 2)

**Comment by Niall7459** [comment]
Don't worry, I seem to have fixed it now, works as normal.

Not sure if it affected the outcome but I removed all skulls and animals before trying and it worked.

I love nukkit and really appreciate all the work you put into it, I now run a family server that runs seamlessly 6+ people running on a raspberry pi!
