### ISSUE TITLE
Unable to place crafted items

### ISSUE THREAD

**Issue by HiddenMotives** [Nukkit/Nukkit#760]
Hmm not sure if this is a common occurrence but in my world with no plugins, after grabbing some wood and forming it into planks and creating a craft table placing it down would cancel the event? The crafting table disappears. Placing wood planks disappear aswell, but the naturally found wood/dirt/sand can be placed and broken no problem.

**Comment by stayandwait** [comment]
This maybe a duplicate issue because I reported this issue also. I hope they fix this.

**Comment by stayandwait** [comment]
Dublicate #576
