### ISSUE TITLE
Water generator fix

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#763]
Add WATER , not STILL_WATER to not exist without water and empty holes to fill water everywhere
![screenshot_2016-05-10-14-21-24](https://cloud.githubusercontent.com/assets/13573011/15144866/d62121c4-16ba-11e6-956a-9f296dd86063.png)

**Comment by thebigsmileXD** [comment]
Notice: Still water is faster ;)

**Comment by Snake1999** [comment]
Could you please please please buy a computer to do developing works? AIDE is too bad for big projects such as nukkit plugins

**Comment by NycuRO** [comment]
@Snake1999 Now i'm using windows 10 ,computer ;)
