### ISSUE TITLE
Some kind of usernames can't join

### ISSUE THREAD

**Issue by iVertx** [Nukkit/Nukkit#77]
Well, i was just making some stress tests with Nukkit, and after a little time I discovered a issue with usernames, a really weird issue :p 

I don't know if it's a uuid issue or something like that but that's what is happening (example):

If i put "vertx" as my username, the chunk loading screen didn't appear to me, My client freeze on locating server screen, but the server console report a sucessfull join...

If I put "VertxVertx" i was able to reach the loading screen, but i freeze in there...

With "Vertx1" my client crashes

Finally, with "VertxVertx1" i was able to join sucessfully... Idk exactly what the hell is the logic behind the usernames, but whatever the pattern, some can join, some can't, simply changing some characters and capital letters + numbers...

Anyway thank you guys for this amazing pm-mp alternative :) keep up your good work!

**Comment by xxFlare** [comment]
@iVertx Can you try to delete your players folder and try to join as vertex? Thanks!

**Comment by MagicDroidX** [comment]
:D There might be some issue in the NETWORKING part and yes, we have already started fixing.

**Comment by CavinMiana** [comment]
@MagicDroidX I have an issue to. Something to do when you load your world sometimes I get stuck in one area and I can't move. But I can open my inventory and stuff so that's kinda weird. Idk if anyone else is having this issue. Might be something to do with my phone but I just want to clarify with everyone else. * Sorry I did not make a separate issue I just thought my issue was similar with this one :)

**Comment by MagicDroidX** [comment]
@CavinMiana OK, I'll check it out.

**Comment by MagicDroidX** [comment]
Would plz test it again? I have just improved the RakNet hours ago.

**Comment by CavinMiana** [comment]
Ok @MagicDroidX

**Comment by iVertx** [comment]
@MagicDroidX sorry took so long to reply, no, the issue still there :/

And @xxFlare deleting player's data did not solve the issue, it's unfortunatelly related directly to usernames, since no mather what the player data says about this player, this is the first thing that I tested due to the exacly same problem that pocketmine 1.4 had a while ago, solved by deleting the player data, but that isn't the problem here...

Seems like for some reason the chunks aren't being sent to usernames who got this problem...

**Comment by Angelic47** [comment]
I used "vertx" as my username, and seems everythings goes well.
![image](https://cloud.githubusercontent.com/assets/8847879/11551016/267fd36e-99b0-11e5-93e4-856539a1d314.png)
Delete player's data and world folder, then try again please.
