### ISSUE TITLE
Chunk duplicating on FLAT

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#772]
If you change any chunk in flat so new chunks are same like this one 
Btw why you dont believe me?
![screenshot_2016-05-16-20-22-43](https://cloud.githubusercontent.com/assets/10363500/15299307/122de61e-1ba4-11e6-9fae-6f26cc0bec92.png)
![screenshot_2016-05-16-20-22-07](https://cloud.githubusercontent.com/assets/10363500/15299292/00185824-1ba4-11e6-91df-c5420bdcbd93.png)
![screenshot_2016-03-23-15-02-32](https://cloud.githubusercontent.com/assets/10363500/15299377/60005b56-1ba4-11e6-837c-90cbbd57762a.png)

**Comment by MagicDroidX** [comment]
It is possible as flat chunks are generated by clone the existing one.

**Comment by JackboyPlay** [comment]
Worldedit for poor peoples xD

**Comment by boy0001** [comment]
`chunk.clone()` on Anvil is broken. That's the cause
