### ISSUE TITLE
When falling you get teleported upwards

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#775]
In creative mode, when I dig down trying to get to bedrock, I eventually get teleported back upwards.

**Steps to reproduce**
- Dig down as much as you can, until it teleports you back to the surface again.

If this doesn't happen then come out of the hole and just fall back into the 1 block hole you dug and it will teleport you back to the surface, the teleporting happens over and over again.

**I did a few more tests and this doesn't always happen**

**Comment by Pub4Game** [comment]
I can't reproduce it.

**Comment by stayandwait** [comment]
It doesn't always happen

**Comment by Pub4Game** [comment]
I tried like 20 times, but I understand what you're saying.

**Comment by Tee7even** [comment]
It surely was happening in PocketMine, but I haven't seen it in Nukkit yet...

**Comment by boybook** [comment]
It just happen with your bad network or low tps!
Server will find you are moving too fast. Some times, you will move more than 10 blocks each tick, then the server teleport you back.

These codes make it happen:
if ((distanceSquared / ((double) (tickDiff * tickDiff))) > 100 && this.getGamemode() < 3) {
            revert = true;
        } else {
