### ISSUE TITLE
Repository mengcraft Down

### ISSUE THREAD

**Issue by net32** [Nukkit/Nukkit#776]
Repository of MengCraft it is down:

http://ci.mengcraft.com:8080/plugin/repository/everything/

**Comment by Pub4Game** [comment]
Use this: https://circleci.com/gh/Nukkit/Nukkit/tree/master

**Comment by net32** [comment]
yes but, i need a maven repository like:

```
        <repository>
            <id>mengcraft</id>
            <url>http://ci.mengcraft.com:8080/plugin/repository/everything/</url>
        </repository>
```

Mengcraft repo turn on but its very slow!
Nukkit needs a oficial maven repo!

**Comment by Pub4Game** [comment]
@net32 you can use http://ci.regularbox.com/job/nukkit/
