### ISSUE TITLE
Bug armour

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#782]
If you have armour în equipement and quit server and join, armour disapreal..

**Comment by MohiPE** [comment]
Always?

**Comment by NycuRO** [comment]
Yes

**Comment by Pub4Game** [comment]
No, this happens if the player is in creative.

**Comment by Pub4Game** [comment]
Had to return changes, sorry, I don't know how to fix it.

**Comment by wasted123** [comment]
No, I don't see this bug

**Comment by MagicDroidX** [comment]
Fixed by this commit:https://github.com/Nukkit/Nukkit/commit/f02d2b3397877e0866dd9bfd57b9edd3d953a297

**Comment by Pub4Game** [comment]
@MagicDroidX https://www.youtube.com/watch?v=-K_YQrPOBAA

This happens in creative

**Comment by File14** [comment]
Maybe it will help for some fixes: https://github.com/iTXTech/Genisys/pull/1621
