### ISSUE TITLE
Bug with lava and water

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#79]
If you put lava and water next to it, you get it

![image](https://cloud.githubusercontent.com/assets/11244874/11451801/774fb62c-95e3-11e5-867d-f3f35b62b853.png)

or 

![image](https://cloud.githubusercontent.com/assets/11244874/11451807/c2f24306-95e3-11e5-8364-fb1d400d87f7.png)

**Comment by Angelic47** [comment]
yeah that's a bug we have already started fixing, thank you :-)

**Comment by MagicDroidX** [comment]
:D That's actually a really interest bug lol. I pretty like it(XD).

**Comment by caoli5288** [comment]
hummmmmmmmm lol
