### ISSUE TITLE
can i use custome name?

### ISSUE THREAD

**Issue by haniokasai** [Nukkit/Nukkit#798]
i tried this.
player.getInventory().addItem(Item.get(276,0,1,"{display:{Name:CUSTOM NAME HERE}}"));
but nothing happened.
custom name is unavailable?

**Comment by Pub4Game** [comment]
Just example:
`Item item = ((Player) sender).getInventory().getItemInHand().setCustomName("§bCustom Name :D");((Player) sender).getInventory().setItemInHand(item);
`
