### ISSUE TITLE
Strange bug with block

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#81]
If you rapidly tap any object on the ground, it appears like this block
![image](https://cloud.githubusercontent.com/assets/11244874/11451854/230298a8-95e5-11e5-9c8c-1deb5cb00d48.png)

For example, the snow puts a Redstone torch 
Lighter - earth
Scissors - Watermelon

**Comment by Angelic47** [comment]
yeah, the blocks which written with "update!" are "world update" block, when you use somethings that need update some blocks (like using hoe on grass, etc. ), it would generate a "world update" block.
however, sometimes nukkit can't process this request correctly, then you will see this strange bug.
we will fix it soon :D
now you can break this block directly and nothing will happen
