### ISSUE TITLE
The number of slots in inventory

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#83]
On the server fewer slots than in a single game

Server:
![image](https://cloud.githubusercontent.com/assets/11244874/11456593/12e3fb64-969f-11e5-8af9-4be99e2b8e77.png)

Single game:
![image](https://cloud.githubusercontent.com/assets/11244874/11456594/16af6ee0-969f-11e5-814c-fd39e6602680.png)

**Comment by MagicDroidX** [comment]
hmmmm
