### ISSUE TITLE
Bugs with server

### ISSUE THREAD

**Issue by wasted123** [Nukkit/Nukkit#837]
Sometimes the server freezes, like this:
sometimes u can find the server but couldn't join it, it will keep loading and the server terminal won't show that somebody is trying to join, unless u press enter.

**Comment by Pub4Game** [comment]
Use the latest build.

**Comment by wasted123** [comment]
I haven't seen this problem in the latest version, because I just download it this morning, and if it occurs, i'll tell u guys. :)

**Comment by Snake1999** [comment]
Seems weird, but I can't find out how this courses, and I can't reproduce in all my devices.:(

**Comment by Snake1999** [comment]
Seems weird, but I can't find out how this courses, and I can't reproduce in all my devices.:(
