### ISSUE TITLE
will it function with mcpe client 15.0?

### ISSUE THREAD

**Issue by Bidou0418** [Nukkit/Nukkit#839]

**Comment by daniktheboss** [comment]
Just wait!! It's been one day since it came out!!

**Comment by Niall7459** [comment]
Execute this in terminal:

git clone --branch "0.15.0" https://github.com/Nukkit/Nukkit
mvn clean
mvn package

**Comment by daniktheboss** [comment]
Or we can download 0.15 branch and use it?

**Comment by daniktheboss** [comment]
Put the src folder in?

**Comment by File14** [comment]
@Niall7459 `$ mvn clean
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.053 s
[INFO] Finished at: 2016-06-16T08:01:31+02:00
[INFO] Final Memory: 14M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\#######/###). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

`

**Comment by File14** [comment]
@Niall7459 I've done this but I just get an error when I startup the server.
` [INFO] Loading server properties...
[ALERT] java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at cn.nukkit.utils.Utils.readFile(Utils.java:57)
	at cn.nukkit.lang.BaseLang.loadLang(BaseLang.java:90)
	at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:39)
	at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:31)
	at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:27)
	at cn.nukkit.Server.<init>(Server.java:273)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)`

**Comment by File14** [comment]
@Niall7459 I've that build now, however I can't connect to the server even if it says 0.15.0 at the serverlist menu.

**Comment by Niall7459** [comment]
Yeah theres a problem with the build anyway so it wont work.

**Comment by File14** [comment]
Okay, thanks for a quick answer! :)

**Comment by j-melling** [comment]
The branch has been removed. Where is the work on v15 happening?

**Comment by Pub4Game** [comment]
Yes, but very unsuccessful, the game crash after login.

**Comment by Pub4Game** [comment]
Yes, but very unsuccessful, the game crash after login.

**Comment by rcsupermanjob** [comment]
may mcpe 0.15 changed packet‘buffer

**Comment by Pub4Game** [comment]
@rcsupermanjob already fixed.
