### ISSUE TITLE
BukkitPE

### ISSUE THREAD

**Issue by dallinac** [Nukkit/Nukkit#840]
I emailed GitHub about BukkitPE, but they said only Nukkit can make the DMCA Takedown Request. I really think that this should be done since all BukkitPE has done is steal other's work (even their forum runs off the same software as the Nukkit forum)

**Comment by MrPowerGamerBR** [comment]
Why do you think Nukkit could do a DMCA takedown? They aren't violating any
licensing (AFAIK I didn't look at everything) and it is on the project
readme that is a Nukkit fork with some features.

Also, the forum uses Xenforo, that's like saying Nukkit stole the forum
software Bukkit uses
Em 14 de jun de 2016 12:23, "Dallin Christensen" <notifications@github.com>
escreveu:

**Comment by Aericio** [comment]
Why does everyone use XenForo o.o It costs so much.

**Comment by Tee7even** [comment]
@Aericio but it's, no doubt, the best forum software.

**Comment by Aericio** [comment]
True... well if they can afford it them whatever.

**Comment by Niall7459** [comment]
They have taken Nukkits code, and removed all the class headers and notes and replaced it with there own claiming themselves as the auhtors.

**Comment by MrPowerGamerBR** [comment]
@Niall7459 from the project's readme:

> BukkitPE is also a fork of Nukkit but we've plan on adding more features to it. You may check otu there project at here

**Comment by Niall7459** [comment]
Yes but they cant replace "Nukkit Team Author: MagicXDroid" with there own "author"

**Comment by Kjgohr5600** [comment]
The owner of the copyright (i.e., in most cases, the true author) could sue the plagiarist in federal court for violation of the copyright. Any work created in the USA after 1st. Mar 1989 is automatically protected by copyright, even if there is no copyright notice attached to the work. 17 USC, Sub-Section 102, 401, and

**Comment by Kjgohr5600** [comment]
Credit: http://www.checkforplagiarism.net/plagiarism-law
