### ISSUE TITLE
Question: should I add more to the generator

### ISSUE THREAD

**Issue by Niall7459** [Nukkit/Nukkit#844]
Do you want me to do works on the generator like

Add jungle
Add ponds
Smooth biome color

**Comment by daniktheboss** [comment]
Wait there already done with 0.15 update? I mean I think that we should update it first and then think of adding pistons and stuff

**Comment by daniktheboss** [comment]
And or world generators

**Comment by Niall7459** [comment]
Yeah.

**Comment by Niall7459** [comment]
I don't think theres a 0.15 update yet.

**Comment by Pub4Game** [comment]
@Niall7459 If you can help, we will be very happy, **but do not need to create some issue for this.**

**Comment by Niall7459** [comment]
Sorry, iforgot about the gitter chat room
