### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by tpmdud** [Nukkit/Nukkit#846]
I can't connect to either of my servers i tried to set up. Once i connect my Samsung s5 stucks on a generating world loading screen and my server returns:
`logged out due to Login timeout`
I tried it on a odriod c2 running ubuntu aswell as my windows 8 desktop pc.

Did i do something wrong or is it a bug?

EDIT: Phone has v0.15.0 installed

**Comment by Pub4Game** [comment]
Nukkit does not support 0.15.0.

**Comment by tpmdud** [comment]
So what am i supposed to do? where can i see a list of supported clients or anything that makes me able to connect? Is my version just to new?
Coudn't find anything at all, i just started using mcpe for my cousin today, longtime desktop mc user/admin though.

**Comment by Pub4Game** [comment]
Just wait, we will soon update to 0.15.0 Nukkit
