### ISSUE TITLE
Bugs the update 0.15.0

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#853]
- [x] Player movement is not visible to others.
- [x] Client-side crash when the player is near the with mobs or spawned them.
- [x]  Block updates are not sent to the client.
- [x] You can see the animation of damage when hitting a player in the creative.
- [x] Old worlds may not work?!

**Comment by Niall7459** [comment]
I really appreciate the work you do, I'm going to give a shot at fixing the entities and older worlds.

Also number 2 is also present in 0.14 versions.

**Comment by Niall7459** [comment]
Probably not fixed but worth a try:
https://github.com/Nukkit/Nukkit/pull/857

**Comment by Pub4Game** [comment]
@Niall7459 @Creeperface01 Now the old worlds do not lead to client crash. Thanks for the help.

**Comment by Niall7459** [comment]
Wait so this also fix https://github.com/Nukkit/Nukkit/issues/721
?

**Comment by Pub4Game** [comment]
@Niall7459 Ohh... No, there's another problem.

**Comment by Niall7459** [comment]
Waaat?

**Comment by Pub4Game** [comment]
I'll fix it :3 don't worry

**Comment by Niall7459** [comment]
What's the one about 256 blocks?

**Comment by Niall7459** [comment]
Also block updates, does this mean that other client cannot see player place/break blocks?

**Comment by Pub4Game** [comment]
@Niall7459 Oops, I thought they made the world in 256 blocks.

**Comment by Pub4Game** [comment]
@Niall7459 Check yourself and see...

**Comment by Niall7459** [comment]
Also is there any reason other mobs have not been implemented, compatibility issues, because if not I will add them , well try to at least

**Comment by Creeperface01** [comment]
so if you spawn an entity, mcpe crashes?

**Comment by Pub4Game** [comment]
No

**Comment by Creeperface01** [comment]
but sometimes it crashes (when game starts)

**Comment by Pub4Game** [comment]
Update Nukkit and remove all mobs

**Comment by Pub4Game** [comment]
Oh yeah, baby, 0.15.0 is already almost here
