### ISSUE TITLE
【0.15.0`s Request】 Names in Xboxlive

### ISSUE THREAD

**Issue by fuyutsuki** [Nukkit/Nukkit#858]
I would like you to to put also the name that contains a blank.
Sorry to rush you if you were going to implement.
(Google translation used)

**Comment by Pub4Game** [comment]
I don't understand what you're saying. Our chat https://gitter.im/Nukkit/Nukkit

**Comment by fuyutsuki** [comment]
Okay, I'm sorry

**Comment by jython234** [comment]
He wants support for names with a space in them.

**Comment by Pub4Game** [comment]
Ahhh! Thank you! If possible, I will definitely do it!

**Comment by fuyutsuki** [comment]
@jython
Thank you…!!

@Pub4Game
I'm sorry the English poor…
But, Thanks to improve!!

**Comment by File14** [comment]
<3

**Comment by File14** [comment]
Please this needs to be fixed. Add so username supports spaces.

**Comment by Pub4Game** [comment]
It should seriously consider, because it will harm all plugin developers and make the process of creating teams is much more difficult.

**Comment by File14** [comment]
Can't you do this: If player contains a space then you remove the space so it will be set as: "TestAccount" instead of "Test Account"? @Pub4Game

**Comment by Pub4Game** [comment]
Have you thought that maybe the player with the nickname without a space?

**Comment by File14** [comment]
Can't you add a special letter instead? Like a letter that people can't use normally?

**Comment by Pub4Game** [comment]
My God, I think I have already said that it takes time, it is necessary to consider carefully, to avoid problems in the future!

**Comment by fuyutsuki** [comment]
Or it can not be resolved by replacing the "space" of the name of the parameter to "hyphey"?

**Comment by fuyutsuki** [comment]
For example, as "Test Player" -> "Test-Player"

However, if as long as it is difficult to accommodate, it is I think that there is no way.

**Comment by Tee7even** [comment]
>For example, as "Test Player" -> "Test-Player"
>However, if as long as it is difficult to accommodate, it is I think that there is no way.

That's not a solution, but a workaround.

**Comment by fuyutsuki** [comment]
That or is that correspondence is impossible?

**Comment by burtonis** [comment]
I'm trying to do the same thing - I have an Xbox Live username with a space in it.

There is a Pocketmine plugin "NameCorrector" [https://forums.pocketmine.net/plugins/namecorrector.1270/](url) which does exactly this.  I've tried just putting NameCorrector.phar in the plugins directory, but it doesn't load.

Any suggestions?

**Comment by fuyutsuki** [comment]
Oh,I try it
thanks!

**Comment by fuyutsuki** [comment]
Oh,I try it.  
thanks!

**Comment by File14** [comment]
I just found out a big server network did, they just replaced the space with underline.

**Comment by fuyutsuki** [comment]
that idea is I proposed...(not underline, hyphey.)
If you could change the processing of the internal server that way, I think so will be better Nukkit.

**Comment by Niall7459** [comment]
Or store all player data with a Client ID (UUID Equivalent for PE) So the players can change there names whilst keeping there inventory and settings (game mode, health, location, username, etc.)

**Comment by File14** [comment]
Easier to just a replace... @Niall7459
