### ISSUE TITLE
Teleport Location > Set Pitch & Yaw is not working!

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#863]
If I teleport the player with a set Pitch and Yaw it doesn't face what it should.	

Location l = new Location(0.5, 60, 0.5, 10, 10);
player.teleport(l);

**Comment by Creeperface01** [comment]
you can create a pull request

**Comment by boybook** [comment]
You can try Location.fromProject()

**Comment by Creeperface01** [comment]
He means Location.fromObject()

**Comment by File14** [comment]
Doesn't teleport when I use that.
