### ISSUE TITLE
Double Chest

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#867]
![](https://i.gyazo.com/92d9e2cb88bad4bff7128d3d2c5fd6bb.png)
If you have a double chest and you have cancelled the break event. 

Then if you try to **break** it and then it comes back like this: 
![](https://i.gyazo.com/585876a781f4ddb5bb99ffac74620a81.png)

Then if I right click the chest to try to open it then my client freeze and it crashes.

**Comment by Pub4Game** [comment]
I can't reproduce it

**Comment by File14** [comment]
Where is a video I'e made: https://www.youtube.com/watch?v=d3wqFCc8XUU

Keep in mind that I've cancelled block break event and cancelled chest opening in Survival mode so that's why I go into Gamemode 1 when trying to open the chest. @Pub4Game

**Comment by Pub4Game** [comment]
Not reproducibly.

**Comment by File14** [comment]
Oki
