### ISSUE TITLE
Can't Install Plugin

### ISSUE THREAD

**Issue by ChaostixZix** [Nukkit/Nukkit#870]
When I Put Phar Plugins File on /plugin, And Then Restarting Nukkit, No Plugins Loaded

**Comment by MrPowerGamerBR** [comment]
Because Nukkit doesn't support and never will support PocketMine plugins.

Nukkit uses Java, PocketMine uses PHP, you can't except cross-compatibility for plugins for server software written in different languages.

**Comment by ChaostixZix** [comment]
Thanks, Im New At nukit, Sorry
