### ISSUE TITLE
[Win 10][0.15.0] Crafting not working :(

### ISSUE THREAD

**Issue by D3thw0lf** [Nukkit/Nukkit#871]
If you try to craft anything, the item gets put back into inventory.

I've read that this could be possible a Client Bug but you've fixed the scrollbar bug (or it's gone on servers magically with 0.15.x) so I guess this is more a package problem? (I've never coded for minecraft so don't get angry with me mkay :3)

Anyways...If this is RLY (not a "urgh we don't want to support"-thing) not a Client problem then is there a chance that this gets fixed in a near future? Id love to have a crossplay server for pocket AND for Windows Players.

Error-Log: http://pastebin.com/GciPp0MG

Cheers

PS: Sorry for my bad english. <3

**Comment by Pub4Game** [comment]
Dublicate https://github.com/Nukkit/Nukkit/issues/576
