### ISSUE TITLE
Bug with isUsingChunk?

### ISSUE THREAD

**Issue by xxFlare** [Nukkit/Nukkit#877]
Nukkit is loading up to 400 chunks for one player, even when I change chunk settings.

PocketMine does 30 chunks at a time. And I can't get PM to load 100 chunks for one player (PM unloads them for freeing memory)

Could this be a bug with Nukkit not realizing some chunks are not being used?

**Comment by boybook** [comment]
The max-chunk in nukkit.yml has been abandoned!
And there is a new setting in server.properties >> view-distance=10
The number of loaded chunks is view-distance ^ 2 * pai

**Comment by Creeperface01** [comment]
What is pai? :D

**Comment by boybook** [comment]
π

**Comment by Creeperface01** [comment]
So viewdistance is r?

**Comment by Creeperface01** [comment]
But it should be 2 * viewdistance * PI

**Comment by Creeperface01** [comment]
Shouldnt it?

**Comment by xxFlare** [comment]
@boybook Oh, did not know that. Might be helpful to remove the option in the YML ;p.

Will test it out soon.

**Comment by xxFlare** [comment]
@boybook A view distance of 10 should not load 400 chunks for a player. :[

**Comment by NiclasOlofsson** [comment]
You are right @xxFlare a view distance of 10 should not load 400, it should load 441 chunks.

**Comment by Creeperface01** [comment]
No.. It should load 63 chunks

**Comment by NiclasOlofsson** [comment]
View distance is in chunks, not blocks @Creeperface01. But in any case I have no idea how you got to 63. Care to explain?

**Comment by Creeperface01** [comment]
2 * viewdistance * π

**Comment by NiclasOlofsson** [comment]
So for you 10x10x3.14 => 63?

**Comment by Creeperface01** [comment]
Why viewdistance² ? Its circle xontent => 2 * viewDistance * π

**Comment by NiclasOlofsson** [comment]
Let me google that for you @Creeperface01 

https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=circle+calc:+find+Area+radius+10

**Comment by Creeperface01** [comment]
![image](https://cloud.githubusercontent.com/assets/10363500/16383431/5b0f6482-3c85-11e6-986e-f5e9675e99a5.png)
62.8 so i suppose it is 63 chunks

**Comment by NiclasOlofsson** [comment]
Your are so sweet @Creeperface01. I'll let you have this as an epic Pyrrhic victory :-)

**Comment by Creeperface01** [comment]
no sorry :D it is 317

**Comment by Creeperface01** [comment]
but not 441

**Comment by NiclasOlofsson** [comment]
<G> 317! It is 314+ and it's 441 because the chunks are square and it includes all the chunks it touches, even the ones not entirely inside the area.

**Comment by Creeperface01** [comment]
ok :smile:
