### ISSUE TITLE
Drop item bugs on MC:PE Windows 10 

### ISSUE THREAD

**Issue by grzegorz2047** [Nukkit/Nukkit#878]
### Issue description

While running it's impossible to drop item using q button. When I was in creative mode sometimes it was cloning items (potion of invisibility)
### Steps to reproduce the issue
1. run MC PE WIN 10
2. gather few items
3. try to drop any item
### OS and versions

- Nukkit: latest
- OS: WIN 10
- Device: PC
### Crashdump, backtrace or other files

- ...
  no errors

**Comment by File14** [comment]
Yes, this is correct. I've the same issuse. However if I'm in Creative Mode and try to drag and drop items from my inventory in the gamemode 1 block selection it just comes back the blocks I've dragged. It's very buggy.

**Comment by fromgate** [comment]
Can confirm for W10 creative mode

**Comment by intagaming** [comment]
Genisys has fixed this problem. This probably the way to go :-?

**Comment by Snake1999** [comment]
Could you confirm it again in the latest version ?)

**Comment by File14** [comment]
I'll check.

**Comment by File14** [comment]
I can still confirm this bug.

**Comment by Creeperface01** [comment]
but its buggy only sometimes.... sometimes it works well
