### ISSUE TITLE
Block.SOIL does not exist? Add it?

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#884]
I can't use Block.SOIL it says that it doesn't exist and I need that to disable crops tramping.

Can you guys add it?

**Comment by Tee7even** [comment]
Block.FARMLAND
Please search before reporting.

**Comment by File14** [comment]
I tried with that one but it's not working.

**Comment by Tee7even** [comment]
What exactly doesn't work?

**Comment by File14** [comment]
@EventHandler
	  public void soilChangePlayer(PlayerInteractEvent e)
	  {
	    if ((e.getAction() == PlayerInteractEvent.PHYSICAL) && (e.getBlock().getId() == 60)){
	      e.setCancelled(true);
	    }
	  }

It still works to destroy crops and the soil by jumping on it.

**Comment by Pub4Game** [comment]
Will be implemented in the future may be

**Comment by File14** [comment]
Why maybe? It should be.
