### ISSUE TITLE
Can't see FloatingTextParticle

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#885]
### Issue description
When I create a FloatingTextParticle I can't see it. Glitch?

### Steps to reproduce the issue
Check your code and see if it's something wrong in it.

### OS and versions

* Nukkit: Latest
* OS: Windows 10
* Device: PC

**Comment by NiclasOlofsson** [comment]
It's broken in 0.15 since you need to point to the entity to see it's nametag. Use invisible players instead, not adding them to the player list.

**Comment by File14** [comment]
Okay, thanks.
