### ISSUE TITLE
Water Bug! Must be fixed!

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#889]
### Issue description
Once I place the water it goes everywhere!
See video: https://www.youtube.com/watch?v=SQTVHm2_xs0&feature=youtu.be

### Steps to reproduce the issue
Patch it in your code?

### OS and versions

* Nukkit: Latest
* OS: Windows 10
* Device: PC

@Pub4Game 
@Tee7even 
@MagicDroidX

**Comment by MagicDroidX** [comment]
@Pub4Game Please revert this commit. https://github.com/Nukkit/Nukkit/commit/a58e012dbb65b412be8695834c7e96a9e4d792cd
