### ISSUE TITLE
Weird Items With Creative Mode on Join

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#890]
### Issue description
Sometimes when I join my server in Creative Mode (gm 1) I get some items that I shouldn't, I don't get my inventory that I used to have before. See Screenshot: https://i.gyazo.com/7d2e57c9608c2bf256b8f16c37c1506e.png
Then if I logout and login again I get my real inventory: https://i.gyazo.com/3b12f42d6505f7d537b0a8e20e3c96c1.png

### Steps to reproduce the issue
You join a server with Survival mode get some items then you turn on your gamemode 1 and then quit and join back.

### OS and versions
* Nukkit: Build 1158
* OS: Windows 10
* Device: Pc

### Crashdump, backtrace or other files
No Errors

**Comment by Tee7even** [comment]
>Latest

Provide **exact** version.

**Comment by File14** [comment]
Edited @Tee7even

**Comment by Pub4Game** [comment]
I can't reproduce. I not found the code that will be given these items.
