### ISSUE TITLE
I doesn't get damage by fall or suffocation in a block.

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#892]
### Issue description

 When I fall from high tower in Survival mode, I doesn't get fall damage. And I doesn't get damage by suffocation in a wall.

### Steps to reproduce the issue

1. Check the code in the place, where is applying the fall damage and the suffocation damage.
2. Fix it! ;)

### OS and versions

* Nukkit: latest for that moment
* OS: Ubuntu 16.04
* Device: VDS machine

### Crashdump, backtrace or other files

* none

**Comment by Pub4Game** [comment]
This also works fine, please check all this without the plugins, and then write.
