### ISSUE TITLE
Weird water mechanics

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#896]
### Issue description

Water spreads across air when placed on blocks and doesn't stop. 
This bug looks similar to #700 although the water didn't seem to float in there video.
![Water1](http://image.prntscr.com/image/bc332ff82d0141539d0a4ba887b1f5ff.png)
The small patches of water are from when I first noticed it.

![Water2](http://image.prntscr.com/image/60aedb7e05124db88ff03e97b71b3edd.png)
This image shows the water not dropping from the trees but floating in air.
### Steps to reproduce the issue

1. Place water on a high block so the water can flow down
2. Water starts spreading and floating without stopping

### OS and versions

* Nukkit: Nukkit 1.0dev
* OS: Windows 10
* Device: PC ?

**Comment by Pub4Game** [comment]
You use new build? https://github.com/Nukkit/Nukkit/commit/17dacee1bd615a08b4e3a28c0f6ecd5c9031d2ef

**Comment by File14** [comment]
It's fixed after I reported it.

**Comment by imjack** [comment]
I think I was on a later build
