### ISSUE TITLE
p.getInventory().open(p); not working?

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#905]
### Issue description
The player's inventory doesn't open with this code:
p.getInventory().open(p);

I have tried this too: p.addWindow(p.getInventory());

It should open, is it a bug in Nukkit?

### Steps to reproduce the issue
Use this code in an event and it should open the player's inventory but it doesn't (Nothing happends).

### OS and versions

* Nukkit: Build 1119
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files
No errors

**Comment by Creeperface01** [comment]
i think it shouldn't open

**Comment by File14** [comment]
Well, how do you open the invetory then? @Creeperface01

**Comment by Creeperface01** [comment]
im afraid you can't

**Comment by Creeperface01** [comment]
MCPE doesn't support this. SO close this issue

**Comment by File14** [comment]
How do you know?

**Comment by Creeperface01** [comment]
you can try:
ContainerOpenPacket pk = new ContainerOpenPacket();
        pk.windowid = (byte) p.getWindowId(p.getInventory());
        pk.type = (byte) p.getInventory().getType().getNetworkType();
        pk.slots = p.getInventory().getSize();
        pk.x = (int) p.x;
        pk.y = (int) p.y;
        pk.z = (int) p.z;
        pk.entityId = 0;

p.dataPacket(pk);

**Comment by File14** [comment]
Thanks ;) I'll try now.
