### ISSUE TITLE
Fake snow: Strange issue on Nukkit?MCPE

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#906]
### Issue description

**Fake snow: Strange issue on Nukkit?MCPE** 

When you walking near to Ice Plains biome (without snow) or changing current biome to Ice Plains - snow will be appear out of nowhere.

It's a fake snow. You cannot break it or find using plugins (scaning area).

If you close client and move back you will see area without snow, than after some time, snow will appear again.

Server didn't send any packets, that contains snow data!!!
### Steps to reproduce the issue
1. Login to server and find a cold biome biome (Ice plains).
2. Wait some time - and snow will cover this area.
3. Logoff from server
4. Login again and you will see this area without snow
5. Snow will appear again
### Video demonstrating the issue:

https://youtu.be/-P_Ze1-oPuc
### What I tried:
1. I tried to catch generator. This snow is not produced by generator/populart
2. Tried to catch packets. It looks like there's no packet that force client to show this fake snow.

**Comment by fromgate** [comment]
@Snake1999 @MagicDroidX 
Any ideas? What could it be?

**Comment by imjack** [comment]
Maybe it's just client side if the client knows the biome it assumes there should be snow there?

**Comment by Creeperface01** [comment]
Players can break it :D

**Comment by Niall7459** [comment]
Maybe Ice biome is meant to be snowy? new client side feature?

**Comment by thebigsmileXD** [comment]
Pretty sure its client sided. I have this on a realms too. https://bugs.mojang.com/browse/MCPE-16103

**Comment by Pub4Game** [comment]
@thebigsmileXD Great! I hope they soon will fix it.

**Comment by thebigsmileXD** [comment]
https://bugs.mojang.com/browse/REALMS-110

**Comment by AppPhil** [comment]
I changed the extends of IcePlainsBiome to SnowyBiome and then there were only small areas in the IcePlainsBiome were you could see snow but the server can't see it.

**Comment by thebigsmileXD** [comment]
I actually looped through every block in chunks when loaded and set the biome to plains in my hub.

**Comment by HmHmmHm** [comment]
It can be checked even when the spawned Ice Golem.

**Comment by thebigsmileXD** [comment]
@HmHmmHm Yes, i mentioned it in the bug report on jira

**Comment by Creeperface01** [comment]
close?

**Comment by thebigsmileXD** [comment]
I found the reason for this sh*t. Mojang added "snowAccumulation" in 0.15 to Biomes. This shit always generates client side

**Comment by Creeperface01** [comment]
But its client side so it should be closed
