### ISSUE TITLE
check ground state idea

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#907]
hi, i got an idea. Player sends in MovePacket if is on ground. So what if we temporaly remove CheckGroundState and use ground state from MovePacket? yes i know, mods can modify this, but idk about any mod that can do that, so what do you think? nukkit would be a bit faster!

@Pub4Game @ProjectInfinity @MagicDroidX @Snake1999 @fromgate

**Comment by ProjectInfinity** [comment]
You don't know about any /current/ mod that does this. But by removing that check, are we not just opening up for the ability to implement this?

Have you done any profiling to see how much this would affect nukkit?

**Comment by Creeperface01** [comment]
it is not only faster but better too. And mod developers can make kill aura or nukker and these are a lot easier than changing packets (i think) so i think if they want to do some hack, they would already made these mods.

**Comment by Creeperface01** [comment]
and we can change it back everytime

**Comment by fromgate** [comment]
What about to add an option in to nukkit.yml to allow server owner to choose which method to use?

And I think it's a good idea to combine these methods. 
Use packet data, but sometime (once per second, for example) check actual state and if packet data and calculated are differs - kick player from the server.

**Comment by Pub4Game** [comment]
@fromgate I don't think this is good. 

At the moment we have things more important. Perhaps it will be implemented in the future.
