### ISSUE TITLE
Player movement is laggy

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#909]
players move laggy in 0.15
You can test it here: pe.GameTeam.cz

**Comment by File14** [comment]
Yes, I can confirm this. I just tested to PvP on my localhost server and the PvP Knockback is very strange for the "viewer(s)".

**Comment by Creeperface01** [comment]
But lags are more important, i suppose its a packet bug

**Comment by Niall7459** [comment]
Confirmed

**Comment by Creeperface01** [comment]
@Pub4Game i think this is the most important now

**Comment by File14** [comment]
Yes, because it affects the gameplay pretty much.

**Comment by Creeperface01** [comment]
@PeratX what have you changed in Player movement sending for 0.15? please

**Comment by Creeperface01** [comment]
and what about this? (from PM) https://github.com/Creeperface01/NukkitGT/commit/bcc613e9cdd100d26fb84b9f9a80110d475f2b94

**Comment by Creeperface01** [comment]
no :/

**Comment by Creeperface01** [comment]
i had to close my BedWars server because its not playabe now :/

**Comment by Creeperface01** [comment]
Have you any idea?

**Comment by Pub4Game** [comment]
No ideas

**Comment by Creeperface01** [comment]
i think we can remove addPlayerMovement() and replace it with normal addEntityMovement()

**Comment by Creeperface01** [comment]
because other projects uses MoveEntityPacket instead of MovePlayerPacket

**Comment by Pub4Game** [comment]
This bug is only in Nukkit? in PocketMine okay?

**Comment by Creeperface01** [comment]
yes and in any other project too :/

**Comment by Pub4Game** [comment]
Okay, I'll try to fix it today.

**Comment by Creeperface01** [comment]
Ok thx :) im triying too

**Comment by Creeperface01** [comment]
but move sending system is still same isn't it? so it must be somewhere in MovePackets

**Comment by Creeperface01** [comment]
Nukkit move sending is a bit different so maybe...

**Comment by Creeperface01** [comment]
@Pub4Game I think i fixed it! Because it works now. Look at last 2 commits
https://github.com/Creeperface01/NukkitGT/commits/master

**Comment by Pub4Game** [comment]
Please create a clean branch with the changes and I'll look through them

**Comment by Creeperface01** [comment]
I have not any clean branch do how to create new branch from nukkit's master?

**Comment by Pub4Game** [comment]
I think you should just delete the whole repository :D https://github.com/Creeperface01/NukkitGT/

**Comment by Creeperface01** [comment]
Or If i use github editor to edit a file, it creates a new branch
