### ISSUE TITLE
Bug with drop item

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#91]
I threw the ground, but it is not visible on earth, although if you go forward, I'll be able to pick it up

If you rejoin to server, then the drop will be seen

![image](https://cloud.githubusercontent.com/assets/11244874/11459936/30b312c0-96f3-11e5-8b28-e9d9c2ccfd12.png)
![image](https://cloud.githubusercontent.com/assets/11244874/11459939/35d2daec-96f3-11e5-8f71-5603052d0b56.png)
![image](https://cloud.githubusercontent.com/assets/11244874/11459943/578a95b2-96f3-11e5-9c36-147f8f0e9f15.png)

**Comment by Angelic47** [comment]
it seems that has been fixed at #100 , just try again please :D

**Comment by Pub4Game** [comment]
Nice! Thank you! Tonight will check

**Comment by Angelic47** [comment]
My pleasure :D
