### ISSUE TITLE
Nukkit To-Do

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#92]
Could you make a list of what you have done, and what was left of it)) It would be very convenient to follow the development of Nukkit. Thank you

**Comment by Snake1999** [comment]
Good idea :+1:

**Comment by Pub4Game** [comment]
When you make the list?

**Comment by MagicDroidX** [comment]
Well you know.
The list will be:
bug fixing
bug fixing 
and
bug fixing

**Comment by Pub4Game** [comment]
Ahah)) will there be hunger, experience, enchantment, etc?

**Comment by MagicDroidX** [comment]
No doubt a plan is being made for these.

**Comment by xxFlare** [comment]
@Pub4Game 
There are too many bugs to start a list to add features.
Possibly after most vanilla bugs are fixed..
