### ISSUE TITLE
Laggy worlds

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#935]
MCPE is laggy when playing on nukkit, i think it is something with blocks sending maybe block light calculating?

**Comment by Creeperface01** [comment]
@Pub4Game it begin after (maybe 10 minutes or more). So probably nukkit sens something to player but forgets to remove it.

**Comment by Tee7even** [comment]
I see lags only in snowy biomes and it's not Nukkit bug.

**Comment by Creeperface01** [comment]
hmm. Try to join to pe.gameteam.cz. Its bedwars server so very small map but its laggy. Item spawning is improved so its not the cause

**Comment by Tee7even** [comment]
Seems ok to me. Don't see any lag...

**Comment by Pub4Game** [comment]
I can not connect

**Comment by Pub4Game** [comment]
I also didn't see any lag...

**Comment by Creeperface01** [comment]
as i said it is gradually, so after 10 or more minutes. But if you have powerfull device you do not notice it

**Comment by Tee7even** [comment]
Are you sure it's a bug in Nukkit?

**Comment by File14** [comment]
No issuses here.

**Comment by Creeperface01** [comment]
i have no idea what can causes this and i had same bedwars in php and it worked well

**Comment by omgA4L** [comment]
I also have this same problem, when I restart the server I can join my server quickly but after a few mins the building terrain takes a long time and stuff becomes laggy for the player, also players keep crashing in my world at different times (Probs from the lag)
