### ISSUE TITLE
Server doesn't close when crashing or out of memory

### ISSUE THREAD

**Issue by tiNsLeY799** [Nukkit/Nukkit#937]
When the server reaches it's memory capacity at 100%, along with the loading capacity, the server closes however, the window it is running on does not close. Instead, the query and RCON is online but the server does not function.
This is a major issue if you are away and cannot manage it.
As much as I would insert the OutOfMemory debug message, I cannot find it in the server.txt as it most likely was not recorded due to the full memory.
You can recreate this by overloading your server, or as my clients put it, "place mobs everywhere" and "throws bottles of enchanting".
I am running on Windows 7, using Build 383.

**Comment by Pub4Game** [comment]
When you learn how to use the template? Is it very difficult?

**Comment by Creeperface01** [comment]
remove PAUSE from start file

**Comment by wasted123** [comment]
how 2 place animals, isn't nukkit not yet support animals?

**Comment by tiNsLeY799** [comment]
My start.bat does not have pause

Mob AI is not implemented yet. You can choose to make them spawn in the
server.properties

**Comment by wasted123** [comment]
i turned it on but it wont spawn mobs

**Comment by Creeperface01** [comment]
Use pureentities plugin

**Comment by wasted123** [comment]
like which one

**Comment by Snake1999** [comment]
DO DISCUSS ONLY ONE TOPIC IN ONE ISSUE THREAD.
THIS IS NOT A FORUM

**Comment by tiNsLeY799** [comment]
Yes.. much agreed. I merely asked for help with this but I get questions
about an entity manager..?

**Comment by Creeperface01** [comment]
Try to catch Java outOfMemoryException :D If it exists

**Comment by tiNsLeY799** [comment]
Ah! That's what's causing it. It does exist, but only if you manage to get
your server memory to 100% and load percentage to 100%.

**Comment by Striker209** [comment]
@tiNsLeY799 I'm having the same issue with Genisys (jailed by my PHP code :D)
So you say you fixed it? How?

**Comment by tiNsLeY799** [comment]
THANK YOU SO MUCH
