### ISSUE TITLE
Moved Wrongly On Slabs?

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#943]
### Issue description

Is it possible to disable the "(playername) has moved wrongly" feature? Because it is very buggy, especially when you walk on slabs and for players with a higher ping.

### Steps to reproduce the issue

1. Walk and jump around with high ping.
2. Try walking on slabs and you will get stuck sometimes due to the "moved wrongly" checking.

### OS and versions

* Nukkit: Build 1218
* OS: Windows 10
* Device: PC

**EDIT:** Even worse when you've Speed 2 Effect/Potion.

**Comment by Pub4Game** [comment]
My last comment for you. https://github.com/Nukkit/Nukkit/issues/420
