### ISSUE TITLE
plugin depend

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#944]
### Issue description
my plugin depends on plugin 1 everything works well but on server shutdown server unloads plugin 1 and than my plugin that depends on plugin 1 isn't it bug?

### Steps to reproduce the issue
create 2 plugins

### OS and versions
* Nukkit: nukkit
* OS: Windows
* Device: HP

**Comment by caoli5288** [comment]
You mean your plugin will not disable(will not call onDisable)?

**Comment by Creeperface01** [comment]
No but dependencies are wrong when disabiling plugins

**Comment by caoli5288** [comment]
You mean dependencies disable before your plugin?

**Comment by Creeperface01** [comment]
Yes
