### ISSUE TITLE
Clients stuck in Building Terrain

### ISSUE THREAD

**Issue by tiNsLeY799** [Nukkit/Nukkit#946]
As the title says, when players who have registered (or not) on the server, they cannot log in. Literally. Even if they're not, they cannot log in to the server but the server still recognizes that they're trying to log in. The Console doesn't send any backtraces or exceptions. I will show the player trying to log in:

2016-7-22 20:25:10 [DEBUG] Raising level "Trading_Post" tick rate to 1 ticks
2016-7-22 20:33:58 [INFO] dannyt4304[/50.49.22.179:19132] logged in with entity id 482 at (Trading_Post, 123.1775, 65.0, 158.5815)
2016-7-22 20:34:06 [INFO] dannyt4304[/50.49.22.179:19132] logged out due to client disconnect
2016-7-22 20:34:18 [INFO] dannyt4304[/50.49.22.179:19132] logged in with entity id 483 at (Trading_Post, 123.1775, 65.0, 158.5815)
2016-7-22 20:34:25 [INFO] dannyt4304[/50.49.22.179:19132] logged out due to client disconnect
2016-7-22 20:36:08 [INFO] dannyt4304[/50.49.22.179:19132] logged in with entity id 484 at (Trading_Post, 123.1775, 65.0, 158.5815)
2016-7-22 20:36:46 [INFO] dannyt4304[/50.49.22.179:19132] logged out due to client disconnect
2016-7-22 20:37:08 [INFO] dannyt4304[/50.49.22.179:19132] logged in with entity id 485 at (Trading_Post, 123.1775, 65.0, 158.5815)
2016-7-22 20:37:27 [INFO] dannyt4304[/50.49.22.179:19132] logged out due to client disconnect
2016-7-22 20:37:58 [INFO] dannyt4304[/50.49.22.179:19132] logged in with entity id 486 at (Trading_Post, 123.1775, 65.0, 158.5815)
2016-7-22 20:38:04 [INFO] dannyt4304[/50.49.22.179:19132] logged out due to client disconnect

**Reproduce**
My clients have gotten this by:
1) Teleporting into buggy worlds
2) Logging out and logging in (slightly redundant)
3) I've changed the .jar and reloading the server.

**OS and version**
I am using Nukkit build 392.
My OS the server runs on is Windows 7.
I am using android 5.1 and my tablet android 3.1

**Crashdump, backtrace or other files**
I will provide several player.dats
[corrupted_playerdats.zip](https://github.com/Nukkit/Nukkit/files/379468/corrupted_playerdats.zip)
to see it was corrupted for this to happen.

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/17077779/e014b23a-50e5-11e6-8e13-ef8c907126ec.png)
I'm fine, check your plugins .

**Comment by tiNsLeY799** [comment]
I did try and reset player's.dat file to see if they were corrupted. I use
plugins:
AutoBroadcast
Economy - API, Land, Shop
Essentials PE
Factions-For-Nukkit
Madperms
Multiworld
Pocketvote
Presents
Toolspro
Welcome
WorldEdit

These are all up to date, and the latest update.
P.S) I see you've gotten the gamer tag of one of my staff, one of the two
files I provided.

**Comment by Tee7even** [comment]
>Presents 
>These are all up to date
Welp, can't guarantee that. I didn't update Presents in quite a while. And Nukkit develops very rapidly.
