### ISSUE TITLE
Chunk won't Generate

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#947]
### Issue description

When using the code below the chunk won't generate: 
`		int x = 750;
		int z = 1700;`
		`level.generateChunk(x >> 4, z >> 4, true);`
		`System.out.println(level.getChunk(x >> 4, z >> 4).isGenerated());`

### Steps to reproduce the issue

1. Use code above

### OS and versions

* Nukkit: This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v0.15.0 alpha (protocol version 81)  (Build #392 on mengcraft)
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files

No dumps only returning false

**Comment by MagicDroidX** [comment]
Chunk generation is asynchronous.
