### ISSUE TITLE
can not use decimal numbers in teleport command

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#948]
### Issue description
i can not use e.g. /tp 128.5 45 23.9

### Steps to reproduce the issue
use /tp command

**Comment by Pub4Game** [comment]
=_=

**Comment by File14** [comment]
I know, it's pretty annoying. :panda_face:

**Comment by Creeperface01** [comment]
What's wrong? :D

**Comment by File14** [comment]
Fix it ;D

**Comment by Creeperface01** [comment]
I mean nzmbers such as 5.6886 or 243.5
