### ISSUE TITLE
Action debug messages

### ISSUE THREAD

**Issue by Niall7459** [Nukkit/Nukkit#953]
I am getting random messages on player interactions, place break.

I keep getting "action: 1" in the console.
I am using the 0.15.4 release.

**Comment by File14** [comment]
Same issuse, it is VERY annoying to have these messages.

**Comment by Niall7459** [comment]
Been around for a long time since the 0.15 release, thought it would just be a debug feature to help testing but it is still here and quite surprised no one has noticed/placed a issue

**Comment by File14** [comment]
I thought the same

**Comment by File14** [comment]
@MagicDroidX @Pub4Game

**Comment by Pub4Game** [comment]
Issue do not conform to the template, from the description I can't understand anything.
