### ISSUE TITLE
Action Debug Message Console

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#957]
### Issue description
Everytime I break or place a block it says in console "action: 1". 

### Steps to reproduce the issue
1. Login to your server.
2. Break or place a block.
3. See for yourself in console that it says "action: 1" even if debug is disabled.

### OS and versions
* Nukkit: 1240
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files
* No Errors

@Pub4Game 
Feels better now?...

**Comment by Pub4Game** [comment]
It has nothing to do with the Nukkit, remove your plugins and check again.

**Comment by fromgate** [comment]
I think it's a plugin debug info. Someone forget to remove debug info from the plugin

**Comment by File14** [comment]
I got rekt.
