### ISSUE TITLE
Redstone implementing

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#959]
Hi, what about redstone implementing? wouldn't be better some method like onRedstoneUpdate(int power) instead of current system?

**Comment by Creeperface01** [comment]
because various redstone activators, power blocks in different radius

**Comment by Tee7even** [comment]
Could you please not use issues for questions? You can ask your question at gitter and, if someone has an answer, it will be answered there.

**Comment by Creeperface01** [comment]
yes, but after my message will be next 10000 another messages... and i doubt you read them all...

**Comment by Creeperface01** [comment]
because on gitter is open discussion but this question is only for nukkit devs (@Pub4Game )

**Comment by Creeperface01** [comment]
and i'd make pull request with that
