### ISSUE TITLE
Enchant Table Not Working...

### ISSUE THREAD

**Issue by yungtechboy1** [Nukkit/Nukkit#963]
### Issue description

For some reason when I try and Enchant the Item does not go in my Inventory... I did some debuging and it seems that it is the the Enchant Inventory but is never added to or sent to the player's inventory so when you try and put that item in your hand the server says you dont have that item... I would Debug it my self but compiling the Nukkit Project was a bit too much for me to do right now
### Steps to reproduce the issue

Just try and Enchant an Item then add it to your Inv
### OS and versions

Newest Build...

**Comment by Creeperface01** [comment]
enchanting is not fully implemented yet

**Comment by shanwer** [comment]
We didn't write enchant table function yet,but you can use /enchant command to enchant your item.

**Comment by Creeperface01** [comment]
wait, enchant should work i just checked source code hmm....

**Comment by yungtechboy1** [comment]
Yea That what I fixed in my Push

**Comment by Snake1999** [comment]
Can you try if you can enchant again in the latest build? @yungtechboy1

**Comment by yungtechboy1** [comment]
@Snake1999 Sure Ill Check Now :)
