### ISSUE TITLE
Nukkit's Memory (Strange)

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#969]
### Issue description

The server is taking more and more memory for no reason. If I start the server then I get 1/2 hours then the memory is very high. If it comes up to 80% it just randomly goes back to 3% as normal. (**No plugins** installed & new generated world) Gif: https://i.gyazo.com/5c8543d2f43a0ac0e831aca09dccc555.gif

### Steps to reproduce the issue

1. Start a server without any plugins!
2. Just wait and watch!

### OS and versions

* Nukkit: Build 1255
* OS: Ubuntu 16.04
* Device: Doesn't matter

### Crashdump, backtrace or other files

* No errors.
* Timings report but it doesn't show anything special: https://timings.aikar.co/v2/?id=0c2f70da44a24145917efe811b2a8d2a

When it's raising: https://i.gyazo.com/9eab4c586a1694bf495d32fe257fe94a.gif

 @Pub4Game Can you take a look at this? :)

**Comment by Pub4Game** [comment]
Yes, I can confirm the problem is with the RAM

**Comment by File14** [comment]
Well, I just noticed the Nemisys does the same but it just goes up to 30% then it goes back as normal.

**Comment by MagicDroidX** [comment]
It depends on the memory limit of JVM.

**Comment by robske110** [comment]
Huh? This seems like sth in nukkit is filling up the memory with garbage and the garbage collcetor has to collect it all the time. This is a serious performance problem too

**Comment by File14** [comment]
Yes, it should be fixed. It fills it up to 80% and then it goes back to 5% and starts filling again! @robske110

**Comment by MagicDroidX** [comment]
The memory limit you set to the JVM is too low so that the garbage collection is triggered very often. If there is any memory leak, you can never have your memory drop down. Learn how to use -Xmx.

**Comment by robske110** [comment]
That has nothing to do with that. I think he has enough memory allowed. you can, for example reproduce this behavior by doing
for(int i = 0; i <= 1000){
new SomeBigClassWithMuchVarsInIt(73,63,28);
}
As there is no reference to the class, it'll be destoryed the next time the garbage collector goes over it. Please try to think first, before blaming too less memory for a memory jump.

**Comment by File14** [comment]
@MagicDroidX I give the server 2GBs of RAM, so I think it's enough... ._.

**Comment by robske110** [comment]
I'm now leaving you alone here. I don't use nukkit exactly because of these reactions to issues btw...
