### ISSUE TITLE
Infinite Joining

### ISSUE THREAD

**Issue by RedstoneAlmeida** [Nukkit/Nukkit#973]
### Issue description

Write a short description about the issue
![image](https://cloud.githubusercontent.com/assets/15146680/17488080/129d985e-5d6e-11e6-9428-1960fd174d39.png)

Joining infinite on Nukkit for Multicraft
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Nukkit:
* OS:
* Device:

### Crashdump, backtrace or other files

* ...

**Comment by Tee7even** [comment]
If you are experiencing this bug only with Multicraft, it's not Nukkit's bug. 
Provide more info, this issue is incorrect.

**Comment by RedstoneAlmeida** [comment]
have a chanse to generator nether in nukkit?

**Comment by mhsjlw** [comment]
Make sure the server pings you before you connect, or else the RakNet login itself will not be initialised properly

**Comment by RedstoneAlmeida** [comment]
i''m tested, bug is continued :(

**Comment by Snake1999** [comment]
First, this is maybe not a Nukkit issue.
Then, 2 different things should be send in 2 issues
