### ISSUE TITLE
getInventory().addItem　bug

### ISSUE THREAD

**Issue by haniokasai** [Nukkit/Nukkit#977]
i did
 player.getInventory().addItem(Item.get(346, 0, 1).setCustomName("FooBar"));
,but that item wasnt added in player's inventory.

however ,after player was killed,i did addItem , item was added in player's inventory.

**Comment by MrGenga** [comment]
Do player.getInventory().sendContents(player) after giving

**Comment by haniokasai** [comment]
il try it.
