### ISSUE TITLE
FloatingTextParticle does not work

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#979]
Sorry for short text...
I'm in gym right now. :/

**Comment by File14** [comment]
It working, close the issuse.

**Comment by sero583** [comment]
@File14 It doesn't
I did:
public void onJoin(PlayerJoinEvent event) {
event.getPlayer().sendMessage("Welcome!");
FloatingTextParticle ftp = new FloatingTextParticle(event.getPlayer().getPosition(), event.getPlayer.getName() + " joined.");
event.getPlayer().getLevel().addParticle(ftp);
}

The welcome! messages comes but there doesn't comes any hologram (aka ftp (!!not file transfer protocol!!)), so i won't close the issue, in Genisys & Co. it is since 0.15.4 broken too!
The issue will stay open, my friend...

**Comment by File14** [comment]
Use this:

FloatingTextParticle particle = new FloatingTextParticle(location, "§cHello!");

then you do:
player.getLevel().addParticle(particle1, player);

**Comment by sero583** [comment]
@File14 Thank you, sorry for being a bit rude to you :/.
I will close this issue, when i tested it, i need to get asap to my laptop to test it.
How to fix your problem:
In PC maps the world have too BlockID's which aren't in PE you know and those will get too sent to MC:PE/Win10 and then it crashes, you need to fix it with a world converter.

**Comment by File14** [comment]
Okay thanks.

**Comment by sero583** [comment]
I'll keep this issue open, since i've tested it right now and it still dont works.

**Comment by Tee7even** [comment]
![image](https://cloud.githubusercontent.com/assets/6763610/17572745/e7203914-5f5e-11e6-8e31-8d042f844b77.png)
You just doing something wrong (didn't register event listener for example).

**Comment by File14** [comment]
Exactly @Tee7even thats what im trying to say be he doesn't trust me.

**Comment by sero583** [comment]
@File14 @Tee7even I do my events working too fine, but in my MC:PE it doesnt work.
That bug is in Genisys too...
(Note: I use 0.15.4, does it maybe lays on it?)

**Comment by Tee7even** [comment]
It works both on my Windows 10 PC and my Android Phone, 0.15.6 and 0.15.4. **Both.**

**Comment by sero583** [comment]
@Tee7even You see it only if your pointer is on the FTP (!!not file transfering protocol!!)?

**Comment by sero583** [comment]
This issue is strange...
Very strange.

**Comment by Tee7even** [comment]
I see it all the time and from every position. If I could see with back of my head in this game, no doubt, I would see it too.
