### ISSUE TITLE
Very buggy world loading and memory leak

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#980]
### Issue description

Sometimes I get ConcurrentModificationException or NullPointerException on world drawing. Some worlds after reloading by plugin, spams with NullPointerException and players is going to lagggg. And 
almost every day I have crashing with out of memory and file hs_err_pid(pid).log, but I wrote -Xmx1152M. Genisys doesn't crashes.
### Steps to reproduce the issue

1. Try to reload some worlds.
2. Try to start server with 20 players, and with mini-game.

### OS and versions

* Nukkit: 1.0dev, version 0.15.4(protocol 82)
* OS: Ubuntu 16.04 x86_64
* Device: Virtual Dedicated Server

### Crashdump, backtrace or other files

* I didn't have hs_err logs, because I have cron task to remove all log files(occupy a lot of space(it took me 13 GB)).

**Comment by Creeperface01** [comment]
i have server with 40 - 60 players and Annihilation minigame and runs fine :D

**Comment by Creeperface01** [comment]
but im using modified nukkit so idk :D

**Comment by MagicDroidX** [comment]
I am running a server with 80-100 players and NPC AIs and also works fine.
Memory usage is 25% of 1024M and load is 30%-50%.

**Comment by NycuRO** [comment]
@MagicDroidX What's your nukkit.yml and server-proprietes? How you use 25% of 1024M ? :o:
