### ISSUE TITLE
World never being sent to player on second join onward

### ISSUE THREAD

**Issue by Twister915** [Nukkit/Nukkit#983]
### Issue description
When a player (any player) rejoins a server, they can no longer see the world. This persists through restarts of the client, deleting of the players folder, and restarts of the server. The only remedy is to completely delete the world, and only then can you see the world a single time.

### Steps to reproduce the issue
* Delete worlds folder
* Start server
* Join server
* See chunks
* Disconnect from server
* Rejoin
* No world can be seen ingame (essentially a void world)

### OS and versions
* Nukkit: on version cae8bf522c38ffda0a73891d01e8c00cdc6925b3 (built using mvn clean package)
* OS: iOS
* Device: iPhone 6S+

**Comment by Pub4Game** [comment]
Hmm... You can test this build? https://www.dropbox.com/s/hddotk11pn0psud/nukkit-1.0-SNAPSHOT.jar?dl=0

**Comment by Twister915** [comment]
Works great and is much snappier. Is this a version that's available on github or is this something you're working on locally?

**Comment by Pub4Game** [comment]
@Twister915 Please check the latest build. The issue can be closed?
https://github.com/Nukkit/Nukkit/commit/074e67c046c3e29b759190e54bc406cc922b2274

**Comment by Twister915** [comment]
This version fixes the described issue, but has other issues. I've mentioned them to you on gitter, but I can also open a separate issue if you want @Pub4Game
