### ISSUE TITLE
Unable to destroy blocks in survival

### ISSUE THREAD

**Issue by Twister915** [Nukkit/Nukkit#984]
### Issue description
When I join the server, I am in survival. I cannot break any blocks around me in the world. After I switch to creative, I can break blocks. If I switch back to survival without logging out, I can also break blocks.

### Steps to reproduce the issue
1. Start a Nukkit server up
2. Join the server (in survival)
3. Attempt to break a block
4. Block will animate as breaking, but not disappear at all client side.

(remedy)
1. Change mode to creative
2. Change mode to survival

**Comment by Pub4Game** [comment]
@Twister915 Check again :)

**Comment by Twister915** [comment]
Confirmed working again.
