### ISSUE TITLE
crafting issie with win10 edition 

### ISSUE THREAD

**Issue by lcswolf** [Nukkit/Nukkit#991]
Unable to craft items with win 10 this error comes up in the log:
14.08 21:51:52 [Server] ALERT java.lang.ArrayIndexOutOfBoundsException: 0
14.08 21:51:52 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2778)
14.08 21:51:52 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:193)
14.08 21:51:52 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:164)
14.08 21:51:52 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1744)
14.08 21:51:52 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
14.08 21:51:52 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
14.08 21:51:52 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
14.08 21:51:52 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:75)
14.08 21:51:52 [Server] INFO at cn.nukkit.Server.tick(Server.java:983)
14.08 21:51:52 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:785)
14.08 21:51:52 [Server] INFO at cn.nukkit.Server.start(Server.java:765)
14.08 21:51:52 [Server] INFO at cn.nukkit.Server.<init>(Server.java:456)
14.08 21:51:52 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:65)
14.08 21:51:53 [Server] ALERT java.lang.ArrayIndexOutOfBoundsException: 0
14.08 21:51:53 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2778)
14.08 21:51:53 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:193)
14.08 21:51:53 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:164)
14.08 21:51:53 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1744)
14.08 21:51:53 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
14.08 21:51:53 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
14.08 21:51:53 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
14.08 21:51:53 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:75)
14.08 21:51:53 [Server] INFO at cn.nukkit.Server.tick(Server.java:983)
14.08 21:51:53 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:785)
14.08 21:51:53 [Server] INFO at cn.nukkit.Server.start(Server.java:765)
14.08 21:51:53 [Server] INFO at cn.nukkit.Server.<init>(Server.java:456)
14.08 21:51:55 [Multicraft] Skipped 2 lines due to rate limit (30/s)
14.08 21:51:55 [Server] ALERT java.lang.ArrayIndexOutOfBoundsException: 0
14.08 21:51:55 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2778)
14.08 21:51:55 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:193)
14.08 21:51:55 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:164)
14.08 21:51:55 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1744)
14.08 21:51:55 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
14.08 21:51:55 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
14.08 21:51:55 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
14.08 21:51:55 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:75)
14.08 21:51:55 [Server] INFO at cn.nukkit.Server.tick(Server.java:983)
14.08 21:51:55 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:785)
14.08 21:51:55 [Server] INFO at cn.nukkit.Server.start(Server.java:765)
14.08 21:51:55 [Server] INFO at cn.nukkit.Server.<init>(Server.java:456)
14.08 21:51:55 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:65)
14.08 21:52:12 [Server] ALERT java.lang.ArrayIndexOutOfBoundsException: 0
14.08 21:52:12 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2778)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:193)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:164)
14.08 21:52:12 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1744)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
14.08 21:52:12 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:75)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.tick(Server.java:983)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:785)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.start(Server.java:765)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.<init>(Server.java:456)
14.08 21:52:12 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:65)
14.08 21:52:12 [Server] ALERT java.lang.ArrayIndexOutOfBoundsException: 0
14.08 21:52:12 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2778)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:193)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:164)
14.08 21:52:12 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1744)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
14.08 21:52:12 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
14.08 21:52:12 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:75)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.tick(Server.java:983)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:785)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.start(Server.java:765)
14.08 21:52:12 [Server] INFO at cn.nukkit.Server.<init>(Server.java:456)

**Comment by Pub4Game** [comment]
Dublicate

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/issues/576
