### ISSUE TITLE
Server Not Fully Stoping

### ISSUE THREAD

**Issue by yungtechboy1** [Nukkit/Nukkit#992]
### Issue description
After Starting up the server stopping the server never fully works 

### Steps to reproduce the issue
1. Start Server
2. Stop Server

### OS and versions
* Nukkit: Build 421
* OS: Linux Ubuntu
* Device: 

### Crashdump, backtrace or other files

fac5@usloft2508:~$ java -jar nukkit-1.0-SNAPSHOT.jar
15:25:02 [INFO] Loading nukkit.yml...
15:25:02 [INFO] Loading server properties...
15:25:02 [INFO] Selected English (eng) as the base language
15:25:02 [INFO] Starting Minecraft: PE server version v0.15.6 alpha
15:25:02 [INFO] Opening server on 0.0.0.0:19000
15:25:02 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
15:25:02 [INFO] Nukkit is distributed under the LGPL License
15:25:02 [INFO] Preparing level "world"
15:25:02 [INFO] Starting GS4 status listener
15:25:02 [INFO] Setting query port to 19000
15:25:02 [INFO] Query is running on 0.0.0.0:19000
15:25:02 [INFO] Default game type: Survival Mode
15:25:02 [INFO] Done (0.801s)! For help, type "help" or "?"
> stop
15:25:04 [INFO] [CONSOLE: Stopping the server]
15:25:04 [INFO] Unloading level "world"
>

**Comment by Creeperface01** [comment]
yes and if it says server was killed forcefully it still isnt fully stopped
