### ISSUE TITLE
onEnable order is not equal to loading order (Plugin dependency)

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#996]
When plugin is depended (or soft depended) on another plugin, loading order works fine.
But execution of onEnable methods are goes in random order.

So if plugin A depends on plugin B you can see loading:

Load plugin B
Load plugin A

But they could load in different order:
Enable plugin A
Enable plugin B.

If plugin B must initialize variables that could be used in another plugin - you will not able to use plugin B from plugin A in onEnable method. Only after full server loading.

Here is example of this issue, noticed by @Pub4Game 
[Screenshot](http://i.imgur.com/7Bhw2bo.png)

As you can see DbLib was loaded before Serverauth plugin, but Serverauth was enabled before DbLib.

**Comment by Creeperface01** [comment]
same on disabiling

**Comment by Creeperface01** [comment]
i can not confirm this.

**Comment by PeratX** [comment]
View the plugin manager load and enable logic and you will see.
