### ISSUE TITLE
Unknown kicking

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#998]
### Issue description

A large amount of players randomly get kicked from there server.
### Steps to reproduce the issue

1. ... Unknown...
2. ...

### OS and versions

* Nukkit: This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v0.15.6 alpha (protocol version 82)
* OS: Linux
* Device: Phone and PC

### Crashdump, backtrace or other files

[Disconnect] User NAME[/User IP has disconnected, reason: unknown

**Comment by Creeperface01** [comment]
are you using nemisys?

**Comment by File14** [comment]
If this is log is from his Nukkit console it's not Nemisys.

Nukkit disconnect messages are working but if you run Nemisys it just says "disconnect".

**Comment by Creeperface01** [comment]
It isnt nukkits log i think

**Comment by imjack** [comment]
Nope it's nukkit. I just removed the data like name and ip. The server log gets flooded since everyone  gets kicked

**Comment by daniktheboss** [comment]
Are u going on a issue closing spree?
