### ISSUE TITLE
reborn abandoded?

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#999]
### Issue description

Latest commit at reborn are more than month ago!
### Steps to reproduce the issue

1. Say me, abandoded it, or work in progress?

### OS and versions

* Nukkit: reborn
* OS: os? Not os
* Device: device? Not device

### Crashdump, backtrace or other files

* ...

**Comment by Pub4Game** [comment]
This is not the place for questions. All questions can be asked on nukkit.io
